// Code generated by Datly for consentgrants; DO NOT EDIT.

package consentgrants

// ListGrantsInput is the generated input scaffold for consentgrants.
type ListGrantsInput struct {
	Namespace string              `parameter:"Namespace,kind=query,in=namespace,dataType=string,required=true"`
	RecordID  string              `parameter:"RecordID,kind=query,in=recordID,dataType=string,required=true"`
	Has       *ListGrantsInputHas `setMarker:"true" typeName:"ListGrantsInputHas" json:"-" sqlx:"-"`
}

type ListGrantsInputHas struct {
	Namespace bool
	RecordID  bool
}
