// Code generated by Datly for consentgrants; DO NOT EDIT.

package consentgrants

import (
	embed "embed"
	xdatly "github.com/viant/xdatly"
	reflect "reflect"
)

func init() {}

// Component is the generated component scaffold for consentgrants.
type ConsentgrantsComponent struct {
	Contract xdatly.Component[ListGrantsInput, ListGrantsOutput] "component:\"consentgrants,path=/internal/data/consentgrants,method=GET,connector=user,view=consentgrants\" routeName:\"consentgrants\" caseFormat:\"lc\""
}

// ConsentgrantsDatlyType returns the public component type.
func ConsentgrantsDatlyType() reflect.Type {
	return reflect.TypeOf((*ConsentgrantsComponent)(nil)).Elem()
}

// The package-level value keeps this real component type reachable for runtime discovery.
var ConsentgrantsDatly = new(ConsentgrantsComponent)
var _datlyReachableConsentgrantsComponent = reflect.TypeFor[ConsentgrantsComponent]()

func (ConsentgrantsComponent) EmbedFS() *embed.FS {
	return &ConsentgrantsDatlyResources
}

func (ConsentgrantsComponent) EmbedNamespace() string {
	return ConsentgrantsDatlyResourceNamespace
}
