// Code generated by Datly for consentdecide; DO NOT EDIT.

package consentdecide

// DecideOutput is the generated output scaffold for consentdecide.
type DecideOutput struct {
	Data []*Record `parameter:"Data,kind=output,in=body,dataType=[]*Record"`
}
