// Code generated by Datly for ListRecordingEvents; DO NOT EDIT.

package listrecordingevents

// RecordedEvent is generated canonical view metadata for ListRecordingEvents.
type RecordedEvent struct {
	Namespace   *string `sqlx:"namespace,required=true,primaryKey=true" json:"namespace"`
	Id          *string `sqlx:"id,required=true,primaryKey=true" json:"id"`
	RecordingId *string `sqlx:"recording_id,required=true" json:"recordingId"`
	Sequence    *int    `sqlx:"sequence,required=true" json:"sequence"`
	Kind        *string `sqlx:"kind,required=true" json:"kind"`
	PayloadJson *string `sqlx:"payload_json,required=true" json:"payloadJson"`
	CreatedAt   *string `sqlx:"created_at,required=true" json:"createdAt"`
}
