// Code generated by Datly for ListScenarios; DO NOT EDIT.

package scenariolist

// ListScenariosInput is the generated input scaffold for ListScenarios.
type ListScenariosInput struct {
	Namespace     string                 `parameter:"Namespace,kind=query,in=namespace,dataType=string,required=true"`
	ScenarioID    string                 `parameter:"ScenarioID,kind=query,in=scenarioId,dataType=string,required=true"`
	Revision      string                 `parameter:"Revision,kind=query,in=revision,dataType=string,required=true"`
	Limit         int                    `parameter:"Limit,kind=query,in=limit,dataType=int,required=true"`
	ObjectiveHash string                 `parameter:"ObjectiveHash,kind=query,in=objectiveHash,dataType=string,required=true"`
	AfterID       string                 `parameter:"AfterID,kind=query,in=afterId,dataType=string,required=true"`
	AfterRevision string                 `parameter:"AfterRevision,kind=query,in=afterRevision,dataType=string,required=true"`
	Has           *ListScenariosInputHas `setMarker:"true" typeName:"ListScenariosInputHas" json:"-" sqlx:"-"`
}

type ListScenariosInputHas struct {
	Namespace     bool
	ScenarioID    bool
	Revision      bool
	Limit         bool
	ObjectiveHash bool
	AfterID       bool
	AfterRevision bool
}
