// Code generated by Datly for ListScenarios; DO NOT EDIT.

package scenariolist

// ListScenariosOutput is the generated output scaffold for ListScenarios.
type ListScenariosOutput struct {
	Data []*ScenarioRevision `parameter:"Data,kind=output,in=view,dataType=[]*ScenarioRevision" view:"ListScenarios,type=ScenarioRevision,table=scenario_revisions" sql:"uri=mechanize_data_scenariolist_list_scenarios:sql/list_scenarios.sql"`
}
