// Code generated by Datly for consentcreate; DO NOT EDIT.

package consentcreate

import "embed"

// DatlyResourceNamespace identifies this package's generated resource filesystem.
const ConsentcreateDatlyResourceNamespace = "mechanize_data_consentcreate_consentcreate"

//go:embed "sql/audit.sql" "sql/consentcreate.sql"
var ConsentcreateDatlyResources embed.FS
