// Code generated by Datly for StatePatch; DO NOT EDIT.

package statepatch

import (
	fmt2 "fmt"
	xshape "github.com/viant/x/shape"
)

func (entity *RunState) GetRevision() *int {
	return entity.Revision
}
func (entity *RunState) SetRevision(value *int) {
	entity.Revision = value
	if entity.Has == nil {
		entity.Has = &RunStateHas{}
	}
	entity.Has.Revision = true
}
func (entity *RunState) GetNamespace() *string {
	return entity.Namespace
}
func (entity *RunState) SetNamespace(value *string) {
	entity.Namespace = value
	if entity.Has == nil {
		entity.Has = &RunStateHas{}
	}
	entity.Has.Namespace = true
}
func (entity *RunState) GetId() *string {
	return entity.Id
}
func (entity *RunState) SetId(value *string) {
	entity.Id = value
	if entity.Has == nil {
		entity.Has = &RunStateHas{}
	}
	entity.Has.Id = true
}
func (entity *RunState) GetStatus() *string {
	return entity.Status
}
func (entity *RunState) SetStatus(value *string) {
	entity.Status = value
	if entity.Has == nil {
		entity.Has = &RunStateHas{}
	}
	entity.Has.Status = true
}
func (entity *RunState) GetVariables() []*Variable {
	return entity.Variables
}
func (entity *RunState) SetVariables(value []*Variable) {
	entity.Variables = value
	if entity.Has == nil {
		entity.Has = &RunStateHas{}
	}
	entity.Has.Variables = true
}
func (entity *Variable) GetNamespace() *string {
	return entity.Namespace
}
func (entity *Variable) SetNamespace(value *string) {
	entity.Namespace = value
	if entity.Has == nil {
		entity.Has = &VariableHas{}
	}
	entity.Has.Namespace = true
}
func (entity *Variable) GetRunId() *string {
	return entity.RunId
}
func (entity *Variable) SetRunId(value *string) {
	entity.RunId = value
	if entity.Has == nil {
		entity.Has = &VariableHas{}
	}
	entity.Has.RunId = true
}
func (entity *Variable) GetName() *string {
	return entity.Name
}
func (entity *Variable) SetName(value *string) {
	entity.Name = value
	if entity.Has == nil {
		entity.Has = &VariableHas{}
	}
	entity.Has.Name = true
}
func (entity *Variable) GetValueJson() *string {
	return entity.ValueJson
}
func (entity *Variable) SetValueJson(value *string) {
	entity.ValueJson = value
	if entity.Has == nil {
		entity.Has = &VariableHas{}
	}
	entity.Has.ValueJson = true
}
func (input *StatePatchInput) ProjectCurrentVariablesParentKeys(previous []*CurrentStatePatchView) ([]struct {
	Namespace *string "sqlx:\"namespace\""
	RunId     *string "sqlx:\"run_id\""
}, error) {
	result := []struct {
		Namespace *string "sqlx:\"namespace\""
		RunId     *string "sqlx:\"run_id\""
	}{}
	for _, row := range previous {
		if row == nil {
			continue
		}
		if row.Namespace == nil || row.Id == nil {
			return nil, fmt2.Errorf("scoped parent identity is null")
		}
		result = append(result, struct {
			Namespace *string "sqlx:\"namespace\""
			RunId     *string "sqlx:\"run_id\""
		}{Namespace: row.Namespace, RunId: row.Id})
	}
	return result, nil
}
func (input *StatePatchInput) ProjectCurrentUnresolvedKeys(body []*RunState, current []*CurrentStatePatchView) ([]struct {
	Value0 string "sqlx:\"namespace\""
	Value1 string "sqlx:\"run_id\""
}, error) {
	type identity struct {
		K0 string
		K1 string
	}
	type lookupKey struct {
		Value0 string
		Value1 string
	}
	index := make(map[identity]*CurrentStatePatchView)
	previousRows, err := (xshape.Collection[CurrentStatePatchView]{}).Pointers(current)
	if err != nil {
		return nil, err
	}
	for _, previous := range previousRows {
		if previous == nil || !(previous.Namespace != nil && previous.Id != nil) {
			continue
		}
		key := identity{*previous.Namespace, *previous.Id}
		if _, exists := index[key]; exists {
			return nil, fmt2.Errorf("lookup current identity is duplicated")
		}
		index[key] = previous
	}
	seen := make(map[lookupKey]bool)
	var result []struct {
		Value0 string "sqlx:\"namespace\""
		Value1 string "sqlx:\"run_id\""
	}
	rows, err := (xshape.Collection[RunState]{}).Pointers(body)
	if err != nil {
		return nil, err
	}
	for _, row := range rows {
		if row == nil {
			continue
		}
		var previous *CurrentStatePatchView
		if row.Has != nil && row.Has.Namespace && row.Namespace != nil && row.Has.Id && row.Id != nil {
			previous = index[identity{*row.Namespace, *row.Id}]
		}
		var value0 string
		if row.Has != nil && row.Has.Namespace {
			if !(row.Namespace != nil) {
				continue
			}
			value0 = *row.Namespace
		} else {
			if previous == nil || !(previous.Namespace != nil) {
				continue
			}
			value0 = *previous.Namespace
		}
		var value1 string
		if row.Has != nil && row.Has.Id {
			if !(row.Id != nil) {
				continue
			}
			value1 = *row.Id
		} else {
			if previous == nil || !(previous.Id != nil) {
				continue
			}
			value1 = *previous.Id
		}
		tuple := lookupKey{value0, value1}
		if seen[tuple] {
			continue
		}
		seen[tuple] = true
		result = append(result, struct {
			Value0 string "sqlx:\"namespace\""
			Value1 string "sqlx:\"run_id\""
		}{value0, value1})
	}
	return result, nil
}
