// Code generated by Datly for StatePatch; DO NOT EDIT.

package statepatch

import (
	context "context"
	fmt "fmt"
	xshape "github.com/viant/x/shape"
	xhandler "github.com/viant/xdatly/handler"
	reflect "reflect"
)

type StatePatchHandlerCurrentStatePatchSlice []*CurrentStatePatchView

func StatePatchHandlerCurrentStatePatchIndexByRevisionKey(value *CurrentStatePatchView) (int, bool) {
	var zero int
	if value == nil {
		return zero, false
	}
	if value.Revision == nil {
		return zero, false
	}
	return *value.Revision, true
}

type StatePatchHandlerCurrentStatePatchIndexedByRevision map[int]*CurrentStatePatchView

func (rows StatePatchHandlerCurrentStatePatchSlice) IndexByRevision() (StatePatchHandlerCurrentStatePatchIndexedByRevision, error) {
	result := make(StatePatchHandlerCurrentStatePatchIndexedByRevision)
	for _, row := range rows {
		key, ok := StatePatchHandlerCurrentStatePatchIndexByRevisionKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index StatePatchHandlerCurrentStatePatchSlice.IndexByRevision")
		}
		result[key] = row
	}
	return result, nil
}
func (index StatePatchHandlerCurrentStatePatchIndexedByRevision) Has(key int) bool {
	_, ok := index[key]
	return ok
}

type StatePatchHandlerCurrentStatePatchGroupedByRevision map[int][]*CurrentStatePatchView

func (rows StatePatchHandlerCurrentStatePatchSlice) GroupByRevision() StatePatchHandlerCurrentStatePatchGroupedByRevision {
	result := make(StatePatchHandlerCurrentStatePatchGroupedByRevision)
	for _, row := range rows {
		key, ok := StatePatchHandlerCurrentStatePatchIndexByRevisionKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index StatePatchHandlerCurrentStatePatchGroupedByRevision) Has(key int) bool {
	_, ok := index[key]
	return ok
}
func StatePatchHandlerCurrentStatePatchIndexByNamespaceKey(value *CurrentStatePatchView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.Namespace == nil {
		return zero, false
	}
	return *value.Namespace, true
}

type StatePatchHandlerCurrentStatePatchIndexedByNamespace map[string]*CurrentStatePatchView

func (rows StatePatchHandlerCurrentStatePatchSlice) IndexByNamespace() (StatePatchHandlerCurrentStatePatchIndexedByNamespace, error) {
	result := make(StatePatchHandlerCurrentStatePatchIndexedByNamespace)
	for _, row := range rows {
		key, ok := StatePatchHandlerCurrentStatePatchIndexByNamespaceKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index StatePatchHandlerCurrentStatePatchSlice.IndexByNamespace")
		}
		result[key] = row
	}
	return result, nil
}
func (index StatePatchHandlerCurrentStatePatchIndexedByNamespace) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type StatePatchHandlerCurrentStatePatchGroupedByNamespace map[string][]*CurrentStatePatchView

func (rows StatePatchHandlerCurrentStatePatchSlice) GroupByNamespace() StatePatchHandlerCurrentStatePatchGroupedByNamespace {
	result := make(StatePatchHandlerCurrentStatePatchGroupedByNamespace)
	for _, row := range rows {
		key, ok := StatePatchHandlerCurrentStatePatchIndexByNamespaceKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index StatePatchHandlerCurrentStatePatchGroupedByNamespace) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func StatePatchHandlerCurrentStatePatchIndexByIdKey(value *CurrentStatePatchView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.Id == nil {
		return zero, false
	}
	return *value.Id, true
}

type StatePatchHandlerCurrentStatePatchIndexedById map[string]*CurrentStatePatchView

func (rows StatePatchHandlerCurrentStatePatchSlice) IndexById() (StatePatchHandlerCurrentStatePatchIndexedById, error) {
	result := make(StatePatchHandlerCurrentStatePatchIndexedById)
	for _, row := range rows {
		key, ok := StatePatchHandlerCurrentStatePatchIndexByIdKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index StatePatchHandlerCurrentStatePatchSlice.IndexById")
		}
		result[key] = row
	}
	return result, nil
}
func (index StatePatchHandlerCurrentStatePatchIndexedById) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type StatePatchHandlerCurrentStatePatchGroupedById map[string][]*CurrentStatePatchView

func (rows StatePatchHandlerCurrentStatePatchSlice) GroupById() StatePatchHandlerCurrentStatePatchGroupedById {
	result := make(StatePatchHandlerCurrentStatePatchGroupedById)
	for _, row := range rows {
		key, ok := StatePatchHandlerCurrentStatePatchIndexByIdKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index StatePatchHandlerCurrentStatePatchGroupedById) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func StatePatchHandlerCurrentStatePatchIndexByStatusKey(value *CurrentStatePatchView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.Status == nil {
		return zero, false
	}
	return *value.Status, true
}

type StatePatchHandlerCurrentStatePatchIndexedByStatus map[string]*CurrentStatePatchView

func (rows StatePatchHandlerCurrentStatePatchSlice) IndexByStatus() (StatePatchHandlerCurrentStatePatchIndexedByStatus, error) {
	result := make(StatePatchHandlerCurrentStatePatchIndexedByStatus)
	for _, row := range rows {
		key, ok := StatePatchHandlerCurrentStatePatchIndexByStatusKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index StatePatchHandlerCurrentStatePatchSlice.IndexByStatus")
		}
		result[key] = row
	}
	return result, nil
}
func (index StatePatchHandlerCurrentStatePatchIndexedByStatus) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type StatePatchHandlerCurrentStatePatchGroupedByStatus map[string][]*CurrentStatePatchView

func (rows StatePatchHandlerCurrentStatePatchSlice) GroupByStatus() StatePatchHandlerCurrentStatePatchGroupedByStatus {
	result := make(StatePatchHandlerCurrentStatePatchGroupedByStatus)
	for _, row := range rows {
		key, ok := StatePatchHandlerCurrentStatePatchIndexByStatusKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index StatePatchHandlerCurrentStatePatchGroupedByStatus) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type StatePatchHandlerCurrentStatePatchKey struct {
	Namespace string
	Id        string
}

func StatePatchHandlerCurrentStatePatchIndexByKeyKey(value *CurrentStatePatchView) (StatePatchHandlerCurrentStatePatchKey, bool) {
	var zero StatePatchHandlerCurrentStatePatchKey
	if value == nil {
		return zero, false
	}
	if value.Namespace == nil {
		return zero, false
	}
	if value.Id == nil {
		return zero, false
	}
	return StatePatchHandlerCurrentStatePatchKey{Namespace: *value.Namespace, Id: *value.Id}, true
}

type StatePatchHandlerCurrentStatePatchIndexedByKey map[StatePatchHandlerCurrentStatePatchKey]*CurrentStatePatchView

func (rows StatePatchHandlerCurrentStatePatchSlice) IndexByKey() (StatePatchHandlerCurrentStatePatchIndexedByKey, error) {
	result := make(StatePatchHandlerCurrentStatePatchIndexedByKey)
	for _, row := range rows {
		key, ok := StatePatchHandlerCurrentStatePatchIndexByKeyKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index StatePatchHandlerCurrentStatePatchSlice.IndexByKey")
		}
		result[key] = row
	}
	return result, nil
}
func (index StatePatchHandlerCurrentStatePatchIndexedByKey) Has(key StatePatchHandlerCurrentStatePatchKey) bool {
	_, ok := index[key]
	return ok
}

type StatePatchHandlerCurrentStatePatchGroupedByKey map[StatePatchHandlerCurrentStatePatchKey][]*CurrentStatePatchView

func (rows StatePatchHandlerCurrentStatePatchSlice) GroupByKey() StatePatchHandlerCurrentStatePatchGroupedByKey {
	result := make(StatePatchHandlerCurrentStatePatchGroupedByKey)
	for _, row := range rows {
		key, ok := StatePatchHandlerCurrentStatePatchIndexByKeyKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index StatePatchHandlerCurrentStatePatchGroupedByKey) Has(key StatePatchHandlerCurrentStatePatchKey) bool {
	_, ok := index[key]
	return ok
}

type StatePatchHandlerCurrentVariablesSlice []*CurrentVariablesView

func StatePatchHandlerCurrentVariablesIndexByNamespaceKey(value *CurrentVariablesView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.Namespace == nil {
		return zero, false
	}
	return *value.Namespace, true
}

type StatePatchHandlerCurrentVariablesIndexedByNamespace map[string]*CurrentVariablesView

func (rows StatePatchHandlerCurrentVariablesSlice) IndexByNamespace() (StatePatchHandlerCurrentVariablesIndexedByNamespace, error) {
	result := make(StatePatchHandlerCurrentVariablesIndexedByNamespace)
	for _, row := range rows {
		key, ok := StatePatchHandlerCurrentVariablesIndexByNamespaceKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index StatePatchHandlerCurrentVariablesSlice.IndexByNamespace")
		}
		result[key] = row
	}
	return result, nil
}
func (index StatePatchHandlerCurrentVariablesIndexedByNamespace) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type StatePatchHandlerCurrentVariablesGroupedByNamespace map[string][]*CurrentVariablesView

func (rows StatePatchHandlerCurrentVariablesSlice) GroupByNamespace() StatePatchHandlerCurrentVariablesGroupedByNamespace {
	result := make(StatePatchHandlerCurrentVariablesGroupedByNamespace)
	for _, row := range rows {
		key, ok := StatePatchHandlerCurrentVariablesIndexByNamespaceKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index StatePatchHandlerCurrentVariablesGroupedByNamespace) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func StatePatchHandlerCurrentVariablesIndexByRunIdKey(value *CurrentVariablesView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.RunId == nil {
		return zero, false
	}
	return *value.RunId, true
}

type StatePatchHandlerCurrentVariablesIndexedByRunId map[string]*CurrentVariablesView

func (rows StatePatchHandlerCurrentVariablesSlice) IndexByRunId() (StatePatchHandlerCurrentVariablesIndexedByRunId, error) {
	result := make(StatePatchHandlerCurrentVariablesIndexedByRunId)
	for _, row := range rows {
		key, ok := StatePatchHandlerCurrentVariablesIndexByRunIdKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index StatePatchHandlerCurrentVariablesSlice.IndexByRunId")
		}
		result[key] = row
	}
	return result, nil
}
func (index StatePatchHandlerCurrentVariablesIndexedByRunId) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type StatePatchHandlerCurrentVariablesGroupedByRunId map[string][]*CurrentVariablesView

func (rows StatePatchHandlerCurrentVariablesSlice) GroupByRunId() StatePatchHandlerCurrentVariablesGroupedByRunId {
	result := make(StatePatchHandlerCurrentVariablesGroupedByRunId)
	for _, row := range rows {
		key, ok := StatePatchHandlerCurrentVariablesIndexByRunIdKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index StatePatchHandlerCurrentVariablesGroupedByRunId) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func StatePatchHandlerCurrentVariablesIndexByNameKey(value *CurrentVariablesView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.Name == nil {
		return zero, false
	}
	return *value.Name, true
}

type StatePatchHandlerCurrentVariablesIndexedByName map[string]*CurrentVariablesView

func (rows StatePatchHandlerCurrentVariablesSlice) IndexByName() (StatePatchHandlerCurrentVariablesIndexedByName, error) {
	result := make(StatePatchHandlerCurrentVariablesIndexedByName)
	for _, row := range rows {
		key, ok := StatePatchHandlerCurrentVariablesIndexByNameKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index StatePatchHandlerCurrentVariablesSlice.IndexByName")
		}
		result[key] = row
	}
	return result, nil
}
func (index StatePatchHandlerCurrentVariablesIndexedByName) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type StatePatchHandlerCurrentVariablesGroupedByName map[string][]*CurrentVariablesView

func (rows StatePatchHandlerCurrentVariablesSlice) GroupByName() StatePatchHandlerCurrentVariablesGroupedByName {
	result := make(StatePatchHandlerCurrentVariablesGroupedByName)
	for _, row := range rows {
		key, ok := StatePatchHandlerCurrentVariablesIndexByNameKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index StatePatchHandlerCurrentVariablesGroupedByName) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func StatePatchHandlerCurrentVariablesIndexByValueJsonKey(value *CurrentVariablesView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.ValueJson == nil {
		return zero, false
	}
	return *value.ValueJson, true
}

type StatePatchHandlerCurrentVariablesIndexedByValueJson map[string]*CurrentVariablesView

func (rows StatePatchHandlerCurrentVariablesSlice) IndexByValueJson() (StatePatchHandlerCurrentVariablesIndexedByValueJson, error) {
	result := make(StatePatchHandlerCurrentVariablesIndexedByValueJson)
	for _, row := range rows {
		key, ok := StatePatchHandlerCurrentVariablesIndexByValueJsonKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index StatePatchHandlerCurrentVariablesSlice.IndexByValueJson")
		}
		result[key] = row
	}
	return result, nil
}
func (index StatePatchHandlerCurrentVariablesIndexedByValueJson) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type StatePatchHandlerCurrentVariablesGroupedByValueJson map[string][]*CurrentVariablesView

func (rows StatePatchHandlerCurrentVariablesSlice) GroupByValueJson() StatePatchHandlerCurrentVariablesGroupedByValueJson {
	result := make(StatePatchHandlerCurrentVariablesGroupedByValueJson)
	for _, row := range rows {
		key, ok := StatePatchHandlerCurrentVariablesIndexByValueJsonKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index StatePatchHandlerCurrentVariablesGroupedByValueJson) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type StatePatchHandlerCurrentVariablesKey struct {
	Namespace string
	RunId     string
	Name      string
}

func StatePatchHandlerCurrentVariablesIndexByKeyKey(value *CurrentVariablesView) (StatePatchHandlerCurrentVariablesKey, bool) {
	var zero StatePatchHandlerCurrentVariablesKey
	if value == nil {
		return zero, false
	}
	if value.Namespace == nil {
		return zero, false
	}
	if value.RunId == nil {
		return zero, false
	}
	if value.Name == nil {
		return zero, false
	}
	return StatePatchHandlerCurrentVariablesKey{Namespace: *value.Namespace, RunId: *value.RunId, Name: *value.Name}, true
}

type StatePatchHandlerCurrentVariablesIndexedByKey map[StatePatchHandlerCurrentVariablesKey]*CurrentVariablesView

func (rows StatePatchHandlerCurrentVariablesSlice) IndexByKey() (StatePatchHandlerCurrentVariablesIndexedByKey, error) {
	result := make(StatePatchHandlerCurrentVariablesIndexedByKey)
	for _, row := range rows {
		key, ok := StatePatchHandlerCurrentVariablesIndexByKeyKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index StatePatchHandlerCurrentVariablesSlice.IndexByKey")
		}
		result[key] = row
	}
	return result, nil
}
func (index StatePatchHandlerCurrentVariablesIndexedByKey) Has(key StatePatchHandlerCurrentVariablesKey) bool {
	_, ok := index[key]
	return ok
}

type StatePatchHandlerCurrentVariablesGroupedByKey map[StatePatchHandlerCurrentVariablesKey][]*CurrentVariablesView

func (rows StatePatchHandlerCurrentVariablesSlice) GroupByKey() StatePatchHandlerCurrentVariablesGroupedByKey {
	result := make(StatePatchHandlerCurrentVariablesGroupedByKey)
	for _, row := range rows {
		key, ok := StatePatchHandlerCurrentVariablesIndexByKeyKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index StatePatchHandlerCurrentVariablesGroupedByKey) Has(key StatePatchHandlerCurrentVariablesKey) bool {
	_, ok := index[key]
	return ok
}

type StatePatchHandlerCurrentVariablesNamespaceAndRunIdKey struct {
	Namespace string
	RunId     string
}

func StatePatchHandlerCurrentVariablesIndexByNamespaceAndRunIdKey(value *CurrentVariablesView) (StatePatchHandlerCurrentVariablesNamespaceAndRunIdKey, bool) {
	var zero StatePatchHandlerCurrentVariablesNamespaceAndRunIdKey
	if value == nil {
		return zero, false
	}
	if value.Namespace == nil {
		return zero, false
	}
	if value.RunId == nil {
		return zero, false
	}
	return StatePatchHandlerCurrentVariablesNamespaceAndRunIdKey{Namespace: *value.Namespace, RunId: *value.RunId}, true
}

type StatePatchHandlerCurrentVariablesIndexedByNamespaceAndRunId map[StatePatchHandlerCurrentVariablesNamespaceAndRunIdKey]*CurrentVariablesView

func (rows StatePatchHandlerCurrentVariablesSlice) IndexByNamespaceAndRunId() (StatePatchHandlerCurrentVariablesIndexedByNamespaceAndRunId, error) {
	result := make(StatePatchHandlerCurrentVariablesIndexedByNamespaceAndRunId)
	for _, row := range rows {
		key, ok := StatePatchHandlerCurrentVariablesIndexByNamespaceAndRunIdKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index StatePatchHandlerCurrentVariablesSlice.IndexByNamespaceAndRunId")
		}
		result[key] = row
	}
	return result, nil
}
func (index StatePatchHandlerCurrentVariablesIndexedByNamespaceAndRunId) Has(key StatePatchHandlerCurrentVariablesNamespaceAndRunIdKey) bool {
	_, ok := index[key]
	return ok
}

type StatePatchHandlerCurrentVariablesGroupedByNamespaceAndRunId map[StatePatchHandlerCurrentVariablesNamespaceAndRunIdKey][]*CurrentVariablesView

func (rows StatePatchHandlerCurrentVariablesSlice) GroupByNamespaceAndRunId() StatePatchHandlerCurrentVariablesGroupedByNamespaceAndRunId {
	result := make(StatePatchHandlerCurrentVariablesGroupedByNamespaceAndRunId)
	for _, row := range rows {
		key, ok := StatePatchHandlerCurrentVariablesIndexByNamespaceAndRunIdKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index StatePatchHandlerCurrentVariablesGroupedByNamespaceAndRunId) Has(key StatePatchHandlerCurrentVariablesNamespaceAndRunIdKey) bool {
	_, ok := index[key]
	return ok
}

type StatePatchHandlerCurrentUnresolvedSlice []*CurrentUnresolvedView

func StatePatchHandlerCurrentUnresolvedIndexByNamespaceKey(value *CurrentUnresolvedView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.Namespace == nil {
		return zero, false
	}
	return *value.Namespace, true
}

type StatePatchHandlerCurrentUnresolvedIndexedByNamespace map[string]*CurrentUnresolvedView

func (rows StatePatchHandlerCurrentUnresolvedSlice) IndexByNamespace() (StatePatchHandlerCurrentUnresolvedIndexedByNamespace, error) {
	result := make(StatePatchHandlerCurrentUnresolvedIndexedByNamespace)
	for _, row := range rows {
		key, ok := StatePatchHandlerCurrentUnresolvedIndexByNamespaceKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index StatePatchHandlerCurrentUnresolvedSlice.IndexByNamespace")
		}
		result[key] = row
	}
	return result, nil
}
func (index StatePatchHandlerCurrentUnresolvedIndexedByNamespace) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type StatePatchHandlerCurrentUnresolvedGroupedByNamespace map[string][]*CurrentUnresolvedView

func (rows StatePatchHandlerCurrentUnresolvedSlice) GroupByNamespace() StatePatchHandlerCurrentUnresolvedGroupedByNamespace {
	result := make(StatePatchHandlerCurrentUnresolvedGroupedByNamespace)
	for _, row := range rows {
		key, ok := StatePatchHandlerCurrentUnresolvedIndexByNamespaceKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index StatePatchHandlerCurrentUnresolvedGroupedByNamespace) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func StatePatchHandlerCurrentUnresolvedIndexByIdKey(value *CurrentUnresolvedView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.Id == nil {
		return zero, false
	}
	return *value.Id, true
}

type StatePatchHandlerCurrentUnresolvedIndexedById map[string]*CurrentUnresolvedView

func (rows StatePatchHandlerCurrentUnresolvedSlice) IndexById() (StatePatchHandlerCurrentUnresolvedIndexedById, error) {
	result := make(StatePatchHandlerCurrentUnresolvedIndexedById)
	for _, row := range rows {
		key, ok := StatePatchHandlerCurrentUnresolvedIndexByIdKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index StatePatchHandlerCurrentUnresolvedSlice.IndexById")
		}
		result[key] = row
	}
	return result, nil
}
func (index StatePatchHandlerCurrentUnresolvedIndexedById) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type StatePatchHandlerCurrentUnresolvedGroupedById map[string][]*CurrentUnresolvedView

func (rows StatePatchHandlerCurrentUnresolvedSlice) GroupById() StatePatchHandlerCurrentUnresolvedGroupedById {
	result := make(StatePatchHandlerCurrentUnresolvedGroupedById)
	for _, row := range rows {
		key, ok := StatePatchHandlerCurrentUnresolvedIndexByIdKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index StatePatchHandlerCurrentUnresolvedGroupedById) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func StatePatchHandlerCurrentUnresolvedIndexByAttemptIdKey(value *CurrentUnresolvedView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.AttemptId == nil {
		return zero, false
	}
	return *value.AttemptId, true
}

type StatePatchHandlerCurrentUnresolvedIndexedByAttemptId map[string]*CurrentUnresolvedView

func (rows StatePatchHandlerCurrentUnresolvedSlice) IndexByAttemptId() (StatePatchHandlerCurrentUnresolvedIndexedByAttemptId, error) {
	result := make(StatePatchHandlerCurrentUnresolvedIndexedByAttemptId)
	for _, row := range rows {
		key, ok := StatePatchHandlerCurrentUnresolvedIndexByAttemptIdKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index StatePatchHandlerCurrentUnresolvedSlice.IndexByAttemptId")
		}
		result[key] = row
	}
	return result, nil
}
func (index StatePatchHandlerCurrentUnresolvedIndexedByAttemptId) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type StatePatchHandlerCurrentUnresolvedGroupedByAttemptId map[string][]*CurrentUnresolvedView

func (rows StatePatchHandlerCurrentUnresolvedSlice) GroupByAttemptId() StatePatchHandlerCurrentUnresolvedGroupedByAttemptId {
	result := make(StatePatchHandlerCurrentUnresolvedGroupedByAttemptId)
	for _, row := range rows {
		key, ok := StatePatchHandlerCurrentUnresolvedIndexByAttemptIdKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index StatePatchHandlerCurrentUnresolvedGroupedByAttemptId) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func StatePatchHandlerCurrentUnresolvedIndexByRunIdKey(value *CurrentUnresolvedView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.RunId == nil {
		return zero, false
	}
	return *value.RunId, true
}

type StatePatchHandlerCurrentUnresolvedIndexedByRunId map[string]*CurrentUnresolvedView

func (rows StatePatchHandlerCurrentUnresolvedSlice) IndexByRunId() (StatePatchHandlerCurrentUnresolvedIndexedByRunId, error) {
	result := make(StatePatchHandlerCurrentUnresolvedIndexedByRunId)
	for _, row := range rows {
		key, ok := StatePatchHandlerCurrentUnresolvedIndexByRunIdKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index StatePatchHandlerCurrentUnresolvedSlice.IndexByRunId")
		}
		result[key] = row
	}
	return result, nil
}
func (index StatePatchHandlerCurrentUnresolvedIndexedByRunId) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type StatePatchHandlerCurrentUnresolvedGroupedByRunId map[string][]*CurrentUnresolvedView

func (rows StatePatchHandlerCurrentUnresolvedSlice) GroupByRunId() StatePatchHandlerCurrentUnresolvedGroupedByRunId {
	result := make(StatePatchHandlerCurrentUnresolvedGroupedByRunId)
	for _, row := range rows {
		key, ok := StatePatchHandlerCurrentUnresolvedIndexByRunIdKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index StatePatchHandlerCurrentUnresolvedGroupedByRunId) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func StatePatchHandlerCurrentUnresolvedIndexByBusinessKeyKey(value *CurrentUnresolvedView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.BusinessKey == nil {
		return zero, false
	}
	return *value.BusinessKey, true
}

type StatePatchHandlerCurrentUnresolvedIndexedByBusinessKey map[string]*CurrentUnresolvedView

func (rows StatePatchHandlerCurrentUnresolvedSlice) IndexByBusinessKey() (StatePatchHandlerCurrentUnresolvedIndexedByBusinessKey, error) {
	result := make(StatePatchHandlerCurrentUnresolvedIndexedByBusinessKey)
	for _, row := range rows {
		key, ok := StatePatchHandlerCurrentUnresolvedIndexByBusinessKeyKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index StatePatchHandlerCurrentUnresolvedSlice.IndexByBusinessKey")
		}
		result[key] = row
	}
	return result, nil
}
func (index StatePatchHandlerCurrentUnresolvedIndexedByBusinessKey) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type StatePatchHandlerCurrentUnresolvedGroupedByBusinessKey map[string][]*CurrentUnresolvedView

func (rows StatePatchHandlerCurrentUnresolvedSlice) GroupByBusinessKey() StatePatchHandlerCurrentUnresolvedGroupedByBusinessKey {
	result := make(StatePatchHandlerCurrentUnresolvedGroupedByBusinessKey)
	for _, row := range rows {
		key, ok := StatePatchHandlerCurrentUnresolvedIndexByBusinessKeyKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index StatePatchHandlerCurrentUnresolvedGroupedByBusinessKey) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func StatePatchHandlerCurrentUnresolvedIndexByStateKey(value *CurrentUnresolvedView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.State == nil {
		return zero, false
	}
	return *value.State, true
}

type StatePatchHandlerCurrentUnresolvedIndexedByState map[string]*CurrentUnresolvedView

func (rows StatePatchHandlerCurrentUnresolvedSlice) IndexByState() (StatePatchHandlerCurrentUnresolvedIndexedByState, error) {
	result := make(StatePatchHandlerCurrentUnresolvedIndexedByState)
	for _, row := range rows {
		key, ok := StatePatchHandlerCurrentUnresolvedIndexByStateKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index StatePatchHandlerCurrentUnresolvedSlice.IndexByState")
		}
		result[key] = row
	}
	return result, nil
}
func (index StatePatchHandlerCurrentUnresolvedIndexedByState) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type StatePatchHandlerCurrentUnresolvedGroupedByState map[string][]*CurrentUnresolvedView

func (rows StatePatchHandlerCurrentUnresolvedSlice) GroupByState() StatePatchHandlerCurrentUnresolvedGroupedByState {
	result := make(StatePatchHandlerCurrentUnresolvedGroupedByState)
	for _, row := range rows {
		key, ok := StatePatchHandlerCurrentUnresolvedIndexByStateKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index StatePatchHandlerCurrentUnresolvedGroupedByState) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func StatePatchHandlerCurrentUnresolvedIndexByRevisionKey(value *CurrentUnresolvedView) (int, bool) {
	var zero int
	if value == nil {
		return zero, false
	}
	if value.Revision == nil {
		return zero, false
	}
	return *value.Revision, true
}

type StatePatchHandlerCurrentUnresolvedIndexedByRevision map[int]*CurrentUnresolvedView

func (rows StatePatchHandlerCurrentUnresolvedSlice) IndexByRevision() (StatePatchHandlerCurrentUnresolvedIndexedByRevision, error) {
	result := make(StatePatchHandlerCurrentUnresolvedIndexedByRevision)
	for _, row := range rows {
		key, ok := StatePatchHandlerCurrentUnresolvedIndexByRevisionKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index StatePatchHandlerCurrentUnresolvedSlice.IndexByRevision")
		}
		result[key] = row
	}
	return result, nil
}
func (index StatePatchHandlerCurrentUnresolvedIndexedByRevision) Has(key int) bool {
	_, ok := index[key]
	return ok
}

type StatePatchHandlerCurrentUnresolvedGroupedByRevision map[int][]*CurrentUnresolvedView

func (rows StatePatchHandlerCurrentUnresolvedSlice) GroupByRevision() StatePatchHandlerCurrentUnresolvedGroupedByRevision {
	result := make(StatePatchHandlerCurrentUnresolvedGroupedByRevision)
	for _, row := range rows {
		key, ok := StatePatchHandlerCurrentUnresolvedIndexByRevisionKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index StatePatchHandlerCurrentUnresolvedGroupedByRevision) Has(key int) bool {
	_, ok := index[key]
	return ok
}
func StatePatchHandlerCurrentUnresolvedIndexByEvidenceJsonKey(value *CurrentUnresolvedView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.EvidenceJson == nil {
		return zero, false
	}
	return *value.EvidenceJson, true
}

type StatePatchHandlerCurrentUnresolvedIndexedByEvidenceJson map[string]*CurrentUnresolvedView

func (rows StatePatchHandlerCurrentUnresolvedSlice) IndexByEvidenceJson() (StatePatchHandlerCurrentUnresolvedIndexedByEvidenceJson, error) {
	result := make(StatePatchHandlerCurrentUnresolvedIndexedByEvidenceJson)
	for _, row := range rows {
		key, ok := StatePatchHandlerCurrentUnresolvedIndexByEvidenceJsonKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index StatePatchHandlerCurrentUnresolvedSlice.IndexByEvidenceJson")
		}
		result[key] = row
	}
	return result, nil
}
func (index StatePatchHandlerCurrentUnresolvedIndexedByEvidenceJson) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type StatePatchHandlerCurrentUnresolvedGroupedByEvidenceJson map[string][]*CurrentUnresolvedView

func (rows StatePatchHandlerCurrentUnresolvedSlice) GroupByEvidenceJson() StatePatchHandlerCurrentUnresolvedGroupedByEvidenceJson {
	result := make(StatePatchHandlerCurrentUnresolvedGroupedByEvidenceJson)
	for _, row := range rows {
		key, ok := StatePatchHandlerCurrentUnresolvedIndexByEvidenceJsonKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index StatePatchHandlerCurrentUnresolvedGroupedByEvidenceJson) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type StatePatchHandlerCurrentUnresolvedKey struct {
	Namespace string
	Id        string
}

func StatePatchHandlerCurrentUnresolvedIndexByKeyKey(value *CurrentUnresolvedView) (StatePatchHandlerCurrentUnresolvedKey, bool) {
	var zero StatePatchHandlerCurrentUnresolvedKey
	if value == nil {
		return zero, false
	}
	if value.Namespace == nil {
		return zero, false
	}
	if value.Id == nil {
		return zero, false
	}
	return StatePatchHandlerCurrentUnresolvedKey{Namespace: *value.Namespace, Id: *value.Id}, true
}

type StatePatchHandlerCurrentUnresolvedIndexedByKey map[StatePatchHandlerCurrentUnresolvedKey]*CurrentUnresolvedView

func (rows StatePatchHandlerCurrentUnresolvedSlice) IndexByKey() (StatePatchHandlerCurrentUnresolvedIndexedByKey, error) {
	result := make(StatePatchHandlerCurrentUnresolvedIndexedByKey)
	for _, row := range rows {
		key, ok := StatePatchHandlerCurrentUnresolvedIndexByKeyKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index StatePatchHandlerCurrentUnresolvedSlice.IndexByKey")
		}
		result[key] = row
	}
	return result, nil
}
func (index StatePatchHandlerCurrentUnresolvedIndexedByKey) Has(key StatePatchHandlerCurrentUnresolvedKey) bool {
	_, ok := index[key]
	return ok
}

type StatePatchHandlerCurrentUnresolvedGroupedByKey map[StatePatchHandlerCurrentUnresolvedKey][]*CurrentUnresolvedView

func (rows StatePatchHandlerCurrentUnresolvedSlice) GroupByKey() StatePatchHandlerCurrentUnresolvedGroupedByKey {
	result := make(StatePatchHandlerCurrentUnresolvedGroupedByKey)
	for _, row := range rows {
		key, ok := StatePatchHandlerCurrentUnresolvedIndexByKeyKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index StatePatchHandlerCurrentUnresolvedGroupedByKey) Has(key StatePatchHandlerCurrentUnresolvedKey) bool {
	_, ok := index[key]
	return ok
}

type StatePatchHandlerCurrentUnresolvedNamespaceAndRunIdKey struct {
	Namespace string
	RunId     string
}

func StatePatchHandlerCurrentUnresolvedIndexByNamespaceAndRunIdKey(value *CurrentUnresolvedView) (StatePatchHandlerCurrentUnresolvedNamespaceAndRunIdKey, bool) {
	var zero StatePatchHandlerCurrentUnresolvedNamespaceAndRunIdKey
	if value == nil {
		return zero, false
	}
	if value.Namespace == nil {
		return zero, false
	}
	if value.RunId == nil {
		return zero, false
	}
	return StatePatchHandlerCurrentUnresolvedNamespaceAndRunIdKey{Namespace: *value.Namespace, RunId: *value.RunId}, true
}

type StatePatchHandlerCurrentUnresolvedIndexedByNamespaceAndRunId map[StatePatchHandlerCurrentUnresolvedNamespaceAndRunIdKey]*CurrentUnresolvedView

func (rows StatePatchHandlerCurrentUnresolvedSlice) IndexByNamespaceAndRunId() (StatePatchHandlerCurrentUnresolvedIndexedByNamespaceAndRunId, error) {
	result := make(StatePatchHandlerCurrentUnresolvedIndexedByNamespaceAndRunId)
	for _, row := range rows {
		key, ok := StatePatchHandlerCurrentUnresolvedIndexByNamespaceAndRunIdKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index StatePatchHandlerCurrentUnresolvedSlice.IndexByNamespaceAndRunId")
		}
		result[key] = row
	}
	return result, nil
}
func (index StatePatchHandlerCurrentUnresolvedIndexedByNamespaceAndRunId) Has(key StatePatchHandlerCurrentUnresolvedNamespaceAndRunIdKey) bool {
	_, ok := index[key]
	return ok
}

type StatePatchHandlerCurrentUnresolvedGroupedByNamespaceAndRunId map[StatePatchHandlerCurrentUnresolvedNamespaceAndRunIdKey][]*CurrentUnresolvedView

func (rows StatePatchHandlerCurrentUnresolvedSlice) GroupByNamespaceAndRunId() StatePatchHandlerCurrentUnresolvedGroupedByNamespaceAndRunId {
	result := make(StatePatchHandlerCurrentUnresolvedGroupedByNamespaceAndRunId)
	for _, row := range rows {
		key, ok := StatePatchHandlerCurrentUnresolvedIndexByNamespaceAndRunIdKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index StatePatchHandlerCurrentUnresolvedGroupedByNamespaceAndRunId) Has(key StatePatchHandlerCurrentUnresolvedNamespaceAndRunIdKey) bool {
	_, ok := index[key]
	return ok
}

type StatePatchHandlerReadIndexes struct {
	CurrentStatePatch                           StatePatchHandlerCurrentStatePatchSlice
	CurrentStatePatchByKey                      StatePatchHandlerCurrentStatePatchIndexedByKey
	CurrentStatePatchGroupedByKey               StatePatchHandlerCurrentStatePatchGroupedByKey
	CurrentVariables                            StatePatchHandlerCurrentVariablesSlice
	CurrentVariablesByKey                       StatePatchHandlerCurrentVariablesIndexedByKey
	CurrentVariablesGroupedByNamespaceAndRunId  StatePatchHandlerCurrentVariablesGroupedByNamespaceAndRunId
	CurrentUnresolved                           StatePatchHandlerCurrentUnresolvedSlice
	CurrentUnresolvedByKey                      StatePatchHandlerCurrentUnresolvedIndexedByKey
	CurrentUnresolvedGroupedByNamespaceAndRunId StatePatchHandlerCurrentUnresolvedGroupedByNamespaceAndRunId
}

func BuildStatePatchHandlerReadIndexes(ctx context.Context, input *StatePatchInput) (*StatePatchHandlerReadIndexes, error) {
	if input == nil {
		return nil, fmt.Errorf("read indexes require input")
	}
	metadata, ok := xhandler.ReadMetadataFromContext(ctx)
	if !ok || (xshape.Runtime{}).IsNil(metadata) {
		return nil, fmt.Errorf("read indexes require bound read metadata")
	}
	result := &StatePatchHandlerReadIndexes{}
	{
		projection, err := metadata.Projection("CurrentStatePatch")
		if err != nil {
			return nil, err
		}
		if (xshape.Runtime{}).IsNil(projection) {
			return nil, fmt.Errorf("application read projection is unavailable: CurrentStatePatch")
		}
		inputAccess, err := xshape.Linked(reflect.TypeOf((*StatePatchInput)(nil)).Elem()).Accessor("CurrentStatePatch")
		if err != nil {
			return nil, err
		}
		carrier, err := inputAccess.Get(input)
		if err != nil {
			return nil, err
		}
		value := carrier.Interface()
		if projection.DirectOutput() && projection.RootHolder() != "" {
			return nil, fmt.Errorf("direct application read cannot declare a root holder")
		}
		if !projection.DirectOutput() {
			holder := projection.RootHolder()
			if holder == "" {
				return nil, fmt.Errorf("wrapped read projection requires a canonical root holder")
			}
			accessor, err := xshape.Linked(carrier.Type()).Accessor(holder)
			if err != nil {
				return nil, err
			}
			if _, err := (xshape.Collection[CurrentStatePatchView]{}).Pointers(reflect.Zero(accessor.Type()).Interface()); err != nil {
				return nil, err
			}
			root, present, err := accessor.GetOptional(value)
			if err != nil {
				return nil, err
			}
			if present {
				value = root.Interface()
			} else {
				value = []*CurrentStatePatchView(nil)
			}
		}
		rows, err := (xshape.Collection[CurrentStatePatchView]{}).Pointers(value)
		if err != nil {
			return nil, err
		}
		for ordinal, row := range rows {
			if row == nil {
				continue
			}
			loaded, err := projection.Fields(ordinal)
			if err != nil {
				return nil, err
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("Revision") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentStatePatch.Revision")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("Namespace") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentStatePatch.Namespace")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("Id") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentStatePatch.Id")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("Status") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentStatePatch.Status")
			}
		}
		cloned, err := (xshape.Runtime{}).CloneValue(rows, xshape.CloneOptions{})
		if err != nil {
			return nil, err
		}
		result.CurrentStatePatch = StatePatchHandlerCurrentStatePatchSlice(cloned.([]*CurrentStatePatchView))
		result.CurrentStatePatchByKey, err = result.CurrentStatePatch.IndexByKey()
		if err != nil {
			return nil, err
		}
		result.CurrentStatePatchGroupedByKey = result.CurrentStatePatch.GroupByKey()
	}
	{
		projection, err := metadata.Projection("CurrentVariables")
		if err != nil {
			return nil, err
		}
		if (xshape.Runtime{}).IsNil(projection) {
			return nil, fmt.Errorf("application read projection is unavailable: CurrentVariables")
		}
		inputAccess, err := xshape.Linked(reflect.TypeOf((*StatePatchInput)(nil)).Elem()).Accessor("CurrentVariables")
		if err != nil {
			return nil, err
		}
		carrier, err := inputAccess.Get(input)
		if err != nil {
			return nil, err
		}
		value := carrier.Interface()
		if projection.DirectOutput() && projection.RootHolder() != "" {
			return nil, fmt.Errorf("direct application read cannot declare a root holder")
		}
		if !projection.DirectOutput() {
			holder := projection.RootHolder()
			if holder == "" {
				return nil, fmt.Errorf("wrapped read projection requires a canonical root holder")
			}
			accessor, err := xshape.Linked(carrier.Type()).Accessor(holder)
			if err != nil {
				return nil, err
			}
			if _, err := (xshape.Collection[CurrentVariablesView]{}).Pointers(reflect.Zero(accessor.Type()).Interface()); err != nil {
				return nil, err
			}
			root, present, err := accessor.GetOptional(value)
			if err != nil {
				return nil, err
			}
			if present {
				value = root.Interface()
			} else {
				value = []*CurrentVariablesView(nil)
			}
		}
		rows, err := (xshape.Collection[CurrentVariablesView]{}).Pointers(value)
		if err != nil {
			return nil, err
		}
		for ordinal, row := range rows {
			if row == nil {
				continue
			}
			loaded, err := projection.Fields(ordinal)
			if err != nil {
				return nil, err
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("Namespace") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentVariables.Namespace")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("RunId") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentVariables.RunId")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("Name") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentVariables.Name")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("ValueJson") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentVariables.ValueJson")
			}
		}
		cloned, err := (xshape.Runtime{}).CloneValue(rows, xshape.CloneOptions{})
		if err != nil {
			return nil, err
		}
		result.CurrentVariables = StatePatchHandlerCurrentVariablesSlice(cloned.([]*CurrentVariablesView))
		result.CurrentVariablesByKey, err = result.CurrentVariables.IndexByKey()
		if err != nil {
			return nil, err
		}
		result.CurrentVariablesGroupedByNamespaceAndRunId = result.CurrentVariables.GroupByNamespaceAndRunId()
	}
	{
		projection, err := metadata.Projection("CurrentUnresolved")
		if err != nil {
			return nil, err
		}
		if (xshape.Runtime{}).IsNil(projection) {
			return nil, fmt.Errorf("application read projection is unavailable: CurrentUnresolved")
		}
		inputAccess, err := xshape.Linked(reflect.TypeOf((*StatePatchInput)(nil)).Elem()).Accessor("CurrentUnresolved")
		if err != nil {
			return nil, err
		}
		carrier, err := inputAccess.Get(input)
		if err != nil {
			return nil, err
		}
		value := carrier.Interface()
		if projection.DirectOutput() && projection.RootHolder() != "" {
			return nil, fmt.Errorf("direct application read cannot declare a root holder")
		}
		if !projection.DirectOutput() {
			holder := projection.RootHolder()
			if holder == "" {
				return nil, fmt.Errorf("wrapped read projection requires a canonical root holder")
			}
			accessor, err := xshape.Linked(carrier.Type()).Accessor(holder)
			if err != nil {
				return nil, err
			}
			if _, err := (xshape.Collection[CurrentUnresolvedView]{}).Pointers(reflect.Zero(accessor.Type()).Interface()); err != nil {
				return nil, err
			}
			root, present, err := accessor.GetOptional(value)
			if err != nil {
				return nil, err
			}
			if present {
				value = root.Interface()
			} else {
				value = []*CurrentUnresolvedView(nil)
			}
		}
		rows, err := (xshape.Collection[CurrentUnresolvedView]{}).Pointers(value)
		if err != nil {
			return nil, err
		}
		for ordinal, row := range rows {
			if row == nil {
				continue
			}
			loaded, err := projection.Fields(ordinal)
			if err != nil {
				return nil, err
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("Namespace") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentUnresolved.Namespace")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("Id") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentUnresolved.Id")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("AttemptId") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentUnresolved.AttemptId")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("RunId") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentUnresolved.RunId")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("BusinessKey") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentUnresolved.BusinessKey")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("State") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentUnresolved.State")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("Revision") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentUnresolved.Revision")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("EvidenceJson") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentUnresolved.EvidenceJson")
			}
		}
		cloned, err := (xshape.Runtime{}).CloneValue(rows, xshape.CloneOptions{})
		if err != nil {
			return nil, err
		}
		result.CurrentUnresolved = StatePatchHandlerCurrentUnresolvedSlice(cloned.([]*CurrentUnresolvedView))
		result.CurrentUnresolvedByKey, err = result.CurrentUnresolved.IndexByKey()
		if err != nil {
			return nil, err
		}
		result.CurrentUnresolvedGroupedByNamespaceAndRunId = result.CurrentUnresolved.GroupByNamespaceAndRunId()
	}
	return result, nil
}
func (input *StatePatchInput) PrepareReadIndexes(ctx context.Context) error {
	if input == nil {
		return fmt.Errorf("read indexes require input")
	}
	input._statePatchHandlerReadIndexes = nil
	indexes, err := BuildStatePatchHandlerReadIndexes(ctx, input)
	if err := err; err != nil {
		return err
	}
	input._statePatchHandlerReadIndexes = indexes
	return nil
}
func (input *StatePatchInput) ReadIndexes(ctx context.Context) (*StatePatchHandlerReadIndexes, error) {
	if input == nil {
		return nil, fmt.Errorf("read indexes require input")
	}
	if input._statePatchHandlerReadIndexes == nil {
		if err := input.PrepareReadIndexes(ctx); err != nil {
			return nil, err
		}
	}
	return input._statePatchHandlerReadIndexes, nil
}
