// Code generated by Datly for StatePatch; DO NOT EDIT.

package statepatch

// RunState is generated canonical view metadata for StatePatch.
type RunState struct {
	Revision   *int                `writer:"concurrency" sqlx:"revision,required=true" json:"revision"`
	Namespace  *string             `sqlx:"namespace,refTable=plan_revisions,refColumn=namespace,required=true,primaryKey=true" json:"namespace"`
	Id         *string             `sqlx:"id,required=true,primaryKey=true" json:"id"`
	Status     *string             `sqlx:"status,required=true" json:"status"`
	Variables  []*Variable         `view:"variables,type=Variable,entityHooks=VariableLifecycle,table=run_variables" on:"Namespace:records.namespace=Namespace:variables.namespace,Id:records.id=RunId:variables.run_id" json:"variables" sql:"uri=mechanize_data_statepatch_state_patch:sql/variables.sql"`
	Unresolved []*UnresolvedEffect `view:"unresolved,type=UnresolvedEffect,table=effects,auxiliary=true" on:"Namespace:records.namespace=Namespace:unresolved.namespace,Id:records.id=RunId:unresolved.run_id" json:"unresolved" sql:"uri=mechanize_data_statepatch_state_patch:sql/unresolved.sql"`
	Has        *RunStateHas        `setMarker:"true" format:"-" sqlx:"-" diff:"-" json:"-" typeName:"RunStateHas"`
}

type RunStateHas struct {
	Revision  bool
	Namespace bool
	Id        bool
	Status    bool
	Variables bool
}

// Variable is generated canonical view metadata for StatePatch.
type Variable struct {
	Namespace *string      `sqlx:"namespace,refTable=runs,refColumn=namespace,required=true,primaryKey=true" json:"namespace"`
	RunId     *string      `sqlx:"run_id,refTable=runs,refColumn=id,required=true,primaryKey=true" json:"runId"`
	Name      *string      `sqlx:"name,required=true,primaryKey=true" json:"name"`
	ValueJson *string      `sqlx:"value_json,required=true" json:"valueJson"`
	Has       *VariableHas `setMarker:"true" format:"-" sqlx:"-" diff:"-" json:"-" typeName:"VariableHas"`
}

type VariableHas struct {
	Namespace bool
	RunId     bool
	Name      bool
	ValueJson bool
}

// UnresolvedEffect is generated canonical view metadata for StatePatch.
type UnresolvedEffect struct {
	Namespace    *string `sqlx:"namespace,refTable=attempts,refColumn=namespace,required=true,primaryKey=true" json:"namespace"`
	Id           *string `sqlx:"id,required=true,primaryKey=true" json:"id"`
	AttemptId    *string `sqlx:"attempt_id,refTable=attempts,refColumn=id,required=true" json:"attemptId"`
	RunId        *string `sqlx:"run_id,required=true" json:"runId"`
	BusinessKey  *string `sqlx:"business_key,required=true" json:"businessKey"`
	State        *string `sqlx:"state,required=true" json:"state"`
	Revision     *int    `sqlx:"revision,required=true" json:"revision"`
	EvidenceJson *string `sqlx:"evidence_json" json:"evidenceJson"`
}

// CurrentStatePatchView is generated canonical view metadata for StatePatch.
type CurrentStatePatchView struct {
	Revision  *int    `sqlx:"revision,required=true" json:"revision"`
	Namespace *string `sqlx:"namespace,refTable=plan_revisions,refColumn=namespace,required=true,primaryKey=true" json:"namespace"`
	Id        *string `sqlx:"id,required=true,primaryKey=true" json:"id"`
	Status    *string `sqlx:"status,required=true" json:"status"`
}

// CurrentVariablesView is generated canonical view metadata for StatePatch.
type CurrentVariablesView struct {
	Namespace *string `sqlx:"namespace,refTable=runs,refColumn=namespace,required=true,primaryKey=true" json:"namespace"`
	RunId     *string `sqlx:"run_id,refTable=runs,refColumn=id,required=true,primaryKey=true" json:"runId"`
	Name      *string `sqlx:"name,required=true,primaryKey=true" json:"name"`
	ValueJson *string `sqlx:"value_json,required=true" json:"valueJson"`
}

// CurrentUnresolvedView is generated canonical view metadata for StatePatch.
type CurrentUnresolvedView struct {
	Namespace    *string `sqlx:"namespace,refTable=attempts,refColumn=namespace,required=true,primaryKey=true" json:"namespace"`
	Id           *string `sqlx:"id,required=true,primaryKey=true" json:"id"`
	AttemptId    *string `sqlx:"attempt_id,refTable=attempts,refColumn=id,required=true" json:"attemptId"`
	RunId        *string `sqlx:"run_id,required=true" json:"runId"`
	BusinessKey  *string `sqlx:"business_key,required=true" json:"businessKey"`
	State        *string `sqlx:"state,required=true" json:"state"`
	Revision     *int    `sqlx:"revision,required=true" json:"revision"`
	EvidenceJson *string `sqlx:"evidence_json" json:"evidenceJson"`
}

type StatePatchKeysRow struct {
	Namespace *string `sqlx:"namespace"`
	Id        *string `sqlx:"id"`
}
