// Code generated by Datly for applicationpolicywrite; DO NOT EDIT.

package applicationpolicywrite

func (entity *PolicyRecord) GetRevision() *int {
	return entity.Revision
}
func (entity *PolicyRecord) SetRevision(value *int) {
	entity.Revision = value
	if entity.Has == nil {
		entity.Has = &PolicyRecordHas{}
	}
	entity.Has.Revision = true
}
func (entity *PolicyRecord) GetNamespace() *string {
	return entity.Namespace
}
func (entity *PolicyRecord) SetNamespace(value *string) {
	entity.Namespace = value
	if entity.Has == nil {
		entity.Has = &PolicyRecordHas{}
	}
	entity.Has.Namespace = true
}
func (entity *PolicyRecord) GetId() *string {
	return entity.Id
}
func (entity *PolicyRecord) SetId(value *string) {
	entity.Id = value
	if entity.Has == nil {
		entity.Has = &PolicyRecordHas{}
	}
	entity.Has.Id = true
}
func (entity *PolicyRecord) GetPolicyJson() *string {
	return entity.PolicyJson
}
func (entity *PolicyRecord) SetPolicyJson(value *string) {
	entity.PolicyJson = value
	if entity.Has == nil {
		entity.Has = &PolicyRecordHas{}
	}
	entity.Has.PolicyJson = true
}
func (entity *PolicyRecord) GetCreatedAt() *string {
	return entity.CreatedAt
}
func (entity *PolicyRecord) SetCreatedAt(value *string) {
	entity.CreatedAt = value
	if entity.Has == nil {
		entity.Has = &PolicyRecordHas{}
	}
	entity.Has.CreatedAt = true
}
func (entity *PolicyRecord) GetUpdatedAt() *string {
	return entity.UpdatedAt
}
func (entity *PolicyRecord) SetUpdatedAt(value *string) {
	entity.UpdatedAt = value
	if entity.Has == nil {
		entity.Has = &PolicyRecordHas{}
	}
	entity.Has.UpdatedAt = true
}
