// Code generated by Datly for applicationpolicywrite; DO NOT EDIT.

package applicationpolicywrite

import (
	context "context"
	fmt "fmt"
	xshape "github.com/viant/x/shape"
	xhandler "github.com/viant/xdatly/handler"
	reflect "reflect"
)

type ApplicationpolicywriteHandlerCurrentApplicationpolicywriteSlice []*CurrentApplicationpolicywriteView

func ApplicationpolicywriteHandlerCurrentApplicationpolicywriteIndexByRevisionKey(value *CurrentApplicationpolicywriteView) (int, bool) {
	var zero int
	if value == nil {
		return zero, false
	}
	if value.Revision == nil {
		return zero, false
	}
	return *value.Revision, true
}

type ApplicationpolicywriteHandlerCurrentApplicationpolicywriteIndexedByRevision map[int]*CurrentApplicationpolicywriteView

func (rows ApplicationpolicywriteHandlerCurrentApplicationpolicywriteSlice) IndexByRevision() (ApplicationpolicywriteHandlerCurrentApplicationpolicywriteIndexedByRevision, error) {
	result := make(ApplicationpolicywriteHandlerCurrentApplicationpolicywriteIndexedByRevision)
	for _, row := range rows {
		key, ok := ApplicationpolicywriteHandlerCurrentApplicationpolicywriteIndexByRevisionKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index ApplicationpolicywriteHandlerCurrentApplicationpolicywriteSlice.IndexByRevision")
		}
		result[key] = row
	}
	return result, nil
}
func (index ApplicationpolicywriteHandlerCurrentApplicationpolicywriteIndexedByRevision) Has(key int) bool {
	_, ok := index[key]
	return ok
}

type ApplicationpolicywriteHandlerCurrentApplicationpolicywriteGroupedByRevision map[int][]*CurrentApplicationpolicywriteView

func (rows ApplicationpolicywriteHandlerCurrentApplicationpolicywriteSlice) GroupByRevision() ApplicationpolicywriteHandlerCurrentApplicationpolicywriteGroupedByRevision {
	result := make(ApplicationpolicywriteHandlerCurrentApplicationpolicywriteGroupedByRevision)
	for _, row := range rows {
		key, ok := ApplicationpolicywriteHandlerCurrentApplicationpolicywriteIndexByRevisionKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index ApplicationpolicywriteHandlerCurrentApplicationpolicywriteGroupedByRevision) Has(key int) bool {
	_, ok := index[key]
	return ok
}
func ApplicationpolicywriteHandlerCurrentApplicationpolicywriteIndexByNamespaceKey(value *CurrentApplicationpolicywriteView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.Namespace == nil {
		return zero, false
	}
	return *value.Namespace, true
}

type ApplicationpolicywriteHandlerCurrentApplicationpolicywriteIndexedByNamespace map[string]*CurrentApplicationpolicywriteView

func (rows ApplicationpolicywriteHandlerCurrentApplicationpolicywriteSlice) IndexByNamespace() (ApplicationpolicywriteHandlerCurrentApplicationpolicywriteIndexedByNamespace, error) {
	result := make(ApplicationpolicywriteHandlerCurrentApplicationpolicywriteIndexedByNamespace)
	for _, row := range rows {
		key, ok := ApplicationpolicywriteHandlerCurrentApplicationpolicywriteIndexByNamespaceKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index ApplicationpolicywriteHandlerCurrentApplicationpolicywriteSlice.IndexByNamespace")
		}
		result[key] = row
	}
	return result, nil
}
func (index ApplicationpolicywriteHandlerCurrentApplicationpolicywriteIndexedByNamespace) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type ApplicationpolicywriteHandlerCurrentApplicationpolicywriteGroupedByNamespace map[string][]*CurrentApplicationpolicywriteView

func (rows ApplicationpolicywriteHandlerCurrentApplicationpolicywriteSlice) GroupByNamespace() ApplicationpolicywriteHandlerCurrentApplicationpolicywriteGroupedByNamespace {
	result := make(ApplicationpolicywriteHandlerCurrentApplicationpolicywriteGroupedByNamespace)
	for _, row := range rows {
		key, ok := ApplicationpolicywriteHandlerCurrentApplicationpolicywriteIndexByNamespaceKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index ApplicationpolicywriteHandlerCurrentApplicationpolicywriteGroupedByNamespace) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func ApplicationpolicywriteHandlerCurrentApplicationpolicywriteIndexByIdKey(value *CurrentApplicationpolicywriteView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.Id == nil {
		return zero, false
	}
	return *value.Id, true
}

type ApplicationpolicywriteHandlerCurrentApplicationpolicywriteIndexedById map[string]*CurrentApplicationpolicywriteView

func (rows ApplicationpolicywriteHandlerCurrentApplicationpolicywriteSlice) IndexById() (ApplicationpolicywriteHandlerCurrentApplicationpolicywriteIndexedById, error) {
	result := make(ApplicationpolicywriteHandlerCurrentApplicationpolicywriteIndexedById)
	for _, row := range rows {
		key, ok := ApplicationpolicywriteHandlerCurrentApplicationpolicywriteIndexByIdKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index ApplicationpolicywriteHandlerCurrentApplicationpolicywriteSlice.IndexById")
		}
		result[key] = row
	}
	return result, nil
}
func (index ApplicationpolicywriteHandlerCurrentApplicationpolicywriteIndexedById) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type ApplicationpolicywriteHandlerCurrentApplicationpolicywriteGroupedById map[string][]*CurrentApplicationpolicywriteView

func (rows ApplicationpolicywriteHandlerCurrentApplicationpolicywriteSlice) GroupById() ApplicationpolicywriteHandlerCurrentApplicationpolicywriteGroupedById {
	result := make(ApplicationpolicywriteHandlerCurrentApplicationpolicywriteGroupedById)
	for _, row := range rows {
		key, ok := ApplicationpolicywriteHandlerCurrentApplicationpolicywriteIndexByIdKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index ApplicationpolicywriteHandlerCurrentApplicationpolicywriteGroupedById) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func ApplicationpolicywriteHandlerCurrentApplicationpolicywriteIndexByPolicyJsonKey(value *CurrentApplicationpolicywriteView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.PolicyJson == nil {
		return zero, false
	}
	return *value.PolicyJson, true
}

type ApplicationpolicywriteHandlerCurrentApplicationpolicywriteIndexedByPolicyJson map[string]*CurrentApplicationpolicywriteView

func (rows ApplicationpolicywriteHandlerCurrentApplicationpolicywriteSlice) IndexByPolicyJson() (ApplicationpolicywriteHandlerCurrentApplicationpolicywriteIndexedByPolicyJson, error) {
	result := make(ApplicationpolicywriteHandlerCurrentApplicationpolicywriteIndexedByPolicyJson)
	for _, row := range rows {
		key, ok := ApplicationpolicywriteHandlerCurrentApplicationpolicywriteIndexByPolicyJsonKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index ApplicationpolicywriteHandlerCurrentApplicationpolicywriteSlice.IndexByPolicyJson")
		}
		result[key] = row
	}
	return result, nil
}
func (index ApplicationpolicywriteHandlerCurrentApplicationpolicywriteIndexedByPolicyJson) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type ApplicationpolicywriteHandlerCurrentApplicationpolicywriteGroupedByPolicyJson map[string][]*CurrentApplicationpolicywriteView

func (rows ApplicationpolicywriteHandlerCurrentApplicationpolicywriteSlice) GroupByPolicyJson() ApplicationpolicywriteHandlerCurrentApplicationpolicywriteGroupedByPolicyJson {
	result := make(ApplicationpolicywriteHandlerCurrentApplicationpolicywriteGroupedByPolicyJson)
	for _, row := range rows {
		key, ok := ApplicationpolicywriteHandlerCurrentApplicationpolicywriteIndexByPolicyJsonKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index ApplicationpolicywriteHandlerCurrentApplicationpolicywriteGroupedByPolicyJson) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func ApplicationpolicywriteHandlerCurrentApplicationpolicywriteIndexByCreatedAtKey(value *CurrentApplicationpolicywriteView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.CreatedAt == nil {
		return zero, false
	}
	return *value.CreatedAt, true
}

type ApplicationpolicywriteHandlerCurrentApplicationpolicywriteIndexedByCreatedAt map[string]*CurrentApplicationpolicywriteView

func (rows ApplicationpolicywriteHandlerCurrentApplicationpolicywriteSlice) IndexByCreatedAt() (ApplicationpolicywriteHandlerCurrentApplicationpolicywriteIndexedByCreatedAt, error) {
	result := make(ApplicationpolicywriteHandlerCurrentApplicationpolicywriteIndexedByCreatedAt)
	for _, row := range rows {
		key, ok := ApplicationpolicywriteHandlerCurrentApplicationpolicywriteIndexByCreatedAtKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index ApplicationpolicywriteHandlerCurrentApplicationpolicywriteSlice.IndexByCreatedAt")
		}
		result[key] = row
	}
	return result, nil
}
func (index ApplicationpolicywriteHandlerCurrentApplicationpolicywriteIndexedByCreatedAt) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type ApplicationpolicywriteHandlerCurrentApplicationpolicywriteGroupedByCreatedAt map[string][]*CurrentApplicationpolicywriteView

func (rows ApplicationpolicywriteHandlerCurrentApplicationpolicywriteSlice) GroupByCreatedAt() ApplicationpolicywriteHandlerCurrentApplicationpolicywriteGroupedByCreatedAt {
	result := make(ApplicationpolicywriteHandlerCurrentApplicationpolicywriteGroupedByCreatedAt)
	for _, row := range rows {
		key, ok := ApplicationpolicywriteHandlerCurrentApplicationpolicywriteIndexByCreatedAtKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index ApplicationpolicywriteHandlerCurrentApplicationpolicywriteGroupedByCreatedAt) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func ApplicationpolicywriteHandlerCurrentApplicationpolicywriteIndexByUpdatedAtKey(value *CurrentApplicationpolicywriteView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.UpdatedAt == nil {
		return zero, false
	}
	return *value.UpdatedAt, true
}

type ApplicationpolicywriteHandlerCurrentApplicationpolicywriteIndexedByUpdatedAt map[string]*CurrentApplicationpolicywriteView

func (rows ApplicationpolicywriteHandlerCurrentApplicationpolicywriteSlice) IndexByUpdatedAt() (ApplicationpolicywriteHandlerCurrentApplicationpolicywriteIndexedByUpdatedAt, error) {
	result := make(ApplicationpolicywriteHandlerCurrentApplicationpolicywriteIndexedByUpdatedAt)
	for _, row := range rows {
		key, ok := ApplicationpolicywriteHandlerCurrentApplicationpolicywriteIndexByUpdatedAtKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index ApplicationpolicywriteHandlerCurrentApplicationpolicywriteSlice.IndexByUpdatedAt")
		}
		result[key] = row
	}
	return result, nil
}
func (index ApplicationpolicywriteHandlerCurrentApplicationpolicywriteIndexedByUpdatedAt) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type ApplicationpolicywriteHandlerCurrentApplicationpolicywriteGroupedByUpdatedAt map[string][]*CurrentApplicationpolicywriteView

func (rows ApplicationpolicywriteHandlerCurrentApplicationpolicywriteSlice) GroupByUpdatedAt() ApplicationpolicywriteHandlerCurrentApplicationpolicywriteGroupedByUpdatedAt {
	result := make(ApplicationpolicywriteHandlerCurrentApplicationpolicywriteGroupedByUpdatedAt)
	for _, row := range rows {
		key, ok := ApplicationpolicywriteHandlerCurrentApplicationpolicywriteIndexByUpdatedAtKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index ApplicationpolicywriteHandlerCurrentApplicationpolicywriteGroupedByUpdatedAt) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type ApplicationpolicywriteHandlerCurrentApplicationpolicywriteKey struct {
	Namespace string
	Id        string
}

func ApplicationpolicywriteHandlerCurrentApplicationpolicywriteIndexByKeyKey(value *CurrentApplicationpolicywriteView) (ApplicationpolicywriteHandlerCurrentApplicationpolicywriteKey, bool) {
	var zero ApplicationpolicywriteHandlerCurrentApplicationpolicywriteKey
	if value == nil {
		return zero, false
	}
	if value.Namespace == nil {
		return zero, false
	}
	if value.Id == nil {
		return zero, false
	}
	return ApplicationpolicywriteHandlerCurrentApplicationpolicywriteKey{Namespace: *value.Namespace, Id: *value.Id}, true
}

type ApplicationpolicywriteHandlerCurrentApplicationpolicywriteIndexedByKey map[ApplicationpolicywriteHandlerCurrentApplicationpolicywriteKey]*CurrentApplicationpolicywriteView

func (rows ApplicationpolicywriteHandlerCurrentApplicationpolicywriteSlice) IndexByKey() (ApplicationpolicywriteHandlerCurrentApplicationpolicywriteIndexedByKey, error) {
	result := make(ApplicationpolicywriteHandlerCurrentApplicationpolicywriteIndexedByKey)
	for _, row := range rows {
		key, ok := ApplicationpolicywriteHandlerCurrentApplicationpolicywriteIndexByKeyKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index ApplicationpolicywriteHandlerCurrentApplicationpolicywriteSlice.IndexByKey")
		}
		result[key] = row
	}
	return result, nil
}
func (index ApplicationpolicywriteHandlerCurrentApplicationpolicywriteIndexedByKey) Has(key ApplicationpolicywriteHandlerCurrentApplicationpolicywriteKey) bool {
	_, ok := index[key]
	return ok
}

type ApplicationpolicywriteHandlerCurrentApplicationpolicywriteGroupedByKey map[ApplicationpolicywriteHandlerCurrentApplicationpolicywriteKey][]*CurrentApplicationpolicywriteView

func (rows ApplicationpolicywriteHandlerCurrentApplicationpolicywriteSlice) GroupByKey() ApplicationpolicywriteHandlerCurrentApplicationpolicywriteGroupedByKey {
	result := make(ApplicationpolicywriteHandlerCurrentApplicationpolicywriteGroupedByKey)
	for _, row := range rows {
		key, ok := ApplicationpolicywriteHandlerCurrentApplicationpolicywriteIndexByKeyKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index ApplicationpolicywriteHandlerCurrentApplicationpolicywriteGroupedByKey) Has(key ApplicationpolicywriteHandlerCurrentApplicationpolicywriteKey) bool {
	_, ok := index[key]
	return ok
}

type ApplicationpolicywriteHandlerReadIndexes struct {
	CurrentApplicationpolicywrite      ApplicationpolicywriteHandlerCurrentApplicationpolicywriteSlice
	CurrentApplicationpolicywriteByKey ApplicationpolicywriteHandlerCurrentApplicationpolicywriteIndexedByKey
}

func BuildApplicationpolicywriteHandlerReadIndexes(ctx context.Context, input *WriteApplicationPolicyInput) (*ApplicationpolicywriteHandlerReadIndexes, error) {
	if input == nil {
		return nil, fmt.Errorf("read indexes require input")
	}
	metadata, ok := xhandler.ReadMetadataFromContext(ctx)
	if !ok || (xshape.Runtime{}).IsNil(metadata) {
		return nil, fmt.Errorf("read indexes require bound read metadata")
	}
	result := &ApplicationpolicywriteHandlerReadIndexes{}
	{
		projection, err := metadata.Projection("CurrentApplicationpolicywrite")
		if err != nil {
			return nil, err
		}
		if (xshape.Runtime{}).IsNil(projection) {
			return nil, fmt.Errorf("application read projection is unavailable: CurrentApplicationpolicywrite")
		}
		inputAccess, err := xshape.Linked(reflect.TypeOf((*WriteApplicationPolicyInput)(nil)).Elem()).Accessor("CurrentApplicationpolicywrite")
		if err != nil {
			return nil, err
		}
		carrier, err := inputAccess.Get(input)
		if err != nil {
			return nil, err
		}
		value := carrier.Interface()
		if projection.DirectOutput() && projection.RootHolder() != "" {
			return nil, fmt.Errorf("direct application read cannot declare a root holder")
		}
		if !projection.DirectOutput() {
			holder := projection.RootHolder()
			if holder == "" {
				return nil, fmt.Errorf("wrapped read projection requires a canonical root holder")
			}
			accessor, err := xshape.Linked(carrier.Type()).Accessor(holder)
			if err != nil {
				return nil, err
			}
			if _, err := (xshape.Collection[CurrentApplicationpolicywriteView]{}).Pointers(reflect.Zero(accessor.Type()).Interface()); err != nil {
				return nil, err
			}
			root, present, err := accessor.GetOptional(value)
			if err != nil {
				return nil, err
			}
			if present {
				value = root.Interface()
			} else {
				value = []*CurrentApplicationpolicywriteView(nil)
			}
		}
		rows, err := (xshape.Collection[CurrentApplicationpolicywriteView]{}).Pointers(value)
		if err != nil {
			return nil, err
		}
		for ordinal, row := range rows {
			if row == nil {
				continue
			}
			loaded, err := projection.Fields(ordinal)
			if err != nil {
				return nil, err
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("Revision") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentApplicationpolicywrite.Revision")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("Namespace") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentApplicationpolicywrite.Namespace")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("Id") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentApplicationpolicywrite.Id")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("PolicyJson") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentApplicationpolicywrite.PolicyJson")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("CreatedAt") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentApplicationpolicywrite.CreatedAt")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("UpdatedAt") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentApplicationpolicywrite.UpdatedAt")
			}
		}
		cloned, err := (xshape.Runtime{}).CloneValue(rows, xshape.CloneOptions{})
		if err != nil {
			return nil, err
		}
		result.CurrentApplicationpolicywrite = ApplicationpolicywriteHandlerCurrentApplicationpolicywriteSlice(cloned.([]*CurrentApplicationpolicywriteView))
		result.CurrentApplicationpolicywriteByKey, err = result.CurrentApplicationpolicywrite.IndexByKey()
		if err != nil {
			return nil, err
		}
	}
	return result, nil
}
func (input *WriteApplicationPolicyInput) PrepareReadIndexes(ctx context.Context) error {
	if input == nil {
		return fmt.Errorf("read indexes require input")
	}
	input._applicationpolicywriteHandlerReadIndexes = nil
	indexes, err := BuildApplicationpolicywriteHandlerReadIndexes(ctx, input)
	if err := err; err != nil {
		return err
	}
	input._applicationpolicywriteHandlerReadIndexes = indexes
	return nil
}
func (input *WriteApplicationPolicyInput) ReadIndexes(ctx context.Context) (*ApplicationpolicywriteHandlerReadIndexes, error) {
	if input == nil {
		return nil, fmt.Errorf("read indexes require input")
	}
	if input._applicationpolicywriteHandlerReadIndexes == nil {
		if err := input.PrepareReadIndexes(ctx); err != nil {
			return nil, err
		}
	}
	return input._applicationpolicywriteHandlerReadIndexes, nil
}
