// Code generated by Datly for applicationpolicywrite; DO NOT EDIT.

package applicationpolicywrite

// WriteApplicationPolicyOutput is the generated output scaffold for applicationpolicywrite.
type WriteApplicationPolicyOutput struct {
	Data []*PolicyRecord `parameter:"Data,kind=output,in=body,dataType=[]*PolicyRecord"`
}
