// Code generated by Datly for applicationpolicywrite; DO NOT EDIT.

package applicationpolicywrite

import "embed"

// DatlyResourceNamespace identifies this package's generated resource filesystem.
const ApplicationpolicywriteDatlyResourceNamespace = "mechanize_data_applicationpolicywrite_applicationpolicywrite"

//go:embed "sql/applicationpolicywrite.sql" "sql/applicationpolicywrite_keys.sql" "sql/current_applicationpolicywrite.sql"
var ApplicationpolicywriteDatlyResources embed.FS
