// Code generated by Datly for LeaseCleanupEvidence; DO NOT EDIT.

package leasecleanupevidence

func (input *LeaseCleanupEvidenceInput) SetNamespace(value string) {
	if input == nil {
		return
	}
	input.Namespace = value
	if input.Has == nil {
		input.Has = &LeaseCleanupEvidenceInputHas{}
	}
	input.Has.Namespace = true
}

func (input *LeaseCleanupEvidenceInput) SetLeaseEpoch(value int) {
	if input == nil {
		return
	}
	input.LeaseEpoch = value
	if input.Has == nil {
		input.Has = &LeaseCleanupEvidenceInputHas{}
	}
	input.Has.LeaseEpoch = true
}
