// Code generated by Datly for LeaseCleanupEvidence; DO NOT EDIT.

package leasecleanupevidence

// LeaseCleanupEvidenceInput is the generated input scaffold for LeaseCleanupEvidence.
type LeaseCleanupEvidenceInput struct {
	Namespace  string                        `parameter:"Namespace,kind=query,in=namespace,dataType=string,required=true"`
	LeaseEpoch int                           `parameter:"LeaseEpoch,kind=query,in=leaseEpoch,dataType=int,required=true"`
	Has        *LeaseCleanupEvidenceInputHas `setMarker:"true" typeName:"LeaseCleanupEvidenceInputHas" json:"-" sqlx:"-"`
}

type LeaseCleanupEvidenceInputHas struct {
	Namespace  bool
	LeaseEpoch bool
}
