// Code generated by Datly for LeaseCleanupEvidence; DO NOT EDIT.

package leasecleanupevidence

import "embed"

// DatlyResourceNamespace identifies this package's generated resource filesystem.
const LeaseCleanupEvidenceDatlyResourceNamespace = "mechanize_data_leasecleanupevidence_lease_cleanup_evidence"

//go:embed "sql/lease_cleanup_evidence.sql"
var LeaseCleanupEvidenceDatlyResources embed.FS
