// Code generated by Datly for LeaseCleanupEvidence; DO NOT EDIT.

package leasecleanupevidence

// AttemptEvidence is generated canonical view metadata for LeaseCleanupEvidence.
type AttemptEvidence struct {
	TotalAttempts      int     `sqlx:"total_attempts" json:"totalAttempts"`
	Namespace          *string `sqlx:"namespace,refTable=runs,refColumn=namespace,required=true,primaryKey=true" json:"namespace"`
	Id                 *string `sqlx:"id,required=true,primaryKey=true" json:"id"`
	RunId              *string `sqlx:"run_id,refTable=runs,refColumn=id,required=true" json:"runId"`
	LeaseEpoch         *int    `sqlx:"lease_epoch,required=true" json:"leaseEpoch"`
	EffectId           *string `sqlx:"effect_id" json:"effectId"`
	EffectState        *string `sqlx:"effect_state" json:"effectState"`
	EffectRevision     *int    `sqlx:"effect_revision" json:"effectRevision"`
	EvidenceJson       *string `sqlx:"evidence_json" json:"evidenceJson"`
	IntentEventId      *string `sqlx:"intent_event_id" json:"intentEventId"`
	IntentSequence     *int    `sqlx:"intent_sequence" json:"intentSequence"`
	OutcomeEventId     *string `sqlx:"outcome_event_id" json:"outcomeEventId"`
	OutcomeSequence    *int    `sqlx:"outcome_sequence" json:"outcomeSequence"`
	OutcomePayloadJson *string `sqlx:"outcome_payload_json" json:"outcomePayloadJson"`
}
