// Code generated by Datly for WriteChromeRetirement; DO NOT EDIT.

package chromeretirementwrite

import (
	fmt2 "fmt"
)

func (entity *Retirement) GetRevision() *int {
	return entity.Revision
}
func (entity *Retirement) SetRevision(value *int) {
	entity.Revision = value
	if entity.Has == nil {
		entity.Has = &RetirementHas{}
	}
	entity.Has.Revision = true
}
func (entity *Retirement) GetNamespace() *string {
	return entity.Namespace
}
func (entity *Retirement) SetNamespace(value *string) {
	entity.Namespace = value
	if entity.Has == nil {
		entity.Has = &RetirementHas{}
	}
	entity.Has.Namespace = true
}
func (entity *Retirement) GetId() *string {
	return entity.Id
}
func (entity *Retirement) SetId(value *string) {
	entity.Id = value
	if entity.Has == nil {
		entity.Has = &RetirementHas{}
	}
	entity.Has.Id = true
}
func (entity *Retirement) GetClientId() *string {
	return entity.ClientId
}
func (entity *Retirement) SetClientId(value *string) {
	entity.ClientId = value
	if entity.Has == nil {
		entity.Has = &RetirementHas{}
	}
	entity.Has.ClientId = true
}
func (entity *Retirement) GetRequestId() *string {
	return entity.RequestId
}
func (entity *Retirement) SetRequestId(value *string) {
	entity.RequestId = value
	if entity.Has == nil {
		entity.Has = &RetirementHas{}
	}
	entity.Has.RequestId = true
}
func (entity *Retirement) GetProfileChannel() *string {
	return entity.ProfileChannel
}
func (entity *Retirement) SetProfileChannel(value *string) {
	entity.ProfileChannel = value
	if entity.Has == nil {
		entity.Has = &RetirementHas{}
	}
	entity.Has.ProfileChannel = true
}
func (entity *Retirement) GetBrowserInstance() *string {
	return entity.BrowserInstance
}
func (entity *Retirement) SetBrowserInstance(value *string) {
	entity.BrowserInstance = value
	if entity.Has == nil {
		entity.Has = &RetirementHas{}
	}
	entity.Has.BrowserInstance = true
}
func (entity *Retirement) GetTrustScope() *string {
	return entity.TrustScope
}
func (entity *Retirement) SetTrustScope(value *string) {
	entity.TrustScope = value
	if entity.Has == nil {
		entity.Has = &RetirementHas{}
	}
	entity.Has.TrustScope = true
}
func (entity *Retirement) GetOldBrokerEpoch() *string {
	return entity.OldBrokerEpoch
}
func (entity *Retirement) SetOldBrokerEpoch(value *string) {
	entity.OldBrokerEpoch = value
	if entity.Has == nil {
		entity.Has = &RetirementHas{}
	}
	entity.Has.OldBrokerEpoch = true
}
func (entity *Retirement) GetOldChannelEpoch() *string {
	return entity.OldChannelEpoch
}
func (entity *Retirement) SetOldChannelEpoch(value *string) {
	entity.OldChannelEpoch = value
	if entity.Has == nil {
		entity.Has = &RetirementHas{}
	}
	entity.Has.OldChannelEpoch = true
}
func (entity *Retirement) GetOldScopeHash() *string {
	return entity.OldScopeHash
}
func (entity *Retirement) SetOldScopeHash(value *string) {
	entity.OldScopeHash = value
	if entity.Has == nil {
		entity.Has = &RetirementHas{}
	}
	entity.Has.OldScopeHash = true
}
func (entity *Retirement) GetProcessEvidenceJson() *string {
	return entity.ProcessEvidenceJson
}
func (entity *Retirement) SetProcessEvidenceJson(value *string) {
	entity.ProcessEvidenceJson = value
	if entity.Has == nil {
		entity.Has = &RetirementHas{}
	}
	entity.Has.ProcessEvidenceJson = true
}
func (entity *Retirement) GetPolicyEvidenceJson() *string {
	return entity.PolicyEvidenceJson
}
func (entity *Retirement) SetPolicyEvidenceJson(value *string) {
	entity.PolicyEvidenceJson = value
	if entity.Has == nil {
		entity.Has = &RetirementHas{}
	}
	entity.Has.PolicyEvidenceJson = true
}
func (entity *Retirement) GetEvidenceDigest() *string {
	return entity.EvidenceDigest
}
func (entity *Retirement) SetEvidenceDigest(value *string) {
	entity.EvidenceDigest = value
	if entity.Has == nil {
		entity.Has = &RetirementHas{}
	}
	entity.Has.EvidenceDigest = true
}
func (entity *Retirement) GetPhase() *string {
	return entity.Phase
}
func (entity *Retirement) SetPhase(value *string) {
	entity.Phase = value
	if entity.Has == nil {
		entity.Has = &RetirementHas{}
	}
	entity.Has.Phase = true
}
func (entity *Retirement) GetManifestDigest() *string {
	return entity.ManifestDigest
}
func (entity *Retirement) SetManifestDigest(value *string) {
	entity.ManifestDigest = value
	if entity.Has == nil {
		entity.Has = &RetirementHas{}
	}
	entity.Has.ManifestDigest = true
}
func (entity *Retirement) GetManifestCount() *int {
	return entity.ManifestCount
}
func (entity *Retirement) SetManifestCount(value *int) {
	entity.ManifestCount = value
	if entity.Has == nil {
		entity.Has = &RetirementHas{}
	}
	entity.Has.ManifestCount = true
}
func (entity *Retirement) GetReceiptCount() *int {
	return entity.ReceiptCount
}
func (entity *Retirement) SetReceiptCount(value *int) {
	entity.ReceiptCount = value
	if entity.Has == nil {
		entity.Has = &RetirementHas{}
	}
	entity.Has.ReceiptCount = true
}
func (entity *Retirement) GetAdoptionEvidenceJson() *string {
	return entity.AdoptionEvidenceJson
}
func (entity *Retirement) SetAdoptionEvidenceJson(value *string) {
	entity.AdoptionEvidenceJson = value
	if entity.Has == nil {
		entity.Has = &RetirementHas{}
	}
	entity.Has.AdoptionEvidenceJson = true
}
func (entity *Retirement) GetAdoptionDigest() *string {
	return entity.AdoptionDigest
}
func (entity *Retirement) SetAdoptionDigest(value *string) {
	entity.AdoptionDigest = value
	if entity.Has == nil {
		entity.Has = &RetirementHas{}
	}
	entity.Has.AdoptionDigest = true
}
func (entity *Retirement) GetCreatedAt() *string {
	return entity.CreatedAt
}
func (entity *Retirement) SetCreatedAt(value *string) {
	entity.CreatedAt = value
	if entity.Has == nil {
		entity.Has = &RetirementHas{}
	}
	entity.Has.CreatedAt = true
}
func (entity *Retirement) GetUpdatedAt() *string {
	return entity.UpdatedAt
}
func (entity *Retirement) SetUpdatedAt(value *string) {
	entity.UpdatedAt = value
	if entity.Has == nil {
		entity.Has = &RetirementHas{}
	}
	entity.Has.UpdatedAt = true
}
func (entity *Retirement) GetManifests() []*Manifest {
	return entity.Manifests
}
func (entity *Retirement) SetManifests(value []*Manifest) {
	entity.Manifests = value
	if entity.Has == nil {
		entity.Has = &RetirementHas{}
	}
	entity.Has.Manifests = true
}
func (entity *Retirement) GetAudit() []*Audit {
	return entity.Audit
}
func (entity *Retirement) SetAudit(value []*Audit) {
	entity.Audit = value
	if entity.Has == nil {
		entity.Has = &RetirementHas{}
	}
	entity.Has.Audit = true
}
func (entity *Manifest) GetNamespace() *string {
	return entity.Namespace
}
func (entity *Manifest) SetNamespace(value *string) {
	entity.Namespace = value
	if entity.Has == nil {
		entity.Has = &ManifestHas{}
	}
	entity.Has.Namespace = true
}
func (entity *Manifest) GetTransitionId() *string {
	return entity.TransitionId
}
func (entity *Manifest) SetTransitionId(value *string) {
	entity.TransitionId = value
	if entity.Has == nil {
		entity.Has = &ManifestHas{}
	}
	entity.Has.TransitionId = true
}
func (entity *Manifest) GetId() *string {
	return entity.Id
}
func (entity *Manifest) SetId(value *string) {
	entity.Id = value
	if entity.Has == nil {
		entity.Has = &ManifestHas{}
	}
	entity.Has.Id = true
}
func (entity *Manifest) GetDocumentIdentityJson() *string {
	return entity.DocumentIdentityJson
}
func (entity *Manifest) SetDocumentIdentityJson(value *string) {
	entity.DocumentIdentityJson = value
	if entity.Has == nil {
		entity.Has = &ManifestHas{}
	}
	entity.Has.DocumentIdentityJson = true
}
func (entity *Manifest) GetReceiptRevision() *int {
	return entity.ReceiptRevision
}
func (entity *Manifest) SetReceiptRevision(value *int) {
	entity.ReceiptRevision = value
	if entity.Has == nil {
		entity.Has = &ManifestHas{}
	}
	entity.Has.ReceiptRevision = true
}
func (entity *Manifest) GetReceiptCount() *int {
	return entity.ReceiptCount
}
func (entity *Manifest) SetReceiptCount(value *int) {
	entity.ReceiptCount = value
	if entity.Has == nil {
		entity.Has = &ManifestHas{}
	}
	entity.Has.ReceiptCount = true
}
func (entity *Manifest) GetCanonicalManifestJson() *string {
	return entity.CanonicalManifestJson
}
func (entity *Manifest) SetCanonicalManifestJson(value *string) {
	entity.CanonicalManifestJson = value
	if entity.Has == nil {
		entity.Has = &ManifestHas{}
	}
	entity.Has.CanonicalManifestJson = true
}
func (entity *Manifest) GetManifestDigest() *string {
	return entity.ManifestDigest
}
func (entity *Manifest) SetManifestDigest(value *string) {
	entity.ManifestDigest = value
	if entity.Has == nil {
		entity.Has = &ManifestHas{}
	}
	entity.Has.ManifestDigest = true
}
func (entity *Manifest) GetCreatedAt() *string {
	return entity.CreatedAt
}
func (entity *Manifest) SetCreatedAt(value *string) {
	entity.CreatedAt = value
	if entity.Has == nil {
		entity.Has = &ManifestHas{}
	}
	entity.Has.CreatedAt = true
}
func (entity *Audit) GetNamespace() *string {
	return entity.Namespace
}
func (entity *Audit) SetNamespace(value *string) {
	entity.Namespace = value
	if entity.Has == nil {
		entity.Has = &AuditHas{}
	}
	entity.Has.Namespace = true
}
func (entity *Audit) GetId() *string {
	return entity.Id
}
func (entity *Audit) SetId(value *string) {
	entity.Id = value
	if entity.Has == nil {
		entity.Has = &AuditHas{}
	}
	entity.Has.Id = true
}
func (entity *Audit) GetTransitionId() *string {
	return entity.TransitionId
}
func (entity *Audit) SetTransitionId(value *string) {
	entity.TransitionId = value
	if entity.Has == nil {
		entity.Has = &AuditHas{}
	}
	entity.Has.TransitionId = true
}
func (entity *Audit) GetPhase() *string {
	return entity.Phase
}
func (entity *Audit) SetPhase(value *string) {
	entity.Phase = value
	if entity.Has == nil {
		entity.Has = &AuditHas{}
	}
	entity.Has.Phase = true
}
func (entity *Audit) GetPriorRevision() *int {
	return entity.PriorRevision
}
func (entity *Audit) SetPriorRevision(value *int) {
	entity.PriorRevision = value
	if entity.Has == nil {
		entity.Has = &AuditHas{}
	}
	entity.Has.PriorRevision = true
}
func (entity *Audit) GetSequence() *int {
	return entity.Sequence
}
func (entity *Audit) SetSequence(value *int) {
	entity.Sequence = value
	if entity.Has == nil {
		entity.Has = &AuditHas{}
	}
	entity.Has.Sequence = true
}
func (entity *Audit) GetRequestId() *string {
	return entity.RequestId
}
func (entity *Audit) SetRequestId(value *string) {
	entity.RequestId = value
	if entity.Has == nil {
		entity.Has = &AuditHas{}
	}
	entity.Has.RequestId = true
}
func (entity *Audit) GetPayloadJson() *string {
	return entity.PayloadJson
}
func (entity *Audit) SetPayloadJson(value *string) {
	entity.PayloadJson = value
	if entity.Has == nil {
		entity.Has = &AuditHas{}
	}
	entity.Has.PayloadJson = true
}
func (entity *Audit) GetCreatedAt() *string {
	return entity.CreatedAt
}
func (entity *Audit) SetCreatedAt(value *string) {
	entity.CreatedAt = value
	if entity.Has == nil {
		entity.Has = &AuditHas{}
	}
	entity.Has.CreatedAt = true
}
func (input *WriteChromeRetirementInput) ProjectCurrentManifestsParentKeys(previous []*CurrentWriteChromeRetirementView) ([]struct {
	Namespace    *string "sqlx:\"namespace\""
	TransitionId *string "sqlx:\"transition_id\""
}, error) {
	result := []struct {
		Namespace    *string "sqlx:\"namespace\""
		TransitionId *string "sqlx:\"transition_id\""
	}{}
	for _, row := range previous {
		if row == nil {
			continue
		}
		if row.Namespace == nil || row.Id == nil {
			return nil, fmt2.Errorf("scoped parent identity is null")
		}
		result = append(result, struct {
			Namespace    *string "sqlx:\"namespace\""
			TransitionId *string "sqlx:\"transition_id\""
		}{Namespace: row.Namespace, TransitionId: row.Id})
	}
	return result, nil
}
func (input *WriteChromeRetirementInput) ProjectCurrentAuditParentKeys(previous []*CurrentWriteChromeRetirementView) ([]struct {
	Namespace    *string "sqlx:\"namespace\""
	TransitionId *string "sqlx:\"transition_id\""
}, error) {
	result := []struct {
		Namespace    *string "sqlx:\"namespace\""
		TransitionId *string "sqlx:\"transition_id\""
	}{}
	for _, row := range previous {
		if row == nil {
			continue
		}
		if row.Namespace == nil || row.Id == nil {
			return nil, fmt2.Errorf("scoped parent identity is null")
		}
		result = append(result, struct {
			Namespace    *string "sqlx:\"namespace\""
			TransitionId *string "sqlx:\"transition_id\""
		}{Namespace: row.Namespace, TransitionId: row.Id})
	}
	return result, nil
}
