// Code generated by Datly for PublishScenarioDraft; DO NOT EDIT.

package scenariopublish

func (input *PublishScenarioDraftInput) SetNamespace(value string) {
	if input == nil {
		return
	}
	input.Namespace = value
	if input.Has == nil {
		input.Has = &PublishScenarioDraftInputHas{}
	}
	input.Has.Namespace = true
}

func (input *PublishScenarioDraftInput) SetPublishScenarioDraft(value []*ScenarioRevision) {
	if input == nil {
		return
	}
	input.PublishScenarioDraft = value
	if input.Has == nil {
		input.Has = &PublishScenarioDraftInputHas{}
	}
	input.Has.PublishScenarioDraft = true
}
