// Code generated by Datly for PublishScenarioDraft; DO NOT EDIT.

package scenariopublish

// PublishScenarioDraftOutput is the generated output scaffold for PublishScenarioDraft.
type PublishScenarioDraftOutput struct {
	Data []*ScenarioRevision `parameter:"Data,kind=output,in=body,dataType=[]*ScenarioRevision"`
}
