// Code generated by Datly for AttachOperation; DO NOT EDIT.

package attachoperation

import (
	fmt2 "fmt"
	xshape "github.com/viant/x/shape"
)

func (entity *Run) GetRevision() *int {
	return entity.Revision
}
func (entity *Run) SetRevision(value *int) {
	entity.Revision = value
	if entity.Has == nil {
		entity.Has = &RunHas{}
	}
	entity.Has.Revision = true
}
func (entity *Run) GetNamespace() *string {
	return entity.Namespace
}
func (entity *Run) SetNamespace(value *string) {
	entity.Namespace = value
	if entity.Has == nil {
		entity.Has = &RunHas{}
	}
	entity.Has.Namespace = true
}
func (entity *Run) GetId() *string {
	return entity.Id
}
func (entity *Run) SetId(value *string) {
	entity.Id = value
	if entity.Has == nil {
		entity.Has = &RunHas{}
	}
	entity.Has.Id = true
}
func (entity *Run) GetPlanId() *string {
	return entity.PlanId
}
func (entity *Run) SetPlanId(value *string) {
	entity.PlanId = value
	if entity.Has == nil {
		entity.Has = &RunHas{}
	}
	entity.Has.PlanId = true
}
func (entity *Run) GetStatus() *string {
	return entity.Status
}
func (entity *Run) SetStatus(value *string) {
	entity.Status = value
	if entity.Has == nil {
		entity.Has = &RunHas{}
	}
	entity.Has.Status = true
}
func (entity *Run) GetEndlySessionId() *string {
	return entity.EndlySessionId
}
func (entity *Run) SetEndlySessionId(value *string) {
	entity.EndlySessionId = value
	if entity.Has == nil {
		entity.Has = &RunHas{}
	}
	entity.Has.EndlySessionId = true
}
func (entity *Run) GetEndlyOperationId() *string {
	return entity.EndlyOperationId
}
func (entity *Run) SetEndlyOperationId(value *string) {
	entity.EndlyOperationId = value
	if entity.Has == nil {
		entity.Has = &RunHas{}
	}
	entity.Has.EndlyOperationId = true
}
func (entity *Run) GetCreatedAt() *string {
	return entity.CreatedAt
}
func (entity *Run) SetCreatedAt(value *string) {
	entity.CreatedAt = value
	if entity.Has == nil {
		entity.Has = &RunHas{}
	}
	entity.Has.CreatedAt = true
}
func (entity *Run) GetUpdatedAt() *string {
	return entity.UpdatedAt
}
func (entity *Run) SetUpdatedAt(value *string) {
	entity.UpdatedAt = value
	if entity.Has == nil {
		entity.Has = &RunHas{}
	}
	entity.Has.UpdatedAt = true
}
func (entity *Run) GetEvents() []*Event {
	return entity.Events
}
func (entity *Run) SetEvents(value []*Event) {
	entity.Events = value
	if entity.Has == nil {
		entity.Has = &RunHas{}
	}
	entity.Has.Events = true
}
func (entity *Event) GetNamespace() *string {
	return entity.Namespace
}
func (entity *Event) SetNamespace(value *string) {
	entity.Namespace = value
	if entity.Has == nil {
		entity.Has = &EventHas{}
	}
	entity.Has.Namespace = true
}
func (entity *Event) GetId() *string {
	return entity.Id
}
func (entity *Event) SetId(value *string) {
	entity.Id = value
	if entity.Has == nil {
		entity.Has = &EventHas{}
	}
	entity.Has.Id = true
}
func (entity *Event) GetRunId() *string {
	return entity.RunId
}
func (entity *Event) SetRunId(value *string) {
	entity.RunId = value
	if entity.Has == nil {
		entity.Has = &EventHas{}
	}
	entity.Has.RunId = true
}
func (entity *Event) GetAttemptId() *string {
	return entity.AttemptId
}
func (entity *Event) SetAttemptId(value *string) {
	entity.AttemptId = value
	if entity.Has == nil {
		entity.Has = &EventHas{}
	}
	entity.Has.AttemptId = true
}
func (entity *Event) GetSequence() *int {
	return entity.Sequence
}
func (entity *Event) SetSequence(value *int) {
	entity.Sequence = value
	if entity.Has == nil {
		entity.Has = &EventHas{}
	}
	entity.Has.Sequence = true
}
func (entity *Event) GetKind() *string {
	return entity.Kind
}
func (entity *Event) SetKind(value *string) {
	entity.Kind = value
	if entity.Has == nil {
		entity.Has = &EventHas{}
	}
	entity.Has.Kind = true
}
func (entity *Event) GetPayloadJson() *string {
	return entity.PayloadJson
}
func (entity *Event) SetPayloadJson(value *string) {
	entity.PayloadJson = value
	if entity.Has == nil {
		entity.Has = &EventHas{}
	}
	entity.Has.PayloadJson = true
}
func (entity *Event) GetCreatedAt() *string {
	return entity.CreatedAt
}
func (entity *Event) SetCreatedAt(value *string) {
	entity.CreatedAt = value
	if entity.Has == nil {
		entity.Has = &EventHas{}
	}
	entity.Has.CreatedAt = true
}
func (input *AttachOperationInput) ProjectCurrentEventsParentKeys(previous []*CurrentAttachOperationView) ([]struct {
	Namespace *string "sqlx:\"namespace\""
	RunId     *string "sqlx:\"run_id\""
}, error) {
	result := []struct {
		Namespace *string "sqlx:\"namespace\""
		RunId     *string "sqlx:\"run_id\""
	}{}
	for _, row := range previous {
		if row == nil {
			continue
		}
		if row.Namespace == nil || row.Id == nil {
			return nil, fmt2.Errorf("scoped parent identity is null")
		}
		result = append(result, struct {
			Namespace *string "sqlx:\"namespace\""
			RunId     *string "sqlx:\"run_id\""
		}{Namespace: row.Namespace, RunId: row.Id})
	}
	return result, nil
}
func (input *AttachOperationInput) ProjectCurrentUnresolvedKeys(body []*Run, current []*CurrentAttachOperationView) ([]struct {
	Value0 string "sqlx:\"namespace\""
	Value1 string "sqlx:\"run_id\""
}, error) {
	type identity struct {
		K0 string
		K1 string
	}
	type lookupKey struct {
		Value0 string
		Value1 string
	}
	index := make(map[identity]*CurrentAttachOperationView)
	previousRows, err := (xshape.Collection[CurrentAttachOperationView]{}).Pointers(current)
	if err != nil {
		return nil, err
	}
	for _, previous := range previousRows {
		if previous == nil || !(previous.Namespace != nil && previous.Id != nil) {
			continue
		}
		key := identity{*previous.Namespace, *previous.Id}
		if _, exists := index[key]; exists {
			return nil, fmt2.Errorf("lookup current identity is duplicated")
		}
		index[key] = previous
	}
	seen := make(map[lookupKey]bool)
	var result []struct {
		Value0 string "sqlx:\"namespace\""
		Value1 string "sqlx:\"run_id\""
	}
	rows, err := (xshape.Collection[Run]{}).Pointers(body)
	if err != nil {
		return nil, err
	}
	for _, row := range rows {
		if row == nil {
			continue
		}
		var previous *CurrentAttachOperationView
		if row.Has != nil && row.Has.Namespace && row.Namespace != nil && row.Has.Id && row.Id != nil {
			previous = index[identity{*row.Namespace, *row.Id}]
		}
		var value0 string
		if row.Has != nil && row.Has.Namespace {
			if !(row.Namespace != nil) {
				continue
			}
			value0 = *row.Namespace
		} else {
			if previous == nil || !(previous.Namespace != nil) {
				continue
			}
			value0 = *previous.Namespace
		}
		var value1 string
		if row.Has != nil && row.Has.Id {
			if !(row.Id != nil) {
				continue
			}
			value1 = *row.Id
		} else {
			if previous == nil || !(previous.Id != nil) {
				continue
			}
			value1 = *previous.Id
		}
		tuple := lookupKey{value0, value1}
		if seen[tuple] {
			continue
		}
		seen[tuple] = true
		result = append(result, struct {
			Value0 string "sqlx:\"namespace\""
			Value1 string "sqlx:\"run_id\""
		}{value0, value1})
	}
	return result, nil
}
