// Code generated by Datly for AttachOperation; DO NOT EDIT.

package attachoperation

import (
	context "context"
	fmt "fmt"
	xshape "github.com/viant/x/shape"
	xhandler "github.com/viant/xdatly/handler"
	reflect "reflect"
)

type AttachOperationHandlerCurrentAttachOperationSlice []*CurrentAttachOperationView

func AttachOperationHandlerCurrentAttachOperationIndexByRevisionKey(value *CurrentAttachOperationView) (int, bool) {
	var zero int
	if value == nil {
		return zero, false
	}
	if value.Revision == nil {
		return zero, false
	}
	return *value.Revision, true
}

type AttachOperationHandlerCurrentAttachOperationIndexedByRevision map[int]*CurrentAttachOperationView

func (rows AttachOperationHandlerCurrentAttachOperationSlice) IndexByRevision() (AttachOperationHandlerCurrentAttachOperationIndexedByRevision, error) {
	result := make(AttachOperationHandlerCurrentAttachOperationIndexedByRevision)
	for _, row := range rows {
		key, ok := AttachOperationHandlerCurrentAttachOperationIndexByRevisionKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index AttachOperationHandlerCurrentAttachOperationSlice.IndexByRevision")
		}
		result[key] = row
	}
	return result, nil
}
func (index AttachOperationHandlerCurrentAttachOperationIndexedByRevision) Has(key int) bool {
	_, ok := index[key]
	return ok
}

type AttachOperationHandlerCurrentAttachOperationGroupedByRevision map[int][]*CurrentAttachOperationView

func (rows AttachOperationHandlerCurrentAttachOperationSlice) GroupByRevision() AttachOperationHandlerCurrentAttachOperationGroupedByRevision {
	result := make(AttachOperationHandlerCurrentAttachOperationGroupedByRevision)
	for _, row := range rows {
		key, ok := AttachOperationHandlerCurrentAttachOperationIndexByRevisionKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index AttachOperationHandlerCurrentAttachOperationGroupedByRevision) Has(key int) bool {
	_, ok := index[key]
	return ok
}
func AttachOperationHandlerCurrentAttachOperationIndexByNamespaceKey(value *CurrentAttachOperationView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.Namespace == nil {
		return zero, false
	}
	return *value.Namespace, true
}

type AttachOperationHandlerCurrentAttachOperationIndexedByNamespace map[string]*CurrentAttachOperationView

func (rows AttachOperationHandlerCurrentAttachOperationSlice) IndexByNamespace() (AttachOperationHandlerCurrentAttachOperationIndexedByNamespace, error) {
	result := make(AttachOperationHandlerCurrentAttachOperationIndexedByNamespace)
	for _, row := range rows {
		key, ok := AttachOperationHandlerCurrentAttachOperationIndexByNamespaceKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index AttachOperationHandlerCurrentAttachOperationSlice.IndexByNamespace")
		}
		result[key] = row
	}
	return result, nil
}
func (index AttachOperationHandlerCurrentAttachOperationIndexedByNamespace) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type AttachOperationHandlerCurrentAttachOperationGroupedByNamespace map[string][]*CurrentAttachOperationView

func (rows AttachOperationHandlerCurrentAttachOperationSlice) GroupByNamespace() AttachOperationHandlerCurrentAttachOperationGroupedByNamespace {
	result := make(AttachOperationHandlerCurrentAttachOperationGroupedByNamespace)
	for _, row := range rows {
		key, ok := AttachOperationHandlerCurrentAttachOperationIndexByNamespaceKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index AttachOperationHandlerCurrentAttachOperationGroupedByNamespace) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func AttachOperationHandlerCurrentAttachOperationIndexByIdKey(value *CurrentAttachOperationView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.Id == nil {
		return zero, false
	}
	return *value.Id, true
}

type AttachOperationHandlerCurrentAttachOperationIndexedById map[string]*CurrentAttachOperationView

func (rows AttachOperationHandlerCurrentAttachOperationSlice) IndexById() (AttachOperationHandlerCurrentAttachOperationIndexedById, error) {
	result := make(AttachOperationHandlerCurrentAttachOperationIndexedById)
	for _, row := range rows {
		key, ok := AttachOperationHandlerCurrentAttachOperationIndexByIdKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index AttachOperationHandlerCurrentAttachOperationSlice.IndexById")
		}
		result[key] = row
	}
	return result, nil
}
func (index AttachOperationHandlerCurrentAttachOperationIndexedById) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type AttachOperationHandlerCurrentAttachOperationGroupedById map[string][]*CurrentAttachOperationView

func (rows AttachOperationHandlerCurrentAttachOperationSlice) GroupById() AttachOperationHandlerCurrentAttachOperationGroupedById {
	result := make(AttachOperationHandlerCurrentAttachOperationGroupedById)
	for _, row := range rows {
		key, ok := AttachOperationHandlerCurrentAttachOperationIndexByIdKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index AttachOperationHandlerCurrentAttachOperationGroupedById) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func AttachOperationHandlerCurrentAttachOperationIndexByPlanIdKey(value *CurrentAttachOperationView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.PlanId == nil {
		return zero, false
	}
	return *value.PlanId, true
}

type AttachOperationHandlerCurrentAttachOperationIndexedByPlanId map[string]*CurrentAttachOperationView

func (rows AttachOperationHandlerCurrentAttachOperationSlice) IndexByPlanId() (AttachOperationHandlerCurrentAttachOperationIndexedByPlanId, error) {
	result := make(AttachOperationHandlerCurrentAttachOperationIndexedByPlanId)
	for _, row := range rows {
		key, ok := AttachOperationHandlerCurrentAttachOperationIndexByPlanIdKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index AttachOperationHandlerCurrentAttachOperationSlice.IndexByPlanId")
		}
		result[key] = row
	}
	return result, nil
}
func (index AttachOperationHandlerCurrentAttachOperationIndexedByPlanId) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type AttachOperationHandlerCurrentAttachOperationGroupedByPlanId map[string][]*CurrentAttachOperationView

func (rows AttachOperationHandlerCurrentAttachOperationSlice) GroupByPlanId() AttachOperationHandlerCurrentAttachOperationGroupedByPlanId {
	result := make(AttachOperationHandlerCurrentAttachOperationGroupedByPlanId)
	for _, row := range rows {
		key, ok := AttachOperationHandlerCurrentAttachOperationIndexByPlanIdKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index AttachOperationHandlerCurrentAttachOperationGroupedByPlanId) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func AttachOperationHandlerCurrentAttachOperationIndexByStatusKey(value *CurrentAttachOperationView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.Status == nil {
		return zero, false
	}
	return *value.Status, true
}

type AttachOperationHandlerCurrentAttachOperationIndexedByStatus map[string]*CurrentAttachOperationView

func (rows AttachOperationHandlerCurrentAttachOperationSlice) IndexByStatus() (AttachOperationHandlerCurrentAttachOperationIndexedByStatus, error) {
	result := make(AttachOperationHandlerCurrentAttachOperationIndexedByStatus)
	for _, row := range rows {
		key, ok := AttachOperationHandlerCurrentAttachOperationIndexByStatusKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index AttachOperationHandlerCurrentAttachOperationSlice.IndexByStatus")
		}
		result[key] = row
	}
	return result, nil
}
func (index AttachOperationHandlerCurrentAttachOperationIndexedByStatus) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type AttachOperationHandlerCurrentAttachOperationGroupedByStatus map[string][]*CurrentAttachOperationView

func (rows AttachOperationHandlerCurrentAttachOperationSlice) GroupByStatus() AttachOperationHandlerCurrentAttachOperationGroupedByStatus {
	result := make(AttachOperationHandlerCurrentAttachOperationGroupedByStatus)
	for _, row := range rows {
		key, ok := AttachOperationHandlerCurrentAttachOperationIndexByStatusKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index AttachOperationHandlerCurrentAttachOperationGroupedByStatus) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func AttachOperationHandlerCurrentAttachOperationIndexByEndlySessionIdKey(value *CurrentAttachOperationView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.EndlySessionId == nil {
		return zero, false
	}
	return *value.EndlySessionId, true
}

type AttachOperationHandlerCurrentAttachOperationIndexedByEndlySessionId map[string]*CurrentAttachOperationView

func (rows AttachOperationHandlerCurrentAttachOperationSlice) IndexByEndlySessionId() (AttachOperationHandlerCurrentAttachOperationIndexedByEndlySessionId, error) {
	result := make(AttachOperationHandlerCurrentAttachOperationIndexedByEndlySessionId)
	for _, row := range rows {
		key, ok := AttachOperationHandlerCurrentAttachOperationIndexByEndlySessionIdKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index AttachOperationHandlerCurrentAttachOperationSlice.IndexByEndlySessionId")
		}
		result[key] = row
	}
	return result, nil
}
func (index AttachOperationHandlerCurrentAttachOperationIndexedByEndlySessionId) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type AttachOperationHandlerCurrentAttachOperationGroupedByEndlySessionId map[string][]*CurrentAttachOperationView

func (rows AttachOperationHandlerCurrentAttachOperationSlice) GroupByEndlySessionId() AttachOperationHandlerCurrentAttachOperationGroupedByEndlySessionId {
	result := make(AttachOperationHandlerCurrentAttachOperationGroupedByEndlySessionId)
	for _, row := range rows {
		key, ok := AttachOperationHandlerCurrentAttachOperationIndexByEndlySessionIdKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index AttachOperationHandlerCurrentAttachOperationGroupedByEndlySessionId) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func AttachOperationHandlerCurrentAttachOperationIndexByEndlyOperationIdKey(value *CurrentAttachOperationView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.EndlyOperationId == nil {
		return zero, false
	}
	return *value.EndlyOperationId, true
}

type AttachOperationHandlerCurrentAttachOperationIndexedByEndlyOperationId map[string]*CurrentAttachOperationView

func (rows AttachOperationHandlerCurrentAttachOperationSlice) IndexByEndlyOperationId() (AttachOperationHandlerCurrentAttachOperationIndexedByEndlyOperationId, error) {
	result := make(AttachOperationHandlerCurrentAttachOperationIndexedByEndlyOperationId)
	for _, row := range rows {
		key, ok := AttachOperationHandlerCurrentAttachOperationIndexByEndlyOperationIdKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index AttachOperationHandlerCurrentAttachOperationSlice.IndexByEndlyOperationId")
		}
		result[key] = row
	}
	return result, nil
}
func (index AttachOperationHandlerCurrentAttachOperationIndexedByEndlyOperationId) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type AttachOperationHandlerCurrentAttachOperationGroupedByEndlyOperationId map[string][]*CurrentAttachOperationView

func (rows AttachOperationHandlerCurrentAttachOperationSlice) GroupByEndlyOperationId() AttachOperationHandlerCurrentAttachOperationGroupedByEndlyOperationId {
	result := make(AttachOperationHandlerCurrentAttachOperationGroupedByEndlyOperationId)
	for _, row := range rows {
		key, ok := AttachOperationHandlerCurrentAttachOperationIndexByEndlyOperationIdKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index AttachOperationHandlerCurrentAttachOperationGroupedByEndlyOperationId) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func AttachOperationHandlerCurrentAttachOperationIndexByCreatedAtKey(value *CurrentAttachOperationView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.CreatedAt == nil {
		return zero, false
	}
	return *value.CreatedAt, true
}

type AttachOperationHandlerCurrentAttachOperationIndexedByCreatedAt map[string]*CurrentAttachOperationView

func (rows AttachOperationHandlerCurrentAttachOperationSlice) IndexByCreatedAt() (AttachOperationHandlerCurrentAttachOperationIndexedByCreatedAt, error) {
	result := make(AttachOperationHandlerCurrentAttachOperationIndexedByCreatedAt)
	for _, row := range rows {
		key, ok := AttachOperationHandlerCurrentAttachOperationIndexByCreatedAtKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index AttachOperationHandlerCurrentAttachOperationSlice.IndexByCreatedAt")
		}
		result[key] = row
	}
	return result, nil
}
func (index AttachOperationHandlerCurrentAttachOperationIndexedByCreatedAt) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type AttachOperationHandlerCurrentAttachOperationGroupedByCreatedAt map[string][]*CurrentAttachOperationView

func (rows AttachOperationHandlerCurrentAttachOperationSlice) GroupByCreatedAt() AttachOperationHandlerCurrentAttachOperationGroupedByCreatedAt {
	result := make(AttachOperationHandlerCurrentAttachOperationGroupedByCreatedAt)
	for _, row := range rows {
		key, ok := AttachOperationHandlerCurrentAttachOperationIndexByCreatedAtKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index AttachOperationHandlerCurrentAttachOperationGroupedByCreatedAt) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func AttachOperationHandlerCurrentAttachOperationIndexByUpdatedAtKey(value *CurrentAttachOperationView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.UpdatedAt == nil {
		return zero, false
	}
	return *value.UpdatedAt, true
}

type AttachOperationHandlerCurrentAttachOperationIndexedByUpdatedAt map[string]*CurrentAttachOperationView

func (rows AttachOperationHandlerCurrentAttachOperationSlice) IndexByUpdatedAt() (AttachOperationHandlerCurrentAttachOperationIndexedByUpdatedAt, error) {
	result := make(AttachOperationHandlerCurrentAttachOperationIndexedByUpdatedAt)
	for _, row := range rows {
		key, ok := AttachOperationHandlerCurrentAttachOperationIndexByUpdatedAtKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index AttachOperationHandlerCurrentAttachOperationSlice.IndexByUpdatedAt")
		}
		result[key] = row
	}
	return result, nil
}
func (index AttachOperationHandlerCurrentAttachOperationIndexedByUpdatedAt) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type AttachOperationHandlerCurrentAttachOperationGroupedByUpdatedAt map[string][]*CurrentAttachOperationView

func (rows AttachOperationHandlerCurrentAttachOperationSlice) GroupByUpdatedAt() AttachOperationHandlerCurrentAttachOperationGroupedByUpdatedAt {
	result := make(AttachOperationHandlerCurrentAttachOperationGroupedByUpdatedAt)
	for _, row := range rows {
		key, ok := AttachOperationHandlerCurrentAttachOperationIndexByUpdatedAtKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index AttachOperationHandlerCurrentAttachOperationGroupedByUpdatedAt) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type AttachOperationHandlerCurrentAttachOperationKey struct {
	Namespace string
	Id        string
}

func AttachOperationHandlerCurrentAttachOperationIndexByKeyKey(value *CurrentAttachOperationView) (AttachOperationHandlerCurrentAttachOperationKey, bool) {
	var zero AttachOperationHandlerCurrentAttachOperationKey
	if value == nil {
		return zero, false
	}
	if value.Namespace == nil {
		return zero, false
	}
	if value.Id == nil {
		return zero, false
	}
	return AttachOperationHandlerCurrentAttachOperationKey{Namespace: *value.Namespace, Id: *value.Id}, true
}

type AttachOperationHandlerCurrentAttachOperationIndexedByKey map[AttachOperationHandlerCurrentAttachOperationKey]*CurrentAttachOperationView

func (rows AttachOperationHandlerCurrentAttachOperationSlice) IndexByKey() (AttachOperationHandlerCurrentAttachOperationIndexedByKey, error) {
	result := make(AttachOperationHandlerCurrentAttachOperationIndexedByKey)
	for _, row := range rows {
		key, ok := AttachOperationHandlerCurrentAttachOperationIndexByKeyKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index AttachOperationHandlerCurrentAttachOperationSlice.IndexByKey")
		}
		result[key] = row
	}
	return result, nil
}
func (index AttachOperationHandlerCurrentAttachOperationIndexedByKey) Has(key AttachOperationHandlerCurrentAttachOperationKey) bool {
	_, ok := index[key]
	return ok
}

type AttachOperationHandlerCurrentAttachOperationGroupedByKey map[AttachOperationHandlerCurrentAttachOperationKey][]*CurrentAttachOperationView

func (rows AttachOperationHandlerCurrentAttachOperationSlice) GroupByKey() AttachOperationHandlerCurrentAttachOperationGroupedByKey {
	result := make(AttachOperationHandlerCurrentAttachOperationGroupedByKey)
	for _, row := range rows {
		key, ok := AttachOperationHandlerCurrentAttachOperationIndexByKeyKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index AttachOperationHandlerCurrentAttachOperationGroupedByKey) Has(key AttachOperationHandlerCurrentAttachOperationKey) bool {
	_, ok := index[key]
	return ok
}

type AttachOperationHandlerCurrentEventsSlice []*CurrentEventsView

func AttachOperationHandlerCurrentEventsIndexByNamespaceKey(value *CurrentEventsView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.Namespace == nil {
		return zero, false
	}
	return *value.Namespace, true
}

type AttachOperationHandlerCurrentEventsIndexedByNamespace map[string]*CurrentEventsView

func (rows AttachOperationHandlerCurrentEventsSlice) IndexByNamespace() (AttachOperationHandlerCurrentEventsIndexedByNamespace, error) {
	result := make(AttachOperationHandlerCurrentEventsIndexedByNamespace)
	for _, row := range rows {
		key, ok := AttachOperationHandlerCurrentEventsIndexByNamespaceKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index AttachOperationHandlerCurrentEventsSlice.IndexByNamespace")
		}
		result[key] = row
	}
	return result, nil
}
func (index AttachOperationHandlerCurrentEventsIndexedByNamespace) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type AttachOperationHandlerCurrentEventsGroupedByNamespace map[string][]*CurrentEventsView

func (rows AttachOperationHandlerCurrentEventsSlice) GroupByNamespace() AttachOperationHandlerCurrentEventsGroupedByNamespace {
	result := make(AttachOperationHandlerCurrentEventsGroupedByNamespace)
	for _, row := range rows {
		key, ok := AttachOperationHandlerCurrentEventsIndexByNamespaceKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index AttachOperationHandlerCurrentEventsGroupedByNamespace) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func AttachOperationHandlerCurrentEventsIndexByIdKey(value *CurrentEventsView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.Id == nil {
		return zero, false
	}
	return *value.Id, true
}

type AttachOperationHandlerCurrentEventsIndexedById map[string]*CurrentEventsView

func (rows AttachOperationHandlerCurrentEventsSlice) IndexById() (AttachOperationHandlerCurrentEventsIndexedById, error) {
	result := make(AttachOperationHandlerCurrentEventsIndexedById)
	for _, row := range rows {
		key, ok := AttachOperationHandlerCurrentEventsIndexByIdKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index AttachOperationHandlerCurrentEventsSlice.IndexById")
		}
		result[key] = row
	}
	return result, nil
}
func (index AttachOperationHandlerCurrentEventsIndexedById) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type AttachOperationHandlerCurrentEventsGroupedById map[string][]*CurrentEventsView

func (rows AttachOperationHandlerCurrentEventsSlice) GroupById() AttachOperationHandlerCurrentEventsGroupedById {
	result := make(AttachOperationHandlerCurrentEventsGroupedById)
	for _, row := range rows {
		key, ok := AttachOperationHandlerCurrentEventsIndexByIdKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index AttachOperationHandlerCurrentEventsGroupedById) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func AttachOperationHandlerCurrentEventsIndexByRunIdKey(value *CurrentEventsView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.RunId == nil {
		return zero, false
	}
	return *value.RunId, true
}

type AttachOperationHandlerCurrentEventsIndexedByRunId map[string]*CurrentEventsView

func (rows AttachOperationHandlerCurrentEventsSlice) IndexByRunId() (AttachOperationHandlerCurrentEventsIndexedByRunId, error) {
	result := make(AttachOperationHandlerCurrentEventsIndexedByRunId)
	for _, row := range rows {
		key, ok := AttachOperationHandlerCurrentEventsIndexByRunIdKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index AttachOperationHandlerCurrentEventsSlice.IndexByRunId")
		}
		result[key] = row
	}
	return result, nil
}
func (index AttachOperationHandlerCurrentEventsIndexedByRunId) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type AttachOperationHandlerCurrentEventsGroupedByRunId map[string][]*CurrentEventsView

func (rows AttachOperationHandlerCurrentEventsSlice) GroupByRunId() AttachOperationHandlerCurrentEventsGroupedByRunId {
	result := make(AttachOperationHandlerCurrentEventsGroupedByRunId)
	for _, row := range rows {
		key, ok := AttachOperationHandlerCurrentEventsIndexByRunIdKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index AttachOperationHandlerCurrentEventsGroupedByRunId) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func AttachOperationHandlerCurrentEventsIndexByAttemptIdKey(value *CurrentEventsView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.AttemptId == nil {
		return zero, false
	}
	return *value.AttemptId, true
}

type AttachOperationHandlerCurrentEventsIndexedByAttemptId map[string]*CurrentEventsView

func (rows AttachOperationHandlerCurrentEventsSlice) IndexByAttemptId() (AttachOperationHandlerCurrentEventsIndexedByAttemptId, error) {
	result := make(AttachOperationHandlerCurrentEventsIndexedByAttemptId)
	for _, row := range rows {
		key, ok := AttachOperationHandlerCurrentEventsIndexByAttemptIdKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index AttachOperationHandlerCurrentEventsSlice.IndexByAttemptId")
		}
		result[key] = row
	}
	return result, nil
}
func (index AttachOperationHandlerCurrentEventsIndexedByAttemptId) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type AttachOperationHandlerCurrentEventsGroupedByAttemptId map[string][]*CurrentEventsView

func (rows AttachOperationHandlerCurrentEventsSlice) GroupByAttemptId() AttachOperationHandlerCurrentEventsGroupedByAttemptId {
	result := make(AttachOperationHandlerCurrentEventsGroupedByAttemptId)
	for _, row := range rows {
		key, ok := AttachOperationHandlerCurrentEventsIndexByAttemptIdKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index AttachOperationHandlerCurrentEventsGroupedByAttemptId) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func AttachOperationHandlerCurrentEventsIndexBySequenceKey(value *CurrentEventsView) (int, bool) {
	var zero int
	if value == nil {
		return zero, false
	}
	if value.Sequence == nil {
		return zero, false
	}
	return *value.Sequence, true
}

type AttachOperationHandlerCurrentEventsIndexedBySequence map[int]*CurrentEventsView

func (rows AttachOperationHandlerCurrentEventsSlice) IndexBySequence() (AttachOperationHandlerCurrentEventsIndexedBySequence, error) {
	result := make(AttachOperationHandlerCurrentEventsIndexedBySequence)
	for _, row := range rows {
		key, ok := AttachOperationHandlerCurrentEventsIndexBySequenceKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index AttachOperationHandlerCurrentEventsSlice.IndexBySequence")
		}
		result[key] = row
	}
	return result, nil
}
func (index AttachOperationHandlerCurrentEventsIndexedBySequence) Has(key int) bool {
	_, ok := index[key]
	return ok
}

type AttachOperationHandlerCurrentEventsGroupedBySequence map[int][]*CurrentEventsView

func (rows AttachOperationHandlerCurrentEventsSlice) GroupBySequence() AttachOperationHandlerCurrentEventsGroupedBySequence {
	result := make(AttachOperationHandlerCurrentEventsGroupedBySequence)
	for _, row := range rows {
		key, ok := AttachOperationHandlerCurrentEventsIndexBySequenceKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index AttachOperationHandlerCurrentEventsGroupedBySequence) Has(key int) bool {
	_, ok := index[key]
	return ok
}
func AttachOperationHandlerCurrentEventsIndexByKindKey(value *CurrentEventsView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.Kind == nil {
		return zero, false
	}
	return *value.Kind, true
}

type AttachOperationHandlerCurrentEventsIndexedByKind map[string]*CurrentEventsView

func (rows AttachOperationHandlerCurrentEventsSlice) IndexByKind() (AttachOperationHandlerCurrentEventsIndexedByKind, error) {
	result := make(AttachOperationHandlerCurrentEventsIndexedByKind)
	for _, row := range rows {
		key, ok := AttachOperationHandlerCurrentEventsIndexByKindKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index AttachOperationHandlerCurrentEventsSlice.IndexByKind")
		}
		result[key] = row
	}
	return result, nil
}
func (index AttachOperationHandlerCurrentEventsIndexedByKind) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type AttachOperationHandlerCurrentEventsGroupedByKind map[string][]*CurrentEventsView

func (rows AttachOperationHandlerCurrentEventsSlice) GroupByKind() AttachOperationHandlerCurrentEventsGroupedByKind {
	result := make(AttachOperationHandlerCurrentEventsGroupedByKind)
	for _, row := range rows {
		key, ok := AttachOperationHandlerCurrentEventsIndexByKindKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index AttachOperationHandlerCurrentEventsGroupedByKind) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func AttachOperationHandlerCurrentEventsIndexByPayloadJsonKey(value *CurrentEventsView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.PayloadJson == nil {
		return zero, false
	}
	return *value.PayloadJson, true
}

type AttachOperationHandlerCurrentEventsIndexedByPayloadJson map[string]*CurrentEventsView

func (rows AttachOperationHandlerCurrentEventsSlice) IndexByPayloadJson() (AttachOperationHandlerCurrentEventsIndexedByPayloadJson, error) {
	result := make(AttachOperationHandlerCurrentEventsIndexedByPayloadJson)
	for _, row := range rows {
		key, ok := AttachOperationHandlerCurrentEventsIndexByPayloadJsonKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index AttachOperationHandlerCurrentEventsSlice.IndexByPayloadJson")
		}
		result[key] = row
	}
	return result, nil
}
func (index AttachOperationHandlerCurrentEventsIndexedByPayloadJson) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type AttachOperationHandlerCurrentEventsGroupedByPayloadJson map[string][]*CurrentEventsView

func (rows AttachOperationHandlerCurrentEventsSlice) GroupByPayloadJson() AttachOperationHandlerCurrentEventsGroupedByPayloadJson {
	result := make(AttachOperationHandlerCurrentEventsGroupedByPayloadJson)
	for _, row := range rows {
		key, ok := AttachOperationHandlerCurrentEventsIndexByPayloadJsonKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index AttachOperationHandlerCurrentEventsGroupedByPayloadJson) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func AttachOperationHandlerCurrentEventsIndexByCreatedAtKey(value *CurrentEventsView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.CreatedAt == nil {
		return zero, false
	}
	return *value.CreatedAt, true
}

type AttachOperationHandlerCurrentEventsIndexedByCreatedAt map[string]*CurrentEventsView

func (rows AttachOperationHandlerCurrentEventsSlice) IndexByCreatedAt() (AttachOperationHandlerCurrentEventsIndexedByCreatedAt, error) {
	result := make(AttachOperationHandlerCurrentEventsIndexedByCreatedAt)
	for _, row := range rows {
		key, ok := AttachOperationHandlerCurrentEventsIndexByCreatedAtKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index AttachOperationHandlerCurrentEventsSlice.IndexByCreatedAt")
		}
		result[key] = row
	}
	return result, nil
}
func (index AttachOperationHandlerCurrentEventsIndexedByCreatedAt) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type AttachOperationHandlerCurrentEventsGroupedByCreatedAt map[string][]*CurrentEventsView

func (rows AttachOperationHandlerCurrentEventsSlice) GroupByCreatedAt() AttachOperationHandlerCurrentEventsGroupedByCreatedAt {
	result := make(AttachOperationHandlerCurrentEventsGroupedByCreatedAt)
	for _, row := range rows {
		key, ok := AttachOperationHandlerCurrentEventsIndexByCreatedAtKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index AttachOperationHandlerCurrentEventsGroupedByCreatedAt) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type AttachOperationHandlerCurrentEventsKey struct {
	Namespace string
	Id        string
}

func AttachOperationHandlerCurrentEventsIndexByKeyKey(value *CurrentEventsView) (AttachOperationHandlerCurrentEventsKey, bool) {
	var zero AttachOperationHandlerCurrentEventsKey
	if value == nil {
		return zero, false
	}
	if value.Namespace == nil {
		return zero, false
	}
	if value.Id == nil {
		return zero, false
	}
	return AttachOperationHandlerCurrentEventsKey{Namespace: *value.Namespace, Id: *value.Id}, true
}

type AttachOperationHandlerCurrentEventsIndexedByKey map[AttachOperationHandlerCurrentEventsKey]*CurrentEventsView

func (rows AttachOperationHandlerCurrentEventsSlice) IndexByKey() (AttachOperationHandlerCurrentEventsIndexedByKey, error) {
	result := make(AttachOperationHandlerCurrentEventsIndexedByKey)
	for _, row := range rows {
		key, ok := AttachOperationHandlerCurrentEventsIndexByKeyKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index AttachOperationHandlerCurrentEventsSlice.IndexByKey")
		}
		result[key] = row
	}
	return result, nil
}
func (index AttachOperationHandlerCurrentEventsIndexedByKey) Has(key AttachOperationHandlerCurrentEventsKey) bool {
	_, ok := index[key]
	return ok
}

type AttachOperationHandlerCurrentEventsGroupedByKey map[AttachOperationHandlerCurrentEventsKey][]*CurrentEventsView

func (rows AttachOperationHandlerCurrentEventsSlice) GroupByKey() AttachOperationHandlerCurrentEventsGroupedByKey {
	result := make(AttachOperationHandlerCurrentEventsGroupedByKey)
	for _, row := range rows {
		key, ok := AttachOperationHandlerCurrentEventsIndexByKeyKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index AttachOperationHandlerCurrentEventsGroupedByKey) Has(key AttachOperationHandlerCurrentEventsKey) bool {
	_, ok := index[key]
	return ok
}

type AttachOperationHandlerCurrentEventsNamespaceAndRunIdKey struct {
	Namespace string
	RunId     string
}

func AttachOperationHandlerCurrentEventsIndexByNamespaceAndRunIdKey(value *CurrentEventsView) (AttachOperationHandlerCurrentEventsNamespaceAndRunIdKey, bool) {
	var zero AttachOperationHandlerCurrentEventsNamespaceAndRunIdKey
	if value == nil {
		return zero, false
	}
	if value.Namespace == nil {
		return zero, false
	}
	if value.RunId == nil {
		return zero, false
	}
	return AttachOperationHandlerCurrentEventsNamespaceAndRunIdKey{Namespace: *value.Namespace, RunId: *value.RunId}, true
}

type AttachOperationHandlerCurrentEventsIndexedByNamespaceAndRunId map[AttachOperationHandlerCurrentEventsNamespaceAndRunIdKey]*CurrentEventsView

func (rows AttachOperationHandlerCurrentEventsSlice) IndexByNamespaceAndRunId() (AttachOperationHandlerCurrentEventsIndexedByNamespaceAndRunId, error) {
	result := make(AttachOperationHandlerCurrentEventsIndexedByNamespaceAndRunId)
	for _, row := range rows {
		key, ok := AttachOperationHandlerCurrentEventsIndexByNamespaceAndRunIdKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index AttachOperationHandlerCurrentEventsSlice.IndexByNamespaceAndRunId")
		}
		result[key] = row
	}
	return result, nil
}
func (index AttachOperationHandlerCurrentEventsIndexedByNamespaceAndRunId) Has(key AttachOperationHandlerCurrentEventsNamespaceAndRunIdKey) bool {
	_, ok := index[key]
	return ok
}

type AttachOperationHandlerCurrentEventsGroupedByNamespaceAndRunId map[AttachOperationHandlerCurrentEventsNamespaceAndRunIdKey][]*CurrentEventsView

func (rows AttachOperationHandlerCurrentEventsSlice) GroupByNamespaceAndRunId() AttachOperationHandlerCurrentEventsGroupedByNamespaceAndRunId {
	result := make(AttachOperationHandlerCurrentEventsGroupedByNamespaceAndRunId)
	for _, row := range rows {
		key, ok := AttachOperationHandlerCurrentEventsIndexByNamespaceAndRunIdKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index AttachOperationHandlerCurrentEventsGroupedByNamespaceAndRunId) Has(key AttachOperationHandlerCurrentEventsNamespaceAndRunIdKey) bool {
	_, ok := index[key]
	return ok
}

type AttachOperationHandlerCurrentUnresolvedSlice []*CurrentUnresolvedView

func AttachOperationHandlerCurrentUnresolvedIndexByNamespaceKey(value *CurrentUnresolvedView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.Namespace == nil {
		return zero, false
	}
	return *value.Namespace, true
}

type AttachOperationHandlerCurrentUnresolvedIndexedByNamespace map[string]*CurrentUnresolvedView

func (rows AttachOperationHandlerCurrentUnresolvedSlice) IndexByNamespace() (AttachOperationHandlerCurrentUnresolvedIndexedByNamespace, error) {
	result := make(AttachOperationHandlerCurrentUnresolvedIndexedByNamespace)
	for _, row := range rows {
		key, ok := AttachOperationHandlerCurrentUnresolvedIndexByNamespaceKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index AttachOperationHandlerCurrentUnresolvedSlice.IndexByNamespace")
		}
		result[key] = row
	}
	return result, nil
}
func (index AttachOperationHandlerCurrentUnresolvedIndexedByNamespace) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type AttachOperationHandlerCurrentUnresolvedGroupedByNamespace map[string][]*CurrentUnresolvedView

func (rows AttachOperationHandlerCurrentUnresolvedSlice) GroupByNamespace() AttachOperationHandlerCurrentUnresolvedGroupedByNamespace {
	result := make(AttachOperationHandlerCurrentUnresolvedGroupedByNamespace)
	for _, row := range rows {
		key, ok := AttachOperationHandlerCurrentUnresolvedIndexByNamespaceKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index AttachOperationHandlerCurrentUnresolvedGroupedByNamespace) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func AttachOperationHandlerCurrentUnresolvedIndexByIdKey(value *CurrentUnresolvedView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.Id == nil {
		return zero, false
	}
	return *value.Id, true
}

type AttachOperationHandlerCurrentUnresolvedIndexedById map[string]*CurrentUnresolvedView

func (rows AttachOperationHandlerCurrentUnresolvedSlice) IndexById() (AttachOperationHandlerCurrentUnresolvedIndexedById, error) {
	result := make(AttachOperationHandlerCurrentUnresolvedIndexedById)
	for _, row := range rows {
		key, ok := AttachOperationHandlerCurrentUnresolvedIndexByIdKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index AttachOperationHandlerCurrentUnresolvedSlice.IndexById")
		}
		result[key] = row
	}
	return result, nil
}
func (index AttachOperationHandlerCurrentUnresolvedIndexedById) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type AttachOperationHandlerCurrentUnresolvedGroupedById map[string][]*CurrentUnresolvedView

func (rows AttachOperationHandlerCurrentUnresolvedSlice) GroupById() AttachOperationHandlerCurrentUnresolvedGroupedById {
	result := make(AttachOperationHandlerCurrentUnresolvedGroupedById)
	for _, row := range rows {
		key, ok := AttachOperationHandlerCurrentUnresolvedIndexByIdKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index AttachOperationHandlerCurrentUnresolvedGroupedById) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func AttachOperationHandlerCurrentUnresolvedIndexByAttemptIdKey(value *CurrentUnresolvedView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.AttemptId == nil {
		return zero, false
	}
	return *value.AttemptId, true
}

type AttachOperationHandlerCurrentUnresolvedIndexedByAttemptId map[string]*CurrentUnresolvedView

func (rows AttachOperationHandlerCurrentUnresolvedSlice) IndexByAttemptId() (AttachOperationHandlerCurrentUnresolvedIndexedByAttemptId, error) {
	result := make(AttachOperationHandlerCurrentUnresolvedIndexedByAttemptId)
	for _, row := range rows {
		key, ok := AttachOperationHandlerCurrentUnresolvedIndexByAttemptIdKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index AttachOperationHandlerCurrentUnresolvedSlice.IndexByAttemptId")
		}
		result[key] = row
	}
	return result, nil
}
func (index AttachOperationHandlerCurrentUnresolvedIndexedByAttemptId) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type AttachOperationHandlerCurrentUnresolvedGroupedByAttemptId map[string][]*CurrentUnresolvedView

func (rows AttachOperationHandlerCurrentUnresolvedSlice) GroupByAttemptId() AttachOperationHandlerCurrentUnresolvedGroupedByAttemptId {
	result := make(AttachOperationHandlerCurrentUnresolvedGroupedByAttemptId)
	for _, row := range rows {
		key, ok := AttachOperationHandlerCurrentUnresolvedIndexByAttemptIdKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index AttachOperationHandlerCurrentUnresolvedGroupedByAttemptId) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func AttachOperationHandlerCurrentUnresolvedIndexByRunIdKey(value *CurrentUnresolvedView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.RunId == nil {
		return zero, false
	}
	return *value.RunId, true
}

type AttachOperationHandlerCurrentUnresolvedIndexedByRunId map[string]*CurrentUnresolvedView

func (rows AttachOperationHandlerCurrentUnresolvedSlice) IndexByRunId() (AttachOperationHandlerCurrentUnresolvedIndexedByRunId, error) {
	result := make(AttachOperationHandlerCurrentUnresolvedIndexedByRunId)
	for _, row := range rows {
		key, ok := AttachOperationHandlerCurrentUnresolvedIndexByRunIdKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index AttachOperationHandlerCurrentUnresolvedSlice.IndexByRunId")
		}
		result[key] = row
	}
	return result, nil
}
func (index AttachOperationHandlerCurrentUnresolvedIndexedByRunId) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type AttachOperationHandlerCurrentUnresolvedGroupedByRunId map[string][]*CurrentUnresolvedView

func (rows AttachOperationHandlerCurrentUnresolvedSlice) GroupByRunId() AttachOperationHandlerCurrentUnresolvedGroupedByRunId {
	result := make(AttachOperationHandlerCurrentUnresolvedGroupedByRunId)
	for _, row := range rows {
		key, ok := AttachOperationHandlerCurrentUnresolvedIndexByRunIdKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index AttachOperationHandlerCurrentUnresolvedGroupedByRunId) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func AttachOperationHandlerCurrentUnresolvedIndexByBusinessKeyKey(value *CurrentUnresolvedView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.BusinessKey == nil {
		return zero, false
	}
	return *value.BusinessKey, true
}

type AttachOperationHandlerCurrentUnresolvedIndexedByBusinessKey map[string]*CurrentUnresolvedView

func (rows AttachOperationHandlerCurrentUnresolvedSlice) IndexByBusinessKey() (AttachOperationHandlerCurrentUnresolvedIndexedByBusinessKey, error) {
	result := make(AttachOperationHandlerCurrentUnresolvedIndexedByBusinessKey)
	for _, row := range rows {
		key, ok := AttachOperationHandlerCurrentUnresolvedIndexByBusinessKeyKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index AttachOperationHandlerCurrentUnresolvedSlice.IndexByBusinessKey")
		}
		result[key] = row
	}
	return result, nil
}
func (index AttachOperationHandlerCurrentUnresolvedIndexedByBusinessKey) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type AttachOperationHandlerCurrentUnresolvedGroupedByBusinessKey map[string][]*CurrentUnresolvedView

func (rows AttachOperationHandlerCurrentUnresolvedSlice) GroupByBusinessKey() AttachOperationHandlerCurrentUnresolvedGroupedByBusinessKey {
	result := make(AttachOperationHandlerCurrentUnresolvedGroupedByBusinessKey)
	for _, row := range rows {
		key, ok := AttachOperationHandlerCurrentUnresolvedIndexByBusinessKeyKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index AttachOperationHandlerCurrentUnresolvedGroupedByBusinessKey) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func AttachOperationHandlerCurrentUnresolvedIndexByStateKey(value *CurrentUnresolvedView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.State == nil {
		return zero, false
	}
	return *value.State, true
}

type AttachOperationHandlerCurrentUnresolvedIndexedByState map[string]*CurrentUnresolvedView

func (rows AttachOperationHandlerCurrentUnresolvedSlice) IndexByState() (AttachOperationHandlerCurrentUnresolvedIndexedByState, error) {
	result := make(AttachOperationHandlerCurrentUnresolvedIndexedByState)
	for _, row := range rows {
		key, ok := AttachOperationHandlerCurrentUnresolvedIndexByStateKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index AttachOperationHandlerCurrentUnresolvedSlice.IndexByState")
		}
		result[key] = row
	}
	return result, nil
}
func (index AttachOperationHandlerCurrentUnresolvedIndexedByState) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type AttachOperationHandlerCurrentUnresolvedGroupedByState map[string][]*CurrentUnresolvedView

func (rows AttachOperationHandlerCurrentUnresolvedSlice) GroupByState() AttachOperationHandlerCurrentUnresolvedGroupedByState {
	result := make(AttachOperationHandlerCurrentUnresolvedGroupedByState)
	for _, row := range rows {
		key, ok := AttachOperationHandlerCurrentUnresolvedIndexByStateKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index AttachOperationHandlerCurrentUnresolvedGroupedByState) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func AttachOperationHandlerCurrentUnresolvedIndexByRevisionKey(value *CurrentUnresolvedView) (int, bool) {
	var zero int
	if value == nil {
		return zero, false
	}
	if value.Revision == nil {
		return zero, false
	}
	return *value.Revision, true
}

type AttachOperationHandlerCurrentUnresolvedIndexedByRevision map[int]*CurrentUnresolvedView

func (rows AttachOperationHandlerCurrentUnresolvedSlice) IndexByRevision() (AttachOperationHandlerCurrentUnresolvedIndexedByRevision, error) {
	result := make(AttachOperationHandlerCurrentUnresolvedIndexedByRevision)
	for _, row := range rows {
		key, ok := AttachOperationHandlerCurrentUnresolvedIndexByRevisionKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index AttachOperationHandlerCurrentUnresolvedSlice.IndexByRevision")
		}
		result[key] = row
	}
	return result, nil
}
func (index AttachOperationHandlerCurrentUnresolvedIndexedByRevision) Has(key int) bool {
	_, ok := index[key]
	return ok
}

type AttachOperationHandlerCurrentUnresolvedGroupedByRevision map[int][]*CurrentUnresolvedView

func (rows AttachOperationHandlerCurrentUnresolvedSlice) GroupByRevision() AttachOperationHandlerCurrentUnresolvedGroupedByRevision {
	result := make(AttachOperationHandlerCurrentUnresolvedGroupedByRevision)
	for _, row := range rows {
		key, ok := AttachOperationHandlerCurrentUnresolvedIndexByRevisionKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index AttachOperationHandlerCurrentUnresolvedGroupedByRevision) Has(key int) bool {
	_, ok := index[key]
	return ok
}
func AttachOperationHandlerCurrentUnresolvedIndexByEvidenceJsonKey(value *CurrentUnresolvedView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.EvidenceJson == nil {
		return zero, false
	}
	return *value.EvidenceJson, true
}

type AttachOperationHandlerCurrentUnresolvedIndexedByEvidenceJson map[string]*CurrentUnresolvedView

func (rows AttachOperationHandlerCurrentUnresolvedSlice) IndexByEvidenceJson() (AttachOperationHandlerCurrentUnresolvedIndexedByEvidenceJson, error) {
	result := make(AttachOperationHandlerCurrentUnresolvedIndexedByEvidenceJson)
	for _, row := range rows {
		key, ok := AttachOperationHandlerCurrentUnresolvedIndexByEvidenceJsonKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index AttachOperationHandlerCurrentUnresolvedSlice.IndexByEvidenceJson")
		}
		result[key] = row
	}
	return result, nil
}
func (index AttachOperationHandlerCurrentUnresolvedIndexedByEvidenceJson) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type AttachOperationHandlerCurrentUnresolvedGroupedByEvidenceJson map[string][]*CurrentUnresolvedView

func (rows AttachOperationHandlerCurrentUnresolvedSlice) GroupByEvidenceJson() AttachOperationHandlerCurrentUnresolvedGroupedByEvidenceJson {
	result := make(AttachOperationHandlerCurrentUnresolvedGroupedByEvidenceJson)
	for _, row := range rows {
		key, ok := AttachOperationHandlerCurrentUnresolvedIndexByEvidenceJsonKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index AttachOperationHandlerCurrentUnresolvedGroupedByEvidenceJson) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type AttachOperationHandlerCurrentUnresolvedKey struct {
	Namespace string
	Id        string
}

func AttachOperationHandlerCurrentUnresolvedIndexByKeyKey(value *CurrentUnresolvedView) (AttachOperationHandlerCurrentUnresolvedKey, bool) {
	var zero AttachOperationHandlerCurrentUnresolvedKey
	if value == nil {
		return zero, false
	}
	if value.Namespace == nil {
		return zero, false
	}
	if value.Id == nil {
		return zero, false
	}
	return AttachOperationHandlerCurrentUnresolvedKey{Namespace: *value.Namespace, Id: *value.Id}, true
}

type AttachOperationHandlerCurrentUnresolvedIndexedByKey map[AttachOperationHandlerCurrentUnresolvedKey]*CurrentUnresolvedView

func (rows AttachOperationHandlerCurrentUnresolvedSlice) IndexByKey() (AttachOperationHandlerCurrentUnresolvedIndexedByKey, error) {
	result := make(AttachOperationHandlerCurrentUnresolvedIndexedByKey)
	for _, row := range rows {
		key, ok := AttachOperationHandlerCurrentUnresolvedIndexByKeyKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index AttachOperationHandlerCurrentUnresolvedSlice.IndexByKey")
		}
		result[key] = row
	}
	return result, nil
}
func (index AttachOperationHandlerCurrentUnresolvedIndexedByKey) Has(key AttachOperationHandlerCurrentUnresolvedKey) bool {
	_, ok := index[key]
	return ok
}

type AttachOperationHandlerCurrentUnresolvedGroupedByKey map[AttachOperationHandlerCurrentUnresolvedKey][]*CurrentUnresolvedView

func (rows AttachOperationHandlerCurrentUnresolvedSlice) GroupByKey() AttachOperationHandlerCurrentUnresolvedGroupedByKey {
	result := make(AttachOperationHandlerCurrentUnresolvedGroupedByKey)
	for _, row := range rows {
		key, ok := AttachOperationHandlerCurrentUnresolvedIndexByKeyKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index AttachOperationHandlerCurrentUnresolvedGroupedByKey) Has(key AttachOperationHandlerCurrentUnresolvedKey) bool {
	_, ok := index[key]
	return ok
}

type AttachOperationHandlerCurrentUnresolvedNamespaceAndRunIdKey struct {
	Namespace string
	RunId     string
}

func AttachOperationHandlerCurrentUnresolvedIndexByNamespaceAndRunIdKey(value *CurrentUnresolvedView) (AttachOperationHandlerCurrentUnresolvedNamespaceAndRunIdKey, bool) {
	var zero AttachOperationHandlerCurrentUnresolvedNamespaceAndRunIdKey
	if value == nil {
		return zero, false
	}
	if value.Namespace == nil {
		return zero, false
	}
	if value.RunId == nil {
		return zero, false
	}
	return AttachOperationHandlerCurrentUnresolvedNamespaceAndRunIdKey{Namespace: *value.Namespace, RunId: *value.RunId}, true
}

type AttachOperationHandlerCurrentUnresolvedIndexedByNamespaceAndRunId map[AttachOperationHandlerCurrentUnresolvedNamespaceAndRunIdKey]*CurrentUnresolvedView

func (rows AttachOperationHandlerCurrentUnresolvedSlice) IndexByNamespaceAndRunId() (AttachOperationHandlerCurrentUnresolvedIndexedByNamespaceAndRunId, error) {
	result := make(AttachOperationHandlerCurrentUnresolvedIndexedByNamespaceAndRunId)
	for _, row := range rows {
		key, ok := AttachOperationHandlerCurrentUnresolvedIndexByNamespaceAndRunIdKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index AttachOperationHandlerCurrentUnresolvedSlice.IndexByNamespaceAndRunId")
		}
		result[key] = row
	}
	return result, nil
}
func (index AttachOperationHandlerCurrentUnresolvedIndexedByNamespaceAndRunId) Has(key AttachOperationHandlerCurrentUnresolvedNamespaceAndRunIdKey) bool {
	_, ok := index[key]
	return ok
}

type AttachOperationHandlerCurrentUnresolvedGroupedByNamespaceAndRunId map[AttachOperationHandlerCurrentUnresolvedNamespaceAndRunIdKey][]*CurrentUnresolvedView

func (rows AttachOperationHandlerCurrentUnresolvedSlice) GroupByNamespaceAndRunId() AttachOperationHandlerCurrentUnresolvedGroupedByNamespaceAndRunId {
	result := make(AttachOperationHandlerCurrentUnresolvedGroupedByNamespaceAndRunId)
	for _, row := range rows {
		key, ok := AttachOperationHandlerCurrentUnresolvedIndexByNamespaceAndRunIdKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index AttachOperationHandlerCurrentUnresolvedGroupedByNamespaceAndRunId) Has(key AttachOperationHandlerCurrentUnresolvedNamespaceAndRunIdKey) bool {
	_, ok := index[key]
	return ok
}

type AttachOperationHandlerReadIndexes struct {
	CurrentAttachOperation                      AttachOperationHandlerCurrentAttachOperationSlice
	CurrentAttachOperationByKey                 AttachOperationHandlerCurrentAttachOperationIndexedByKey
	CurrentAttachOperationGroupedByKey          AttachOperationHandlerCurrentAttachOperationGroupedByKey
	CurrentEvents                               AttachOperationHandlerCurrentEventsSlice
	CurrentEventsByKey                          AttachOperationHandlerCurrentEventsIndexedByKey
	CurrentEventsGroupedByNamespaceAndRunId     AttachOperationHandlerCurrentEventsGroupedByNamespaceAndRunId
	CurrentUnresolved                           AttachOperationHandlerCurrentUnresolvedSlice
	CurrentUnresolvedByKey                      AttachOperationHandlerCurrentUnresolvedIndexedByKey
	CurrentUnresolvedGroupedByNamespaceAndRunId AttachOperationHandlerCurrentUnresolvedGroupedByNamespaceAndRunId
}

func BuildAttachOperationHandlerReadIndexes(ctx context.Context, input *AttachOperationInput) (*AttachOperationHandlerReadIndexes, error) {
	if input == nil {
		return nil, fmt.Errorf("read indexes require input")
	}
	metadata, ok := xhandler.ReadMetadataFromContext(ctx)
	if !ok || (xshape.Runtime{}).IsNil(metadata) {
		return nil, fmt.Errorf("read indexes require bound read metadata")
	}
	result := &AttachOperationHandlerReadIndexes{}
	{
		projection, err := metadata.Projection("CurrentAttachOperation")
		if err != nil {
			return nil, err
		}
		if (xshape.Runtime{}).IsNil(projection) {
			return nil, fmt.Errorf("application read projection is unavailable: CurrentAttachOperation")
		}
		inputAccess, err := xshape.Linked(reflect.TypeOf((*AttachOperationInput)(nil)).Elem()).Accessor("CurrentAttachOperation")
		if err != nil {
			return nil, err
		}
		carrier, err := inputAccess.Get(input)
		if err != nil {
			return nil, err
		}
		value := carrier.Interface()
		if projection.DirectOutput() && projection.RootHolder() != "" {
			return nil, fmt.Errorf("direct application read cannot declare a root holder")
		}
		if !projection.DirectOutput() {
			holder := projection.RootHolder()
			if holder == "" {
				return nil, fmt.Errorf("wrapped read projection requires a canonical root holder")
			}
			accessor, err := xshape.Linked(carrier.Type()).Accessor(holder)
			if err != nil {
				return nil, err
			}
			if _, err := (xshape.Collection[CurrentAttachOperationView]{}).Pointers(reflect.Zero(accessor.Type()).Interface()); err != nil {
				return nil, err
			}
			root, present, err := accessor.GetOptional(value)
			if err != nil {
				return nil, err
			}
			if present {
				value = root.Interface()
			} else {
				value = []*CurrentAttachOperationView(nil)
			}
		}
		rows, err := (xshape.Collection[CurrentAttachOperationView]{}).Pointers(value)
		if err != nil {
			return nil, err
		}
		for ordinal, row := range rows {
			if row == nil {
				continue
			}
			loaded, err := projection.Fields(ordinal)
			if err != nil {
				return nil, err
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("Revision") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentAttachOperation.Revision")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("Namespace") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentAttachOperation.Namespace")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("Id") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentAttachOperation.Id")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("PlanId") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentAttachOperation.PlanId")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("Status") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentAttachOperation.Status")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("EndlySessionId") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentAttachOperation.EndlySessionId")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("EndlyOperationId") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentAttachOperation.EndlyOperationId")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("CreatedAt") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentAttachOperation.CreatedAt")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("UpdatedAt") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentAttachOperation.UpdatedAt")
			}
		}
		cloned, err := (xshape.Runtime{}).CloneValue(rows, xshape.CloneOptions{})
		if err != nil {
			return nil, err
		}
		result.CurrentAttachOperation = AttachOperationHandlerCurrentAttachOperationSlice(cloned.([]*CurrentAttachOperationView))
		result.CurrentAttachOperationByKey, err = result.CurrentAttachOperation.IndexByKey()
		if err != nil {
			return nil, err
		}
		result.CurrentAttachOperationGroupedByKey = result.CurrentAttachOperation.GroupByKey()
	}
	{
		projection, err := metadata.Projection("CurrentEvents")
		if err != nil {
			return nil, err
		}
		if (xshape.Runtime{}).IsNil(projection) {
			return nil, fmt.Errorf("application read projection is unavailable: CurrentEvents")
		}
		inputAccess, err := xshape.Linked(reflect.TypeOf((*AttachOperationInput)(nil)).Elem()).Accessor("CurrentEvents")
		if err != nil {
			return nil, err
		}
		carrier, err := inputAccess.Get(input)
		if err != nil {
			return nil, err
		}
		value := carrier.Interface()
		if projection.DirectOutput() && projection.RootHolder() != "" {
			return nil, fmt.Errorf("direct application read cannot declare a root holder")
		}
		if !projection.DirectOutput() {
			holder := projection.RootHolder()
			if holder == "" {
				return nil, fmt.Errorf("wrapped read projection requires a canonical root holder")
			}
			accessor, err := xshape.Linked(carrier.Type()).Accessor(holder)
			if err != nil {
				return nil, err
			}
			if _, err := (xshape.Collection[CurrentEventsView]{}).Pointers(reflect.Zero(accessor.Type()).Interface()); err != nil {
				return nil, err
			}
			root, present, err := accessor.GetOptional(value)
			if err != nil {
				return nil, err
			}
			if present {
				value = root.Interface()
			} else {
				value = []*CurrentEventsView(nil)
			}
		}
		rows, err := (xshape.Collection[CurrentEventsView]{}).Pointers(value)
		if err != nil {
			return nil, err
		}
		for ordinal, row := range rows {
			if row == nil {
				continue
			}
			loaded, err := projection.Fields(ordinal)
			if err != nil {
				return nil, err
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("Namespace") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentEvents.Namespace")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("Id") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentEvents.Id")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("RunId") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentEvents.RunId")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("AttemptId") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentEvents.AttemptId")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("Sequence") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentEvents.Sequence")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("Kind") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentEvents.Kind")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("PayloadJson") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentEvents.PayloadJson")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("CreatedAt") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentEvents.CreatedAt")
			}
		}
		cloned, err := (xshape.Runtime{}).CloneValue(rows, xshape.CloneOptions{})
		if err != nil {
			return nil, err
		}
		result.CurrentEvents = AttachOperationHandlerCurrentEventsSlice(cloned.([]*CurrentEventsView))
		result.CurrentEventsByKey, err = result.CurrentEvents.IndexByKey()
		if err != nil {
			return nil, err
		}
		result.CurrentEventsGroupedByNamespaceAndRunId = result.CurrentEvents.GroupByNamespaceAndRunId()
	}
	{
		projection, err := metadata.Projection("CurrentUnresolved")
		if err != nil {
			return nil, err
		}
		if (xshape.Runtime{}).IsNil(projection) {
			return nil, fmt.Errorf("application read projection is unavailable: CurrentUnresolved")
		}
		inputAccess, err := xshape.Linked(reflect.TypeOf((*AttachOperationInput)(nil)).Elem()).Accessor("CurrentUnresolved")
		if err != nil {
			return nil, err
		}
		carrier, err := inputAccess.Get(input)
		if err != nil {
			return nil, err
		}
		value := carrier.Interface()
		if projection.DirectOutput() && projection.RootHolder() != "" {
			return nil, fmt.Errorf("direct application read cannot declare a root holder")
		}
		if !projection.DirectOutput() {
			holder := projection.RootHolder()
			if holder == "" {
				return nil, fmt.Errorf("wrapped read projection requires a canonical root holder")
			}
			accessor, err := xshape.Linked(carrier.Type()).Accessor(holder)
			if err != nil {
				return nil, err
			}
			if _, err := (xshape.Collection[CurrentUnresolvedView]{}).Pointers(reflect.Zero(accessor.Type()).Interface()); err != nil {
				return nil, err
			}
			root, present, err := accessor.GetOptional(value)
			if err != nil {
				return nil, err
			}
			if present {
				value = root.Interface()
			} else {
				value = []*CurrentUnresolvedView(nil)
			}
		}
		rows, err := (xshape.Collection[CurrentUnresolvedView]{}).Pointers(value)
		if err != nil {
			return nil, err
		}
		for ordinal, row := range rows {
			if row == nil {
				continue
			}
			loaded, err := projection.Fields(ordinal)
			if err != nil {
				return nil, err
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("Namespace") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentUnresolved.Namespace")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("Id") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentUnresolved.Id")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("AttemptId") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentUnresolved.AttemptId")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("RunId") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentUnresolved.RunId")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("BusinessKey") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentUnresolved.BusinessKey")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("State") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentUnresolved.State")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("Revision") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentUnresolved.Revision")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("EvidenceJson") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentUnresolved.EvidenceJson")
			}
		}
		cloned, err := (xshape.Runtime{}).CloneValue(rows, xshape.CloneOptions{})
		if err != nil {
			return nil, err
		}
		result.CurrentUnresolved = AttachOperationHandlerCurrentUnresolvedSlice(cloned.([]*CurrentUnresolvedView))
		result.CurrentUnresolvedByKey, err = result.CurrentUnresolved.IndexByKey()
		if err != nil {
			return nil, err
		}
		result.CurrentUnresolvedGroupedByNamespaceAndRunId = result.CurrentUnresolved.GroupByNamespaceAndRunId()
	}
	return result, nil
}
func (input *AttachOperationInput) PrepareReadIndexes(ctx context.Context) error {
	if input == nil {
		return fmt.Errorf("read indexes require input")
	}
	input._attachOperationHandlerReadIndexes = nil
	indexes, err := BuildAttachOperationHandlerReadIndexes(ctx, input)
	if err := err; err != nil {
		return err
	}
	input._attachOperationHandlerReadIndexes = indexes
	return nil
}
func (input *AttachOperationInput) ReadIndexes(ctx context.Context) (*AttachOperationHandlerReadIndexes, error) {
	if input == nil {
		return nil, fmt.Errorf("read indexes require input")
	}
	if input._attachOperationHandlerReadIndexes == nil {
		if err := input.PrepareReadIndexes(ctx); err != nil {
			return nil, err
		}
	}
	return input._attachOperationHandlerReadIndexes, nil
}
