// Code generated by Datly for AttachOperation; DO NOT EDIT.

package attachoperation

// AttachOperationInput is the generated input scaffold for AttachOperation.
type AttachOperationInput struct {
	Namespace                          string                             `parameter:"Namespace,kind=query,in=namespace,dataType=string,required=true"`
	AttachOperation                    []*Run                             `parameter:"AttachOperation,kind=body,in=Data,dataType=[]*Run,cardinality=Many,required=true" view:"AttachOperation,type=Run,entityHooks=RunLifecycle,table=runs" sql:"uri=mechanize_data_attachoperation_attach_operation:sql/attach_operation.sql"`
	AttachOperationKeys                []AttachOperationKeysRow           `parameter:"AttachOperationKeys,kind=param,in=AttachOperation,cardinality=Many" codec:"structql,'uri=mechanize_data_attachoperation_attach_operation:sql/attach_operation_keys.sql'"`
	CurrentAttachOperation             []*CurrentAttachOperationView      `parameter:"CurrentAttachOperation,kind=view,in=CurrentAttachOperation,cardinality=Many" view:"CurrentAttachOperation,table=runs" sql:"uri=mechanize_data_attachoperation_attach_operation:sql/current_attach_operation.sql"`
	CurrentEvents                      []*CurrentEventsView               `parameter:"CurrentEvents,kind=view,in=CurrentEvents,cardinality=Many" view:"CurrentEvents,table=events" sql:"uri=mechanize_data_attachoperation_attach_operation:sql/current_events.sql"`
	CurrentUnresolved                  []*CurrentUnresolvedView           `parameter:"CurrentUnresolved,kind=view,in=CurrentUnresolved,cardinality=Many" view:"CurrentUnresolved,table=effects,auxiliary=true" sql:"uri=mechanize_data_attachoperation_attach_operation:sql/current_unresolved.sql"`
	_attachOperationHandlerReadIndexes *AttachOperationHandlerReadIndexes `json:"-" sqlx:"-"`
	Has                                *AttachOperationInputHas           `setMarker:"true" typeName:"AttachOperationInputHas" json:"-" sqlx:"-"`
}

type AttachOperationInputHas struct {
	Namespace              bool
	AttachOperation        bool
	AttachOperationKeys    bool
	CurrentAttachOperation bool
	CurrentEvents          bool
	CurrentUnresolved      bool
}
