// Code generated by Datly for AttachOperation; DO NOT EDIT.

package attachoperation

func (input *AttachOperationInput) SetNamespace(value string) {
	if input == nil {
		return
	}
	input.Namespace = value
	if input.Has == nil {
		input.Has = &AttachOperationInputHas{}
	}
	input.Has.Namespace = true
}

func (input *AttachOperationInput) SetAttachOperation(value []*Run) {
	if input == nil {
		return
	}
	input.AttachOperation = value
	if input.Has == nil {
		input.Has = &AttachOperationInputHas{}
	}
	input.Has.AttachOperation = true
}

func (input *AttachOperationInput) SetAttachOperationKeys(value []AttachOperationKeysRow) {
	if input == nil {
		return
	}
	input.AttachOperationKeys = value
	if input.Has == nil {
		input.Has = &AttachOperationInputHas{}
	}
	input.Has.AttachOperationKeys = true
}

func (input *AttachOperationInput) SetCurrentAttachOperation(value []*CurrentAttachOperationView) {
	if input == nil {
		return
	}
	input.CurrentAttachOperation = value
	if input.Has == nil {
		input.Has = &AttachOperationInputHas{}
	}
	input.Has.CurrentAttachOperation = true
}

func (input *AttachOperationInput) SetCurrentEvents(value []*CurrentEventsView) {
	if input == nil {
		return
	}
	input.CurrentEvents = value
	if input.Has == nil {
		input.Has = &AttachOperationInputHas{}
	}
	input.Has.CurrentEvents = true
}

func (input *AttachOperationInput) SetCurrentUnresolved(value []*CurrentUnresolvedView) {
	if input == nil {
		return
	}
	input.CurrentUnresolved = value
	if input.Has == nil {
		input.Has = &AttachOperationInputHas{}
	}
	input.Has.CurrentUnresolved = true
}
