// Code generated by Datly for AttachOperation; DO NOT EDIT.

package attachoperation

// AttachOperationOutput is the generated output scaffold for AttachOperation.
type AttachOperationOutput struct {
	Data []*Run `parameter:"Data,kind=output,in=body,dataType=[]*Run"`
}
