// Code generated by Datly for AttachOperation; DO NOT EDIT.

package attachoperation

import (
	embed "embed"
	xdatly "github.com/viant/xdatly"
	reflect "reflect"
)

func init() {}

// Component is the generated component scaffold for AttachOperation.
type AttachOperationComponent struct {
	Contract xdatly.Component[AttachOperationInput, AttachOperationOutput] "component:\"AttachOperation,path=/internal/data/attachoperation,method=PATCH,connector=user,view=AttachOperation\" routeName:\"AttachOperation\" mutation:\"patch\" caseFormat:\"lc\""
}

// AttachOperationDatlyType returns the public component type.
func AttachOperationDatlyType() reflect.Type {
	return reflect.TypeOf((*AttachOperationComponent)(nil)).Elem()
}

// The package-level value keeps this real component type reachable for runtime discovery.
var AttachOperationDatly = new(AttachOperationComponent)
var _datlyReachableAttachOperationComponent = reflect.TypeFor[AttachOperationComponent]()

func (AttachOperationComponent) EmbedFS() *embed.FS {
	return &AttachOperationDatlyResources
}

func (AttachOperationComponent) EmbedNamespace() string {
	return AttachOperationDatlyResourceNamespace
}
