// Code generated by Datly for AttachOperation; DO NOT EDIT.

package attachoperation

// Run is generated canonical view metadata for AttachOperation.
type Run struct {
	Revision         *int                `writer:"concurrency" sqlx:"revision,required=true" json:"revision"`
	Namespace        *string             `sqlx:"namespace,refTable=plan_revisions,refColumn=namespace,required=true,primaryKey=true" json:"namespace"`
	Id               *string             `sqlx:"id,required=true,primaryKey=true" json:"id"`
	PlanId           *string             `sqlx:"plan_id,refTable=plan_revisions,refColumn=id,required=true" json:"planId"`
	Status           *string             `sqlx:"status,required=true" json:"status"`
	EndlySessionId   *string             `sqlx:"endly_session_id" json:"endlySessionId"`
	EndlyOperationId *string             `sqlx:"endly_operation_id" json:"endlyOperationId"`
	CreatedAt        *string             `sqlx:"created_at,required=true" json:"createdAt"`
	UpdatedAt        *string             `sqlx:"updated_at,required=true" json:"updatedAt"`
	Events           []*Event            `view:"events,type=Event,table=events" on:"Namespace:records.namespace=Namespace:events.namespace,Id:records.id=RunId:events.run_id" json:"events" sql:"uri=mechanize_data_attachoperation_attach_operation:sql/events.sql"`
	Unresolved       []*UnresolvedEffect `view:"unresolved,type=UnresolvedEffect,table=effects,auxiliary=true" on:"Namespace:records.namespace=Namespace:unresolved.namespace,Id:records.id=RunId:unresolved.run_id" json:"unresolved" sql:"uri=mechanize_data_attachoperation_attach_operation:sql/unresolved.sql"`
	Has              *RunHas             `setMarker:"true" format:"-" sqlx:"-" diff:"-" json:"-" typeName:"RunHas"`
}

type RunHas struct {
	Revision         bool
	Namespace        bool
	Id               bool
	PlanId           bool
	Status           bool
	EndlySessionId   bool
	EndlyOperationId bool
	CreatedAt        bool
	UpdatedAt        bool
	Events           bool
}

// Event is generated canonical view metadata for AttachOperation.
type Event struct {
	Namespace   *string   `sqlx:"namespace,refTable=runs,refColumn=namespace,required=true,primaryKey=true" json:"namespace"`
	Id          *string   `sqlx:"id,required=true,primaryKey=true" json:"id"`
	RunId       *string   `sqlx:"run_id,refTable=runs,refColumn=id,required=true" json:"runId"`
	AttemptId   *string   `sqlx:"attempt_id" json:"attemptId"`
	Sequence    *int      `sqlx:"sequence,required=true" json:"sequence"`
	Kind        *string   `sqlx:"kind,required=true" json:"kind"`
	PayloadJson *string   `sqlx:"payload_json,required=true" json:"payloadJson"`
	CreatedAt   *string   `sqlx:"created_at,required=true" json:"createdAt"`
	Has         *EventHas `setMarker:"true" format:"-" sqlx:"-" diff:"-" json:"-" typeName:"EventHas"`
}

type EventHas struct {
	Namespace   bool
	Id          bool
	RunId       bool
	AttemptId   bool
	Sequence    bool
	Kind        bool
	PayloadJson bool
	CreatedAt   bool
}

// UnresolvedEffect is generated canonical view metadata for AttachOperation.
type UnresolvedEffect struct {
	Namespace    *string `sqlx:"namespace,refTable=attempts,refColumn=namespace,required=true,primaryKey=true" json:"namespace"`
	Id           *string `sqlx:"id,required=true,primaryKey=true" json:"id"`
	AttemptId    *string `sqlx:"attempt_id,refTable=attempts,refColumn=id,required=true" json:"attemptId"`
	RunId        *string `sqlx:"run_id,required=true" json:"runId"`
	BusinessKey  *string `sqlx:"business_key,required=true" json:"businessKey"`
	State        *string `sqlx:"state,required=true" json:"state"`
	Revision     *int    `sqlx:"revision,required=true" json:"revision"`
	EvidenceJson *string `sqlx:"evidence_json" json:"evidenceJson"`
}

// CurrentAttachOperationView is generated canonical view metadata for AttachOperation.
type CurrentAttachOperationView struct {
	Revision         *int    `sqlx:"revision,required=true" json:"revision"`
	Namespace        *string `sqlx:"namespace,refTable=plan_revisions,refColumn=namespace,required=true,primaryKey=true" json:"namespace"`
	Id               *string `sqlx:"id,required=true,primaryKey=true" json:"id"`
	PlanId           *string `sqlx:"plan_id,refTable=plan_revisions,refColumn=id,required=true" json:"planId"`
	Status           *string `sqlx:"status,required=true" json:"status"`
	EndlySessionId   *string `sqlx:"endly_session_id" json:"endlySessionId"`
	EndlyOperationId *string `sqlx:"endly_operation_id" json:"endlyOperationId"`
	CreatedAt        *string `sqlx:"created_at,required=true" json:"createdAt"`
	UpdatedAt        *string `sqlx:"updated_at,required=true" json:"updatedAt"`
}

// CurrentEventsView is generated canonical view metadata for AttachOperation.
type CurrentEventsView struct {
	Namespace   *string `sqlx:"namespace,refTable=runs,refColumn=namespace,required=true,primaryKey=true" json:"namespace"`
	Id          *string `sqlx:"id,required=true,primaryKey=true" json:"id"`
	RunId       *string `sqlx:"run_id,refTable=runs,refColumn=id,required=true" json:"runId"`
	AttemptId   *string `sqlx:"attempt_id" json:"attemptId"`
	Sequence    *int    `sqlx:"sequence,required=true" json:"sequence"`
	Kind        *string `sqlx:"kind,required=true" json:"kind"`
	PayloadJson *string `sqlx:"payload_json,required=true" json:"payloadJson"`
	CreatedAt   *string `sqlx:"created_at,required=true" json:"createdAt"`
}

// CurrentUnresolvedView is generated canonical view metadata for AttachOperation.
type CurrentUnresolvedView struct {
	Namespace    *string `sqlx:"namespace,refTable=attempts,refColumn=namespace,required=true,primaryKey=true" json:"namespace"`
	Id           *string `sqlx:"id,required=true,primaryKey=true" json:"id"`
	AttemptId    *string `sqlx:"attempt_id,refTable=attempts,refColumn=id,required=true" json:"attemptId"`
	RunId        *string `sqlx:"run_id,required=true" json:"runId"`
	BusinessKey  *string `sqlx:"business_key,required=true" json:"businessKey"`
	State        *string `sqlx:"state,required=true" json:"state"`
	Revision     *int    `sqlx:"revision,required=true" json:"revision"`
	EvidenceJson *string `sqlx:"evidence_json" json:"evidenceJson"`
}

type AttachOperationKeysRow struct {
	Namespace *string `sqlx:"namespace"`
	Id        *string `sqlx:"id"`
}
