// Code generated by Datly for PublishArtifact; DO NOT EDIT.

package publishartifact

func (entity *Artifact) GetNamespace() *string {
	return entity.Namespace
}
func (entity *Artifact) SetNamespace(value *string) {
	entity.Namespace = value
	if entity.Has == nil {
		entity.Has = &ArtifactHas{}
	}
	entity.Has.Namespace = true
}
func (entity *Artifact) GetId() *string {
	return entity.Id
}
func (entity *Artifact) SetId(value *string) {
	entity.Id = value
	if entity.Has == nil {
		entity.Has = &ArtifactHas{}
	}
	entity.Has.Id = true
}
func (entity *Artifact) GetContentHash() *string {
	return entity.ContentHash
}
func (entity *Artifact) SetContentHash(value *string) {
	entity.ContentHash = value
	if entity.Has == nil {
		entity.Has = &ArtifactHas{}
	}
	entity.Has.ContentHash = true
}
func (entity *Artifact) GetSizeBytes() *int {
	return entity.SizeBytes
}
func (entity *Artifact) SetSizeBytes(value *int) {
	entity.SizeBytes = value
	if entity.Has == nil {
		entity.Has = &ArtifactHas{}
	}
	entity.Has.SizeBytes = true
}
func (entity *Artifact) GetMediaType() *string {
	return entity.MediaType
}
func (entity *Artifact) SetMediaType(value *string) {
	entity.MediaType = value
	if entity.Has == nil {
		entity.Has = &ArtifactHas{}
	}
	entity.Has.MediaType = true
}
func (entity *Artifact) GetKeyReference() *string {
	return entity.KeyReference
}
func (entity *Artifact) SetKeyReference(value *string) {
	entity.KeyReference = value
	if entity.Has == nil {
		entity.Has = &ArtifactHas{}
	}
	entity.Has.KeyReference = true
}
func (entity *Artifact) GetPublicationState() *string {
	return entity.PublicationState
}
func (entity *Artifact) SetPublicationState(value *string) {
	entity.PublicationState = value
	if entity.Has == nil {
		entity.Has = &ArtifactHas{}
	}
	entity.Has.PublicationState = true
}
