// Code generated by Datly for PublishArtifact; DO NOT EDIT.

package publishartifact

// PublishArtifactInput is the generated input scaffold for PublishArtifact.
type PublishArtifactInput struct {
	Namespace       string                   `parameter:"Namespace,kind=query,in=namespace,dataType=string,required=true"`
	PublishArtifact []*Artifact              `parameter:"PublishArtifact,kind=body,in=Data,dataType=[]*Artifact,cardinality=Many,required=true" view:"PublishArtifact,type=Artifact,entityHooks=ArtifactLifecycle,table=artifacts" sql:"uri=mechanize_data_publishartifact_publish_artifact:sql/publish_artifact.sql"`
	Has             *PublishArtifactInputHas `setMarker:"true" typeName:"PublishArtifactInputHas" json:"-" sqlx:"-"`
}

type PublishArtifactInputHas struct {
	Namespace       bool
	PublishArtifact bool
}
