// Code generated by Datly for StateGet; DO NOT EDIT.

package stateget

// StateGetInput is the generated input scaffold for StateGet.
type StateGetInput struct {
	Namespace string            `parameter:"Namespace,kind=query,in=namespace,dataType=string,required=true"`
	RunID     string            `parameter:"RunID,kind=query,in=runId,dataType=string,required=true"`
	Has       *StateGetInputHas `setMarker:"true" typeName:"StateGetInputHas" json:"-" sqlx:"-"`
}

type StateGetInputHas struct {
	Namespace bool
	RunID     bool
}
