// Code generated by Datly for StateGet; DO NOT EDIT.

package stateget

func (input *StateGetInput) SetNamespace(value string) {
	if input == nil {
		return
	}
	input.Namespace = value
	if input.Has == nil {
		input.Has = &StateGetInputHas{}
	}
	input.Has.Namespace = true
}

func (input *StateGetInput) SetRunID(value string) {
	if input == nil {
		return
	}
	input.RunID = value
	if input.Has == nil {
		input.Has = &StateGetInputHas{}
	}
	input.Has.RunID = true
}
