// Code generated by Datly for StateGet; DO NOT EDIT.

package stateget

// StateGetOutput is the generated output scaffold for StateGet.
type StateGetOutput struct {
	Data []*RunState `parameter:"Data,kind=output,in=view,dataType=[]*RunState" view:"StateGet,type=RunState,table=runs" sql:"uri=mechanize_data_stateget_state_get:sql/state_get.sql"`
}
