// Code generated by Datly for StateGet; DO NOT EDIT.

package stateget

import (
	embed "embed"
	xdatly "github.com/viant/xdatly"
	reflect "reflect"
)

func init() {}

// Component is the generated component scaffold for StateGet.
type StateGetComponent struct {
	Contract xdatly.Component[StateGetInput, StateGetOutput] "component:\"StateGet,path=/internal/data/stateget,method=GET,connector=user,view=StateGet\" routeName:\"StateGet\" caseFormat:\"lc\""
}

// StateGetDatlyType returns the public component type.
func StateGetDatlyType() reflect.Type { return reflect.TypeOf((*StateGetComponent)(nil)).Elem() }

// The package-level value keeps this real component type reachable for runtime discovery.
var StateGetDatly = new(StateGetComponent)
var _datlyReachableStateGetComponent = reflect.TypeFor[StateGetComponent]()

func (StateGetComponent) EmbedFS() *embed.FS {
	return &StateGetDatlyResources
}

func (StateGetComponent) EmbedNamespace() string {
	return StateGetDatlyResourceNamespace
}
