// Code generated by Datly for StateGet; DO NOT EDIT.

package stateget

// RunState is generated canonical view metadata for StateGet.
type RunState struct {
	Namespace        *string             `sqlx:"namespace,refTable=plan_revisions,refColumn=namespace,required=true,primaryKey=true" json:"namespace"`
	Id               *string             `sqlx:"id,required=true,primaryKey=true" json:"id"`
	PlanId           *string             `sqlx:"plan_id,refTable=plan_revisions,refColumn=id,required=true" json:"planId"`
	Status           *string             `sqlx:"status,required=true" json:"status"`
	Revision         *int                `sqlx:"revision,required=true" json:"revision"`
	EndlySessionId   *string             `sqlx:"endly_session_id" json:"endlySessionId"`
	EndlyOperationId *string             `sqlx:"endly_operation_id" json:"endlyOperationId"`
	ObjectiveId      *string             `sqlx:"objective_id" json:"objectiveId"`
	Variables        []*Variable         `view:"variables,type=Variable,table=run_variables" on:"Namespace:records.namespace=Namespace:variables.namespace,Id:records.id=RunId:variables.run_id" json:"variables" sql:"uri=mechanize_data_stateget_state_get:sql/variables.sql"`
	Milestones       []*Milestone        `view:"milestones,type=Milestone,table=milestones" on:"Namespace:records.namespace=Namespace:milestones.namespace,Id:records.id=RunId:milestones.run_id" json:"milestones" sql:"uri=mechanize_data_stateget_state_get:sql/milestones.sql"`
	Unresolved       []*UnresolvedEffect `view:"unresolved,type=UnresolvedEffect,table=effects" on:"Namespace:records.namespace=Namespace:unresolved.namespace,Id:records.id=RunId:unresolved.run_id" json:"unresolved" sql:"uri=mechanize_data_stateget_state_get:sql/unresolved.sql"`
	Checkpoints      []*Checkpoint       `view:"checkpoints,type=Checkpoint,table=checkpoints" on:"Namespace:records.namespace=Namespace:checkpoints.namespace,Id:records.id=RunId:checkpoints.run_id" json:"checkpoints" sql:"uri=mechanize_data_stateget_state_get:sql/checkpoints.sql"`
}

// Variable is generated canonical view metadata for StateGet.
type Variable struct {
	Namespace *string `sqlx:"namespace,refTable=runs,refColumn=namespace,required=true,primaryKey=true" json:"namespace"`
	RunId     *string `sqlx:"run_id,refTable=runs,refColumn=id,required=true,primaryKey=true" json:"runId"`
	Name      *string `sqlx:"name,required=true,primaryKey=true" json:"name"`
	ValueJson *string `sqlx:"value_json,required=true" json:"valueJson"`
}

// Milestone is generated canonical view metadata for StateGet.
type Milestone struct {
	Namespace    *string `sqlx:"namespace,refTable=runs,refColumn=namespace,required=true,primaryKey=true" json:"namespace"`
	Id           *string `sqlx:"id,required=true,primaryKey=true" json:"id"`
	RunId        *string `sqlx:"run_id,refTable=runs,refColumn=id,required=true" json:"runId"`
	AttemptId    *string `sqlx:"attempt_id,required=true" json:"attemptId"`
	State        *string `sqlx:"state,required=true" json:"state"`
	EvidenceJson *string `sqlx:"evidence_json" json:"evidenceJson"`
}

// UnresolvedEffect is generated canonical view metadata for StateGet.
type UnresolvedEffect struct {
	Namespace    *string `sqlx:"namespace,refTable=attempts,refColumn=namespace,required=true,primaryKey=true" json:"namespace"`
	Id           *string `sqlx:"id,required=true,primaryKey=true" json:"id"`
	AttemptId    *string `sqlx:"attempt_id,refTable=attempts,refColumn=id,required=true" json:"attemptId"`
	RunId        *string `sqlx:"run_id,required=true" json:"runId"`
	BusinessKey  *string `sqlx:"business_key,required=true" json:"businessKey"`
	State        *string `sqlx:"state,required=true" json:"state"`
	Revision     *int    `sqlx:"revision,required=true" json:"revision"`
	EvidenceJson *string `sqlx:"evidence_json" json:"evidenceJson"`
}

// Checkpoint is generated canonical view metadata for StateGet.
type Checkpoint struct {
	Namespace        *string `sqlx:"namespace,refTable=runs,refColumn=namespace,required=true,primaryKey=true" json:"namespace"`
	Id               *string `sqlx:"id,required=true,primaryKey=true" json:"id"`
	RunId            *string `sqlx:"run_id,refTable=runs,refColumn=id,required=true" json:"runId"`
	PlanId           *string `sqlx:"plan_id,required=true" json:"planId"`
	RunRevision      *int    `sqlx:"run_revision,required=true" json:"runRevision"`
	EventSequence    *int    `sqlx:"event_sequence,required=true" json:"eventSequence"`
	ManifestHash     *string `sqlx:"manifest_hash,required=true" json:"manifestHash"`
	ManifestJson     *string `sqlx:"manifest_json,required=true" json:"manifestJson"`
	PublicationState *string `sqlx:"publication_state,required=true" json:"publicationState"`
	CreatedAt        *string `sqlx:"created_at,required=true" json:"createdAt"`
}
