// Code generated by Datly for PublishPlanRevision; DO NOT EDIT.

package publishplan

// PublishPlanRevisionInput is the generated input scaffold for PublishPlanRevision.
type PublishPlanRevisionInput struct {
	Namespace           string                       `parameter:"Namespace,kind=query,in=namespace,dataType=string,required=true"`
	PublishPlanRevision []*PlanRevision              `parameter:"PublishPlanRevision,kind=body,in=Data,dataType=[]*PlanRevision,cardinality=Many,required=true" view:"PublishPlanRevision,type=PlanRevision,entityHooks=PlanRevisionLifecycle,table=plan_revisions" sql:"uri=mechanize_data_publishplan_publish_plan_revision:sql/publish_plan_revision.sql"`
	Has                 *PublishPlanRevisionInputHas `setMarker:"true" typeName:"PublishPlanRevisionInputHas" json:"-" sqlx:"-"`
}

type PublishPlanRevisionInputHas struct {
	Namespace           bool
	PublishPlanRevision bool
}
