// Code generated by Datly for PublishPlanRevision; DO NOT EDIT.

package publishplan

func (input *PublishPlanRevisionInput) SetNamespace(value string) {
	if input == nil {
		return
	}
	input.Namespace = value
	if input.Has == nil {
		input.Has = &PublishPlanRevisionInputHas{}
	}
	input.Has.Namespace = true
}

func (input *PublishPlanRevisionInput) SetPublishPlanRevision(value []*PlanRevision) {
	if input == nil {
		return
	}
	input.PublishPlanRevision = value
	if input.Has == nil {
		input.Has = &PublishPlanRevisionInputHas{}
	}
	input.Has.PublishPlanRevision = true
}
