// Code generated by Datly for PublishPlanRevision; DO NOT EDIT.

package publishplan

import "embed"

// DatlyResourceNamespace identifies this package's generated resource filesystem.
const PublishPlanRevisionDatlyResourceNamespace = "mechanize_data_publishplan_publish_plan_revision"

//go:embed "sql/publish_plan_revision.sql"
var PublishPlanRevisionDatlyResources embed.FS
