// Code generated by Datly for PublishPlanRevision; DO NOT EDIT.

package publishplan

// PlanRevision is generated canonical view metadata for PublishPlanRevision.
type PlanRevision struct {
	Namespace   *string          `sqlx:"namespace,required=true,primaryKey=true" json:"namespace"`
	Id          *string          `sqlx:"id,required=true,primaryKey=true" json:"id"`
	ParentId    *string          `sqlx:"parent_id" json:"parentId"`
	ObjectiveId *string          `sqlx:"objective_id,required=true" json:"objectiveId"`
	ContentHash *string          `sqlx:"content_hash,required=true" json:"contentHash"`
	ContentJson *string          `sqlx:"content_json,required=true" json:"contentJson"`
	CreatedAt   *string          `sqlx:"created_at,required=true" json:"createdAt"`
	Has         *PlanRevisionHas `setMarker:"true" format:"-" sqlx:"-" diff:"-" json:"-" typeName:"PlanRevisionHas"`
}

type PlanRevisionHas struct {
	Namespace   bool
	Id          bool
	ParentId    bool
	ObjectiveId bool
	ContentHash bool
	ContentJson bool
	CreatedAt   bool
}
