// Code generated by Datly for CreateRun; DO NOT EDIT.

package createrun

func (entity *Run) GetNamespace() *string {
	return entity.Namespace
}
func (entity *Run) SetNamespace(value *string) {
	entity.Namespace = value
	if entity.Has == nil {
		entity.Has = &RunHas{}
	}
	entity.Has.Namespace = true
}
func (entity *Run) GetId() *string {
	return entity.Id
}
func (entity *Run) SetId(value *string) {
	entity.Id = value
	if entity.Has == nil {
		entity.Has = &RunHas{}
	}
	entity.Has.Id = true
}
func (entity *Run) GetPlanId() *string {
	return entity.PlanId
}
func (entity *Run) SetPlanId(value *string) {
	entity.PlanId = value
	if entity.Has == nil {
		entity.Has = &RunHas{}
	}
	entity.Has.PlanId = true
}
func (entity *Run) GetStatus() *string {
	return entity.Status
}
func (entity *Run) SetStatus(value *string) {
	entity.Status = value
	if entity.Has == nil {
		entity.Has = &RunHas{}
	}
	entity.Has.Status = true
}
func (entity *Run) GetRevision() *int {
	return entity.Revision
}
func (entity *Run) SetRevision(value *int) {
	entity.Revision = value
	if entity.Has == nil {
		entity.Has = &RunHas{}
	}
	entity.Has.Revision = true
}
func (entity *Run) GetEndlySessionId() *string {
	return entity.EndlySessionId
}
func (entity *Run) SetEndlySessionId(value *string) {
	entity.EndlySessionId = value
	if entity.Has == nil {
		entity.Has = &RunHas{}
	}
	entity.Has.EndlySessionId = true
}
func (entity *Run) GetEndlyOperationId() *string {
	return entity.EndlyOperationId
}
func (entity *Run) SetEndlyOperationId(value *string) {
	entity.EndlyOperationId = value
	if entity.Has == nil {
		entity.Has = &RunHas{}
	}
	entity.Has.EndlyOperationId = true
}
func (entity *Run) GetCreatedAt() *string {
	return entity.CreatedAt
}
func (entity *Run) SetCreatedAt(value *string) {
	entity.CreatedAt = value
	if entity.Has == nil {
		entity.Has = &RunHas{}
	}
	entity.Has.CreatedAt = true
}
func (entity *Run) GetUpdatedAt() *string {
	return entity.UpdatedAt
}
func (entity *Run) SetUpdatedAt(value *string) {
	entity.UpdatedAt = value
	if entity.Has == nil {
		entity.Has = &RunHas{}
	}
	entity.Has.UpdatedAt = true
}
