// Code generated by Datly for CreateRun; DO NOT EDIT.

package createrun

import "embed"

// DatlyResourceNamespace identifies this package's generated resource filesystem.
const CreateRunDatlyResourceNamespace = "mechanize_data_createrun_create_run"

//go:embed "sql/create_run.sql"
var CreateRunDatlyResources embed.FS
