// Code generated by Datly for consenttrusted; DO NOT EDIT.

package consenttrusted

func (input *ListTrustedInput) SetNamespace(value string) {
	if input == nil {
		return
	}
	input.Namespace = value
	if input.Has == nil {
		input.Has = &ListTrustedInputHas{}
	}
	input.Has.Namespace = true
}

func (input *ListTrustedInput) SetClientID(value string) {
	if input == nil {
		return
	}
	input.ClientID = value
	if input.Has == nil {
		input.Has = &ListTrustedInputHas{}
	}
	input.Has.ClientID = true
}
