// Code generated by Datly for consenttrusted; DO NOT EDIT.

package consenttrusted

// ListTrustedOutput is the generated output scaffold for consenttrusted.
type ListTrustedOutput struct {
	Data []*Record `parameter:"Data,kind=output,in=view,dataType=[]*Record" view:"consenttrusted,type=Record,table=consent_records,limit=257" sql:"uri=mechanize_data_consenttrusted_consenttrusted:sql/consenttrusted.sql"`
}
