// Code generated by Datly for consenttrusted; DO NOT EDIT.

package consenttrusted

import "embed"

// DatlyResourceNamespace identifies this package's generated resource filesystem.
const ConsenttrustedDatlyResourceNamespace = "mechanize_data_consenttrusted_consenttrusted"

//go:embed "sql/consenttrusted.sql"
var ConsenttrustedDatlyResources embed.FS
