// Code generated by Datly for consenttrusted; DO NOT EDIT.

package consenttrusted

// Record is generated canonical view metadata for consenttrusted.
type Record struct {
	Namespace        *string `sqlx:"namespace,required=true,primaryKey=true" json:"namespace"`
	Id               *string `sqlx:"id,required=true,primaryKey=true" json:"id"`
	ClientId         *string `sqlx:"client_id,required=true" json:"clientId"`
	ClientName       *string `sqlx:"client_name,required=true" json:"clientName"`
	SessionId        *string `sqlx:"session_id,required=true" json:"sessionId"`
	ScopeJson        *string `sqlx:"scope_json,required=true" json:"scopeJson"`
	ModesJson        *string `sqlx:"modes_json,required=true" json:"modesJson"`
	Purpose          *string `sqlx:"purpose,required=true" json:"purpose"`
	DurationSeconds  *int    `sqlx:"duration_seconds,required=true" json:"durationSeconds"`
	CreatedAt        *int    `sqlx:"created_at,required=true" json:"createdAt"`
	RequestExpiresAt *int    `sqlx:"request_expires_at,required=true" json:"requestExpiresAt"`
	RequestState     *string `sqlx:"request_state,required=true" json:"requestState"`
	Decision         *string `sqlx:"decision,required=true" json:"decision"`
	GrantId          *string `sqlx:"grant_id,required=true" json:"grantId"`
	GrantCreatedAt   *int    `sqlx:"grant_created_at,required=true" json:"grantCreatedAt"`
	GrantExpiresAt   *int    `sqlx:"grant_expires_at,required=true" json:"grantExpiresAt"`
	GrantState       *string `sqlx:"grant_state,required=true" json:"grantState"`
	RevocationState  *string `sqlx:"revocation_state,required=true" json:"revocationState"`
	Revision         *int    `sqlx:"revision,required=true" json:"revision"`
}
