// Code generated by Datly for LoadRecovery; DO NOT EDIT.

package recoveryload

// LoadRecoveryOutput is the generated output scaffold for LoadRecovery.
type LoadRecoveryOutput struct {
	Data []*RecoveryRun `parameter:"Data,kind=output,in=view,dataType=[]*RecoveryRun" view:"LoadRecovery,type=RecoveryRun,table=runs" sql:"uri=mechanize_data_recoveryload_load_recovery:sql/load_recovery.sql"`
}
