// Code generated by Datly for LoadRecovery; DO NOT EDIT.

package recoveryload

// RecoveryRun is generated canonical view metadata for LoadRecovery.
type RecoveryRun struct {
	Namespace        *string           `sqlx:"namespace,refTable=plan_revisions,refColumn=namespace,required=true,primaryKey=true" json:"namespace"`
	Id               *string           `sqlx:"id,required=true,primaryKey=true" json:"id"`
	PlanId           *string           `sqlx:"plan_id,refTable=plan_revisions,refColumn=id,required=true" json:"planId"`
	Status           *string           `sqlx:"status,required=true" json:"status"`
	Revision         *int              `sqlx:"revision,required=true" json:"revision"`
	EndlySessionId   *string           `sqlx:"endly_session_id" json:"endlySessionId"`
	EndlyOperationId *string           `sqlx:"endly_operation_id" json:"endlyOperationId"`
	CreatedAt        *string           `sqlx:"created_at,required=true" json:"createdAt"`
	UpdatedAt        *string           `sqlx:"updated_at,required=true" json:"updatedAt"`
	ObjectiveId      *string           `sqlx:"objective_id" json:"objectiveId"`
	Plans            []*PlanRevision   `view:"plans,type=PlanRevision,table=plan_revisions" on:"Namespace:records.namespace=Namespace:plans.namespace,ObjectiveId:records.objective_id=ObjectiveId:plans.objective_id" json:"plans" sql:"uri=mechanize_data_recoveryload_load_recovery:sql/plans.sql"`
	Attempts         []*Attempt        `view:"attempts,type=Attempt,table=attempts" on:"Namespace:records.namespace=Namespace:attempts.namespace,Id:records.id=RunId:attempts.run_id" json:"attempts" sql:"uri=mechanize_data_recoveryload_load_recovery:sql/attempts.sql"`
	Effects          []*Effect         `view:"effects,type=Effect,table=effects" on:"Namespace:records.namespace=Namespace:effects.namespace,Id:records.id=RunId:effects.run_id" json:"effects" sql:"uri=mechanize_data_recoveryload_load_recovery:sql/effects.sql"`
	Milestones       []*Milestone      `view:"milestones,type=Milestone,table=milestones" on:"Namespace:records.namespace=Namespace:milestones.namespace,Id:records.id=RunId:milestones.run_id" json:"milestones" sql:"uri=mechanize_data_recoveryload_load_recovery:sql/milestones.sql"`
	Variables        []*Variable       `view:"variables,type=Variable,table=run_variables" on:"Namespace:records.namespace=Namespace:variables.namespace,Id:records.id=RunId:variables.run_id" json:"variables" sql:"uri=mechanize_data_recoveryload_load_recovery:sql/variables.sql"`
	Events           []*Event          `view:"events,type=Event,table=events" on:"Namespace:records.namespace=Namespace:events.namespace,Id:records.id=RunId:events.run_id" json:"events" sql:"uri=mechanize_data_recoveryload_load_recovery:sql/events.sql"`
	Workflow         *WorkflowBudget   `view:"workflow,type=WorkflowBudget,table=repair_workflow_budgets" on:"Namespace:records.namespace=Namespace:workflow.namespace,Id:records.id=RunId:workflow.run_id" json:"workflow" sql:"uri=mechanize_data_recoveryload_load_recovery:sql/workflow.sql"`
	Incidents        []*IncidentBudget `view:"incidents,type=IncidentBudget,table=repair_incident_budgets" on:"Namespace:records.namespace=Namespace:incidents.namespace,Id:records.id=RunId:incidents.run_id" json:"incidents" sql:"uri=mechanize_data_recoveryload_load_recovery:sql/incidents.sql"`
	Repairs          []*RepairRevision `view:"repairs,type=RepairRevision,table=repair_revisions" on:"Namespace:records.namespace=Namespace:repairs.namespace,Id:records.id=RunId:repairs.run_id" json:"repairs" sql:"uri=mechanize_data_recoveryload_load_recovery:sql/repairs.sql"`
	Lineage          []*RepairLineage  `view:"lineage,type=RepairLineage,table=repair_lineage" on:"Namespace:records.namespace=Namespace:lineage.namespace,Id:records.id=RunId:lineage.run_id" json:"lineage" sql:"uri=mechanize_data_recoveryload_load_recovery:sql/lineage.sql"`
}

// PlanRevision is generated canonical view metadata for LoadRecovery.
type PlanRevision struct {
	Namespace   *string `sqlx:"namespace,required=true,primaryKey=true" json:"namespace"`
	Id          *string `sqlx:"id,required=true,primaryKey=true" json:"id"`
	ParentId    *string `sqlx:"parent_id" json:"parentId"`
	ObjectiveId *string `sqlx:"objective_id,required=true" json:"objectiveId"`
	ContentHash *string `sqlx:"content_hash,required=true" json:"contentHash"`
	ContentJson *string `sqlx:"content_json,required=true" json:"contentJson"`
	CreatedAt   *string `sqlx:"created_at,required=true" json:"createdAt"`
}

// Attempt is generated canonical view metadata for LoadRecovery.
type Attempt struct {
	Namespace  *string `sqlx:"namespace,refTable=runs,refColumn=namespace,required=true,primaryKey=true" json:"namespace"`
	Id         *string `sqlx:"id,required=true,primaryKey=true" json:"id"`
	RunId      *string `sqlx:"run_id,refTable=runs,refColumn=id,required=true" json:"runId"`
	StepId     *string `sqlx:"step_id,required=true" json:"stepId"`
	PlanId     *string `sqlx:"plan_id,required=true" json:"planId"`
	LeaseEpoch *int    `sqlx:"lease_epoch,required=true" json:"leaseEpoch"`
	State      *string `sqlx:"state,required=true" json:"state"`
	CreatedAt  *string `sqlx:"created_at,required=true" json:"createdAt"`
}

// Effect is generated canonical view metadata for LoadRecovery.
type Effect struct {
	Namespace    *string `sqlx:"namespace,refTable=attempts,refColumn=namespace,required=true,primaryKey=true" json:"namespace"`
	Id           *string `sqlx:"id,required=true,primaryKey=true" json:"id"`
	AttemptId    *string `sqlx:"attempt_id,refTable=attempts,refColumn=id,required=true" json:"attemptId"`
	RunId        *string `sqlx:"run_id,required=true" json:"runId"`
	BusinessKey  *string `sqlx:"business_key,required=true" json:"businessKey"`
	State        *string `sqlx:"state,required=true" json:"state"`
	Revision     *int    `sqlx:"revision,required=true" json:"revision"`
	EvidenceJson *string `sqlx:"evidence_json" json:"evidenceJson"`
}

// Milestone is generated canonical view metadata for LoadRecovery.
type Milestone struct {
	Namespace    *string `sqlx:"namespace,refTable=runs,refColumn=namespace,required=true,primaryKey=true" json:"namespace"`
	Id           *string `sqlx:"id,required=true,primaryKey=true" json:"id"`
	RunId        *string `sqlx:"run_id,refTable=runs,refColumn=id,required=true" json:"runId"`
	AttemptId    *string `sqlx:"attempt_id,required=true" json:"attemptId"`
	State        *string `sqlx:"state,required=true" json:"state"`
	EvidenceJson *string `sqlx:"evidence_json" json:"evidenceJson"`
}

// Variable is generated canonical view metadata for LoadRecovery.
type Variable struct {
	Namespace *string `sqlx:"namespace,refTable=runs,refColumn=namespace,required=true,primaryKey=true" json:"namespace"`
	RunId     *string `sqlx:"run_id,refTable=runs,refColumn=id,required=true,primaryKey=true" json:"runId"`
	Name      *string `sqlx:"name,required=true,primaryKey=true" json:"name"`
	ValueJson *string `sqlx:"value_json,required=true" json:"valueJson"`
}

// Event is generated canonical view metadata for LoadRecovery.
type Event struct {
	Namespace   *string `sqlx:"namespace,refTable=runs,refColumn=namespace,required=true,primaryKey=true" json:"namespace"`
	Id          *string `sqlx:"id,required=true,primaryKey=true" json:"id"`
	RunId       *string `sqlx:"run_id,refTable=runs,refColumn=id,required=true" json:"runId"`
	AttemptId   *string `sqlx:"attempt_id" json:"attemptId"`
	Sequence    *int    `sqlx:"sequence,required=true" json:"sequence"`
	Kind        *string `sqlx:"kind,required=true" json:"kind"`
	PayloadJson *string `sqlx:"payload_json,required=true" json:"payloadJson"`
	CreatedAt   *string `sqlx:"created_at,required=true" json:"createdAt"`
}

// WorkflowBudget is generated canonical view metadata for LoadRecovery.
type WorkflowBudget struct {
	Namespace    *string `sqlx:"namespace,refTable=runs,refColumn=namespace,required=true,primaryKey=true" json:"namespace"`
	RunId        *string `sqlx:"run_id,refTable=runs,refColumn=id,required=true,primaryKey=true" json:"runId"`
	Revision     *int    `sqlx:"revision,required=true" json:"revision"`
	MaxRepairs   *int    `sqlx:"max_repairs,required=true" json:"maxRepairs"`
	UsedRepairs  *int    `sqlx:"used_repairs,required=true" json:"usedRepairs"`
	MaxElapsedMs *int    `sqlx:"max_elapsed_ms,required=true" json:"maxElapsedMs"`
	ElapsedMs    *int    `sqlx:"elapsed_ms,required=true" json:"elapsedMs"`
}

// IncidentBudget is generated canonical view metadata for LoadRecovery.
type IncidentBudget struct {
	Namespace    *string `sqlx:"namespace,refTable=runs,refColumn=namespace,required=true,primaryKey=true" json:"namespace"`
	RunId        *string `sqlx:"run_id,refTable=runs,refColumn=id,required=true,primaryKey=true" json:"runId"`
	Id           *string `sqlx:"id,required=true,primaryKey=true" json:"id"`
	Revision     *int    `sqlx:"revision,required=true" json:"revision"`
	MaxRepairs   *int    `sqlx:"max_repairs,required=true" json:"maxRepairs"`
	UsedRepairs  *int    `sqlx:"used_repairs,required=true" json:"usedRepairs"`
	MaxElapsedMs *int    `sqlx:"max_elapsed_ms,required=true" json:"maxElapsedMs"`
	ElapsedMs    *int    `sqlx:"elapsed_ms,required=true" json:"elapsedMs"`
}

// RepairRevision is generated canonical view metadata for LoadRecovery.
type RepairRevision struct {
	Namespace         *string `sqlx:"namespace,refTable=runs,refColumn=namespace,required=true,primaryKey=true" json:"namespace"`
	Id                *string `sqlx:"id,required=true,primaryKey=true" json:"id"`
	RunId             *string `sqlx:"run_id,refTable=runs,refColumn=id,required=true" json:"runId"`
	ParentPlanId      *string `sqlx:"parent_plan_id,refTable=plan_revisions,refColumn=id,required=true" json:"parentPlanId"`
	NewPlanId         *string `sqlx:"new_plan_id,refTable=plan_revisions,refColumn=id,required=true" json:"newPlanId"`
	ParentContentHash *string `sqlx:"parent_content_hash,required=true" json:"parentContentHash"`
	ParentPlanHash    *string `sqlx:"parent_plan_hash,required=true" json:"parentPlanHash"`
	PlanHash          *string `sqlx:"plan_hash,required=true" json:"planHash"`
	ObjectiveHash     *string `sqlx:"objective_hash,required=true" json:"objectiveHash"`
	PatchHash         *string `sqlx:"patch_hash,required=true" json:"patchHash"`
	EvidenceJson      *string `sqlx:"evidence_json,required=true" json:"evidenceJson"`
	PolicyHash        *string `sqlx:"policy_hash,required=true" json:"policyHash"`
	CompletedSteps    *int    `sqlx:"completed_steps,required=true" json:"completedSteps"`
	IncidentId        *string `sqlx:"incident_id,required=true" json:"incidentId"`
	RunRevision       *int    `sqlx:"run_revision,required=true" json:"runRevision"`
	AdmittedAt        *string `sqlx:"admitted_at,required=true" json:"admittedAt"`
}

// RepairLineage is generated canonical view metadata for LoadRecovery.
type RepairLineage struct {
	Namespace      *string `sqlx:"namespace,refTable=repair_revisions,refColumn=namespace,required=true,primaryKey=true" json:"namespace"`
	Id             *string `sqlx:"id,required=true,primaryKey=true" json:"id"`
	RunId          *string `sqlx:"run_id,required=true" json:"runId"`
	RepairId       *string `sqlx:"repair_id,refTable=repair_revisions,refColumn=id,required=true" json:"repairId"`
	NewPlanId      *string `sqlx:"new_plan_id,refTable=plan_revisions,refColumn=id,required=true" json:"newPlanId"`
	StepId         *string `sqlx:"step_id,required=true" json:"stepId"`
	StepIndex      *int    `sqlx:"step_index,required=true" json:"stepIndex"`
	OriginalPlanId *string `sqlx:"original_plan_id,refTable=plan_revisions,refColumn=id,required=true" json:"originalPlanId"`
	OriginalStepId *string `sqlx:"original_step_id,required=true" json:"originalStepId"`
	AttemptId      *string `sqlx:"attempt_id,refTable=attempts,refColumn=id,required=true" json:"attemptId"`
	EffectId       *string `sqlx:"effect_id,refTable=effects,refColumn=id,required=true" json:"effectId"`
	BusinessKey    *string `sqlx:"business_key,required=true" json:"businessKey"`
	ResultHash     *string `sqlx:"result_hash,required=true" json:"resultHash"`
	State          *string `sqlx:"state,required=true" json:"state"`
}
