// Code generated by Datly for consentrequests; DO NOT EDIT.

package consentrequests

// ListRequestsInput is the generated input scaffold for consentrequests.
type ListRequestsInput struct {
	Namespace string                `parameter:"Namespace,kind=query,in=namespace,dataType=string,required=true"`
	RecordID  string                `parameter:"RecordID,kind=query,in=recordID,dataType=string,required=true"`
	Has       *ListRequestsInputHas `setMarker:"true" typeName:"ListRequestsInputHas" json:"-" sqlx:"-"`
}

type ListRequestsInputHas struct {
	Namespace bool
	RecordID  bool
}
