// Code generated by Datly for consentrequests; DO NOT EDIT.

package consentrequests

// ListRequestsOutput is the generated output scaffold for consentrequests.
type ListRequestsOutput struct {
	Data []*Record `parameter:"Data,kind=output,in=view,dataType=[]*Record" view:"consentrequests,type=Record,table=consent_records,limit=200" sql:"uri=mechanize_data_consentrequests_consentrequests:sql/consentrequests.sql"`
}
