// Code generated by Datly for consentrequests; DO NOT EDIT.

package consentrequests

import "embed"

// DatlyResourceNamespace identifies this package's generated resource filesystem.
const ConsentrequestsDatlyResourceNamespace = "mechanize_data_consentrequests_consentrequests"

//go:embed "sql/audit.sql" "sql/consentrequests.sql"
var ConsentrequestsDatlyResources embed.FS
