// Code generated by Datly for consentrequests; DO NOT EDIT.

package consentrequests

import (
	embed "embed"
	xdatly "github.com/viant/xdatly"
	reflect "reflect"
)

func init() {}

// Component is the generated component scaffold for consentrequests.
type ConsentrequestsComponent struct {
	Contract xdatly.Component[ListRequestsInput, ListRequestsOutput] "component:\"consentrequests,path=/internal/data/consentrequests,method=GET,connector=user,view=consentrequests\" routeName:\"consentrequests\" caseFormat:\"lc\""
}

// ConsentrequestsDatlyType returns the public component type.
func ConsentrequestsDatlyType() reflect.Type {
	return reflect.TypeOf((*ConsentrequestsComponent)(nil)).Elem()
}

// The package-level value keeps this real component type reachable for runtime discovery.
var ConsentrequestsDatly = new(ConsentrequestsComponent)
var _datlyReachableConsentrequestsComponent = reflect.TypeFor[ConsentrequestsComponent]()

func (ConsentrequestsComponent) EmbedFS() *embed.FS {
	return &ConsentrequestsDatlyResources
}

func (ConsentrequestsComponent) EmbedNamespace() string {
	return ConsentrequestsDatlyResourceNamespace
}
