// Code generated by Datly for ListChromeAttemptBindings; DO NOT EDIT.

package chromeattemptbindinglist

// ListChromeAttemptBindingsInput is the generated input scaffold for ListChromeAttemptBindings.
type ListChromeAttemptBindingsInput struct {
	Namespace       string                             `parameter:"Namespace,kind=query,in=namespace,dataType=string,required=true"`
	ClientID        string                             `parameter:"ClientID,kind=query,in=clientId,dataType=string,required=true"`
	ProfileChannel  string                             `parameter:"ProfileChannel,kind=query,in=profileChannel,dataType=string,required=true"`
	BrowserInstance string                             `parameter:"BrowserInstance,kind=query,in=browserInstance,dataType=string,required=true"`
	BrokerEpoch     string                             `parameter:"BrokerEpoch,kind=query,in=brokerEpoch,dataType=string,required=true"`
	ChannelEpoch    string                             `parameter:"ChannelEpoch,kind=query,in=channelEpoch,dataType=string,required=true"`
	ScopeHash       string                             `parameter:"ScopeHash,kind=query,in=scopeHash,dataType=string,required=true"`
	Has             *ListChromeAttemptBindingsInputHas `setMarker:"true" typeName:"ListChromeAttemptBindingsInputHas" json:"-" sqlx:"-"`
}

type ListChromeAttemptBindingsInputHas struct {
	Namespace       bool
	ClientID        bool
	ProfileChannel  bool
	BrowserInstance bool
	BrokerEpoch     bool
	ChannelEpoch    bool
	ScopeHash       bool
}
