// Code generated by Datly for ListChromeAttemptBindings; DO NOT EDIT.

package chromeattemptbindinglist

func (input *ListChromeAttemptBindingsInput) SetNamespace(value string) {
	if input == nil {
		return
	}
	input.Namespace = value
	if input.Has == nil {
		input.Has = &ListChromeAttemptBindingsInputHas{}
	}
	input.Has.Namespace = true
}

func (input *ListChromeAttemptBindingsInput) SetClientID(value string) {
	if input == nil {
		return
	}
	input.ClientID = value
	if input.Has == nil {
		input.Has = &ListChromeAttemptBindingsInputHas{}
	}
	input.Has.ClientID = true
}

func (input *ListChromeAttemptBindingsInput) SetProfileChannel(value string) {
	if input == nil {
		return
	}
	input.ProfileChannel = value
	if input.Has == nil {
		input.Has = &ListChromeAttemptBindingsInputHas{}
	}
	input.Has.ProfileChannel = true
}

func (input *ListChromeAttemptBindingsInput) SetBrowserInstance(value string) {
	if input == nil {
		return
	}
	input.BrowserInstance = value
	if input.Has == nil {
		input.Has = &ListChromeAttemptBindingsInputHas{}
	}
	input.Has.BrowserInstance = true
}

func (input *ListChromeAttemptBindingsInput) SetBrokerEpoch(value string) {
	if input == nil {
		return
	}
	input.BrokerEpoch = value
	if input.Has == nil {
		input.Has = &ListChromeAttemptBindingsInputHas{}
	}
	input.Has.BrokerEpoch = true
}

func (input *ListChromeAttemptBindingsInput) SetChannelEpoch(value string) {
	if input == nil {
		return
	}
	input.ChannelEpoch = value
	if input.Has == nil {
		input.Has = &ListChromeAttemptBindingsInputHas{}
	}
	input.Has.ChannelEpoch = true
}

func (input *ListChromeAttemptBindingsInput) SetScopeHash(value string) {
	if input == nil {
		return
	}
	input.ScopeHash = value
	if input.Has == nil {
		input.Has = &ListChromeAttemptBindingsInputHas{}
	}
	input.Has.ScopeHash = true
}
