// Code generated by Datly for LoadPlan; DO NOT EDIT.

package loadplan

import (
	embed "embed"
	xdatly "github.com/viant/xdatly"
	reflect "reflect"
)

func init() {}

// Component is the generated component scaffold for LoadPlan.
type LoadPlanComponent struct {
	Contract xdatly.Component[LoadPlanInput, LoadPlanOutput] "component:\"LoadPlan,path=/internal/data/loadplan,method=GET,connector=user,view=LoadPlan\" routeName:\"LoadPlan\" caseFormat:\"lc\""
}

// LoadPlanDatlyType returns the public component type.
func LoadPlanDatlyType() reflect.Type { return reflect.TypeOf((*LoadPlanComponent)(nil)).Elem() }

// The package-level value keeps this real component type reachable for runtime discovery.
var LoadPlanDatly = new(LoadPlanComponent)
var _datlyReachableLoadPlanComponent = reflect.TypeFor[LoadPlanComponent]()

func (LoadPlanComponent) EmbedFS() *embed.FS {
	return &LoadPlanDatlyResources
}

func (LoadPlanComponent) EmbedNamespace() string {
	return LoadPlanDatlyResourceNamespace
}
