// Code generated by Datly for CommitOutcome; DO NOT EDIT.

package commitoutcome

// CommitOutcomeInput is the generated input scaffold for CommitOutcome.
type CommitOutcomeInput struct {
	Namespace                        string                           `parameter:"Namespace,kind=query,in=namespace,dataType=string,required=true"`
	CommitOutcome                    []*Effect                        `parameter:"CommitOutcome,kind=body,in=Data,dataType=[]*Effect,cardinality=Many,required=true" view:"CommitOutcome,type=Effect,entityHooks=EffectLifecycle,table=effects" sql:"uri=mechanize_data_commitoutcome_commit_outcome:sql/commit_outcome.sql"`
	CommitOutcomeKeys                []CommitOutcomeKeysRow           `parameter:"CommitOutcomeKeys,kind=param,in=CommitOutcome,cardinality=Many" codec:"structql,'uri=mechanize_data_commitoutcome_commit_outcome:sql/commit_outcome_keys.sql'"`
	CurrentCommitOutcome             []*CurrentCommitOutcomeView      `parameter:"CurrentCommitOutcome,kind=view,in=CurrentCommitOutcome,cardinality=Many" view:"CurrentCommitOutcome,table=effects" sql:"uri=mechanize_data_commitoutcome_commit_outcome:sql/current_commit_outcome.sql"`
	CurrentMilestones                []*CurrentMilestonesView         `parameter:"CurrentMilestones,kind=view,in=CurrentMilestones,cardinality=Many" view:"CurrentMilestones,table=milestones" sql:"uri=mechanize_data_commitoutcome_commit_outcome:sql/current_milestones.sql"`
	CurrentEvents                    []*CurrentEventsView             `parameter:"CurrentEvents,kind=view,in=CurrentEvents,cardinality=Many" view:"CurrentEvents,table=events" sql:"uri=mechanize_data_commitoutcome_commit_outcome:sql/current_events.sql"`
	_commitOutcomeHandlerReadIndexes *CommitOutcomeHandlerReadIndexes `json:"-" sqlx:"-"`
	Has                              *CommitOutcomeInputHas           `setMarker:"true" typeName:"CommitOutcomeInputHas" json:"-" sqlx:"-"`
}

type CommitOutcomeInputHas struct {
	Namespace            bool
	CommitOutcome        bool
	CommitOutcomeKeys    bool
	CurrentCommitOutcome bool
	CurrentMilestones    bool
	CurrentEvents        bool
}
