// Code generated by Datly for LeaseEffects; DO NOT EDIT.

package leaseeffects

func (input *LeaseEffectsInput) SetNamespace(value string) {
	if input == nil {
		return
	}
	input.Namespace = value
	if input.Has == nil {
		input.Has = &LeaseEffectsInputHas{}
	}
	input.Has.Namespace = true
}

func (input *LeaseEffectsInput) SetLeaseEpoch(value int) {
	if input == nil {
		return
	}
	input.LeaseEpoch = value
	if input.Has == nil {
		input.Has = &LeaseEffectsInputHas{}
	}
	input.Has.LeaseEpoch = true
}
