// Code generated by Datly for TransitionRun; DO NOT EDIT.

package transitionrun

func (input *TransitionRunInput) SetNamespace(value string) {
	if input == nil {
		return
	}
	input.Namespace = value
	if input.Has == nil {
		input.Has = &TransitionRunInputHas{}
	}
	input.Has.Namespace = true
}

func (input *TransitionRunInput) SetTransitionRun(value []*Run) {
	if input == nil {
		return
	}
	input.TransitionRun = value
	if input.Has == nil {
		input.Has = &TransitionRunInputHas{}
	}
	input.Has.TransitionRun = true
}

func (input *TransitionRunInput) SetTransitionRunKeys(value []TransitionRunKeysRow) {
	if input == nil {
		return
	}
	input.TransitionRunKeys = value
	if input.Has == nil {
		input.Has = &TransitionRunInputHas{}
	}
	input.Has.TransitionRunKeys = true
}

func (input *TransitionRunInput) SetCurrentTransitionRun(value []*CurrentTransitionRunView) {
	if input == nil {
		return
	}
	input.CurrentTransitionRun = value
	if input.Has == nil {
		input.Has = &TransitionRunInputHas{}
	}
	input.Has.CurrentTransitionRun = true
}

func (input *TransitionRunInput) SetCurrentEvents(value []*CurrentEventsView) {
	if input == nil {
		return
	}
	input.CurrentEvents = value
	if input.Has == nil {
		input.Has = &TransitionRunInputHas{}
	}
	input.Has.CurrentEvents = true
}

func (input *TransitionRunInput) SetCurrentUnresolved(value []*CurrentUnresolvedView) {
	if input == nil {
		return
	}
	input.CurrentUnresolved = value
	if input.Has == nil {
		input.Has = &TransitionRunInputHas{}
	}
	input.Has.CurrentUnresolved = true
}
