// Code generated by Datly for TransitionRun; DO NOT EDIT.

package transitionrun

// TransitionRunOutput is the generated output scaffold for TransitionRun.
type TransitionRunOutput struct {
	Data []*Run `parameter:"Data,kind=output,in=body,dataType=[]*Run"`
}
