// Code generated by Datly for TransitionRun; DO NOT EDIT.

package transitionrun

import "embed"

// DatlyResourceNamespace identifies this package's generated resource filesystem.
const TransitionRunDatlyResourceNamespace = "mechanize_data_transitionrun_transition_run"

//go:embed "sql/current_events.sql" "sql/current_transition_run.sql" "sql/current_unresolved.sql" "sql/events.sql" "sql/transition_run.sql" "sql/transition_run_keys.sql" "sql/unresolved.sql"
var TransitionRunDatlyResources embed.FS
