// Code generated by Datly for TransitionRun; DO NOT EDIT.

package transitionrun

import (
	embed "embed"
	xdatly "github.com/viant/xdatly"
	reflect "reflect"
)

func init() {}

// Component is the generated component scaffold for TransitionRun.
type TransitionRunComponent struct {
	Contract xdatly.Component[TransitionRunInput, TransitionRunOutput] "component:\"TransitionRun,path=/internal/data/transitionrun,method=PATCH,connector=user,view=TransitionRun\" routeName:\"TransitionRun\" mutation:\"patch\" caseFormat:\"lc\""
}

// TransitionRunDatlyType returns the public component type.
func TransitionRunDatlyType() reflect.Type {
	return reflect.TypeOf((*TransitionRunComponent)(nil)).Elem()
}

// The package-level value keeps this real component type reachable for runtime discovery.
var TransitionRunDatly = new(TransitionRunComponent)
var _datlyReachableTransitionRunComponent = reflect.TypeFor[TransitionRunComponent]()

func (TransitionRunComponent) EmbedFS() *embed.FS {
	return &TransitionRunDatlyResources
}

func (TransitionRunComponent) EmbedNamespace() string {
	return TransitionRunDatlyResourceNamespace
}
