// Code generated by Datly for LoadRun; DO NOT EDIT.

package loadrun

// LoadRunInput is the generated input scaffold for LoadRun.
type LoadRunInput struct {
	Namespace string           `parameter:"Namespace,kind=query,in=namespace,dataType=string,required=true"`
	RunID     string           `parameter:"RunID,kind=query,in=runId,dataType=string,required=true"`
	Has       *LoadRunInputHas `setMarker:"true" typeName:"LoadRunInputHas" json:"-" sqlx:"-"`
}

type LoadRunInputHas struct {
	Namespace bool
	RunID     bool
}
