// Code generated by Datly for LoadRun; DO NOT EDIT.

package loadrun

// LoadRunOutput is the generated output scaffold for LoadRun.
type LoadRunOutput struct {
	Data []*Run `parameter:"Data,kind=output,in=view,dataType=[]*Run" view:"LoadRun,type=Run,table=runs" sql:"uri=mechanize_data_loadrun_load_run:sql/load_run.sql"`
}
