// Code generated by Datly for LoadRun; DO NOT EDIT.

package loadrun

import "embed"

// DatlyResourceNamespace identifies this package's generated resource filesystem.
const LoadRunDatlyResourceNamespace = "mechanize_data_loadrun_load_run"

//go:embed "sql/attempts.sql" "sql/checkpoints.sql" "sql/effects.sql" "sql/events.sql" "sql/load_run.sql" "sql/milestones.sql" "sql/plan.sql"
var LoadRunDatlyResources embed.FS
