// Code generated by Datly for LoadRun; DO NOT EDIT.

package loadrun

// Run is generated canonical view metadata for LoadRun.
type Run struct {
	Namespace        *string       `sqlx:"namespace,refTable=plan_revisions,refColumn=namespace,required=true,primaryKey=true" json:"namespace"`
	Id               *string       `sqlx:"id,required=true,primaryKey=true" json:"id"`
	PlanId           *string       `sqlx:"plan_id,refTable=plan_revisions,refColumn=id,required=true" json:"planId"`
	Status           *string       `sqlx:"status,required=true" json:"status"`
	Revision         *int          `sqlx:"revision,required=true" json:"revision"`
	EndlySessionId   *string       `sqlx:"endly_session_id" json:"endlySessionId"`
	EndlyOperationId *string       `sqlx:"endly_operation_id" json:"endlyOperationId"`
	CreatedAt        *string       `sqlx:"created_at,required=true" json:"createdAt"`
	UpdatedAt        *string       `sqlx:"updated_at,required=true" json:"updatedAt"`
	Attempts         []*Attempt    `view:"attempts,type=Attempt,table=attempts" on:"Namespace:records.namespace=Namespace:attempts.namespace,Id:records.id=RunId:attempts.run_id" json:"attempts" sql:"uri=mechanize_data_loadrun_load_run:sql/attempts.sql"`
	Effects          []*Effect     `view:"effects,type=Effect,table=effects" on:"Namespace:records.namespace=Namespace:effects.namespace,Id:records.id=RunId:effects.run_id" json:"effects" sql:"uri=mechanize_data_loadrun_load_run:sql/effects.sql"`
	Checkpoints      []*Checkpoint `view:"checkpoints,type=Checkpoint,table=checkpoints" on:"Namespace:records.namespace=Namespace:checkpoints.namespace,Id:records.id=RunId:checkpoints.run_id" json:"checkpoints" sql:"uri=mechanize_data_loadrun_load_run:sql/checkpoints.sql"`
	Milestones       []*Milestone  `view:"milestones,type=Milestone,table=milestones" on:"Namespace:records.namespace=Namespace:milestones.namespace,Id:records.id=RunId:milestones.run_id" json:"milestones" sql:"uri=mechanize_data_loadrun_load_run:sql/milestones.sql"`
	Plan             *PlanRevision `view:"plan,type=PlanRevision,table=plan_revisions" on:"Namespace:records.namespace=Namespace:plan.namespace,PlanId:records.plan_id=Id:plan.id" json:"plan" sql:"uri=mechanize_data_loadrun_load_run:sql/plan.sql"`
	Events           []*Event      `view:"events,type=Event,table=events" on:"Namespace:records.namespace=Namespace:events.namespace,Id:records.id=RunId:events.run_id" json:"events" sql:"uri=mechanize_data_loadrun_load_run:sql/events.sql"`
}

// Attempt is generated canonical view metadata for LoadRun.
type Attempt struct {
	Namespace  *string `sqlx:"namespace,refTable=runs,refColumn=namespace,required=true,primaryKey=true" json:"namespace"`
	Id         *string `sqlx:"id,required=true,primaryKey=true" json:"id"`
	RunId      *string `sqlx:"run_id,refTable=runs,refColumn=id,required=true" json:"runId"`
	StepId     *string `sqlx:"step_id,required=true" json:"stepId"`
	PlanId     *string `sqlx:"plan_id,required=true" json:"planId"`
	LeaseEpoch *int    `sqlx:"lease_epoch,required=true" json:"leaseEpoch"`
	State      *string `sqlx:"state,required=true" json:"state"`
	CreatedAt  *string `sqlx:"created_at,required=true" json:"createdAt"`
}

// Effect is generated canonical view metadata for LoadRun.
type Effect struct {
	Namespace    *string `sqlx:"namespace,refTable=attempts,refColumn=namespace,required=true,primaryKey=true" json:"namespace"`
	Id           *string `sqlx:"id,required=true,primaryKey=true" json:"id"`
	AttemptId    *string `sqlx:"attempt_id,refTable=attempts,refColumn=id,required=true" json:"attemptId"`
	RunId        *string `sqlx:"run_id,required=true" json:"runId"`
	BusinessKey  *string `sqlx:"business_key,required=true" json:"businessKey"`
	State        *string `sqlx:"state,required=true" json:"state"`
	Revision     *int    `sqlx:"revision,required=true" json:"revision"`
	EvidenceJson *string `sqlx:"evidence_json" json:"evidenceJson"`
}

// Checkpoint is generated canonical view metadata for LoadRun.
type Checkpoint struct {
	Namespace        *string `sqlx:"namespace,refTable=runs,refColumn=namespace,required=true,primaryKey=true" json:"namespace"`
	Id               *string `sqlx:"id,required=true,primaryKey=true" json:"id"`
	RunId            *string `sqlx:"run_id,refTable=runs,refColumn=id,required=true" json:"runId"`
	PlanId           *string `sqlx:"plan_id,required=true" json:"planId"`
	RunRevision      *int    `sqlx:"run_revision,required=true" json:"runRevision"`
	EventSequence    *int    `sqlx:"event_sequence,required=true" json:"eventSequence"`
	ManifestHash     *string `sqlx:"manifest_hash,required=true" json:"manifestHash"`
	ManifestJson     *string `sqlx:"manifest_json,required=true" json:"manifestJson"`
	PublicationState *string `sqlx:"publication_state,required=true" json:"publicationState"`
	CreatedAt        *string `sqlx:"created_at,required=true" json:"createdAt"`
}

// Milestone is generated canonical view metadata for LoadRun.
type Milestone struct {
	Namespace    *string `sqlx:"namespace,refTable=runs,refColumn=namespace,required=true,primaryKey=true" json:"namespace"`
	Id           *string `sqlx:"id,required=true,primaryKey=true" json:"id"`
	RunId        *string `sqlx:"run_id,refTable=runs,refColumn=id,required=true" json:"runId"`
	AttemptId    *string `sqlx:"attempt_id,required=true" json:"attemptId"`
	State        *string `sqlx:"state,required=true" json:"state"`
	EvidenceJson *string `sqlx:"evidence_json" json:"evidenceJson"`
}

// PlanRevision is generated canonical view metadata for LoadRun.
type PlanRevision struct {
	Namespace   *string `sqlx:"namespace,required=true,primaryKey=true" json:"namespace"`
	Id          *string `sqlx:"id,required=true,primaryKey=true" json:"id"`
	ParentId    *string `sqlx:"parent_id" json:"parentId"`
	ObjectiveId *string `sqlx:"objective_id,required=true" json:"objectiveId"`
	ContentHash *string `sqlx:"content_hash,required=true" json:"contentHash"`
	ContentJson *string `sqlx:"content_json,required=true" json:"contentJson"`
	CreatedAt   *string `sqlx:"created_at,required=true" json:"createdAt"`
}

// Event is generated canonical view metadata for LoadRun.
type Event struct {
	Namespace   *string `sqlx:"namespace,refTable=runs,refColumn=namespace,required=true,primaryKey=true" json:"namespace"`
	Id          *string `sqlx:"id,required=true,primaryKey=true" json:"id"`
	RunId       *string `sqlx:"run_id,refTable=runs,refColumn=id,required=true" json:"runId"`
	AttemptId   *string `sqlx:"attempt_id" json:"attemptId"`
	Sequence    *int    `sqlx:"sequence,required=true" json:"sequence"`
	Kind        *string `sqlx:"kind,required=true" json:"kind"`
	PayloadJson *string `sqlx:"payload_json,required=true" json:"payloadJson"`
	CreatedAt   *string `sqlx:"created_at,required=true" json:"createdAt"`
}
