// Code generated by Datly for GetArtifact; DO NOT EDIT.

package getartifact

func (input *GetArtifactInput) SetNamespace(value string) {
	if input == nil {
		return
	}
	input.Namespace = value
	if input.Has == nil {
		input.Has = &GetArtifactInputHas{}
	}
	input.Has.Namespace = true
}

func (input *GetArtifactInput) SetArtifactID(value string) {
	if input == nil {
		return
	}
	input.ArtifactID = value
	if input.Has == nil {
		input.Has = &GetArtifactInputHas{}
	}
	input.Has.ArtifactID = true
}
