// Code generated by Datly for GetArtifact; DO NOT EDIT.

package getartifact

import (
	embed "embed"
	xdatly "github.com/viant/xdatly"
	reflect "reflect"
)

func init() {}

// Component is the generated component scaffold for GetArtifact.
type GetArtifactComponent struct {
	Contract xdatly.Component[GetArtifactInput, GetArtifactOutput] "component:\"GetArtifact,path=/internal/data/getartifact,method=GET,connector=user,view=GetArtifact\" routeName:\"GetArtifact\" caseFormat:\"lc\""
}

// GetArtifactDatlyType returns the public component type.
func GetArtifactDatlyType() reflect.Type { return reflect.TypeOf((*GetArtifactComponent)(nil)).Elem() }

// The package-level value keeps this real component type reachable for runtime discovery.
var GetArtifactDatly = new(GetArtifactComponent)
var _datlyReachableGetArtifactComponent = reflect.TypeFor[GetArtifactComponent]()

func (GetArtifactComponent) EmbedFS() *embed.FS {
	return &GetArtifactDatlyResources
}

func (GetArtifactComponent) EmbedNamespace() string {
	return GetArtifactDatlyResourceNamespace
}
