// Code generated by Datly for BeginAttempt; DO NOT EDIT.

package beginattempt

// BeginAttemptInput is the generated input scaffold for BeginAttempt.
type BeginAttemptInput struct {
	Namespace                       string                          `parameter:"Namespace,kind=query,in=namespace,dataType=string,required=true"`
	BeginAttempt                    []*Run                          `parameter:"BeginAttempt,kind=body,in=Data,dataType=[]*Run,cardinality=Many,required=true" view:"BeginAttempt,type=Run,entityHooks=RunLifecycle,table=runs" sql:"uri=mechanize_data_beginattempt_begin_attempt:sql/begin_attempt.sql"`
	BeginAttemptKeys                []BeginAttemptKeysRow           `parameter:"BeginAttemptKeys,kind=param,in=BeginAttempt,cardinality=Many" codec:"structql,'uri=mechanize_data_beginattempt_begin_attempt:sql/begin_attempt_keys.sql'"`
	CurrentBeginAttempt             []*CurrentBeginAttemptView      `parameter:"CurrentBeginAttempt,kind=view,in=CurrentBeginAttempt,cardinality=Many" view:"CurrentBeginAttempt,table=runs" sql:"uri=mechanize_data_beginattempt_begin_attempt:sql/current_begin_attempt.sql"`
	CurrentAttempts                 []*CurrentAttemptsView          `parameter:"CurrentAttempts,kind=view,in=CurrentAttempts,cardinality=Many" view:"CurrentAttempts,table=attempts" sql:"uri=mechanize_data_beginattempt_begin_attempt:sql/current_attempts.sql"`
	CurrentIntents                  []*CurrentIntentsView           `parameter:"CurrentIntents,kind=view,in=CurrentIntents,cardinality=Many" view:"CurrentIntents,table=effects" sql:"uri=mechanize_data_beginattempt_begin_attempt:sql/current_intents.sql"`
	CurrentEvents                   []*CurrentEventsView            `parameter:"CurrentEvents,kind=view,in=CurrentEvents,cardinality=Many" view:"CurrentEvents,table=events" sql:"uri=mechanize_data_beginattempt_begin_attempt:sql/current_events.sql"`
	_beginAttemptHandlerReadIndexes *BeginAttemptHandlerReadIndexes `json:"-" sqlx:"-"`
	Has                             *BeginAttemptInputHas           `setMarker:"true" typeName:"BeginAttemptInputHas" json:"-" sqlx:"-"`
}

type BeginAttemptInputHas struct {
	Namespace           bool
	BeginAttempt        bool
	BeginAttemptKeys    bool
	CurrentBeginAttempt bool
	CurrentAttempts     bool
	CurrentIntents      bool
	CurrentEvents       bool
}
