// Code generated by Datly for BeginAttempt; DO NOT EDIT.

package beginattempt

// Run is generated canonical view metadata for BeginAttempt.
type Run struct {
	Revision         *int                `writer:"concurrency" sqlx:"revision,required=true" json:"revision"`
	Namespace        *string             `sqlx:"namespace,refTable=plan_revisions,refColumn=namespace,required=true,primaryKey=true" json:"namespace"`
	Id               *string             `sqlx:"id,required=true,primaryKey=true" json:"id"`
	PlanId           *string             `sqlx:"plan_id,refTable=plan_revisions,refColumn=id,required=true" json:"planId"`
	Status           *string             `sqlx:"status,required=true" json:"status"`
	EndlySessionId   *string             `sqlx:"endly_session_id" json:"endlySessionId"`
	EndlyOperationId *string             `sqlx:"endly_operation_id" json:"endlyOperationId"`
	CreatedAt        *string             `sqlx:"created_at,required=true" json:"createdAt"`
	UpdatedAt        *string             `sqlx:"updated_at,required=true" json:"updatedAt"`
	Attempts         []*Attempt          `view:"attempts,type=Attempt,entityHooks=AttemptLifecycle,table=attempts" on:"Namespace:records.namespace=Namespace:attempts.namespace,Id:records.id=RunId:attempts.run_id" json:"attempts" sql:"uri=mechanize_data_beginattempt_begin_attempt:sql/attempts.sql"`
	Unresolved       []*UnresolvedEffect `view:"unresolved,type=UnresolvedEffect,table=effects,auxiliary=true" on:"Namespace:records.namespace=Namespace:unresolved.namespace,Id:records.id=RunId:unresolved.run_id" json:"unresolved" sql:"uri=mechanize_data_beginattempt_begin_attempt:sql/unresolved.sql"`
	Has              *RunHas             `setMarker:"true" format:"-" sqlx:"-" diff:"-" json:"-" typeName:"RunHas"`
}

type RunHas struct {
	Revision         bool
	Namespace        bool
	Id               bool
	PlanId           bool
	Status           bool
	EndlySessionId   bool
	EndlyOperationId bool
	CreatedAt        bool
	UpdatedAt        bool
	Attempts         bool
}

// Attempt is generated canonical view metadata for BeginAttempt.
type Attempt struct {
	Namespace  *string     `sqlx:"namespace,refTable=runs,refColumn=namespace,required=true,primaryKey=true" json:"namespace"`
	Id         *string     `sqlx:"id,required=true,primaryKey=true" json:"id"`
	RunId      *string     `sqlx:"run_id,refTable=runs,refColumn=id,required=true" json:"runId"`
	StepId     *string     `sqlx:"step_id,required=true" json:"stepId"`
	PlanId     *string     `sqlx:"plan_id,required=true" json:"planId"`
	LeaseEpoch *int        `sqlx:"lease_epoch,required=true" json:"leaseEpoch"`
	State      *string     `sqlx:"state,required=true" json:"state"`
	CreatedAt  *string     `sqlx:"created_at,required=true" json:"createdAt"`
	Intents    []*Intent   `view:"intents,type=Intent,table=effects" on:"Namespace:attempts.namespace=Namespace:intents.namespace,Id:attempts.id=AttemptId:intents.attempt_id" json:"intents" sql:"uri=mechanize_data_beginattempt_begin_attempt:sql/intents.sql"`
	Events     []*Event    `view:"events,type=Event,table=events" on:"Namespace:attempts.namespace=Namespace:events.namespace,Id:attempts.id=AttemptId:events.attempt_id" json:"events" sql:"uri=mechanize_data_beginattempt_begin_attempt:sql/events.sql"`
	Has        *AttemptHas `setMarker:"true" format:"-" sqlx:"-" diff:"-" json:"-" typeName:"AttemptHas"`
}

type AttemptHas struct {
	Namespace  bool
	Id         bool
	RunId      bool
	StepId     bool
	PlanId     bool
	LeaseEpoch bool
	State      bool
	CreatedAt  bool
	Intents    bool
	Events     bool
}

// Intent is generated canonical view metadata for BeginAttempt.
type Intent struct {
	Namespace    *string    `sqlx:"namespace,refTable=attempts,refColumn=namespace,required=true,primaryKey=true" json:"namespace"`
	Id           *string    `sqlx:"id,required=true,primaryKey=true" json:"id"`
	AttemptId    *string    `sqlx:"attempt_id,refTable=attempts,refColumn=id,required=true" json:"attemptId"`
	RunId        *string    `sqlx:"run_id,required=true" json:"runId"`
	BusinessKey  *string    `sqlx:"business_key,required=true" json:"businessKey"`
	State        *string    `sqlx:"state,required=true" json:"state"`
	Revision     *int       `sqlx:"revision,required=true" json:"revision"`
	EvidenceJson *string    `sqlx:"evidence_json" json:"evidenceJson"`
	Has          *IntentHas `setMarker:"true" format:"-" sqlx:"-" diff:"-" json:"-" typeName:"IntentHas"`
}

type IntentHas struct {
	Namespace    bool
	Id           bool
	AttemptId    bool
	RunId        bool
	BusinessKey  bool
	State        bool
	Revision     bool
	EvidenceJson bool
}

// Event is generated canonical view metadata for BeginAttempt.
type Event struct {
	Namespace   *string   `sqlx:"namespace,refTable=runs,refColumn=namespace,required=true,primaryKey=true" json:"namespace"`
	Id          *string   `sqlx:"id,required=true,primaryKey=true" json:"id"`
	RunId       *string   `sqlx:"run_id,refTable=runs,refColumn=id,required=true" json:"runId"`
	AttemptId   *string   `sqlx:"attempt_id" json:"attemptId"`
	Sequence    *int      `sqlx:"sequence,required=true" json:"sequence"`
	Kind        *string   `sqlx:"kind,required=true" json:"kind"`
	PayloadJson *string   `sqlx:"payload_json,required=true" json:"payloadJson"`
	CreatedAt   *string   `sqlx:"created_at,required=true" json:"createdAt"`
	Has         *EventHas `setMarker:"true" format:"-" sqlx:"-" diff:"-" json:"-" typeName:"EventHas"`
}

type EventHas struct {
	Namespace   bool
	Id          bool
	RunId       bool
	AttemptId   bool
	Sequence    bool
	Kind        bool
	PayloadJson bool
	CreatedAt   bool
}

// UnresolvedEffect is generated canonical view metadata for BeginAttempt.
type UnresolvedEffect struct {
	Namespace    *string `sqlx:"namespace,refTable=attempts,refColumn=namespace,required=true,primaryKey=true" json:"namespace"`
	Id           *string `sqlx:"id,required=true,primaryKey=true" json:"id"`
	AttemptId    *string `sqlx:"attempt_id,refTable=attempts,refColumn=id,required=true" json:"attemptId"`
	RunId        *string `sqlx:"run_id,required=true" json:"runId"`
	BusinessKey  *string `sqlx:"business_key,required=true" json:"businessKey"`
	State        *string `sqlx:"state,required=true" json:"state"`
	Revision     *int    `sqlx:"revision,required=true" json:"revision"`
	EvidenceJson *string `sqlx:"evidence_json" json:"evidenceJson"`
}

// CurrentBeginAttemptView is generated canonical view metadata for BeginAttempt.
type CurrentBeginAttemptView struct {
	Revision         *int    `sqlx:"revision,required=true" json:"revision"`
	Namespace        *string `sqlx:"namespace,refTable=plan_revisions,refColumn=namespace,required=true,primaryKey=true" json:"namespace"`
	Id               *string `sqlx:"id,required=true,primaryKey=true" json:"id"`
	PlanId           *string `sqlx:"plan_id,refTable=plan_revisions,refColumn=id,required=true" json:"planId"`
	Status           *string `sqlx:"status,required=true" json:"status"`
	EndlySessionId   *string `sqlx:"endly_session_id" json:"endlySessionId"`
	EndlyOperationId *string `sqlx:"endly_operation_id" json:"endlyOperationId"`
	CreatedAt        *string `sqlx:"created_at,required=true" json:"createdAt"`
	UpdatedAt        *string `sqlx:"updated_at,required=true" json:"updatedAt"`
}

// CurrentAttemptsView is generated canonical view metadata for BeginAttempt.
type CurrentAttemptsView struct {
	Namespace  *string `sqlx:"namespace,refTable=runs,refColumn=namespace,required=true,primaryKey=true" json:"namespace"`
	Id         *string `sqlx:"id,required=true,primaryKey=true" json:"id"`
	RunId      *string `sqlx:"run_id,refTable=runs,refColumn=id,required=true" json:"runId"`
	StepId     *string `sqlx:"step_id,required=true" json:"stepId"`
	PlanId     *string `sqlx:"plan_id,required=true" json:"planId"`
	LeaseEpoch *int    `sqlx:"lease_epoch,required=true" json:"leaseEpoch"`
	State      *string `sqlx:"state,required=true" json:"state"`
	CreatedAt  *string `sqlx:"created_at,required=true" json:"createdAt"`
}

// CurrentIntentsView is generated canonical view metadata for BeginAttempt.
type CurrentIntentsView struct {
	Namespace    *string `sqlx:"namespace,refTable=attempts,refColumn=namespace,required=true,primaryKey=true" json:"namespace"`
	Id           *string `sqlx:"id,required=true,primaryKey=true" json:"id"`
	AttemptId    *string `sqlx:"attempt_id,refTable=attempts,refColumn=id,required=true" json:"attemptId"`
	RunId        *string `sqlx:"run_id,required=true" json:"runId"`
	BusinessKey  *string `sqlx:"business_key,required=true" json:"businessKey"`
	State        *string `sqlx:"state,required=true" json:"state"`
	Revision     *int    `sqlx:"revision,required=true" json:"revision"`
	EvidenceJson *string `sqlx:"evidence_json" json:"evidenceJson"`
}

// CurrentEventsView is generated canonical view metadata for BeginAttempt.
type CurrentEventsView struct {
	Namespace   *string `sqlx:"namespace,refTable=runs,refColumn=namespace,required=true,primaryKey=true" json:"namespace"`
	Id          *string `sqlx:"id,required=true,primaryKey=true" json:"id"`
	RunId       *string `sqlx:"run_id,refTable=runs,refColumn=id,required=true" json:"runId"`
	AttemptId   *string `sqlx:"attempt_id" json:"attemptId"`
	Sequence    *int    `sqlx:"sequence,required=true" json:"sequence"`
	Kind        *string `sqlx:"kind,required=true" json:"kind"`
	PayloadJson *string `sqlx:"payload_json,required=true" json:"payloadJson"`
	CreatedAt   *string `sqlx:"created_at,required=true" json:"createdAt"`
}

type BeginAttemptKeysRow struct {
	Namespace *string `sqlx:"namespace"`
	Id        *string `sqlx:"id"`
}
