// Code generated by Datly for LoadChromeRetirement; DO NOT EDIT.

package chromeretirementget

// LoadChromeRetirementOutput is the generated output scaffold for LoadChromeRetirement.
type LoadChromeRetirementOutput struct {
	Data []*Retirement `parameter:"Data,kind=output,in=view,dataType=[]*Retirement" view:"LoadChromeRetirement,type=Retirement,table=chrome_retirements" sql:"uri=mechanize_data_chromeretirementget_load_chrome_retirement:sql/load_chrome_retirement.sql"`
}
