// Code generated by Datly for LoadChromeRetirement; DO NOT EDIT.

package chromeretirementget

import (
	embed "embed"
	xdatly "github.com/viant/xdatly"
	reflect "reflect"
)

func init() {}

// Component is the generated component scaffold for LoadChromeRetirement.
type LoadChromeRetirementComponent struct {
	Contract xdatly.Component[LoadChromeRetirementInput, LoadChromeRetirementOutput] "component:\"LoadChromeRetirement,path=/internal/data/chromeretirementget,method=GET,connector=user,view=LoadChromeRetirement\" routeName:\"LoadChromeRetirement\" caseFormat:\"lc\""
}

// LoadChromeRetirementDatlyType returns the public component type.
func LoadChromeRetirementDatlyType() reflect.Type {
	return reflect.TypeOf((*LoadChromeRetirementComponent)(nil)).Elem()
}

// The package-level value keeps this real component type reachable for runtime discovery.
var LoadChromeRetirementDatly = new(LoadChromeRetirementComponent)
var _datlyReachableLoadChromeRetirementComponent = reflect.TypeFor[LoadChromeRetirementComponent]()

func (LoadChromeRetirementComponent) EmbedFS() *embed.FS {
	return &LoadChromeRetirementDatlyResources
}

func (LoadChromeRetirementComponent) EmbedNamespace() string {
	return LoadChromeRetirementDatlyResourceNamespace
}
