// Code generated by Datly for StopBoundary; DO NOT EDIT.

package stopboundary

func (input *StopBoundaryInput) SetNamespace(value string) {
	if input == nil {
		return
	}
	input.Namespace = value
	if input.Has == nil {
		input.Has = &StopBoundaryInputHas{}
	}
	input.Has.Namespace = true
}

func (input *StopBoundaryInput) SetStopBoundary(value []*Run) {
	if input == nil {
		return
	}
	input.StopBoundary = value
	if input.Has == nil {
		input.Has = &StopBoundaryInputHas{}
	}
	input.Has.StopBoundary = true
}

func (input *StopBoundaryInput) SetStopBoundaryKeys(value []StopBoundaryKeysRow) {
	if input == nil {
		return
	}
	input.StopBoundaryKeys = value
	if input.Has == nil {
		input.Has = &StopBoundaryInputHas{}
	}
	input.Has.StopBoundaryKeys = true
}

func (input *StopBoundaryInput) SetCurrentStopBoundary(value []*CurrentStopBoundaryView) {
	if input == nil {
		return
	}
	input.CurrentStopBoundary = value
	if input.Has == nil {
		input.Has = &StopBoundaryInputHas{}
	}
	input.Has.CurrentStopBoundary = true
}

func (input *StopBoundaryInput) SetCurrentEvents(value []*CurrentEventsView) {
	if input == nil {
		return
	}
	input.CurrentEvents = value
	if input.Has == nil {
		input.Has = &StopBoundaryInputHas{}
	}
	input.Has.CurrentEvents = true
}
