// Code generated by Datly for StopBoundary; DO NOT EDIT.

package stopboundary

import "embed"

// DatlyResourceNamespace identifies this package's generated resource filesystem.
const StopBoundaryDatlyResourceNamespace = "mechanize_data_stopboundary_stop_boundary"

//go:embed "sql/current_events.sql" "sql/current_stop_boundary.sql" "sql/events.sql" "sql/stop_boundary.sql" "sql/stop_boundary_keys.sql"
var StopBoundaryDatlyResources embed.FS
