// Code generated by Datly for ReconcileEffect; DO NOT EDIT.

package reconcileeffect

import "embed"

// DatlyResourceNamespace identifies this package's generated resource filesystem.
const ReconcileEffectDatlyResourceNamespace = "mechanize_data_reconcileeffect_reconcile_effect"

//go:embed "sql/attempts.sql" "sql/current_attempts.sql" "sql/current_effects.sql" "sql/current_events.sql" "sql/current_milestones.sql" "sql/current_plans.sql" "sql/current_reconcile_effect.sql" "sql/effects.sql" "sql/events.sql" "sql/milestones.sql" "sql/plans.sql" "sql/reconcile_effect.sql" "sql/reconcile_effect_keys.sql"
var ReconcileEffectDatlyResources embed.FS
