// Code generated by Datly for CreateChromeAttemptBinding; DO NOT EDIT.

package chromeattemptbindingcreate

import (
	context "context"
	fmt "fmt"
	xshape "github.com/viant/x/shape"
	xhandler "github.com/viant/xdatly/handler"
	reflect "reflect"
)

type CreateChromeAttemptBindingHandlerIntentReadSlice []*IntentReadRow

func CreateChromeAttemptBindingHandlerIntentReadIndexByNamespaceKey(value *IntentReadRow) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.Namespace == nil {
		return zero, false
	}
	return *value.Namespace, true
}

type CreateChromeAttemptBindingHandlerIntentReadIndexedByNamespace map[string]*IntentReadRow

func (rows CreateChromeAttemptBindingHandlerIntentReadSlice) IndexByNamespace() (CreateChromeAttemptBindingHandlerIntentReadIndexedByNamespace, error) {
	result := make(CreateChromeAttemptBindingHandlerIntentReadIndexedByNamespace)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerIntentReadIndexByNamespaceKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index CreateChromeAttemptBindingHandlerIntentReadSlice.IndexByNamespace")
		}
		result[key] = row
	}
	return result, nil
}
func (index CreateChromeAttemptBindingHandlerIntentReadIndexedByNamespace) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type CreateChromeAttemptBindingHandlerIntentReadGroupedByNamespace map[string][]*IntentReadRow

func (rows CreateChromeAttemptBindingHandlerIntentReadSlice) GroupByNamespace() CreateChromeAttemptBindingHandlerIntentReadGroupedByNamespace {
	result := make(CreateChromeAttemptBindingHandlerIntentReadGroupedByNamespace)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerIntentReadIndexByNamespaceKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index CreateChromeAttemptBindingHandlerIntentReadGroupedByNamespace) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func CreateChromeAttemptBindingHandlerIntentReadIndexByIdKey(value *IntentReadRow) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.Id == nil {
		return zero, false
	}
	return *value.Id, true
}

type CreateChromeAttemptBindingHandlerIntentReadIndexedById map[string]*IntentReadRow

func (rows CreateChromeAttemptBindingHandlerIntentReadSlice) IndexById() (CreateChromeAttemptBindingHandlerIntentReadIndexedById, error) {
	result := make(CreateChromeAttemptBindingHandlerIntentReadIndexedById)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerIntentReadIndexByIdKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index CreateChromeAttemptBindingHandlerIntentReadSlice.IndexById")
		}
		result[key] = row
	}
	return result, nil
}
func (index CreateChromeAttemptBindingHandlerIntentReadIndexedById) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type CreateChromeAttemptBindingHandlerIntentReadGroupedById map[string][]*IntentReadRow

func (rows CreateChromeAttemptBindingHandlerIntentReadSlice) GroupById() CreateChromeAttemptBindingHandlerIntentReadGroupedById {
	result := make(CreateChromeAttemptBindingHandlerIntentReadGroupedById)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerIntentReadIndexByIdKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index CreateChromeAttemptBindingHandlerIntentReadGroupedById) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func CreateChromeAttemptBindingHandlerIntentReadIndexByAttemptIdKey(value *IntentReadRow) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.AttemptId == nil {
		return zero, false
	}
	return *value.AttemptId, true
}

type CreateChromeAttemptBindingHandlerIntentReadIndexedByAttemptId map[string]*IntentReadRow

func (rows CreateChromeAttemptBindingHandlerIntentReadSlice) IndexByAttemptId() (CreateChromeAttemptBindingHandlerIntentReadIndexedByAttemptId, error) {
	result := make(CreateChromeAttemptBindingHandlerIntentReadIndexedByAttemptId)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerIntentReadIndexByAttemptIdKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index CreateChromeAttemptBindingHandlerIntentReadSlice.IndexByAttemptId")
		}
		result[key] = row
	}
	return result, nil
}
func (index CreateChromeAttemptBindingHandlerIntentReadIndexedByAttemptId) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type CreateChromeAttemptBindingHandlerIntentReadGroupedByAttemptId map[string][]*IntentReadRow

func (rows CreateChromeAttemptBindingHandlerIntentReadSlice) GroupByAttemptId() CreateChromeAttemptBindingHandlerIntentReadGroupedByAttemptId {
	result := make(CreateChromeAttemptBindingHandlerIntentReadGroupedByAttemptId)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerIntentReadIndexByAttemptIdKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index CreateChromeAttemptBindingHandlerIntentReadGroupedByAttemptId) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func CreateChromeAttemptBindingHandlerIntentReadIndexByRunIdKey(value *IntentReadRow) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.RunId == nil {
		return zero, false
	}
	return *value.RunId, true
}

type CreateChromeAttemptBindingHandlerIntentReadIndexedByRunId map[string]*IntentReadRow

func (rows CreateChromeAttemptBindingHandlerIntentReadSlice) IndexByRunId() (CreateChromeAttemptBindingHandlerIntentReadIndexedByRunId, error) {
	result := make(CreateChromeAttemptBindingHandlerIntentReadIndexedByRunId)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerIntentReadIndexByRunIdKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index CreateChromeAttemptBindingHandlerIntentReadSlice.IndexByRunId")
		}
		result[key] = row
	}
	return result, nil
}
func (index CreateChromeAttemptBindingHandlerIntentReadIndexedByRunId) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type CreateChromeAttemptBindingHandlerIntentReadGroupedByRunId map[string][]*IntentReadRow

func (rows CreateChromeAttemptBindingHandlerIntentReadSlice) GroupByRunId() CreateChromeAttemptBindingHandlerIntentReadGroupedByRunId {
	result := make(CreateChromeAttemptBindingHandlerIntentReadGroupedByRunId)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerIntentReadIndexByRunIdKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index CreateChromeAttemptBindingHandlerIntentReadGroupedByRunId) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func CreateChromeAttemptBindingHandlerIntentReadIndexByBusinessKeyKey(value *IntentReadRow) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.BusinessKey == nil {
		return zero, false
	}
	return *value.BusinessKey, true
}

type CreateChromeAttemptBindingHandlerIntentReadIndexedByBusinessKey map[string]*IntentReadRow

func (rows CreateChromeAttemptBindingHandlerIntentReadSlice) IndexByBusinessKey() (CreateChromeAttemptBindingHandlerIntentReadIndexedByBusinessKey, error) {
	result := make(CreateChromeAttemptBindingHandlerIntentReadIndexedByBusinessKey)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerIntentReadIndexByBusinessKeyKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index CreateChromeAttemptBindingHandlerIntentReadSlice.IndexByBusinessKey")
		}
		result[key] = row
	}
	return result, nil
}
func (index CreateChromeAttemptBindingHandlerIntentReadIndexedByBusinessKey) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type CreateChromeAttemptBindingHandlerIntentReadGroupedByBusinessKey map[string][]*IntentReadRow

func (rows CreateChromeAttemptBindingHandlerIntentReadSlice) GroupByBusinessKey() CreateChromeAttemptBindingHandlerIntentReadGroupedByBusinessKey {
	result := make(CreateChromeAttemptBindingHandlerIntentReadGroupedByBusinessKey)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerIntentReadIndexByBusinessKeyKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index CreateChromeAttemptBindingHandlerIntentReadGroupedByBusinessKey) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func CreateChromeAttemptBindingHandlerIntentReadIndexByStateKey(value *IntentReadRow) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.State == nil {
		return zero, false
	}
	return *value.State, true
}

type CreateChromeAttemptBindingHandlerIntentReadIndexedByState map[string]*IntentReadRow

func (rows CreateChromeAttemptBindingHandlerIntentReadSlice) IndexByState() (CreateChromeAttemptBindingHandlerIntentReadIndexedByState, error) {
	result := make(CreateChromeAttemptBindingHandlerIntentReadIndexedByState)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerIntentReadIndexByStateKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index CreateChromeAttemptBindingHandlerIntentReadSlice.IndexByState")
		}
		result[key] = row
	}
	return result, nil
}
func (index CreateChromeAttemptBindingHandlerIntentReadIndexedByState) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type CreateChromeAttemptBindingHandlerIntentReadGroupedByState map[string][]*IntentReadRow

func (rows CreateChromeAttemptBindingHandlerIntentReadSlice) GroupByState() CreateChromeAttemptBindingHandlerIntentReadGroupedByState {
	result := make(CreateChromeAttemptBindingHandlerIntentReadGroupedByState)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerIntentReadIndexByStateKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index CreateChromeAttemptBindingHandlerIntentReadGroupedByState) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func CreateChromeAttemptBindingHandlerIntentReadIndexByRevisionKey(value *IntentReadRow) (int, bool) {
	var zero int
	if value == nil {
		return zero, false
	}
	if value.Revision == nil {
		return zero, false
	}
	return *value.Revision, true
}

type CreateChromeAttemptBindingHandlerIntentReadIndexedByRevision map[int]*IntentReadRow

func (rows CreateChromeAttemptBindingHandlerIntentReadSlice) IndexByRevision() (CreateChromeAttemptBindingHandlerIntentReadIndexedByRevision, error) {
	result := make(CreateChromeAttemptBindingHandlerIntentReadIndexedByRevision)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerIntentReadIndexByRevisionKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index CreateChromeAttemptBindingHandlerIntentReadSlice.IndexByRevision")
		}
		result[key] = row
	}
	return result, nil
}
func (index CreateChromeAttemptBindingHandlerIntentReadIndexedByRevision) Has(key int) bool {
	_, ok := index[key]
	return ok
}

type CreateChromeAttemptBindingHandlerIntentReadGroupedByRevision map[int][]*IntentReadRow

func (rows CreateChromeAttemptBindingHandlerIntentReadSlice) GroupByRevision() CreateChromeAttemptBindingHandlerIntentReadGroupedByRevision {
	result := make(CreateChromeAttemptBindingHandlerIntentReadGroupedByRevision)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerIntentReadIndexByRevisionKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index CreateChromeAttemptBindingHandlerIntentReadGroupedByRevision) Has(key int) bool {
	_, ok := index[key]
	return ok
}
func CreateChromeAttemptBindingHandlerIntentReadIndexByEvidenceJsonKey(value *IntentReadRow) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.EvidenceJson == nil {
		return zero, false
	}
	return *value.EvidenceJson, true
}

type CreateChromeAttemptBindingHandlerIntentReadIndexedByEvidenceJson map[string]*IntentReadRow

func (rows CreateChromeAttemptBindingHandlerIntentReadSlice) IndexByEvidenceJson() (CreateChromeAttemptBindingHandlerIntentReadIndexedByEvidenceJson, error) {
	result := make(CreateChromeAttemptBindingHandlerIntentReadIndexedByEvidenceJson)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerIntentReadIndexByEvidenceJsonKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index CreateChromeAttemptBindingHandlerIntentReadSlice.IndexByEvidenceJson")
		}
		result[key] = row
	}
	return result, nil
}
func (index CreateChromeAttemptBindingHandlerIntentReadIndexedByEvidenceJson) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type CreateChromeAttemptBindingHandlerIntentReadGroupedByEvidenceJson map[string][]*IntentReadRow

func (rows CreateChromeAttemptBindingHandlerIntentReadSlice) GroupByEvidenceJson() CreateChromeAttemptBindingHandlerIntentReadGroupedByEvidenceJson {
	result := make(CreateChromeAttemptBindingHandlerIntentReadGroupedByEvidenceJson)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerIntentReadIndexByEvidenceJsonKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index CreateChromeAttemptBindingHandlerIntentReadGroupedByEvidenceJson) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type CreateChromeAttemptBindingHandlerIntentReadKey struct {
	Namespace string
	Id        string
}

func CreateChromeAttemptBindingHandlerIntentReadIndexByKeyKey(value *IntentReadRow) (CreateChromeAttemptBindingHandlerIntentReadKey, bool) {
	var zero CreateChromeAttemptBindingHandlerIntentReadKey
	if value == nil {
		return zero, false
	}
	if value.Namespace == nil {
		return zero, false
	}
	if value.Id == nil {
		return zero, false
	}
	return CreateChromeAttemptBindingHandlerIntentReadKey{Namespace: *value.Namespace, Id: *value.Id}, true
}

type CreateChromeAttemptBindingHandlerIntentReadIndexedByKey map[CreateChromeAttemptBindingHandlerIntentReadKey]*IntentReadRow

func (rows CreateChromeAttemptBindingHandlerIntentReadSlice) IndexByKey() (CreateChromeAttemptBindingHandlerIntentReadIndexedByKey, error) {
	result := make(CreateChromeAttemptBindingHandlerIntentReadIndexedByKey)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerIntentReadIndexByKeyKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index CreateChromeAttemptBindingHandlerIntentReadSlice.IndexByKey")
		}
		result[key] = row
	}
	return result, nil
}
func (index CreateChromeAttemptBindingHandlerIntentReadIndexedByKey) Has(key CreateChromeAttemptBindingHandlerIntentReadKey) bool {
	_, ok := index[key]
	return ok
}

type CreateChromeAttemptBindingHandlerIntentReadGroupedByKey map[CreateChromeAttemptBindingHandlerIntentReadKey][]*IntentReadRow

func (rows CreateChromeAttemptBindingHandlerIntentReadSlice) GroupByKey() CreateChromeAttemptBindingHandlerIntentReadGroupedByKey {
	result := make(CreateChromeAttemptBindingHandlerIntentReadGroupedByKey)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerIntentReadIndexByKeyKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index CreateChromeAttemptBindingHandlerIntentReadGroupedByKey) Has(key CreateChromeAttemptBindingHandlerIntentReadKey) bool {
	_, ok := index[key]
	return ok
}

type CreateChromeAttemptBindingHandlerAttemptReadSlice []*AttemptReadRow

func CreateChromeAttemptBindingHandlerAttemptReadIndexByNamespaceKey(value *AttemptReadRow) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.Namespace == nil {
		return zero, false
	}
	return *value.Namespace, true
}

type CreateChromeAttemptBindingHandlerAttemptReadIndexedByNamespace map[string]*AttemptReadRow

func (rows CreateChromeAttemptBindingHandlerAttemptReadSlice) IndexByNamespace() (CreateChromeAttemptBindingHandlerAttemptReadIndexedByNamespace, error) {
	result := make(CreateChromeAttemptBindingHandlerAttemptReadIndexedByNamespace)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerAttemptReadIndexByNamespaceKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index CreateChromeAttemptBindingHandlerAttemptReadSlice.IndexByNamespace")
		}
		result[key] = row
	}
	return result, nil
}
func (index CreateChromeAttemptBindingHandlerAttemptReadIndexedByNamespace) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type CreateChromeAttemptBindingHandlerAttemptReadGroupedByNamespace map[string][]*AttemptReadRow

func (rows CreateChromeAttemptBindingHandlerAttemptReadSlice) GroupByNamespace() CreateChromeAttemptBindingHandlerAttemptReadGroupedByNamespace {
	result := make(CreateChromeAttemptBindingHandlerAttemptReadGroupedByNamespace)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerAttemptReadIndexByNamespaceKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index CreateChromeAttemptBindingHandlerAttemptReadGroupedByNamespace) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func CreateChromeAttemptBindingHandlerAttemptReadIndexByIdKey(value *AttemptReadRow) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.Id == nil {
		return zero, false
	}
	return *value.Id, true
}

type CreateChromeAttemptBindingHandlerAttemptReadIndexedById map[string]*AttemptReadRow

func (rows CreateChromeAttemptBindingHandlerAttemptReadSlice) IndexById() (CreateChromeAttemptBindingHandlerAttemptReadIndexedById, error) {
	result := make(CreateChromeAttemptBindingHandlerAttemptReadIndexedById)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerAttemptReadIndexByIdKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index CreateChromeAttemptBindingHandlerAttemptReadSlice.IndexById")
		}
		result[key] = row
	}
	return result, nil
}
func (index CreateChromeAttemptBindingHandlerAttemptReadIndexedById) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type CreateChromeAttemptBindingHandlerAttemptReadGroupedById map[string][]*AttemptReadRow

func (rows CreateChromeAttemptBindingHandlerAttemptReadSlice) GroupById() CreateChromeAttemptBindingHandlerAttemptReadGroupedById {
	result := make(CreateChromeAttemptBindingHandlerAttemptReadGroupedById)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerAttemptReadIndexByIdKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index CreateChromeAttemptBindingHandlerAttemptReadGroupedById) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func CreateChromeAttemptBindingHandlerAttemptReadIndexByRunIdKey(value *AttemptReadRow) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.RunId == nil {
		return zero, false
	}
	return *value.RunId, true
}

type CreateChromeAttemptBindingHandlerAttemptReadIndexedByRunId map[string]*AttemptReadRow

func (rows CreateChromeAttemptBindingHandlerAttemptReadSlice) IndexByRunId() (CreateChromeAttemptBindingHandlerAttemptReadIndexedByRunId, error) {
	result := make(CreateChromeAttemptBindingHandlerAttemptReadIndexedByRunId)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerAttemptReadIndexByRunIdKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index CreateChromeAttemptBindingHandlerAttemptReadSlice.IndexByRunId")
		}
		result[key] = row
	}
	return result, nil
}
func (index CreateChromeAttemptBindingHandlerAttemptReadIndexedByRunId) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type CreateChromeAttemptBindingHandlerAttemptReadGroupedByRunId map[string][]*AttemptReadRow

func (rows CreateChromeAttemptBindingHandlerAttemptReadSlice) GroupByRunId() CreateChromeAttemptBindingHandlerAttemptReadGroupedByRunId {
	result := make(CreateChromeAttemptBindingHandlerAttemptReadGroupedByRunId)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerAttemptReadIndexByRunIdKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index CreateChromeAttemptBindingHandlerAttemptReadGroupedByRunId) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func CreateChromeAttemptBindingHandlerAttemptReadIndexByStepIdKey(value *AttemptReadRow) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.StepId == nil {
		return zero, false
	}
	return *value.StepId, true
}

type CreateChromeAttemptBindingHandlerAttemptReadIndexedByStepId map[string]*AttemptReadRow

func (rows CreateChromeAttemptBindingHandlerAttemptReadSlice) IndexByStepId() (CreateChromeAttemptBindingHandlerAttemptReadIndexedByStepId, error) {
	result := make(CreateChromeAttemptBindingHandlerAttemptReadIndexedByStepId)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerAttemptReadIndexByStepIdKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index CreateChromeAttemptBindingHandlerAttemptReadSlice.IndexByStepId")
		}
		result[key] = row
	}
	return result, nil
}
func (index CreateChromeAttemptBindingHandlerAttemptReadIndexedByStepId) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type CreateChromeAttemptBindingHandlerAttemptReadGroupedByStepId map[string][]*AttemptReadRow

func (rows CreateChromeAttemptBindingHandlerAttemptReadSlice) GroupByStepId() CreateChromeAttemptBindingHandlerAttemptReadGroupedByStepId {
	result := make(CreateChromeAttemptBindingHandlerAttemptReadGroupedByStepId)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerAttemptReadIndexByStepIdKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index CreateChromeAttemptBindingHandlerAttemptReadGroupedByStepId) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func CreateChromeAttemptBindingHandlerAttemptReadIndexByPlanIdKey(value *AttemptReadRow) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.PlanId == nil {
		return zero, false
	}
	return *value.PlanId, true
}

type CreateChromeAttemptBindingHandlerAttemptReadIndexedByPlanId map[string]*AttemptReadRow

func (rows CreateChromeAttemptBindingHandlerAttemptReadSlice) IndexByPlanId() (CreateChromeAttemptBindingHandlerAttemptReadIndexedByPlanId, error) {
	result := make(CreateChromeAttemptBindingHandlerAttemptReadIndexedByPlanId)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerAttemptReadIndexByPlanIdKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index CreateChromeAttemptBindingHandlerAttemptReadSlice.IndexByPlanId")
		}
		result[key] = row
	}
	return result, nil
}
func (index CreateChromeAttemptBindingHandlerAttemptReadIndexedByPlanId) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type CreateChromeAttemptBindingHandlerAttemptReadGroupedByPlanId map[string][]*AttemptReadRow

func (rows CreateChromeAttemptBindingHandlerAttemptReadSlice) GroupByPlanId() CreateChromeAttemptBindingHandlerAttemptReadGroupedByPlanId {
	result := make(CreateChromeAttemptBindingHandlerAttemptReadGroupedByPlanId)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerAttemptReadIndexByPlanIdKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index CreateChromeAttemptBindingHandlerAttemptReadGroupedByPlanId) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func CreateChromeAttemptBindingHandlerAttemptReadIndexByLeaseEpochKey(value *AttemptReadRow) (int, bool) {
	var zero int
	if value == nil {
		return zero, false
	}
	if value.LeaseEpoch == nil {
		return zero, false
	}
	return *value.LeaseEpoch, true
}

type CreateChromeAttemptBindingHandlerAttemptReadIndexedByLeaseEpoch map[int]*AttemptReadRow

func (rows CreateChromeAttemptBindingHandlerAttemptReadSlice) IndexByLeaseEpoch() (CreateChromeAttemptBindingHandlerAttemptReadIndexedByLeaseEpoch, error) {
	result := make(CreateChromeAttemptBindingHandlerAttemptReadIndexedByLeaseEpoch)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerAttemptReadIndexByLeaseEpochKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index CreateChromeAttemptBindingHandlerAttemptReadSlice.IndexByLeaseEpoch")
		}
		result[key] = row
	}
	return result, nil
}
func (index CreateChromeAttemptBindingHandlerAttemptReadIndexedByLeaseEpoch) Has(key int) bool {
	_, ok := index[key]
	return ok
}

type CreateChromeAttemptBindingHandlerAttemptReadGroupedByLeaseEpoch map[int][]*AttemptReadRow

func (rows CreateChromeAttemptBindingHandlerAttemptReadSlice) GroupByLeaseEpoch() CreateChromeAttemptBindingHandlerAttemptReadGroupedByLeaseEpoch {
	result := make(CreateChromeAttemptBindingHandlerAttemptReadGroupedByLeaseEpoch)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerAttemptReadIndexByLeaseEpochKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index CreateChromeAttemptBindingHandlerAttemptReadGroupedByLeaseEpoch) Has(key int) bool {
	_, ok := index[key]
	return ok
}
func CreateChromeAttemptBindingHandlerAttemptReadIndexByStateKey(value *AttemptReadRow) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.State == nil {
		return zero, false
	}
	return *value.State, true
}

type CreateChromeAttemptBindingHandlerAttemptReadIndexedByState map[string]*AttemptReadRow

func (rows CreateChromeAttemptBindingHandlerAttemptReadSlice) IndexByState() (CreateChromeAttemptBindingHandlerAttemptReadIndexedByState, error) {
	result := make(CreateChromeAttemptBindingHandlerAttemptReadIndexedByState)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerAttemptReadIndexByStateKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index CreateChromeAttemptBindingHandlerAttemptReadSlice.IndexByState")
		}
		result[key] = row
	}
	return result, nil
}
func (index CreateChromeAttemptBindingHandlerAttemptReadIndexedByState) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type CreateChromeAttemptBindingHandlerAttemptReadGroupedByState map[string][]*AttemptReadRow

func (rows CreateChromeAttemptBindingHandlerAttemptReadSlice) GroupByState() CreateChromeAttemptBindingHandlerAttemptReadGroupedByState {
	result := make(CreateChromeAttemptBindingHandlerAttemptReadGroupedByState)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerAttemptReadIndexByStateKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index CreateChromeAttemptBindingHandlerAttemptReadGroupedByState) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func CreateChromeAttemptBindingHandlerAttemptReadIndexByCreatedAtKey(value *AttemptReadRow) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.CreatedAt == nil {
		return zero, false
	}
	return *value.CreatedAt, true
}

type CreateChromeAttemptBindingHandlerAttemptReadIndexedByCreatedAt map[string]*AttemptReadRow

func (rows CreateChromeAttemptBindingHandlerAttemptReadSlice) IndexByCreatedAt() (CreateChromeAttemptBindingHandlerAttemptReadIndexedByCreatedAt, error) {
	result := make(CreateChromeAttemptBindingHandlerAttemptReadIndexedByCreatedAt)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerAttemptReadIndexByCreatedAtKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index CreateChromeAttemptBindingHandlerAttemptReadSlice.IndexByCreatedAt")
		}
		result[key] = row
	}
	return result, nil
}
func (index CreateChromeAttemptBindingHandlerAttemptReadIndexedByCreatedAt) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type CreateChromeAttemptBindingHandlerAttemptReadGroupedByCreatedAt map[string][]*AttemptReadRow

func (rows CreateChromeAttemptBindingHandlerAttemptReadSlice) GroupByCreatedAt() CreateChromeAttemptBindingHandlerAttemptReadGroupedByCreatedAt {
	result := make(CreateChromeAttemptBindingHandlerAttemptReadGroupedByCreatedAt)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerAttemptReadIndexByCreatedAtKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index CreateChromeAttemptBindingHandlerAttemptReadGroupedByCreatedAt) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type CreateChromeAttemptBindingHandlerAttemptReadKey struct {
	Namespace string
	Id        string
}

func CreateChromeAttemptBindingHandlerAttemptReadIndexByKeyKey(value *AttemptReadRow) (CreateChromeAttemptBindingHandlerAttemptReadKey, bool) {
	var zero CreateChromeAttemptBindingHandlerAttemptReadKey
	if value == nil {
		return zero, false
	}
	if value.Namespace == nil {
		return zero, false
	}
	if value.Id == nil {
		return zero, false
	}
	return CreateChromeAttemptBindingHandlerAttemptReadKey{Namespace: *value.Namespace, Id: *value.Id}, true
}

type CreateChromeAttemptBindingHandlerAttemptReadIndexedByKey map[CreateChromeAttemptBindingHandlerAttemptReadKey]*AttemptReadRow

func (rows CreateChromeAttemptBindingHandlerAttemptReadSlice) IndexByKey() (CreateChromeAttemptBindingHandlerAttemptReadIndexedByKey, error) {
	result := make(CreateChromeAttemptBindingHandlerAttemptReadIndexedByKey)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerAttemptReadIndexByKeyKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index CreateChromeAttemptBindingHandlerAttemptReadSlice.IndexByKey")
		}
		result[key] = row
	}
	return result, nil
}
func (index CreateChromeAttemptBindingHandlerAttemptReadIndexedByKey) Has(key CreateChromeAttemptBindingHandlerAttemptReadKey) bool {
	_, ok := index[key]
	return ok
}

type CreateChromeAttemptBindingHandlerAttemptReadGroupedByKey map[CreateChromeAttemptBindingHandlerAttemptReadKey][]*AttemptReadRow

func (rows CreateChromeAttemptBindingHandlerAttemptReadSlice) GroupByKey() CreateChromeAttemptBindingHandlerAttemptReadGroupedByKey {
	result := make(CreateChromeAttemptBindingHandlerAttemptReadGroupedByKey)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerAttemptReadIndexByKeyKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index CreateChromeAttemptBindingHandlerAttemptReadGroupedByKey) Has(key CreateChromeAttemptBindingHandlerAttemptReadKey) bool {
	_, ok := index[key]
	return ok
}

type CreateChromeAttemptBindingHandlerRunReadSlice []*RunReadRow

func CreateChromeAttemptBindingHandlerRunReadIndexByNamespaceKey(value *RunReadRow) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.Namespace == nil {
		return zero, false
	}
	return *value.Namespace, true
}

type CreateChromeAttemptBindingHandlerRunReadIndexedByNamespace map[string]*RunReadRow

func (rows CreateChromeAttemptBindingHandlerRunReadSlice) IndexByNamespace() (CreateChromeAttemptBindingHandlerRunReadIndexedByNamespace, error) {
	result := make(CreateChromeAttemptBindingHandlerRunReadIndexedByNamespace)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerRunReadIndexByNamespaceKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index CreateChromeAttemptBindingHandlerRunReadSlice.IndexByNamespace")
		}
		result[key] = row
	}
	return result, nil
}
func (index CreateChromeAttemptBindingHandlerRunReadIndexedByNamespace) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type CreateChromeAttemptBindingHandlerRunReadGroupedByNamespace map[string][]*RunReadRow

func (rows CreateChromeAttemptBindingHandlerRunReadSlice) GroupByNamespace() CreateChromeAttemptBindingHandlerRunReadGroupedByNamespace {
	result := make(CreateChromeAttemptBindingHandlerRunReadGroupedByNamespace)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerRunReadIndexByNamespaceKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index CreateChromeAttemptBindingHandlerRunReadGroupedByNamespace) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func CreateChromeAttemptBindingHandlerRunReadIndexByIdKey(value *RunReadRow) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.Id == nil {
		return zero, false
	}
	return *value.Id, true
}

type CreateChromeAttemptBindingHandlerRunReadIndexedById map[string]*RunReadRow

func (rows CreateChromeAttemptBindingHandlerRunReadSlice) IndexById() (CreateChromeAttemptBindingHandlerRunReadIndexedById, error) {
	result := make(CreateChromeAttemptBindingHandlerRunReadIndexedById)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerRunReadIndexByIdKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index CreateChromeAttemptBindingHandlerRunReadSlice.IndexById")
		}
		result[key] = row
	}
	return result, nil
}
func (index CreateChromeAttemptBindingHandlerRunReadIndexedById) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type CreateChromeAttemptBindingHandlerRunReadGroupedById map[string][]*RunReadRow

func (rows CreateChromeAttemptBindingHandlerRunReadSlice) GroupById() CreateChromeAttemptBindingHandlerRunReadGroupedById {
	result := make(CreateChromeAttemptBindingHandlerRunReadGroupedById)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerRunReadIndexByIdKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index CreateChromeAttemptBindingHandlerRunReadGroupedById) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func CreateChromeAttemptBindingHandlerRunReadIndexByPlanIdKey(value *RunReadRow) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.PlanId == nil {
		return zero, false
	}
	return *value.PlanId, true
}

type CreateChromeAttemptBindingHandlerRunReadIndexedByPlanId map[string]*RunReadRow

func (rows CreateChromeAttemptBindingHandlerRunReadSlice) IndexByPlanId() (CreateChromeAttemptBindingHandlerRunReadIndexedByPlanId, error) {
	result := make(CreateChromeAttemptBindingHandlerRunReadIndexedByPlanId)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerRunReadIndexByPlanIdKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index CreateChromeAttemptBindingHandlerRunReadSlice.IndexByPlanId")
		}
		result[key] = row
	}
	return result, nil
}
func (index CreateChromeAttemptBindingHandlerRunReadIndexedByPlanId) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type CreateChromeAttemptBindingHandlerRunReadGroupedByPlanId map[string][]*RunReadRow

func (rows CreateChromeAttemptBindingHandlerRunReadSlice) GroupByPlanId() CreateChromeAttemptBindingHandlerRunReadGroupedByPlanId {
	result := make(CreateChromeAttemptBindingHandlerRunReadGroupedByPlanId)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerRunReadIndexByPlanIdKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index CreateChromeAttemptBindingHandlerRunReadGroupedByPlanId) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func CreateChromeAttemptBindingHandlerRunReadIndexByStatusKey(value *RunReadRow) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.Status == nil {
		return zero, false
	}
	return *value.Status, true
}

type CreateChromeAttemptBindingHandlerRunReadIndexedByStatus map[string]*RunReadRow

func (rows CreateChromeAttemptBindingHandlerRunReadSlice) IndexByStatus() (CreateChromeAttemptBindingHandlerRunReadIndexedByStatus, error) {
	result := make(CreateChromeAttemptBindingHandlerRunReadIndexedByStatus)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerRunReadIndexByStatusKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index CreateChromeAttemptBindingHandlerRunReadSlice.IndexByStatus")
		}
		result[key] = row
	}
	return result, nil
}
func (index CreateChromeAttemptBindingHandlerRunReadIndexedByStatus) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type CreateChromeAttemptBindingHandlerRunReadGroupedByStatus map[string][]*RunReadRow

func (rows CreateChromeAttemptBindingHandlerRunReadSlice) GroupByStatus() CreateChromeAttemptBindingHandlerRunReadGroupedByStatus {
	result := make(CreateChromeAttemptBindingHandlerRunReadGroupedByStatus)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerRunReadIndexByStatusKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index CreateChromeAttemptBindingHandlerRunReadGroupedByStatus) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func CreateChromeAttemptBindingHandlerRunReadIndexByRevisionKey(value *RunReadRow) (int, bool) {
	var zero int
	if value == nil {
		return zero, false
	}
	if value.Revision == nil {
		return zero, false
	}
	return *value.Revision, true
}

type CreateChromeAttemptBindingHandlerRunReadIndexedByRevision map[int]*RunReadRow

func (rows CreateChromeAttemptBindingHandlerRunReadSlice) IndexByRevision() (CreateChromeAttemptBindingHandlerRunReadIndexedByRevision, error) {
	result := make(CreateChromeAttemptBindingHandlerRunReadIndexedByRevision)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerRunReadIndexByRevisionKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index CreateChromeAttemptBindingHandlerRunReadSlice.IndexByRevision")
		}
		result[key] = row
	}
	return result, nil
}
func (index CreateChromeAttemptBindingHandlerRunReadIndexedByRevision) Has(key int) bool {
	_, ok := index[key]
	return ok
}

type CreateChromeAttemptBindingHandlerRunReadGroupedByRevision map[int][]*RunReadRow

func (rows CreateChromeAttemptBindingHandlerRunReadSlice) GroupByRevision() CreateChromeAttemptBindingHandlerRunReadGroupedByRevision {
	result := make(CreateChromeAttemptBindingHandlerRunReadGroupedByRevision)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerRunReadIndexByRevisionKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index CreateChromeAttemptBindingHandlerRunReadGroupedByRevision) Has(key int) bool {
	_, ok := index[key]
	return ok
}
func CreateChromeAttemptBindingHandlerRunReadIndexByEndlySessionIdKey(value *RunReadRow) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.EndlySessionId == nil {
		return zero, false
	}
	return *value.EndlySessionId, true
}

type CreateChromeAttemptBindingHandlerRunReadIndexedByEndlySessionId map[string]*RunReadRow

func (rows CreateChromeAttemptBindingHandlerRunReadSlice) IndexByEndlySessionId() (CreateChromeAttemptBindingHandlerRunReadIndexedByEndlySessionId, error) {
	result := make(CreateChromeAttemptBindingHandlerRunReadIndexedByEndlySessionId)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerRunReadIndexByEndlySessionIdKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index CreateChromeAttemptBindingHandlerRunReadSlice.IndexByEndlySessionId")
		}
		result[key] = row
	}
	return result, nil
}
func (index CreateChromeAttemptBindingHandlerRunReadIndexedByEndlySessionId) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type CreateChromeAttemptBindingHandlerRunReadGroupedByEndlySessionId map[string][]*RunReadRow

func (rows CreateChromeAttemptBindingHandlerRunReadSlice) GroupByEndlySessionId() CreateChromeAttemptBindingHandlerRunReadGroupedByEndlySessionId {
	result := make(CreateChromeAttemptBindingHandlerRunReadGroupedByEndlySessionId)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerRunReadIndexByEndlySessionIdKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index CreateChromeAttemptBindingHandlerRunReadGroupedByEndlySessionId) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func CreateChromeAttemptBindingHandlerRunReadIndexByEndlyOperationIdKey(value *RunReadRow) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.EndlyOperationId == nil {
		return zero, false
	}
	return *value.EndlyOperationId, true
}

type CreateChromeAttemptBindingHandlerRunReadIndexedByEndlyOperationId map[string]*RunReadRow

func (rows CreateChromeAttemptBindingHandlerRunReadSlice) IndexByEndlyOperationId() (CreateChromeAttemptBindingHandlerRunReadIndexedByEndlyOperationId, error) {
	result := make(CreateChromeAttemptBindingHandlerRunReadIndexedByEndlyOperationId)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerRunReadIndexByEndlyOperationIdKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index CreateChromeAttemptBindingHandlerRunReadSlice.IndexByEndlyOperationId")
		}
		result[key] = row
	}
	return result, nil
}
func (index CreateChromeAttemptBindingHandlerRunReadIndexedByEndlyOperationId) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type CreateChromeAttemptBindingHandlerRunReadGroupedByEndlyOperationId map[string][]*RunReadRow

func (rows CreateChromeAttemptBindingHandlerRunReadSlice) GroupByEndlyOperationId() CreateChromeAttemptBindingHandlerRunReadGroupedByEndlyOperationId {
	result := make(CreateChromeAttemptBindingHandlerRunReadGroupedByEndlyOperationId)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerRunReadIndexByEndlyOperationIdKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index CreateChromeAttemptBindingHandlerRunReadGroupedByEndlyOperationId) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func CreateChromeAttemptBindingHandlerRunReadIndexByCreatedAtKey(value *RunReadRow) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.CreatedAt == nil {
		return zero, false
	}
	return *value.CreatedAt, true
}

type CreateChromeAttemptBindingHandlerRunReadIndexedByCreatedAt map[string]*RunReadRow

func (rows CreateChromeAttemptBindingHandlerRunReadSlice) IndexByCreatedAt() (CreateChromeAttemptBindingHandlerRunReadIndexedByCreatedAt, error) {
	result := make(CreateChromeAttemptBindingHandlerRunReadIndexedByCreatedAt)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerRunReadIndexByCreatedAtKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index CreateChromeAttemptBindingHandlerRunReadSlice.IndexByCreatedAt")
		}
		result[key] = row
	}
	return result, nil
}
func (index CreateChromeAttemptBindingHandlerRunReadIndexedByCreatedAt) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type CreateChromeAttemptBindingHandlerRunReadGroupedByCreatedAt map[string][]*RunReadRow

func (rows CreateChromeAttemptBindingHandlerRunReadSlice) GroupByCreatedAt() CreateChromeAttemptBindingHandlerRunReadGroupedByCreatedAt {
	result := make(CreateChromeAttemptBindingHandlerRunReadGroupedByCreatedAt)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerRunReadIndexByCreatedAtKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index CreateChromeAttemptBindingHandlerRunReadGroupedByCreatedAt) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func CreateChromeAttemptBindingHandlerRunReadIndexByUpdatedAtKey(value *RunReadRow) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.UpdatedAt == nil {
		return zero, false
	}
	return *value.UpdatedAt, true
}

type CreateChromeAttemptBindingHandlerRunReadIndexedByUpdatedAt map[string]*RunReadRow

func (rows CreateChromeAttemptBindingHandlerRunReadSlice) IndexByUpdatedAt() (CreateChromeAttemptBindingHandlerRunReadIndexedByUpdatedAt, error) {
	result := make(CreateChromeAttemptBindingHandlerRunReadIndexedByUpdatedAt)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerRunReadIndexByUpdatedAtKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index CreateChromeAttemptBindingHandlerRunReadSlice.IndexByUpdatedAt")
		}
		result[key] = row
	}
	return result, nil
}
func (index CreateChromeAttemptBindingHandlerRunReadIndexedByUpdatedAt) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type CreateChromeAttemptBindingHandlerRunReadGroupedByUpdatedAt map[string][]*RunReadRow

func (rows CreateChromeAttemptBindingHandlerRunReadSlice) GroupByUpdatedAt() CreateChromeAttemptBindingHandlerRunReadGroupedByUpdatedAt {
	result := make(CreateChromeAttemptBindingHandlerRunReadGroupedByUpdatedAt)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerRunReadIndexByUpdatedAtKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index CreateChromeAttemptBindingHandlerRunReadGroupedByUpdatedAt) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type CreateChromeAttemptBindingHandlerRunReadKey struct {
	Namespace string
	Id        string
}

func CreateChromeAttemptBindingHandlerRunReadIndexByKeyKey(value *RunReadRow) (CreateChromeAttemptBindingHandlerRunReadKey, bool) {
	var zero CreateChromeAttemptBindingHandlerRunReadKey
	if value == nil {
		return zero, false
	}
	if value.Namespace == nil {
		return zero, false
	}
	if value.Id == nil {
		return zero, false
	}
	return CreateChromeAttemptBindingHandlerRunReadKey{Namespace: *value.Namespace, Id: *value.Id}, true
}

type CreateChromeAttemptBindingHandlerRunReadIndexedByKey map[CreateChromeAttemptBindingHandlerRunReadKey]*RunReadRow

func (rows CreateChromeAttemptBindingHandlerRunReadSlice) IndexByKey() (CreateChromeAttemptBindingHandlerRunReadIndexedByKey, error) {
	result := make(CreateChromeAttemptBindingHandlerRunReadIndexedByKey)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerRunReadIndexByKeyKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index CreateChromeAttemptBindingHandlerRunReadSlice.IndexByKey")
		}
		result[key] = row
	}
	return result, nil
}
func (index CreateChromeAttemptBindingHandlerRunReadIndexedByKey) Has(key CreateChromeAttemptBindingHandlerRunReadKey) bool {
	_, ok := index[key]
	return ok
}

type CreateChromeAttemptBindingHandlerRunReadGroupedByKey map[CreateChromeAttemptBindingHandlerRunReadKey][]*RunReadRow

func (rows CreateChromeAttemptBindingHandlerRunReadSlice) GroupByKey() CreateChromeAttemptBindingHandlerRunReadGroupedByKey {
	result := make(CreateChromeAttemptBindingHandlerRunReadGroupedByKey)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerRunReadIndexByKeyKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index CreateChromeAttemptBindingHandlerRunReadGroupedByKey) Has(key CreateChromeAttemptBindingHandlerRunReadKey) bool {
	_, ok := index[key]
	return ok
}

type CreateChromeAttemptBindingHandlerPlanReadSlice []*PlanReadRow

func CreateChromeAttemptBindingHandlerPlanReadIndexByNamespaceKey(value *PlanReadRow) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.Namespace == nil {
		return zero, false
	}
	return *value.Namespace, true
}

type CreateChromeAttemptBindingHandlerPlanReadIndexedByNamespace map[string]*PlanReadRow

func (rows CreateChromeAttemptBindingHandlerPlanReadSlice) IndexByNamespace() (CreateChromeAttemptBindingHandlerPlanReadIndexedByNamespace, error) {
	result := make(CreateChromeAttemptBindingHandlerPlanReadIndexedByNamespace)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerPlanReadIndexByNamespaceKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index CreateChromeAttemptBindingHandlerPlanReadSlice.IndexByNamespace")
		}
		result[key] = row
	}
	return result, nil
}
func (index CreateChromeAttemptBindingHandlerPlanReadIndexedByNamespace) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type CreateChromeAttemptBindingHandlerPlanReadGroupedByNamespace map[string][]*PlanReadRow

func (rows CreateChromeAttemptBindingHandlerPlanReadSlice) GroupByNamespace() CreateChromeAttemptBindingHandlerPlanReadGroupedByNamespace {
	result := make(CreateChromeAttemptBindingHandlerPlanReadGroupedByNamespace)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerPlanReadIndexByNamespaceKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index CreateChromeAttemptBindingHandlerPlanReadGroupedByNamespace) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func CreateChromeAttemptBindingHandlerPlanReadIndexByIdKey(value *PlanReadRow) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.Id == nil {
		return zero, false
	}
	return *value.Id, true
}

type CreateChromeAttemptBindingHandlerPlanReadIndexedById map[string]*PlanReadRow

func (rows CreateChromeAttemptBindingHandlerPlanReadSlice) IndexById() (CreateChromeAttemptBindingHandlerPlanReadIndexedById, error) {
	result := make(CreateChromeAttemptBindingHandlerPlanReadIndexedById)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerPlanReadIndexByIdKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index CreateChromeAttemptBindingHandlerPlanReadSlice.IndexById")
		}
		result[key] = row
	}
	return result, nil
}
func (index CreateChromeAttemptBindingHandlerPlanReadIndexedById) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type CreateChromeAttemptBindingHandlerPlanReadGroupedById map[string][]*PlanReadRow

func (rows CreateChromeAttemptBindingHandlerPlanReadSlice) GroupById() CreateChromeAttemptBindingHandlerPlanReadGroupedById {
	result := make(CreateChromeAttemptBindingHandlerPlanReadGroupedById)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerPlanReadIndexByIdKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index CreateChromeAttemptBindingHandlerPlanReadGroupedById) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func CreateChromeAttemptBindingHandlerPlanReadIndexByParentIdKey(value *PlanReadRow) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.ParentId == nil {
		return zero, false
	}
	return *value.ParentId, true
}

type CreateChromeAttemptBindingHandlerPlanReadIndexedByParentId map[string]*PlanReadRow

func (rows CreateChromeAttemptBindingHandlerPlanReadSlice) IndexByParentId() (CreateChromeAttemptBindingHandlerPlanReadIndexedByParentId, error) {
	result := make(CreateChromeAttemptBindingHandlerPlanReadIndexedByParentId)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerPlanReadIndexByParentIdKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index CreateChromeAttemptBindingHandlerPlanReadSlice.IndexByParentId")
		}
		result[key] = row
	}
	return result, nil
}
func (index CreateChromeAttemptBindingHandlerPlanReadIndexedByParentId) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type CreateChromeAttemptBindingHandlerPlanReadGroupedByParentId map[string][]*PlanReadRow

func (rows CreateChromeAttemptBindingHandlerPlanReadSlice) GroupByParentId() CreateChromeAttemptBindingHandlerPlanReadGroupedByParentId {
	result := make(CreateChromeAttemptBindingHandlerPlanReadGroupedByParentId)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerPlanReadIndexByParentIdKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index CreateChromeAttemptBindingHandlerPlanReadGroupedByParentId) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func CreateChromeAttemptBindingHandlerPlanReadIndexByObjectiveIdKey(value *PlanReadRow) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.ObjectiveId == nil {
		return zero, false
	}
	return *value.ObjectiveId, true
}

type CreateChromeAttemptBindingHandlerPlanReadIndexedByObjectiveId map[string]*PlanReadRow

func (rows CreateChromeAttemptBindingHandlerPlanReadSlice) IndexByObjectiveId() (CreateChromeAttemptBindingHandlerPlanReadIndexedByObjectiveId, error) {
	result := make(CreateChromeAttemptBindingHandlerPlanReadIndexedByObjectiveId)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerPlanReadIndexByObjectiveIdKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index CreateChromeAttemptBindingHandlerPlanReadSlice.IndexByObjectiveId")
		}
		result[key] = row
	}
	return result, nil
}
func (index CreateChromeAttemptBindingHandlerPlanReadIndexedByObjectiveId) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type CreateChromeAttemptBindingHandlerPlanReadGroupedByObjectiveId map[string][]*PlanReadRow

func (rows CreateChromeAttemptBindingHandlerPlanReadSlice) GroupByObjectiveId() CreateChromeAttemptBindingHandlerPlanReadGroupedByObjectiveId {
	result := make(CreateChromeAttemptBindingHandlerPlanReadGroupedByObjectiveId)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerPlanReadIndexByObjectiveIdKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index CreateChromeAttemptBindingHandlerPlanReadGroupedByObjectiveId) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func CreateChromeAttemptBindingHandlerPlanReadIndexByContentHashKey(value *PlanReadRow) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.ContentHash == nil {
		return zero, false
	}
	return *value.ContentHash, true
}

type CreateChromeAttemptBindingHandlerPlanReadIndexedByContentHash map[string]*PlanReadRow

func (rows CreateChromeAttemptBindingHandlerPlanReadSlice) IndexByContentHash() (CreateChromeAttemptBindingHandlerPlanReadIndexedByContentHash, error) {
	result := make(CreateChromeAttemptBindingHandlerPlanReadIndexedByContentHash)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerPlanReadIndexByContentHashKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index CreateChromeAttemptBindingHandlerPlanReadSlice.IndexByContentHash")
		}
		result[key] = row
	}
	return result, nil
}
func (index CreateChromeAttemptBindingHandlerPlanReadIndexedByContentHash) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type CreateChromeAttemptBindingHandlerPlanReadGroupedByContentHash map[string][]*PlanReadRow

func (rows CreateChromeAttemptBindingHandlerPlanReadSlice) GroupByContentHash() CreateChromeAttemptBindingHandlerPlanReadGroupedByContentHash {
	result := make(CreateChromeAttemptBindingHandlerPlanReadGroupedByContentHash)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerPlanReadIndexByContentHashKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index CreateChromeAttemptBindingHandlerPlanReadGroupedByContentHash) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func CreateChromeAttemptBindingHandlerPlanReadIndexByContentJsonKey(value *PlanReadRow) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.ContentJson == nil {
		return zero, false
	}
	return *value.ContentJson, true
}

type CreateChromeAttemptBindingHandlerPlanReadIndexedByContentJson map[string]*PlanReadRow

func (rows CreateChromeAttemptBindingHandlerPlanReadSlice) IndexByContentJson() (CreateChromeAttemptBindingHandlerPlanReadIndexedByContentJson, error) {
	result := make(CreateChromeAttemptBindingHandlerPlanReadIndexedByContentJson)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerPlanReadIndexByContentJsonKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index CreateChromeAttemptBindingHandlerPlanReadSlice.IndexByContentJson")
		}
		result[key] = row
	}
	return result, nil
}
func (index CreateChromeAttemptBindingHandlerPlanReadIndexedByContentJson) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type CreateChromeAttemptBindingHandlerPlanReadGroupedByContentJson map[string][]*PlanReadRow

func (rows CreateChromeAttemptBindingHandlerPlanReadSlice) GroupByContentJson() CreateChromeAttemptBindingHandlerPlanReadGroupedByContentJson {
	result := make(CreateChromeAttemptBindingHandlerPlanReadGroupedByContentJson)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerPlanReadIndexByContentJsonKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index CreateChromeAttemptBindingHandlerPlanReadGroupedByContentJson) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func CreateChromeAttemptBindingHandlerPlanReadIndexByCreatedAtKey(value *PlanReadRow) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.CreatedAt == nil {
		return zero, false
	}
	return *value.CreatedAt, true
}

type CreateChromeAttemptBindingHandlerPlanReadIndexedByCreatedAt map[string]*PlanReadRow

func (rows CreateChromeAttemptBindingHandlerPlanReadSlice) IndexByCreatedAt() (CreateChromeAttemptBindingHandlerPlanReadIndexedByCreatedAt, error) {
	result := make(CreateChromeAttemptBindingHandlerPlanReadIndexedByCreatedAt)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerPlanReadIndexByCreatedAtKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index CreateChromeAttemptBindingHandlerPlanReadSlice.IndexByCreatedAt")
		}
		result[key] = row
	}
	return result, nil
}
func (index CreateChromeAttemptBindingHandlerPlanReadIndexedByCreatedAt) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type CreateChromeAttemptBindingHandlerPlanReadGroupedByCreatedAt map[string][]*PlanReadRow

func (rows CreateChromeAttemptBindingHandlerPlanReadSlice) GroupByCreatedAt() CreateChromeAttemptBindingHandlerPlanReadGroupedByCreatedAt {
	result := make(CreateChromeAttemptBindingHandlerPlanReadGroupedByCreatedAt)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerPlanReadIndexByCreatedAtKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index CreateChromeAttemptBindingHandlerPlanReadGroupedByCreatedAt) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type CreateChromeAttemptBindingHandlerPlanReadKey struct {
	Namespace string
	Id        string
}

func CreateChromeAttemptBindingHandlerPlanReadIndexByKeyKey(value *PlanReadRow) (CreateChromeAttemptBindingHandlerPlanReadKey, bool) {
	var zero CreateChromeAttemptBindingHandlerPlanReadKey
	if value == nil {
		return zero, false
	}
	if value.Namespace == nil {
		return zero, false
	}
	if value.Id == nil {
		return zero, false
	}
	return CreateChromeAttemptBindingHandlerPlanReadKey{Namespace: *value.Namespace, Id: *value.Id}, true
}

type CreateChromeAttemptBindingHandlerPlanReadIndexedByKey map[CreateChromeAttemptBindingHandlerPlanReadKey]*PlanReadRow

func (rows CreateChromeAttemptBindingHandlerPlanReadSlice) IndexByKey() (CreateChromeAttemptBindingHandlerPlanReadIndexedByKey, error) {
	result := make(CreateChromeAttemptBindingHandlerPlanReadIndexedByKey)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerPlanReadIndexByKeyKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index CreateChromeAttemptBindingHandlerPlanReadSlice.IndexByKey")
		}
		result[key] = row
	}
	return result, nil
}
func (index CreateChromeAttemptBindingHandlerPlanReadIndexedByKey) Has(key CreateChromeAttemptBindingHandlerPlanReadKey) bool {
	_, ok := index[key]
	return ok
}

type CreateChromeAttemptBindingHandlerPlanReadGroupedByKey map[CreateChromeAttemptBindingHandlerPlanReadKey][]*PlanReadRow

func (rows CreateChromeAttemptBindingHandlerPlanReadSlice) GroupByKey() CreateChromeAttemptBindingHandlerPlanReadGroupedByKey {
	result := make(CreateChromeAttemptBindingHandlerPlanReadGroupedByKey)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerPlanReadIndexByKeyKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index CreateChromeAttemptBindingHandlerPlanReadGroupedByKey) Has(key CreateChromeAttemptBindingHandlerPlanReadKey) bool {
	_, ok := index[key]
	return ok
}

type CreateChromeAttemptBindingHandlerIntentEventReadSlice []*IntentEventRead

func CreateChromeAttemptBindingHandlerIntentEventReadIndexByNamespaceKey(value *IntentEventRead) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.Namespace == nil {
		return zero, false
	}
	return *value.Namespace, true
}

type CreateChromeAttemptBindingHandlerIntentEventReadIndexedByNamespace map[string]*IntentEventRead

func (rows CreateChromeAttemptBindingHandlerIntentEventReadSlice) IndexByNamespace() (CreateChromeAttemptBindingHandlerIntentEventReadIndexedByNamespace, error) {
	result := make(CreateChromeAttemptBindingHandlerIntentEventReadIndexedByNamespace)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerIntentEventReadIndexByNamespaceKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index CreateChromeAttemptBindingHandlerIntentEventReadSlice.IndexByNamespace")
		}
		result[key] = row
	}
	return result, nil
}
func (index CreateChromeAttemptBindingHandlerIntentEventReadIndexedByNamespace) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type CreateChromeAttemptBindingHandlerIntentEventReadGroupedByNamespace map[string][]*IntentEventRead

func (rows CreateChromeAttemptBindingHandlerIntentEventReadSlice) GroupByNamespace() CreateChromeAttemptBindingHandlerIntentEventReadGroupedByNamespace {
	result := make(CreateChromeAttemptBindingHandlerIntentEventReadGroupedByNamespace)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerIntentEventReadIndexByNamespaceKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index CreateChromeAttemptBindingHandlerIntentEventReadGroupedByNamespace) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func CreateChromeAttemptBindingHandlerIntentEventReadIndexByIdKey(value *IntentEventRead) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.Id == nil {
		return zero, false
	}
	return *value.Id, true
}

type CreateChromeAttemptBindingHandlerIntentEventReadIndexedById map[string]*IntentEventRead

func (rows CreateChromeAttemptBindingHandlerIntentEventReadSlice) IndexById() (CreateChromeAttemptBindingHandlerIntentEventReadIndexedById, error) {
	result := make(CreateChromeAttemptBindingHandlerIntentEventReadIndexedById)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerIntentEventReadIndexByIdKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index CreateChromeAttemptBindingHandlerIntentEventReadSlice.IndexById")
		}
		result[key] = row
	}
	return result, nil
}
func (index CreateChromeAttemptBindingHandlerIntentEventReadIndexedById) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type CreateChromeAttemptBindingHandlerIntentEventReadGroupedById map[string][]*IntentEventRead

func (rows CreateChromeAttemptBindingHandlerIntentEventReadSlice) GroupById() CreateChromeAttemptBindingHandlerIntentEventReadGroupedById {
	result := make(CreateChromeAttemptBindingHandlerIntentEventReadGroupedById)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerIntentEventReadIndexByIdKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index CreateChromeAttemptBindingHandlerIntentEventReadGroupedById) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func CreateChromeAttemptBindingHandlerIntentEventReadIndexByRunIdKey(value *IntentEventRead) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.RunId == nil {
		return zero, false
	}
	return *value.RunId, true
}

type CreateChromeAttemptBindingHandlerIntentEventReadIndexedByRunId map[string]*IntentEventRead

func (rows CreateChromeAttemptBindingHandlerIntentEventReadSlice) IndexByRunId() (CreateChromeAttemptBindingHandlerIntentEventReadIndexedByRunId, error) {
	result := make(CreateChromeAttemptBindingHandlerIntentEventReadIndexedByRunId)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerIntentEventReadIndexByRunIdKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index CreateChromeAttemptBindingHandlerIntentEventReadSlice.IndexByRunId")
		}
		result[key] = row
	}
	return result, nil
}
func (index CreateChromeAttemptBindingHandlerIntentEventReadIndexedByRunId) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type CreateChromeAttemptBindingHandlerIntentEventReadGroupedByRunId map[string][]*IntentEventRead

func (rows CreateChromeAttemptBindingHandlerIntentEventReadSlice) GroupByRunId() CreateChromeAttemptBindingHandlerIntentEventReadGroupedByRunId {
	result := make(CreateChromeAttemptBindingHandlerIntentEventReadGroupedByRunId)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerIntentEventReadIndexByRunIdKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index CreateChromeAttemptBindingHandlerIntentEventReadGroupedByRunId) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func CreateChromeAttemptBindingHandlerIntentEventReadIndexByAttemptIdKey(value *IntentEventRead) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.AttemptId == nil {
		return zero, false
	}
	return *value.AttemptId, true
}

type CreateChromeAttemptBindingHandlerIntentEventReadIndexedByAttemptId map[string]*IntentEventRead

func (rows CreateChromeAttemptBindingHandlerIntentEventReadSlice) IndexByAttemptId() (CreateChromeAttemptBindingHandlerIntentEventReadIndexedByAttemptId, error) {
	result := make(CreateChromeAttemptBindingHandlerIntentEventReadIndexedByAttemptId)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerIntentEventReadIndexByAttemptIdKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index CreateChromeAttemptBindingHandlerIntentEventReadSlice.IndexByAttemptId")
		}
		result[key] = row
	}
	return result, nil
}
func (index CreateChromeAttemptBindingHandlerIntentEventReadIndexedByAttemptId) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type CreateChromeAttemptBindingHandlerIntentEventReadGroupedByAttemptId map[string][]*IntentEventRead

func (rows CreateChromeAttemptBindingHandlerIntentEventReadSlice) GroupByAttemptId() CreateChromeAttemptBindingHandlerIntentEventReadGroupedByAttemptId {
	result := make(CreateChromeAttemptBindingHandlerIntentEventReadGroupedByAttemptId)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerIntentEventReadIndexByAttemptIdKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index CreateChromeAttemptBindingHandlerIntentEventReadGroupedByAttemptId) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func CreateChromeAttemptBindingHandlerIntentEventReadIndexBySequenceKey(value *IntentEventRead) (int, bool) {
	var zero int
	if value == nil {
		return zero, false
	}
	if value.Sequence == nil {
		return zero, false
	}
	return *value.Sequence, true
}

type CreateChromeAttemptBindingHandlerIntentEventReadIndexedBySequence map[int]*IntentEventRead

func (rows CreateChromeAttemptBindingHandlerIntentEventReadSlice) IndexBySequence() (CreateChromeAttemptBindingHandlerIntentEventReadIndexedBySequence, error) {
	result := make(CreateChromeAttemptBindingHandlerIntentEventReadIndexedBySequence)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerIntentEventReadIndexBySequenceKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index CreateChromeAttemptBindingHandlerIntentEventReadSlice.IndexBySequence")
		}
		result[key] = row
	}
	return result, nil
}
func (index CreateChromeAttemptBindingHandlerIntentEventReadIndexedBySequence) Has(key int) bool {
	_, ok := index[key]
	return ok
}

type CreateChromeAttemptBindingHandlerIntentEventReadGroupedBySequence map[int][]*IntentEventRead

func (rows CreateChromeAttemptBindingHandlerIntentEventReadSlice) GroupBySequence() CreateChromeAttemptBindingHandlerIntentEventReadGroupedBySequence {
	result := make(CreateChromeAttemptBindingHandlerIntentEventReadGroupedBySequence)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerIntentEventReadIndexBySequenceKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index CreateChromeAttemptBindingHandlerIntentEventReadGroupedBySequence) Has(key int) bool {
	_, ok := index[key]
	return ok
}
func CreateChromeAttemptBindingHandlerIntentEventReadIndexByKindKey(value *IntentEventRead) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.Kind == nil {
		return zero, false
	}
	return *value.Kind, true
}

type CreateChromeAttemptBindingHandlerIntentEventReadIndexedByKind map[string]*IntentEventRead

func (rows CreateChromeAttemptBindingHandlerIntentEventReadSlice) IndexByKind() (CreateChromeAttemptBindingHandlerIntentEventReadIndexedByKind, error) {
	result := make(CreateChromeAttemptBindingHandlerIntentEventReadIndexedByKind)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerIntentEventReadIndexByKindKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index CreateChromeAttemptBindingHandlerIntentEventReadSlice.IndexByKind")
		}
		result[key] = row
	}
	return result, nil
}
func (index CreateChromeAttemptBindingHandlerIntentEventReadIndexedByKind) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type CreateChromeAttemptBindingHandlerIntentEventReadGroupedByKind map[string][]*IntentEventRead

func (rows CreateChromeAttemptBindingHandlerIntentEventReadSlice) GroupByKind() CreateChromeAttemptBindingHandlerIntentEventReadGroupedByKind {
	result := make(CreateChromeAttemptBindingHandlerIntentEventReadGroupedByKind)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerIntentEventReadIndexByKindKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index CreateChromeAttemptBindingHandlerIntentEventReadGroupedByKind) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func CreateChromeAttemptBindingHandlerIntentEventReadIndexByPayloadJsonKey(value *IntentEventRead) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.PayloadJson == nil {
		return zero, false
	}
	return *value.PayloadJson, true
}

type CreateChromeAttemptBindingHandlerIntentEventReadIndexedByPayloadJson map[string]*IntentEventRead

func (rows CreateChromeAttemptBindingHandlerIntentEventReadSlice) IndexByPayloadJson() (CreateChromeAttemptBindingHandlerIntentEventReadIndexedByPayloadJson, error) {
	result := make(CreateChromeAttemptBindingHandlerIntentEventReadIndexedByPayloadJson)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerIntentEventReadIndexByPayloadJsonKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index CreateChromeAttemptBindingHandlerIntentEventReadSlice.IndexByPayloadJson")
		}
		result[key] = row
	}
	return result, nil
}
func (index CreateChromeAttemptBindingHandlerIntentEventReadIndexedByPayloadJson) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type CreateChromeAttemptBindingHandlerIntentEventReadGroupedByPayloadJson map[string][]*IntentEventRead

func (rows CreateChromeAttemptBindingHandlerIntentEventReadSlice) GroupByPayloadJson() CreateChromeAttemptBindingHandlerIntentEventReadGroupedByPayloadJson {
	result := make(CreateChromeAttemptBindingHandlerIntentEventReadGroupedByPayloadJson)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerIntentEventReadIndexByPayloadJsonKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index CreateChromeAttemptBindingHandlerIntentEventReadGroupedByPayloadJson) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func CreateChromeAttemptBindingHandlerIntentEventReadIndexByCreatedAtKey(value *IntentEventRead) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.CreatedAt == nil {
		return zero, false
	}
	return *value.CreatedAt, true
}

type CreateChromeAttemptBindingHandlerIntentEventReadIndexedByCreatedAt map[string]*IntentEventRead

func (rows CreateChromeAttemptBindingHandlerIntentEventReadSlice) IndexByCreatedAt() (CreateChromeAttemptBindingHandlerIntentEventReadIndexedByCreatedAt, error) {
	result := make(CreateChromeAttemptBindingHandlerIntentEventReadIndexedByCreatedAt)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerIntentEventReadIndexByCreatedAtKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index CreateChromeAttemptBindingHandlerIntentEventReadSlice.IndexByCreatedAt")
		}
		result[key] = row
	}
	return result, nil
}
func (index CreateChromeAttemptBindingHandlerIntentEventReadIndexedByCreatedAt) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type CreateChromeAttemptBindingHandlerIntentEventReadGroupedByCreatedAt map[string][]*IntentEventRead

func (rows CreateChromeAttemptBindingHandlerIntentEventReadSlice) GroupByCreatedAt() CreateChromeAttemptBindingHandlerIntentEventReadGroupedByCreatedAt {
	result := make(CreateChromeAttemptBindingHandlerIntentEventReadGroupedByCreatedAt)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerIntentEventReadIndexByCreatedAtKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index CreateChromeAttemptBindingHandlerIntentEventReadGroupedByCreatedAt) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type CreateChromeAttemptBindingHandlerIntentEventReadKey struct {
	Namespace string
	Id        string
}

func CreateChromeAttemptBindingHandlerIntentEventReadIndexByKeyKey(value *IntentEventRead) (CreateChromeAttemptBindingHandlerIntentEventReadKey, bool) {
	var zero CreateChromeAttemptBindingHandlerIntentEventReadKey
	if value == nil {
		return zero, false
	}
	if value.Namespace == nil {
		return zero, false
	}
	if value.Id == nil {
		return zero, false
	}
	return CreateChromeAttemptBindingHandlerIntentEventReadKey{Namespace: *value.Namespace, Id: *value.Id}, true
}

type CreateChromeAttemptBindingHandlerIntentEventReadIndexedByKey map[CreateChromeAttemptBindingHandlerIntentEventReadKey]*IntentEventRead

func (rows CreateChromeAttemptBindingHandlerIntentEventReadSlice) IndexByKey() (CreateChromeAttemptBindingHandlerIntentEventReadIndexedByKey, error) {
	result := make(CreateChromeAttemptBindingHandlerIntentEventReadIndexedByKey)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerIntentEventReadIndexByKeyKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index CreateChromeAttemptBindingHandlerIntentEventReadSlice.IndexByKey")
		}
		result[key] = row
	}
	return result, nil
}
func (index CreateChromeAttemptBindingHandlerIntentEventReadIndexedByKey) Has(key CreateChromeAttemptBindingHandlerIntentEventReadKey) bool {
	_, ok := index[key]
	return ok
}

type CreateChromeAttemptBindingHandlerIntentEventReadGroupedByKey map[CreateChromeAttemptBindingHandlerIntentEventReadKey][]*IntentEventRead

func (rows CreateChromeAttemptBindingHandlerIntentEventReadSlice) GroupByKey() CreateChromeAttemptBindingHandlerIntentEventReadGroupedByKey {
	result := make(CreateChromeAttemptBindingHandlerIntentEventReadGroupedByKey)
	for _, row := range rows {
		key, ok := CreateChromeAttemptBindingHandlerIntentEventReadIndexByKeyKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index CreateChromeAttemptBindingHandlerIntentEventReadGroupedByKey) Has(key CreateChromeAttemptBindingHandlerIntentEventReadKey) bool {
	_, ok := index[key]
	return ok
}

type CreateChromeAttemptBindingHandlerReadIndexes struct {
	IntentRead           CreateChromeAttemptBindingHandlerIntentReadSlice
	IntentReadByKey      CreateChromeAttemptBindingHandlerIntentReadIndexedByKey
	AttemptRead          CreateChromeAttemptBindingHandlerAttemptReadSlice
	AttemptReadByKey     CreateChromeAttemptBindingHandlerAttemptReadIndexedByKey
	RunRead              CreateChromeAttemptBindingHandlerRunReadSlice
	RunReadByKey         CreateChromeAttemptBindingHandlerRunReadIndexedByKey
	PlanRead             CreateChromeAttemptBindingHandlerPlanReadSlice
	PlanReadByKey        CreateChromeAttemptBindingHandlerPlanReadIndexedByKey
	IntentEventRead      CreateChromeAttemptBindingHandlerIntentEventReadSlice
	IntentEventReadByKey CreateChromeAttemptBindingHandlerIntentEventReadIndexedByKey
}

func BuildCreateChromeAttemptBindingHandlerReadIndexes(ctx context.Context, input *CreateChromeAttemptBindingInput) (*CreateChromeAttemptBindingHandlerReadIndexes, error) {
	if input == nil {
		return nil, fmt.Errorf("read indexes require input")
	}
	metadata, ok := xhandler.ReadMetadataFromContext(ctx)
	if !ok || (xshape.Runtime{}).IsNil(metadata) {
		return nil, fmt.Errorf("read indexes require bound read metadata")
	}
	result := &CreateChromeAttemptBindingHandlerReadIndexes{}
	{
		projection, err := metadata.Projection("IntentRead")
		if err != nil {
			return nil, err
		}
		if (xshape.Runtime{}).IsNil(projection) {
			return nil, fmt.Errorf("application read projection is unavailable: IntentRead")
		}
		inputAccess, err := xshape.Linked(reflect.TypeOf((*CreateChromeAttemptBindingInput)(nil)).Elem()).Accessor("IntentRead")
		if err != nil {
			return nil, err
		}
		carrier, err := inputAccess.Get(input)
		if err != nil {
			return nil, err
		}
		value := carrier.Interface()
		if projection.DirectOutput() && projection.RootHolder() != "" {
			return nil, fmt.Errorf("direct application read cannot declare a root holder")
		}
		if !projection.DirectOutput() {
			holder := projection.RootHolder()
			if holder == "" {
				return nil, fmt.Errorf("wrapped read projection requires a canonical root holder")
			}
			accessor, err := xshape.Linked(carrier.Type()).Accessor(holder)
			if err != nil {
				return nil, err
			}
			if _, err := (xshape.Collection[IntentReadRow]{}).Pointers(reflect.Zero(accessor.Type()).Interface()); err != nil {
				return nil, err
			}
			root, present, err := accessor.GetOptional(value)
			if err != nil {
				return nil, err
			}
			if present {
				value = root.Interface()
			} else {
				value = []*IntentReadRow(nil)
			}
		}
		rows, err := (xshape.Collection[IntentReadRow]{}).Pointers(value)
		if err != nil {
			return nil, err
		}
		for ordinal, row := range rows {
			if row == nil {
				continue
			}
			loaded, err := projection.Fields(ordinal)
			if err != nil {
				return nil, err
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("Namespace") {
				return nil, fmt.Errorf("application index field was not loaded: IntentRead.Namespace")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("Id") {
				return nil, fmt.Errorf("application index field was not loaded: IntentRead.Id")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("AttemptId") {
				return nil, fmt.Errorf("application index field was not loaded: IntentRead.AttemptId")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("RunId") {
				return nil, fmt.Errorf("application index field was not loaded: IntentRead.RunId")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("BusinessKey") {
				return nil, fmt.Errorf("application index field was not loaded: IntentRead.BusinessKey")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("State") {
				return nil, fmt.Errorf("application index field was not loaded: IntentRead.State")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("Revision") {
				return nil, fmt.Errorf("application index field was not loaded: IntentRead.Revision")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("EvidenceJson") {
				return nil, fmt.Errorf("application index field was not loaded: IntentRead.EvidenceJson")
			}
		}
		cloned, err := (xshape.Runtime{}).CloneValue(rows, xshape.CloneOptions{})
		if err != nil {
			return nil, err
		}
		result.IntentRead = CreateChromeAttemptBindingHandlerIntentReadSlice(cloned.([]*IntentReadRow))
		result.IntentReadByKey, err = result.IntentRead.IndexByKey()
		if err != nil {
			return nil, err
		}
	}
	{
		projection, err := metadata.Projection("AttemptRead")
		if err != nil {
			return nil, err
		}
		if (xshape.Runtime{}).IsNil(projection) {
			return nil, fmt.Errorf("application read projection is unavailable: AttemptRead")
		}
		inputAccess, err := xshape.Linked(reflect.TypeOf((*CreateChromeAttemptBindingInput)(nil)).Elem()).Accessor("AttemptRead")
		if err != nil {
			return nil, err
		}
		carrier, err := inputAccess.Get(input)
		if err != nil {
			return nil, err
		}
		value := carrier.Interface()
		if projection.DirectOutput() && projection.RootHolder() != "" {
			return nil, fmt.Errorf("direct application read cannot declare a root holder")
		}
		if !projection.DirectOutput() {
			holder := projection.RootHolder()
			if holder == "" {
				return nil, fmt.Errorf("wrapped read projection requires a canonical root holder")
			}
			accessor, err := xshape.Linked(carrier.Type()).Accessor(holder)
			if err != nil {
				return nil, err
			}
			if _, err := (xshape.Collection[AttemptReadRow]{}).Pointers(reflect.Zero(accessor.Type()).Interface()); err != nil {
				return nil, err
			}
			root, present, err := accessor.GetOptional(value)
			if err != nil {
				return nil, err
			}
			if present {
				value = root.Interface()
			} else {
				value = []*AttemptReadRow(nil)
			}
		}
		rows, err := (xshape.Collection[AttemptReadRow]{}).Pointers(value)
		if err != nil {
			return nil, err
		}
		for ordinal, row := range rows {
			if row == nil {
				continue
			}
			loaded, err := projection.Fields(ordinal)
			if err != nil {
				return nil, err
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("Namespace") {
				return nil, fmt.Errorf("application index field was not loaded: AttemptRead.Namespace")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("Id") {
				return nil, fmt.Errorf("application index field was not loaded: AttemptRead.Id")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("RunId") {
				return nil, fmt.Errorf("application index field was not loaded: AttemptRead.RunId")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("StepId") {
				return nil, fmt.Errorf("application index field was not loaded: AttemptRead.StepId")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("PlanId") {
				return nil, fmt.Errorf("application index field was not loaded: AttemptRead.PlanId")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("LeaseEpoch") {
				return nil, fmt.Errorf("application index field was not loaded: AttemptRead.LeaseEpoch")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("State") {
				return nil, fmt.Errorf("application index field was not loaded: AttemptRead.State")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("CreatedAt") {
				return nil, fmt.Errorf("application index field was not loaded: AttemptRead.CreatedAt")
			}
		}
		cloned, err := (xshape.Runtime{}).CloneValue(rows, xshape.CloneOptions{})
		if err != nil {
			return nil, err
		}
		result.AttemptRead = CreateChromeAttemptBindingHandlerAttemptReadSlice(cloned.([]*AttemptReadRow))
		result.AttemptReadByKey, err = result.AttemptRead.IndexByKey()
		if err != nil {
			return nil, err
		}
	}
	{
		projection, err := metadata.Projection("RunRead")
		if err != nil {
			return nil, err
		}
		if (xshape.Runtime{}).IsNil(projection) {
			return nil, fmt.Errorf("application read projection is unavailable: RunRead")
		}
		inputAccess, err := xshape.Linked(reflect.TypeOf((*CreateChromeAttemptBindingInput)(nil)).Elem()).Accessor("RunRead")
		if err != nil {
			return nil, err
		}
		carrier, err := inputAccess.Get(input)
		if err != nil {
			return nil, err
		}
		value := carrier.Interface()
		if projection.DirectOutput() && projection.RootHolder() != "" {
			return nil, fmt.Errorf("direct application read cannot declare a root holder")
		}
		if !projection.DirectOutput() {
			holder := projection.RootHolder()
			if holder == "" {
				return nil, fmt.Errorf("wrapped read projection requires a canonical root holder")
			}
			accessor, err := xshape.Linked(carrier.Type()).Accessor(holder)
			if err != nil {
				return nil, err
			}
			if _, err := (xshape.Collection[RunReadRow]{}).Pointers(reflect.Zero(accessor.Type()).Interface()); err != nil {
				return nil, err
			}
			root, present, err := accessor.GetOptional(value)
			if err != nil {
				return nil, err
			}
			if present {
				value = root.Interface()
			} else {
				value = []*RunReadRow(nil)
			}
		}
		rows, err := (xshape.Collection[RunReadRow]{}).Pointers(value)
		if err != nil {
			return nil, err
		}
		for ordinal, row := range rows {
			if row == nil {
				continue
			}
			loaded, err := projection.Fields(ordinal)
			if err != nil {
				return nil, err
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("Namespace") {
				return nil, fmt.Errorf("application index field was not loaded: RunRead.Namespace")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("Id") {
				return nil, fmt.Errorf("application index field was not loaded: RunRead.Id")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("PlanId") {
				return nil, fmt.Errorf("application index field was not loaded: RunRead.PlanId")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("Status") {
				return nil, fmt.Errorf("application index field was not loaded: RunRead.Status")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("Revision") {
				return nil, fmt.Errorf("application index field was not loaded: RunRead.Revision")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("EndlySessionId") {
				return nil, fmt.Errorf("application index field was not loaded: RunRead.EndlySessionId")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("EndlyOperationId") {
				return nil, fmt.Errorf("application index field was not loaded: RunRead.EndlyOperationId")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("CreatedAt") {
				return nil, fmt.Errorf("application index field was not loaded: RunRead.CreatedAt")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("UpdatedAt") {
				return nil, fmt.Errorf("application index field was not loaded: RunRead.UpdatedAt")
			}
		}
		cloned, err := (xshape.Runtime{}).CloneValue(rows, xshape.CloneOptions{})
		if err != nil {
			return nil, err
		}
		result.RunRead = CreateChromeAttemptBindingHandlerRunReadSlice(cloned.([]*RunReadRow))
		result.RunReadByKey, err = result.RunRead.IndexByKey()
		if err != nil {
			return nil, err
		}
	}
	{
		projection, err := metadata.Projection("PlanRead")
		if err != nil {
			return nil, err
		}
		if (xshape.Runtime{}).IsNil(projection) {
			return nil, fmt.Errorf("application read projection is unavailable: PlanRead")
		}
		inputAccess, err := xshape.Linked(reflect.TypeOf((*CreateChromeAttemptBindingInput)(nil)).Elem()).Accessor("PlanRead")
		if err != nil {
			return nil, err
		}
		carrier, err := inputAccess.Get(input)
		if err != nil {
			return nil, err
		}
		value := carrier.Interface()
		if projection.DirectOutput() && projection.RootHolder() != "" {
			return nil, fmt.Errorf("direct application read cannot declare a root holder")
		}
		if !projection.DirectOutput() {
			holder := projection.RootHolder()
			if holder == "" {
				return nil, fmt.Errorf("wrapped read projection requires a canonical root holder")
			}
			accessor, err := xshape.Linked(carrier.Type()).Accessor(holder)
			if err != nil {
				return nil, err
			}
			if _, err := (xshape.Collection[PlanReadRow]{}).Pointers(reflect.Zero(accessor.Type()).Interface()); err != nil {
				return nil, err
			}
			root, present, err := accessor.GetOptional(value)
			if err != nil {
				return nil, err
			}
			if present {
				value = root.Interface()
			} else {
				value = []*PlanReadRow(nil)
			}
		}
		rows, err := (xshape.Collection[PlanReadRow]{}).Pointers(value)
		if err != nil {
			return nil, err
		}
		for ordinal, row := range rows {
			if row == nil {
				continue
			}
			loaded, err := projection.Fields(ordinal)
			if err != nil {
				return nil, err
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("Namespace") {
				return nil, fmt.Errorf("application index field was not loaded: PlanRead.Namespace")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("Id") {
				return nil, fmt.Errorf("application index field was not loaded: PlanRead.Id")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("ParentId") {
				return nil, fmt.Errorf("application index field was not loaded: PlanRead.ParentId")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("ObjectiveId") {
				return nil, fmt.Errorf("application index field was not loaded: PlanRead.ObjectiveId")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("ContentHash") {
				return nil, fmt.Errorf("application index field was not loaded: PlanRead.ContentHash")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("ContentJson") {
				return nil, fmt.Errorf("application index field was not loaded: PlanRead.ContentJson")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("CreatedAt") {
				return nil, fmt.Errorf("application index field was not loaded: PlanRead.CreatedAt")
			}
		}
		cloned, err := (xshape.Runtime{}).CloneValue(rows, xshape.CloneOptions{})
		if err != nil {
			return nil, err
		}
		result.PlanRead = CreateChromeAttemptBindingHandlerPlanReadSlice(cloned.([]*PlanReadRow))
		result.PlanReadByKey, err = result.PlanRead.IndexByKey()
		if err != nil {
			return nil, err
		}
	}
	{
		projection, err := metadata.Projection("IntentEventRead")
		if err != nil {
			return nil, err
		}
		if (xshape.Runtime{}).IsNil(projection) {
			return nil, fmt.Errorf("application read projection is unavailable: IntentEventRead")
		}
		inputAccess, err := xshape.Linked(reflect.TypeOf((*CreateChromeAttemptBindingInput)(nil)).Elem()).Accessor("IntentEventRead")
		if err != nil {
			return nil, err
		}
		carrier, err := inputAccess.Get(input)
		if err != nil {
			return nil, err
		}
		value := carrier.Interface()
		if projection.DirectOutput() && projection.RootHolder() != "" {
			return nil, fmt.Errorf("direct application read cannot declare a root holder")
		}
		if !projection.DirectOutput() {
			holder := projection.RootHolder()
			if holder == "" {
				return nil, fmt.Errorf("wrapped read projection requires a canonical root holder")
			}
			accessor, err := xshape.Linked(carrier.Type()).Accessor(holder)
			if err != nil {
				return nil, err
			}
			if _, err := (xshape.Collection[IntentEventRead]{}).Pointers(reflect.Zero(accessor.Type()).Interface()); err != nil {
				return nil, err
			}
			root, present, err := accessor.GetOptional(value)
			if err != nil {
				return nil, err
			}
			if present {
				value = root.Interface()
			} else {
				value = []*IntentEventRead(nil)
			}
		}
		rows, err := (xshape.Collection[IntentEventRead]{}).Pointers(value)
		if err != nil {
			return nil, err
		}
		for ordinal, row := range rows {
			if row == nil {
				continue
			}
			loaded, err := projection.Fields(ordinal)
			if err != nil {
				return nil, err
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("Namespace") {
				return nil, fmt.Errorf("application index field was not loaded: IntentEventRead.Namespace")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("Id") {
				return nil, fmt.Errorf("application index field was not loaded: IntentEventRead.Id")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("RunId") {
				return nil, fmt.Errorf("application index field was not loaded: IntentEventRead.RunId")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("AttemptId") {
				return nil, fmt.Errorf("application index field was not loaded: IntentEventRead.AttemptId")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("Sequence") {
				return nil, fmt.Errorf("application index field was not loaded: IntentEventRead.Sequence")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("Kind") {
				return nil, fmt.Errorf("application index field was not loaded: IntentEventRead.Kind")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("PayloadJson") {
				return nil, fmt.Errorf("application index field was not loaded: IntentEventRead.PayloadJson")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("CreatedAt") {
				return nil, fmt.Errorf("application index field was not loaded: IntentEventRead.CreatedAt")
			}
		}
		cloned, err := (xshape.Runtime{}).CloneValue(rows, xshape.CloneOptions{})
		if err != nil {
			return nil, err
		}
		result.IntentEventRead = CreateChromeAttemptBindingHandlerIntentEventReadSlice(cloned.([]*IntentEventRead))
		result.IntentEventReadByKey, err = result.IntentEventRead.IndexByKey()
		if err != nil {
			return nil, err
		}
	}
	return result, nil
}
func (input *CreateChromeAttemptBindingInput) PrepareReadIndexes(ctx context.Context) error {
	if input == nil {
		return fmt.Errorf("read indexes require input")
	}
	input._createChromeAttemptBindingHandlerReadIndexes = nil
	indexes, err := BuildCreateChromeAttemptBindingHandlerReadIndexes(ctx, input)
	if err := err; err != nil {
		return err
	}
	input._createChromeAttemptBindingHandlerReadIndexes = indexes
	return nil
}
func (input *CreateChromeAttemptBindingInput) ReadIndexes(ctx context.Context) (*CreateChromeAttemptBindingHandlerReadIndexes, error) {
	if input == nil {
		return nil, fmt.Errorf("read indexes require input")
	}
	if input._createChromeAttemptBindingHandlerReadIndexes == nil {
		if err := input.PrepareReadIndexes(ctx); err != nil {
			return nil, err
		}
	}
	return input._createChromeAttemptBindingHandlerReadIndexes, nil
}
