// Code generated by Datly for CreateChromeAttemptBinding; DO NOT EDIT.

package chromeattemptbindingcreate

// CreateChromeAttemptBindingInput is the generated input scaffold for CreateChromeAttemptBinding.
type CreateChromeAttemptBindingInput struct {
	Namespace                                     string                                        `parameter:"Namespace,kind=query,in=namespace,dataType=string,required=true"`
	ClientID                                      string                                        `parameter:"ClientID,kind=query,in=clientId,dataType=string,required=true"`
	AttemptID                                     string                                        `parameter:"AttemptID,kind=query,in=attemptId,dataType=string,required=true"`
	EffectID                                      string                                        `parameter:"EffectID,kind=query,in=effectId,dataType=string,required=true"`
	RunID                                         string                                        `parameter:"RunID,kind=query,in=runId,dataType=string,required=true"`
	PlanID                                        string                                        `parameter:"PlanID,kind=query,in=planId,dataType=string,required=true"`
	IntentRead                                    []*IntentReadRow                              `parameter:"IntentRead,kind=view,in=IntentRead,dataType=[]*IntentReadRow,cardinality=many" view:"IntentRead,table=effects" sql:"uri=mechanize_data_chromeattemptbindingcreate_create_chrome_attempt_binding:sql/intent_read.sql"`
	AttemptRead                                   []*AttemptReadRow                             `parameter:"AttemptRead,kind=view,in=AttemptRead,dataType=[]*AttemptReadRow,cardinality=many" view:"AttemptRead,table=attempts" sql:"uri=mechanize_data_chromeattemptbindingcreate_create_chrome_attempt_binding:sql/attempt_read.sql"`
	RunRead                                       []*RunReadRow                                 `parameter:"RunRead,kind=view,in=RunRead,dataType=[]*RunReadRow,cardinality=many" view:"RunRead,table=runs" sql:"uri=mechanize_data_chromeattemptbindingcreate_create_chrome_attempt_binding:sql/run_read.sql"`
	PlanRead                                      []*PlanReadRow                                `parameter:"PlanRead,kind=view,in=PlanRead,dataType=[]*PlanReadRow,cardinality=many" view:"PlanRead,table=plan_revisions" sql:"uri=mechanize_data_chromeattemptbindingcreate_create_chrome_attempt_binding:sql/plan_read.sql"`
	IntentEventRead                               []*IntentEventRead                            `parameter:"IntentEventRead,kind=view,in=IntentEventRead,dataType=[]*IntentEventRead,cardinality=many" view:"IntentEventRead,table=events" sql:"uri=mechanize_data_chromeattemptbindingcreate_create_chrome_attempt_binding:sql/intent_event_read.sql"`
	CreateChromeAttemptBinding                    []*Binding                                    `parameter:"CreateChromeAttemptBinding,kind=body,in=Data,dataType=[]*Binding,cardinality=Many,required=true" view:"CreateChromeAttemptBinding,type=Binding,entityHooks=BindingLifecycle,table=chrome_attempt_bindings" sql:"uri=mechanize_data_chromeattemptbindingcreate_create_chrome_attempt_binding:sql/create_chrome_attempt_binding.sql"`
	_createChromeAttemptBindingHandlerReadIndexes *CreateChromeAttemptBindingHandlerReadIndexes `json:"-" sqlx:"-"`
	Has                                           *CreateChromeAttemptBindingInputHas           `setMarker:"true" typeName:"CreateChromeAttemptBindingInputHas" json:"-" sqlx:"-"`
}

type CreateChromeAttemptBindingInputHas struct {
	Namespace                  bool
	ClientID                   bool
	AttemptID                  bool
	EffectID                   bool
	RunID                      bool
	PlanID                     bool
	IntentRead                 bool
	AttemptRead                bool
	RunRead                    bool
	PlanRead                   bool
	IntentEventRead            bool
	CreateChromeAttemptBinding bool
}
