// Code generated by Datly for CreateChromeAttemptBinding; DO NOT EDIT.

package chromeattemptbindingcreate

import (
	embed "embed"
	xdatly "github.com/viant/xdatly"
	reflect "reflect"
)

func init() {}

// Component is the generated component scaffold for CreateChromeAttemptBinding.
type CreateChromeAttemptBindingComponent struct {
	Contract xdatly.Component[CreateChromeAttemptBindingInput, CreateChromeAttemptBindingOutput] "component:\"CreateChromeAttemptBinding,path=/internal/data/chromeattemptbindingcreate,method=POST,connector=user,view=CreateChromeAttemptBinding\" routeName:\"CreateChromeAttemptBinding\" mutation:\"post\" caseFormat:\"lc\""
}

// CreateChromeAttemptBindingDatlyType returns the public component type.
func CreateChromeAttemptBindingDatlyType() reflect.Type {
	return reflect.TypeOf((*CreateChromeAttemptBindingComponent)(nil)).Elem()
}

// The package-level value keeps this real component type reachable for runtime discovery.
var CreateChromeAttemptBindingDatly = new(CreateChromeAttemptBindingComponent)
var _datlyReachableCreateChromeAttemptBindingComponent = reflect.TypeFor[CreateChromeAttemptBindingComponent]()

func (CreateChromeAttemptBindingComponent) EmbedFS() *embed.FS {
	return &CreateChromeAttemptBindingDatlyResources
}

func (CreateChromeAttemptBindingComponent) EmbedNamespace() string {
	return CreateChromeAttemptBindingDatlyResourceNamespace
}
