// Code generated by Datly for PublishCheckpoint; DO NOT EDIT.

package checkpoint

// PublishCheckpointInput is the generated input scaffold for PublishCheckpoint.
type PublishCheckpointInput struct {
	Namespace                            string                               `parameter:"Namespace,kind=query,in=namespace,dataType=string,required=true"`
	ArtifactIDs                          []string                             `parameter:"ArtifactIDs,kind=query,in=artifactIds,dataType=[]string,required=true"`
	PublishCheckpoint                    []*CheckpointRun                     `parameter:"PublishCheckpoint,kind=body,in=Data,dataType=[]*CheckpointRun,cardinality=Many,required=true" view:"PublishCheckpoint,type=CheckpointRun,entityHooks=CheckpointRunLifecycle,table=runs" sql:"uri=mechanize_data_checkpoint_publish_checkpoint:sql/publish_checkpoint.sql"`
	PublishCheckpointKeys                []PublishCheckpointKeysRow           `parameter:"PublishCheckpointKeys,kind=param,in=PublishCheckpoint,cardinality=Many" codec:"structql,'uri=mechanize_data_checkpoint_publish_checkpoint:sql/publish_checkpoint_keys.sql'"`
	CurrentPublishCheckpoint             []*CurrentPublishCheckpointView      `parameter:"CurrentPublishCheckpoint,kind=view,in=CurrentPublishCheckpoint,cardinality=Many" view:"CurrentPublishCheckpoint,table=runs" sql:"uri=mechanize_data_checkpoint_publish_checkpoint:sql/current_publish_checkpoint.sql"`
	CurrentCheckpoints                   []*CurrentCheckpointsView            `parameter:"CurrentCheckpoints,kind=view,in=CurrentCheckpoints,cardinality=Many" view:"CurrentCheckpoints,table=checkpoints" sql:"uri=mechanize_data_checkpoint_publish_checkpoint:sql/current_checkpoints.sql"`
	CurrentArtifacts                     []*CurrentArtifactsView              `parameter:"CurrentArtifacts,kind=view,in=CurrentArtifacts,cardinality=Many" view:"CurrentArtifacts,table=artifacts,auxiliary=true" sql:"uri=mechanize_data_checkpoint_publish_checkpoint:sql/current_artifacts.sql"`
	CurrentUnresolved                    []*CurrentUnresolvedView             `parameter:"CurrentUnresolved,kind=view,in=CurrentUnresolved,cardinality=Many" view:"CurrentUnresolved,table=effects,auxiliary=true" sql:"uri=mechanize_data_checkpoint_publish_checkpoint:sql/current_unresolved.sql"`
	CurrentLedgerEvents                  []*CurrentLedgerEventsView           `parameter:"CurrentLedgerEvents,kind=view,in=CurrentLedgerEvents,cardinality=Many" view:"CurrentLedgerEvents,table=events,auxiliary=true" sql:"uri=mechanize_data_checkpoint_publish_checkpoint:sql/current_ledger_events.sql"`
	_publishCheckpointHandlerReadIndexes *PublishCheckpointHandlerReadIndexes `json:"-" sqlx:"-"`
	Has                                  *PublishCheckpointInputHas           `setMarker:"true" typeName:"PublishCheckpointInputHas" json:"-" sqlx:"-"`
}

type PublishCheckpointInputHas struct {
	Namespace                bool
	ArtifactIDs              bool
	PublishCheckpoint        bool
	PublishCheckpointKeys    bool
	CurrentPublishCheckpoint bool
	CurrentCheckpoints       bool
	CurrentArtifacts         bool
	CurrentUnresolved        bool
	CurrentLedgerEvents      bool
}
