// Code generated by Datly for PublishCheckpoint; DO NOT EDIT.

package checkpoint

import (
	embed "embed"
	xdatly "github.com/viant/xdatly"
	reflect "reflect"
)

func init() {}

// Component is the generated component scaffold for PublishCheckpoint.
type PublishCheckpointComponent struct {
	Contract xdatly.Component[PublishCheckpointInput, PublishCheckpointOutput] "component:\"PublishCheckpoint,path=/internal/data/checkpoint,method=PATCH,connector=user,view=PublishCheckpoint\" routeName:\"PublishCheckpoint\" mutation:\"patch\" caseFormat:\"lc\""
}

// PublishCheckpointDatlyType returns the public component type.
func PublishCheckpointDatlyType() reflect.Type {
	return reflect.TypeOf((*PublishCheckpointComponent)(nil)).Elem()
}

// The package-level value keeps this real component type reachable for runtime discovery.
var PublishCheckpointDatly = new(PublishCheckpointComponent)
var _datlyReachablePublishCheckpointComponent = reflect.TypeFor[PublishCheckpointComponent]()

func (PublishCheckpointComponent) EmbedFS() *embed.FS {
	return &PublishCheckpointDatlyResources
}

func (PublishCheckpointComponent) EmbedNamespace() string {
	return PublishCheckpointDatlyResourceNamespace
}
