// Code generated by Datly for PublishCheckpoint; DO NOT EDIT.

package checkpoint

// CheckpointRun is generated canonical view metadata for PublishCheckpoint.
type CheckpointRun struct {
	Revision     *int                `writer:"concurrency" sqlx:"revision,required=true" json:"revision"`
	Namespace    *string             `sqlx:"namespace,refTable=plan_revisions,refColumn=namespace,required=true,primaryKey=true" json:"namespace"`
	Id           *string             `sqlx:"id,required=true,primaryKey=true" json:"id"`
	PlanId       *string             `sqlx:"plan_id,refTable=plan_revisions,refColumn=id,required=true" json:"planId"`
	Status       *string             `sqlx:"status,required=true" json:"status"`
	Checkpoints  []*Checkpoint       `view:"checkpoints,type=Checkpoint,entityHooks=CheckpointLifecycle,table=checkpoints" on:"Namespace:records.namespace=Namespace:checkpoints.namespace,Id:records.id=RunId:checkpoints.run_id" json:"checkpoints" sql:"uri=mechanize_data_checkpoint_publish_checkpoint:sql/checkpoints.sql"`
	Artifacts    []*Artifact         `view:"artifacts,type=Artifact,table=artifacts,auxiliary=true" on:"Namespace:records.namespace=Namespace:artifacts.namespace" json:"artifacts" sql:"uri=mechanize_data_checkpoint_publish_checkpoint:sql/artifacts.sql"`
	Unresolved   []*UnresolvedEffect `view:"unresolved,type=UnresolvedEffect,table=effects,auxiliary=true" on:"Namespace:records.namespace=Namespace:unresolved.namespace,Id:records.id=RunId:unresolved.run_id" json:"unresolved" sql:"uri=mechanize_data_checkpoint_publish_checkpoint:sql/unresolved.sql"`
	LedgerEvents []*LedgerEvent      `view:"ledgerEvents,type=LedgerEvent,table=events,auxiliary=true" on:"Namespace:records.namespace=Namespace:ledgerEvents.namespace,Id:records.id=RunId:ledgerEvents.run_id" json:"ledgerEvents" sql:"uri=mechanize_data_checkpoint_publish_checkpoint:sql/ledger_events.sql"`
	Has          *CheckpointRunHas   `setMarker:"true" format:"-" sqlx:"-" diff:"-" json:"-" typeName:"CheckpointRunHas"`
}

type CheckpointRunHas struct {
	Revision    bool
	Namespace   bool
	Id          bool
	PlanId      bool
	Status      bool
	Checkpoints bool
}

// Checkpoint is generated canonical view metadata for PublishCheckpoint.
type Checkpoint struct {
	Namespace        *string        `sqlx:"namespace,refTable=runs,refColumn=namespace,required=true,primaryKey=true" json:"namespace"`
	Id               *string        `sqlx:"id,required=true,primaryKey=true" json:"id"`
	RunId            *string        `sqlx:"run_id,refTable=runs,refColumn=id,required=true" json:"runId"`
	PlanId           *string        `sqlx:"plan_id,required=true" json:"planId"`
	RunRevision      *int           `sqlx:"run_revision,required=true" json:"runRevision"`
	EventSequence    *int           `sqlx:"event_sequence,required=true" json:"eventSequence"`
	ManifestHash     *string        `sqlx:"manifest_hash,required=true" json:"manifestHash"`
	ManifestJson     *string        `sqlx:"manifest_json,required=true" json:"manifestJson"`
	PublicationState *string        `sqlx:"publication_state,required=true" json:"publicationState"`
	CreatedAt        *string        `sqlx:"created_at,required=true" json:"createdAt"`
	Has              *CheckpointHas `setMarker:"true" format:"-" sqlx:"-" diff:"-" json:"-" typeName:"CheckpointHas"`
}

type CheckpointHas struct {
	Namespace        bool
	Id               bool
	RunId            bool
	PlanId           bool
	RunRevision      bool
	EventSequence    bool
	ManifestHash     bool
	ManifestJson     bool
	PublicationState bool
	CreatedAt        bool
}

// Artifact is generated canonical view metadata for PublishCheckpoint.
type Artifact struct {
	Namespace        *string `sqlx:"namespace,required=true,primaryKey=true" json:"namespace"`
	Id               *string `sqlx:"id,required=true,primaryKey=true" json:"id"`
	ContentHash      *string `sqlx:"content_hash,required=true" json:"contentHash"`
	SizeBytes        *int    `sqlx:"size_bytes,required=true" json:"sizeBytes"`
	MediaType        *string `sqlx:"media_type,required=true" json:"mediaType"`
	KeyReference     *string `sqlx:"key_reference" json:"keyReference"`
	PublicationState *string `sqlx:"publication_state,required=true" json:"publicationState"`
}

// UnresolvedEffect is generated canonical view metadata for PublishCheckpoint.
type UnresolvedEffect struct {
	Namespace    *string `sqlx:"namespace,refTable=attempts,refColumn=namespace,required=true,primaryKey=true" json:"namespace"`
	Id           *string `sqlx:"id,required=true,primaryKey=true" json:"id"`
	AttemptId    *string `sqlx:"attempt_id,refTable=attempts,refColumn=id,required=true" json:"attemptId"`
	RunId        *string `sqlx:"run_id,required=true" json:"runId"`
	BusinessKey  *string `sqlx:"business_key,required=true" json:"businessKey"`
	State        *string `sqlx:"state,required=true" json:"state"`
	Revision     *int    `sqlx:"revision,required=true" json:"revision"`
	EvidenceJson *string `sqlx:"evidence_json" json:"evidenceJson"`
}

// LedgerEvent is generated canonical view metadata for PublishCheckpoint.
type LedgerEvent struct {
	Namespace   *string `sqlx:"namespace,refTable=runs,refColumn=namespace,required=true,primaryKey=true" json:"namespace"`
	Id          *string `sqlx:"id,required=true,primaryKey=true" json:"id"`
	RunId       *string `sqlx:"run_id,refTable=runs,refColumn=id,required=true" json:"runId"`
	AttemptId   *string `sqlx:"attempt_id" json:"attemptId"`
	Sequence    *int    `sqlx:"sequence,required=true" json:"sequence"`
	Kind        *string `sqlx:"kind,required=true" json:"kind"`
	PayloadJson *string `sqlx:"payload_json,required=true" json:"payloadJson"`
	CreatedAt   *string `sqlx:"created_at,required=true" json:"createdAt"`
}

// CurrentPublishCheckpointView is generated canonical view metadata for PublishCheckpoint.
type CurrentPublishCheckpointView struct {
	Revision  *int    `sqlx:"revision,required=true" json:"revision"`
	Namespace *string `sqlx:"namespace,refTable=plan_revisions,refColumn=namespace,required=true,primaryKey=true" json:"namespace"`
	Id        *string `sqlx:"id,required=true,primaryKey=true" json:"id"`
	PlanId    *string `sqlx:"plan_id,refTable=plan_revisions,refColumn=id,required=true" json:"planId"`
	Status    *string `sqlx:"status,required=true" json:"status"`
}

// CurrentCheckpointsView is generated canonical view metadata for PublishCheckpoint.
type CurrentCheckpointsView struct {
	Namespace        *string `sqlx:"namespace,refTable=runs,refColumn=namespace,required=true,primaryKey=true" json:"namespace"`
	Id               *string `sqlx:"id,required=true,primaryKey=true" json:"id"`
	RunId            *string `sqlx:"run_id,refTable=runs,refColumn=id,required=true" json:"runId"`
	PlanId           *string `sqlx:"plan_id,required=true" json:"planId"`
	RunRevision      *int    `sqlx:"run_revision,required=true" json:"runRevision"`
	EventSequence    *int    `sqlx:"event_sequence,required=true" json:"eventSequence"`
	ManifestHash     *string `sqlx:"manifest_hash,required=true" json:"manifestHash"`
	ManifestJson     *string `sqlx:"manifest_json,required=true" json:"manifestJson"`
	PublicationState *string `sqlx:"publication_state,required=true" json:"publicationState"`
	CreatedAt        *string `sqlx:"created_at,required=true" json:"createdAt"`
}

// CurrentArtifactsView is generated canonical view metadata for PublishCheckpoint.
type CurrentArtifactsView struct {
	Namespace        *string `sqlx:"namespace,required=true,primaryKey=true" json:"namespace"`
	Id               *string `sqlx:"id,required=true,primaryKey=true" json:"id"`
	ContentHash      *string `sqlx:"content_hash,required=true" json:"contentHash"`
	SizeBytes        *int    `sqlx:"size_bytes,required=true" json:"sizeBytes"`
	MediaType        *string `sqlx:"media_type,required=true" json:"mediaType"`
	KeyReference     *string `sqlx:"key_reference" json:"keyReference"`
	PublicationState *string `sqlx:"publication_state,required=true" json:"publicationState"`
}

// CurrentUnresolvedView is generated canonical view metadata for PublishCheckpoint.
type CurrentUnresolvedView struct {
	Namespace    *string `sqlx:"namespace,refTable=attempts,refColumn=namespace,required=true,primaryKey=true" json:"namespace"`
	Id           *string `sqlx:"id,required=true,primaryKey=true" json:"id"`
	AttemptId    *string `sqlx:"attempt_id,refTable=attempts,refColumn=id,required=true" json:"attemptId"`
	RunId        *string `sqlx:"run_id,required=true" json:"runId"`
	BusinessKey  *string `sqlx:"business_key,required=true" json:"businessKey"`
	State        *string `sqlx:"state,required=true" json:"state"`
	Revision     *int    `sqlx:"revision,required=true" json:"revision"`
	EvidenceJson *string `sqlx:"evidence_json" json:"evidenceJson"`
}

// CurrentLedgerEventsView is generated canonical view metadata for PublishCheckpoint.
type CurrentLedgerEventsView struct {
	Namespace   *string `sqlx:"namespace,refTable=runs,refColumn=namespace,required=true,primaryKey=true" json:"namespace"`
	Id          *string `sqlx:"id,required=true,primaryKey=true" json:"id"`
	RunId       *string `sqlx:"run_id,refTable=runs,refColumn=id,required=true" json:"runId"`
	AttemptId   *string `sqlx:"attempt_id" json:"attemptId"`
	Sequence    *int    `sqlx:"sequence,required=true" json:"sequence"`
	Kind        *string `sqlx:"kind,required=true" json:"kind"`
	PayloadJson *string `sqlx:"payload_json,required=true" json:"payloadJson"`
	CreatedAt   *string `sqlx:"created_at,required=true" json:"createdAt"`
}

type PublishCheckpointKeysRow struct {
	Namespace *string `sqlx:"namespace"`
	Id        *string `sqlx:"id"`
}
