// Code generated by Datly for AppendRecordingEvents; DO NOT EDIT.

package recordevents

func (input *AppendRecordingEventsInput) SetNamespace(value string) {
	if input == nil {
		return
	}
	input.Namespace = value
	if input.Has == nil {
		input.Has = &AppendRecordingEventsInputHas{}
	}
	input.Has.Namespace = true
}

func (input *AppendRecordingEventsInput) SetAppendRecordingEvents(value []*RecordedEvent) {
	if input == nil {
		return
	}
	input.AppendRecordingEvents = value
	if input.Has == nil {
		input.Has = &AppendRecordingEventsInputHas{}
	}
	input.Has.AppendRecordingEvents = true
}
