// Code generated by Datly for ListEvents; DO NOT EDIT.

package listevents

func (input *ListEventsInput) SetNamespace(value string) {
	if input == nil {
		return
	}
	input.Namespace = value
	if input.Has == nil {
		input.Has = &ListEventsInputHas{}
	}
	input.Has.Namespace = true
}

func (input *ListEventsInput) SetRunID(value string) {
	if input == nil {
		return
	}
	input.RunID = value
	if input.Has == nil {
		input.Has = &ListEventsInputHas{}
	}
	input.Has.RunID = true
}
