// Code generated by Datly for ListEvents; DO NOT EDIT.

package listevents

// ListEventsOutput is the generated output scaffold for ListEvents.
type ListEventsOutput struct {
	Data []*Event `parameter:"Data,kind=output,in=view,dataType=[]*Event" view:"ListEvents,type=Event,table=events,limit=200" sql:"uri=mechanize_data_listevents_list_events:sql/list_events.sql"`
}
