// Code generated by Datly for ListEvents; DO NOT EDIT.

package listevents

import "embed"

// DatlyResourceNamespace identifies this package's generated resource filesystem.
const ListEventsDatlyResourceNamespace = "mechanize_data_listevents_list_events"

//go:embed "sql/list_events.sql"
var ListEventsDatlyResources embed.FS
