// Code generated by Datly for ListEvents; DO NOT EDIT.

package listevents

// Event is generated canonical view metadata for ListEvents.
type Event struct {
	Namespace   *string `sqlx:"namespace,refTable=runs,refColumn=namespace,required=true,primaryKey=true" json:"namespace"`
	Id          *string `sqlx:"id,required=true,primaryKey=true" json:"id"`
	RunId       *string `sqlx:"run_id,refTable=runs,refColumn=id,required=true" json:"runId"`
	AttemptId   *string `sqlx:"attempt_id" json:"attemptId"`
	Sequence    *int    `sqlx:"sequence,required=true" json:"sequence"`
	Kind        *string `sqlx:"kind,required=true" json:"kind"`
	PayloadJson *string `sqlx:"payload_json,required=true" json:"payloadJson"`
	CreatedAt   *string `sqlx:"created_at,required=true" json:"createdAt"`
}
