// Code generated by Datly for ListCheckpoints; DO NOT EDIT.

package listcheckpoints

// ListCheckpointsInput is the generated input scaffold for ListCheckpoints.
type ListCheckpointsInput struct {
	Namespace string                   `parameter:"Namespace,kind=query,in=namespace,dataType=string,required=true"`
	RunID     string                   `parameter:"RunID,kind=query,in=runId,dataType=string,required=true"`
	Has       *ListCheckpointsInputHas `setMarker:"true" typeName:"ListCheckpointsInputHas" json:"-" sqlx:"-"`
}

type ListCheckpointsInputHas struct {
	Namespace bool
	RunID     bool
}
