// Code generated by Datly for ListCheckpoints; DO NOT EDIT.

package listcheckpoints

// ListCheckpointsOutput is the generated output scaffold for ListCheckpoints.
type ListCheckpointsOutput struct {
	Data []*Checkpoint `parameter:"Data,kind=output,in=view,dataType=[]*Checkpoint" view:"ListCheckpoints,type=Checkpoint,table=checkpoints,limit=200" sql:"uri=mechanize_data_listcheckpoints_list_checkpoints:sql/list_checkpoints.sql"`
}
