// Code generated by Datly for ListCheckpoints; DO NOT EDIT.

package listcheckpoints

import "embed"

// DatlyResourceNamespace identifies this package's generated resource filesystem.
const ListCheckpointsDatlyResourceNamespace = "mechanize_data_listcheckpoints_list_checkpoints"

//go:embed "sql/list_checkpoints.sql"
var ListCheckpointsDatlyResources embed.FS
