// Code generated by Datly for ListCheckpoints; DO NOT EDIT.

package listcheckpoints

import (
	embed "embed"
	xdatly "github.com/viant/xdatly"
	reflect "reflect"
)

func init() {}

// Component is the generated component scaffold for ListCheckpoints.
type ListCheckpointsComponent struct {
	Contract xdatly.Component[ListCheckpointsInput, ListCheckpointsOutput] "component:\"ListCheckpoints,path=/internal/data/listcheckpoints,method=GET,connector=user,view=ListCheckpoints\" routeName:\"ListCheckpoints\" caseFormat:\"lc\""
}

// ListCheckpointsDatlyType returns the public component type.
func ListCheckpointsDatlyType() reflect.Type {
	return reflect.TypeOf((*ListCheckpointsComponent)(nil)).Elem()
}

// The package-level value keeps this real component type reachable for runtime discovery.
var ListCheckpointsDatly = new(ListCheckpointsComponent)
var _datlyReachableListCheckpointsComponent = reflect.TypeFor[ListCheckpointsComponent]()

func (ListCheckpointsComponent) EmbedFS() *embed.FS {
	return &ListCheckpointsDatlyResources
}

func (ListCheckpointsComponent) EmbedNamespace() string {
	return ListCheckpointsDatlyResourceNamespace
}
