// Code generated by Datly for consentrevoke; DO NOT EDIT.

package consentrevoke

import (
	context "context"
	fmt "fmt"
	xshape "github.com/viant/x/shape"
	xhandler "github.com/viant/xdatly/handler"
	reflect "reflect"
)

type ConsentrevokeHandlerCurrentConsentrevokeSlice []*CurrentConsentrevokeView

func ConsentrevokeHandlerCurrentConsentrevokeIndexByRevisionKey(value *CurrentConsentrevokeView) (int, bool) {
	var zero int
	if value == nil {
		return zero, false
	}
	if value.Revision == nil {
		return zero, false
	}
	return *value.Revision, true
}

type ConsentrevokeHandlerCurrentConsentrevokeIndexedByRevision map[int]*CurrentConsentrevokeView

func (rows ConsentrevokeHandlerCurrentConsentrevokeSlice) IndexByRevision() (ConsentrevokeHandlerCurrentConsentrevokeIndexedByRevision, error) {
	result := make(ConsentrevokeHandlerCurrentConsentrevokeIndexedByRevision)
	for _, row := range rows {
		key, ok := ConsentrevokeHandlerCurrentConsentrevokeIndexByRevisionKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index ConsentrevokeHandlerCurrentConsentrevokeSlice.IndexByRevision")
		}
		result[key] = row
	}
	return result, nil
}
func (index ConsentrevokeHandlerCurrentConsentrevokeIndexedByRevision) Has(key int) bool {
	_, ok := index[key]
	return ok
}

type ConsentrevokeHandlerCurrentConsentrevokeGroupedByRevision map[int][]*CurrentConsentrevokeView

func (rows ConsentrevokeHandlerCurrentConsentrevokeSlice) GroupByRevision() ConsentrevokeHandlerCurrentConsentrevokeGroupedByRevision {
	result := make(ConsentrevokeHandlerCurrentConsentrevokeGroupedByRevision)
	for _, row := range rows {
		key, ok := ConsentrevokeHandlerCurrentConsentrevokeIndexByRevisionKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index ConsentrevokeHandlerCurrentConsentrevokeGroupedByRevision) Has(key int) bool {
	_, ok := index[key]
	return ok
}
func ConsentrevokeHandlerCurrentConsentrevokeIndexByNamespaceKey(value *CurrentConsentrevokeView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.Namespace == nil {
		return zero, false
	}
	return *value.Namespace, true
}

type ConsentrevokeHandlerCurrentConsentrevokeIndexedByNamespace map[string]*CurrentConsentrevokeView

func (rows ConsentrevokeHandlerCurrentConsentrevokeSlice) IndexByNamespace() (ConsentrevokeHandlerCurrentConsentrevokeIndexedByNamespace, error) {
	result := make(ConsentrevokeHandlerCurrentConsentrevokeIndexedByNamespace)
	for _, row := range rows {
		key, ok := ConsentrevokeHandlerCurrentConsentrevokeIndexByNamespaceKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index ConsentrevokeHandlerCurrentConsentrevokeSlice.IndexByNamespace")
		}
		result[key] = row
	}
	return result, nil
}
func (index ConsentrevokeHandlerCurrentConsentrevokeIndexedByNamespace) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type ConsentrevokeHandlerCurrentConsentrevokeGroupedByNamespace map[string][]*CurrentConsentrevokeView

func (rows ConsentrevokeHandlerCurrentConsentrevokeSlice) GroupByNamespace() ConsentrevokeHandlerCurrentConsentrevokeGroupedByNamespace {
	result := make(ConsentrevokeHandlerCurrentConsentrevokeGroupedByNamespace)
	for _, row := range rows {
		key, ok := ConsentrevokeHandlerCurrentConsentrevokeIndexByNamespaceKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index ConsentrevokeHandlerCurrentConsentrevokeGroupedByNamespace) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func ConsentrevokeHandlerCurrentConsentrevokeIndexByIdKey(value *CurrentConsentrevokeView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.Id == nil {
		return zero, false
	}
	return *value.Id, true
}

type ConsentrevokeHandlerCurrentConsentrevokeIndexedById map[string]*CurrentConsentrevokeView

func (rows ConsentrevokeHandlerCurrentConsentrevokeSlice) IndexById() (ConsentrevokeHandlerCurrentConsentrevokeIndexedById, error) {
	result := make(ConsentrevokeHandlerCurrentConsentrevokeIndexedById)
	for _, row := range rows {
		key, ok := ConsentrevokeHandlerCurrentConsentrevokeIndexByIdKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index ConsentrevokeHandlerCurrentConsentrevokeSlice.IndexById")
		}
		result[key] = row
	}
	return result, nil
}
func (index ConsentrevokeHandlerCurrentConsentrevokeIndexedById) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type ConsentrevokeHandlerCurrentConsentrevokeGroupedById map[string][]*CurrentConsentrevokeView

func (rows ConsentrevokeHandlerCurrentConsentrevokeSlice) GroupById() ConsentrevokeHandlerCurrentConsentrevokeGroupedById {
	result := make(ConsentrevokeHandlerCurrentConsentrevokeGroupedById)
	for _, row := range rows {
		key, ok := ConsentrevokeHandlerCurrentConsentrevokeIndexByIdKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index ConsentrevokeHandlerCurrentConsentrevokeGroupedById) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func ConsentrevokeHandlerCurrentConsentrevokeIndexByClientIdKey(value *CurrentConsentrevokeView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.ClientId == nil {
		return zero, false
	}
	return *value.ClientId, true
}

type ConsentrevokeHandlerCurrentConsentrevokeIndexedByClientId map[string]*CurrentConsentrevokeView

func (rows ConsentrevokeHandlerCurrentConsentrevokeSlice) IndexByClientId() (ConsentrevokeHandlerCurrentConsentrevokeIndexedByClientId, error) {
	result := make(ConsentrevokeHandlerCurrentConsentrevokeIndexedByClientId)
	for _, row := range rows {
		key, ok := ConsentrevokeHandlerCurrentConsentrevokeIndexByClientIdKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index ConsentrevokeHandlerCurrentConsentrevokeSlice.IndexByClientId")
		}
		result[key] = row
	}
	return result, nil
}
func (index ConsentrevokeHandlerCurrentConsentrevokeIndexedByClientId) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type ConsentrevokeHandlerCurrentConsentrevokeGroupedByClientId map[string][]*CurrentConsentrevokeView

func (rows ConsentrevokeHandlerCurrentConsentrevokeSlice) GroupByClientId() ConsentrevokeHandlerCurrentConsentrevokeGroupedByClientId {
	result := make(ConsentrevokeHandlerCurrentConsentrevokeGroupedByClientId)
	for _, row := range rows {
		key, ok := ConsentrevokeHandlerCurrentConsentrevokeIndexByClientIdKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index ConsentrevokeHandlerCurrentConsentrevokeGroupedByClientId) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func ConsentrevokeHandlerCurrentConsentrevokeIndexByClientNameKey(value *CurrentConsentrevokeView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.ClientName == nil {
		return zero, false
	}
	return *value.ClientName, true
}

type ConsentrevokeHandlerCurrentConsentrevokeIndexedByClientName map[string]*CurrentConsentrevokeView

func (rows ConsentrevokeHandlerCurrentConsentrevokeSlice) IndexByClientName() (ConsentrevokeHandlerCurrentConsentrevokeIndexedByClientName, error) {
	result := make(ConsentrevokeHandlerCurrentConsentrevokeIndexedByClientName)
	for _, row := range rows {
		key, ok := ConsentrevokeHandlerCurrentConsentrevokeIndexByClientNameKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index ConsentrevokeHandlerCurrentConsentrevokeSlice.IndexByClientName")
		}
		result[key] = row
	}
	return result, nil
}
func (index ConsentrevokeHandlerCurrentConsentrevokeIndexedByClientName) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type ConsentrevokeHandlerCurrentConsentrevokeGroupedByClientName map[string][]*CurrentConsentrevokeView

func (rows ConsentrevokeHandlerCurrentConsentrevokeSlice) GroupByClientName() ConsentrevokeHandlerCurrentConsentrevokeGroupedByClientName {
	result := make(ConsentrevokeHandlerCurrentConsentrevokeGroupedByClientName)
	for _, row := range rows {
		key, ok := ConsentrevokeHandlerCurrentConsentrevokeIndexByClientNameKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index ConsentrevokeHandlerCurrentConsentrevokeGroupedByClientName) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func ConsentrevokeHandlerCurrentConsentrevokeIndexBySessionIdKey(value *CurrentConsentrevokeView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.SessionId == nil {
		return zero, false
	}
	return *value.SessionId, true
}

type ConsentrevokeHandlerCurrentConsentrevokeIndexedBySessionId map[string]*CurrentConsentrevokeView

func (rows ConsentrevokeHandlerCurrentConsentrevokeSlice) IndexBySessionId() (ConsentrevokeHandlerCurrentConsentrevokeIndexedBySessionId, error) {
	result := make(ConsentrevokeHandlerCurrentConsentrevokeIndexedBySessionId)
	for _, row := range rows {
		key, ok := ConsentrevokeHandlerCurrentConsentrevokeIndexBySessionIdKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index ConsentrevokeHandlerCurrentConsentrevokeSlice.IndexBySessionId")
		}
		result[key] = row
	}
	return result, nil
}
func (index ConsentrevokeHandlerCurrentConsentrevokeIndexedBySessionId) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type ConsentrevokeHandlerCurrentConsentrevokeGroupedBySessionId map[string][]*CurrentConsentrevokeView

func (rows ConsentrevokeHandlerCurrentConsentrevokeSlice) GroupBySessionId() ConsentrevokeHandlerCurrentConsentrevokeGroupedBySessionId {
	result := make(ConsentrevokeHandlerCurrentConsentrevokeGroupedBySessionId)
	for _, row := range rows {
		key, ok := ConsentrevokeHandlerCurrentConsentrevokeIndexBySessionIdKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index ConsentrevokeHandlerCurrentConsentrevokeGroupedBySessionId) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func ConsentrevokeHandlerCurrentConsentrevokeIndexByScopeJsonKey(value *CurrentConsentrevokeView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.ScopeJson == nil {
		return zero, false
	}
	return *value.ScopeJson, true
}

type ConsentrevokeHandlerCurrentConsentrevokeIndexedByScopeJson map[string]*CurrentConsentrevokeView

func (rows ConsentrevokeHandlerCurrentConsentrevokeSlice) IndexByScopeJson() (ConsentrevokeHandlerCurrentConsentrevokeIndexedByScopeJson, error) {
	result := make(ConsentrevokeHandlerCurrentConsentrevokeIndexedByScopeJson)
	for _, row := range rows {
		key, ok := ConsentrevokeHandlerCurrentConsentrevokeIndexByScopeJsonKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index ConsentrevokeHandlerCurrentConsentrevokeSlice.IndexByScopeJson")
		}
		result[key] = row
	}
	return result, nil
}
func (index ConsentrevokeHandlerCurrentConsentrevokeIndexedByScopeJson) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type ConsentrevokeHandlerCurrentConsentrevokeGroupedByScopeJson map[string][]*CurrentConsentrevokeView

func (rows ConsentrevokeHandlerCurrentConsentrevokeSlice) GroupByScopeJson() ConsentrevokeHandlerCurrentConsentrevokeGroupedByScopeJson {
	result := make(ConsentrevokeHandlerCurrentConsentrevokeGroupedByScopeJson)
	for _, row := range rows {
		key, ok := ConsentrevokeHandlerCurrentConsentrevokeIndexByScopeJsonKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index ConsentrevokeHandlerCurrentConsentrevokeGroupedByScopeJson) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func ConsentrevokeHandlerCurrentConsentrevokeIndexByModesJsonKey(value *CurrentConsentrevokeView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.ModesJson == nil {
		return zero, false
	}
	return *value.ModesJson, true
}

type ConsentrevokeHandlerCurrentConsentrevokeIndexedByModesJson map[string]*CurrentConsentrevokeView

func (rows ConsentrevokeHandlerCurrentConsentrevokeSlice) IndexByModesJson() (ConsentrevokeHandlerCurrentConsentrevokeIndexedByModesJson, error) {
	result := make(ConsentrevokeHandlerCurrentConsentrevokeIndexedByModesJson)
	for _, row := range rows {
		key, ok := ConsentrevokeHandlerCurrentConsentrevokeIndexByModesJsonKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index ConsentrevokeHandlerCurrentConsentrevokeSlice.IndexByModesJson")
		}
		result[key] = row
	}
	return result, nil
}
func (index ConsentrevokeHandlerCurrentConsentrevokeIndexedByModesJson) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type ConsentrevokeHandlerCurrentConsentrevokeGroupedByModesJson map[string][]*CurrentConsentrevokeView

func (rows ConsentrevokeHandlerCurrentConsentrevokeSlice) GroupByModesJson() ConsentrevokeHandlerCurrentConsentrevokeGroupedByModesJson {
	result := make(ConsentrevokeHandlerCurrentConsentrevokeGroupedByModesJson)
	for _, row := range rows {
		key, ok := ConsentrevokeHandlerCurrentConsentrevokeIndexByModesJsonKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index ConsentrevokeHandlerCurrentConsentrevokeGroupedByModesJson) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func ConsentrevokeHandlerCurrentConsentrevokeIndexByPurposeKey(value *CurrentConsentrevokeView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.Purpose == nil {
		return zero, false
	}
	return *value.Purpose, true
}

type ConsentrevokeHandlerCurrentConsentrevokeIndexedByPurpose map[string]*CurrentConsentrevokeView

func (rows ConsentrevokeHandlerCurrentConsentrevokeSlice) IndexByPurpose() (ConsentrevokeHandlerCurrentConsentrevokeIndexedByPurpose, error) {
	result := make(ConsentrevokeHandlerCurrentConsentrevokeIndexedByPurpose)
	for _, row := range rows {
		key, ok := ConsentrevokeHandlerCurrentConsentrevokeIndexByPurposeKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index ConsentrevokeHandlerCurrentConsentrevokeSlice.IndexByPurpose")
		}
		result[key] = row
	}
	return result, nil
}
func (index ConsentrevokeHandlerCurrentConsentrevokeIndexedByPurpose) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type ConsentrevokeHandlerCurrentConsentrevokeGroupedByPurpose map[string][]*CurrentConsentrevokeView

func (rows ConsentrevokeHandlerCurrentConsentrevokeSlice) GroupByPurpose() ConsentrevokeHandlerCurrentConsentrevokeGroupedByPurpose {
	result := make(ConsentrevokeHandlerCurrentConsentrevokeGroupedByPurpose)
	for _, row := range rows {
		key, ok := ConsentrevokeHandlerCurrentConsentrevokeIndexByPurposeKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index ConsentrevokeHandlerCurrentConsentrevokeGroupedByPurpose) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func ConsentrevokeHandlerCurrentConsentrevokeIndexByDurationSecondsKey(value *CurrentConsentrevokeView) (int, bool) {
	var zero int
	if value == nil {
		return zero, false
	}
	if value.DurationSeconds == nil {
		return zero, false
	}
	return *value.DurationSeconds, true
}

type ConsentrevokeHandlerCurrentConsentrevokeIndexedByDurationSeconds map[int]*CurrentConsentrevokeView

func (rows ConsentrevokeHandlerCurrentConsentrevokeSlice) IndexByDurationSeconds() (ConsentrevokeHandlerCurrentConsentrevokeIndexedByDurationSeconds, error) {
	result := make(ConsentrevokeHandlerCurrentConsentrevokeIndexedByDurationSeconds)
	for _, row := range rows {
		key, ok := ConsentrevokeHandlerCurrentConsentrevokeIndexByDurationSecondsKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index ConsentrevokeHandlerCurrentConsentrevokeSlice.IndexByDurationSeconds")
		}
		result[key] = row
	}
	return result, nil
}
func (index ConsentrevokeHandlerCurrentConsentrevokeIndexedByDurationSeconds) Has(key int) bool {
	_, ok := index[key]
	return ok
}

type ConsentrevokeHandlerCurrentConsentrevokeGroupedByDurationSeconds map[int][]*CurrentConsentrevokeView

func (rows ConsentrevokeHandlerCurrentConsentrevokeSlice) GroupByDurationSeconds() ConsentrevokeHandlerCurrentConsentrevokeGroupedByDurationSeconds {
	result := make(ConsentrevokeHandlerCurrentConsentrevokeGroupedByDurationSeconds)
	for _, row := range rows {
		key, ok := ConsentrevokeHandlerCurrentConsentrevokeIndexByDurationSecondsKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index ConsentrevokeHandlerCurrentConsentrevokeGroupedByDurationSeconds) Has(key int) bool {
	_, ok := index[key]
	return ok
}
func ConsentrevokeHandlerCurrentConsentrevokeIndexByCreatedAtKey(value *CurrentConsentrevokeView) (int, bool) {
	var zero int
	if value == nil {
		return zero, false
	}
	if value.CreatedAt == nil {
		return zero, false
	}
	return *value.CreatedAt, true
}

type ConsentrevokeHandlerCurrentConsentrevokeIndexedByCreatedAt map[int]*CurrentConsentrevokeView

func (rows ConsentrevokeHandlerCurrentConsentrevokeSlice) IndexByCreatedAt() (ConsentrevokeHandlerCurrentConsentrevokeIndexedByCreatedAt, error) {
	result := make(ConsentrevokeHandlerCurrentConsentrevokeIndexedByCreatedAt)
	for _, row := range rows {
		key, ok := ConsentrevokeHandlerCurrentConsentrevokeIndexByCreatedAtKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index ConsentrevokeHandlerCurrentConsentrevokeSlice.IndexByCreatedAt")
		}
		result[key] = row
	}
	return result, nil
}
func (index ConsentrevokeHandlerCurrentConsentrevokeIndexedByCreatedAt) Has(key int) bool {
	_, ok := index[key]
	return ok
}

type ConsentrevokeHandlerCurrentConsentrevokeGroupedByCreatedAt map[int][]*CurrentConsentrevokeView

func (rows ConsentrevokeHandlerCurrentConsentrevokeSlice) GroupByCreatedAt() ConsentrevokeHandlerCurrentConsentrevokeGroupedByCreatedAt {
	result := make(ConsentrevokeHandlerCurrentConsentrevokeGroupedByCreatedAt)
	for _, row := range rows {
		key, ok := ConsentrevokeHandlerCurrentConsentrevokeIndexByCreatedAtKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index ConsentrevokeHandlerCurrentConsentrevokeGroupedByCreatedAt) Has(key int) bool {
	_, ok := index[key]
	return ok
}
func ConsentrevokeHandlerCurrentConsentrevokeIndexByRequestExpiresAtKey(value *CurrentConsentrevokeView) (int, bool) {
	var zero int
	if value == nil {
		return zero, false
	}
	if value.RequestExpiresAt == nil {
		return zero, false
	}
	return *value.RequestExpiresAt, true
}

type ConsentrevokeHandlerCurrentConsentrevokeIndexedByRequestExpiresAt map[int]*CurrentConsentrevokeView

func (rows ConsentrevokeHandlerCurrentConsentrevokeSlice) IndexByRequestExpiresAt() (ConsentrevokeHandlerCurrentConsentrevokeIndexedByRequestExpiresAt, error) {
	result := make(ConsentrevokeHandlerCurrentConsentrevokeIndexedByRequestExpiresAt)
	for _, row := range rows {
		key, ok := ConsentrevokeHandlerCurrentConsentrevokeIndexByRequestExpiresAtKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index ConsentrevokeHandlerCurrentConsentrevokeSlice.IndexByRequestExpiresAt")
		}
		result[key] = row
	}
	return result, nil
}
func (index ConsentrevokeHandlerCurrentConsentrevokeIndexedByRequestExpiresAt) Has(key int) bool {
	_, ok := index[key]
	return ok
}

type ConsentrevokeHandlerCurrentConsentrevokeGroupedByRequestExpiresAt map[int][]*CurrentConsentrevokeView

func (rows ConsentrevokeHandlerCurrentConsentrevokeSlice) GroupByRequestExpiresAt() ConsentrevokeHandlerCurrentConsentrevokeGroupedByRequestExpiresAt {
	result := make(ConsentrevokeHandlerCurrentConsentrevokeGroupedByRequestExpiresAt)
	for _, row := range rows {
		key, ok := ConsentrevokeHandlerCurrentConsentrevokeIndexByRequestExpiresAtKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index ConsentrevokeHandlerCurrentConsentrevokeGroupedByRequestExpiresAt) Has(key int) bool {
	_, ok := index[key]
	return ok
}
func ConsentrevokeHandlerCurrentConsentrevokeIndexByRequestStateKey(value *CurrentConsentrevokeView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.RequestState == nil {
		return zero, false
	}
	return *value.RequestState, true
}

type ConsentrevokeHandlerCurrentConsentrevokeIndexedByRequestState map[string]*CurrentConsentrevokeView

func (rows ConsentrevokeHandlerCurrentConsentrevokeSlice) IndexByRequestState() (ConsentrevokeHandlerCurrentConsentrevokeIndexedByRequestState, error) {
	result := make(ConsentrevokeHandlerCurrentConsentrevokeIndexedByRequestState)
	for _, row := range rows {
		key, ok := ConsentrevokeHandlerCurrentConsentrevokeIndexByRequestStateKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index ConsentrevokeHandlerCurrentConsentrevokeSlice.IndexByRequestState")
		}
		result[key] = row
	}
	return result, nil
}
func (index ConsentrevokeHandlerCurrentConsentrevokeIndexedByRequestState) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type ConsentrevokeHandlerCurrentConsentrevokeGroupedByRequestState map[string][]*CurrentConsentrevokeView

func (rows ConsentrevokeHandlerCurrentConsentrevokeSlice) GroupByRequestState() ConsentrevokeHandlerCurrentConsentrevokeGroupedByRequestState {
	result := make(ConsentrevokeHandlerCurrentConsentrevokeGroupedByRequestState)
	for _, row := range rows {
		key, ok := ConsentrevokeHandlerCurrentConsentrevokeIndexByRequestStateKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index ConsentrevokeHandlerCurrentConsentrevokeGroupedByRequestState) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func ConsentrevokeHandlerCurrentConsentrevokeIndexByDecisionKey(value *CurrentConsentrevokeView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.Decision == nil {
		return zero, false
	}
	return *value.Decision, true
}

type ConsentrevokeHandlerCurrentConsentrevokeIndexedByDecision map[string]*CurrentConsentrevokeView

func (rows ConsentrevokeHandlerCurrentConsentrevokeSlice) IndexByDecision() (ConsentrevokeHandlerCurrentConsentrevokeIndexedByDecision, error) {
	result := make(ConsentrevokeHandlerCurrentConsentrevokeIndexedByDecision)
	for _, row := range rows {
		key, ok := ConsentrevokeHandlerCurrentConsentrevokeIndexByDecisionKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index ConsentrevokeHandlerCurrentConsentrevokeSlice.IndexByDecision")
		}
		result[key] = row
	}
	return result, nil
}
func (index ConsentrevokeHandlerCurrentConsentrevokeIndexedByDecision) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type ConsentrevokeHandlerCurrentConsentrevokeGroupedByDecision map[string][]*CurrentConsentrevokeView

func (rows ConsentrevokeHandlerCurrentConsentrevokeSlice) GroupByDecision() ConsentrevokeHandlerCurrentConsentrevokeGroupedByDecision {
	result := make(ConsentrevokeHandlerCurrentConsentrevokeGroupedByDecision)
	for _, row := range rows {
		key, ok := ConsentrevokeHandlerCurrentConsentrevokeIndexByDecisionKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index ConsentrevokeHandlerCurrentConsentrevokeGroupedByDecision) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func ConsentrevokeHandlerCurrentConsentrevokeIndexByGrantIdKey(value *CurrentConsentrevokeView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.GrantId == nil {
		return zero, false
	}
	return *value.GrantId, true
}

type ConsentrevokeHandlerCurrentConsentrevokeIndexedByGrantId map[string]*CurrentConsentrevokeView

func (rows ConsentrevokeHandlerCurrentConsentrevokeSlice) IndexByGrantId() (ConsentrevokeHandlerCurrentConsentrevokeIndexedByGrantId, error) {
	result := make(ConsentrevokeHandlerCurrentConsentrevokeIndexedByGrantId)
	for _, row := range rows {
		key, ok := ConsentrevokeHandlerCurrentConsentrevokeIndexByGrantIdKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index ConsentrevokeHandlerCurrentConsentrevokeSlice.IndexByGrantId")
		}
		result[key] = row
	}
	return result, nil
}
func (index ConsentrevokeHandlerCurrentConsentrevokeIndexedByGrantId) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type ConsentrevokeHandlerCurrentConsentrevokeGroupedByGrantId map[string][]*CurrentConsentrevokeView

func (rows ConsentrevokeHandlerCurrentConsentrevokeSlice) GroupByGrantId() ConsentrevokeHandlerCurrentConsentrevokeGroupedByGrantId {
	result := make(ConsentrevokeHandlerCurrentConsentrevokeGroupedByGrantId)
	for _, row := range rows {
		key, ok := ConsentrevokeHandlerCurrentConsentrevokeIndexByGrantIdKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index ConsentrevokeHandlerCurrentConsentrevokeGroupedByGrantId) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func ConsentrevokeHandlerCurrentConsentrevokeIndexByGrantCreatedAtKey(value *CurrentConsentrevokeView) (int, bool) {
	var zero int
	if value == nil {
		return zero, false
	}
	if value.GrantCreatedAt == nil {
		return zero, false
	}
	return *value.GrantCreatedAt, true
}

type ConsentrevokeHandlerCurrentConsentrevokeIndexedByGrantCreatedAt map[int]*CurrentConsentrevokeView

func (rows ConsentrevokeHandlerCurrentConsentrevokeSlice) IndexByGrantCreatedAt() (ConsentrevokeHandlerCurrentConsentrevokeIndexedByGrantCreatedAt, error) {
	result := make(ConsentrevokeHandlerCurrentConsentrevokeIndexedByGrantCreatedAt)
	for _, row := range rows {
		key, ok := ConsentrevokeHandlerCurrentConsentrevokeIndexByGrantCreatedAtKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index ConsentrevokeHandlerCurrentConsentrevokeSlice.IndexByGrantCreatedAt")
		}
		result[key] = row
	}
	return result, nil
}
func (index ConsentrevokeHandlerCurrentConsentrevokeIndexedByGrantCreatedAt) Has(key int) bool {
	_, ok := index[key]
	return ok
}

type ConsentrevokeHandlerCurrentConsentrevokeGroupedByGrantCreatedAt map[int][]*CurrentConsentrevokeView

func (rows ConsentrevokeHandlerCurrentConsentrevokeSlice) GroupByGrantCreatedAt() ConsentrevokeHandlerCurrentConsentrevokeGroupedByGrantCreatedAt {
	result := make(ConsentrevokeHandlerCurrentConsentrevokeGroupedByGrantCreatedAt)
	for _, row := range rows {
		key, ok := ConsentrevokeHandlerCurrentConsentrevokeIndexByGrantCreatedAtKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index ConsentrevokeHandlerCurrentConsentrevokeGroupedByGrantCreatedAt) Has(key int) bool {
	_, ok := index[key]
	return ok
}
func ConsentrevokeHandlerCurrentConsentrevokeIndexByGrantExpiresAtKey(value *CurrentConsentrevokeView) (int, bool) {
	var zero int
	if value == nil {
		return zero, false
	}
	if value.GrantExpiresAt == nil {
		return zero, false
	}
	return *value.GrantExpiresAt, true
}

type ConsentrevokeHandlerCurrentConsentrevokeIndexedByGrantExpiresAt map[int]*CurrentConsentrevokeView

func (rows ConsentrevokeHandlerCurrentConsentrevokeSlice) IndexByGrantExpiresAt() (ConsentrevokeHandlerCurrentConsentrevokeIndexedByGrantExpiresAt, error) {
	result := make(ConsentrevokeHandlerCurrentConsentrevokeIndexedByGrantExpiresAt)
	for _, row := range rows {
		key, ok := ConsentrevokeHandlerCurrentConsentrevokeIndexByGrantExpiresAtKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index ConsentrevokeHandlerCurrentConsentrevokeSlice.IndexByGrantExpiresAt")
		}
		result[key] = row
	}
	return result, nil
}
func (index ConsentrevokeHandlerCurrentConsentrevokeIndexedByGrantExpiresAt) Has(key int) bool {
	_, ok := index[key]
	return ok
}

type ConsentrevokeHandlerCurrentConsentrevokeGroupedByGrantExpiresAt map[int][]*CurrentConsentrevokeView

func (rows ConsentrevokeHandlerCurrentConsentrevokeSlice) GroupByGrantExpiresAt() ConsentrevokeHandlerCurrentConsentrevokeGroupedByGrantExpiresAt {
	result := make(ConsentrevokeHandlerCurrentConsentrevokeGroupedByGrantExpiresAt)
	for _, row := range rows {
		key, ok := ConsentrevokeHandlerCurrentConsentrevokeIndexByGrantExpiresAtKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index ConsentrevokeHandlerCurrentConsentrevokeGroupedByGrantExpiresAt) Has(key int) bool {
	_, ok := index[key]
	return ok
}
func ConsentrevokeHandlerCurrentConsentrevokeIndexByGrantStateKey(value *CurrentConsentrevokeView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.GrantState == nil {
		return zero, false
	}
	return *value.GrantState, true
}

type ConsentrevokeHandlerCurrentConsentrevokeIndexedByGrantState map[string]*CurrentConsentrevokeView

func (rows ConsentrevokeHandlerCurrentConsentrevokeSlice) IndexByGrantState() (ConsentrevokeHandlerCurrentConsentrevokeIndexedByGrantState, error) {
	result := make(ConsentrevokeHandlerCurrentConsentrevokeIndexedByGrantState)
	for _, row := range rows {
		key, ok := ConsentrevokeHandlerCurrentConsentrevokeIndexByGrantStateKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index ConsentrevokeHandlerCurrentConsentrevokeSlice.IndexByGrantState")
		}
		result[key] = row
	}
	return result, nil
}
func (index ConsentrevokeHandlerCurrentConsentrevokeIndexedByGrantState) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type ConsentrevokeHandlerCurrentConsentrevokeGroupedByGrantState map[string][]*CurrentConsentrevokeView

func (rows ConsentrevokeHandlerCurrentConsentrevokeSlice) GroupByGrantState() ConsentrevokeHandlerCurrentConsentrevokeGroupedByGrantState {
	result := make(ConsentrevokeHandlerCurrentConsentrevokeGroupedByGrantState)
	for _, row := range rows {
		key, ok := ConsentrevokeHandlerCurrentConsentrevokeIndexByGrantStateKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index ConsentrevokeHandlerCurrentConsentrevokeGroupedByGrantState) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func ConsentrevokeHandlerCurrentConsentrevokeIndexByRevocationStateKey(value *CurrentConsentrevokeView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.RevocationState == nil {
		return zero, false
	}
	return *value.RevocationState, true
}

type ConsentrevokeHandlerCurrentConsentrevokeIndexedByRevocationState map[string]*CurrentConsentrevokeView

func (rows ConsentrevokeHandlerCurrentConsentrevokeSlice) IndexByRevocationState() (ConsentrevokeHandlerCurrentConsentrevokeIndexedByRevocationState, error) {
	result := make(ConsentrevokeHandlerCurrentConsentrevokeIndexedByRevocationState)
	for _, row := range rows {
		key, ok := ConsentrevokeHandlerCurrentConsentrevokeIndexByRevocationStateKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index ConsentrevokeHandlerCurrentConsentrevokeSlice.IndexByRevocationState")
		}
		result[key] = row
	}
	return result, nil
}
func (index ConsentrevokeHandlerCurrentConsentrevokeIndexedByRevocationState) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type ConsentrevokeHandlerCurrentConsentrevokeGroupedByRevocationState map[string][]*CurrentConsentrevokeView

func (rows ConsentrevokeHandlerCurrentConsentrevokeSlice) GroupByRevocationState() ConsentrevokeHandlerCurrentConsentrevokeGroupedByRevocationState {
	result := make(ConsentrevokeHandlerCurrentConsentrevokeGroupedByRevocationState)
	for _, row := range rows {
		key, ok := ConsentrevokeHandlerCurrentConsentrevokeIndexByRevocationStateKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index ConsentrevokeHandlerCurrentConsentrevokeGroupedByRevocationState) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type ConsentrevokeHandlerCurrentConsentrevokeKey struct {
	Namespace string
	Id        string
}

func ConsentrevokeHandlerCurrentConsentrevokeIndexByKeyKey(value *CurrentConsentrevokeView) (ConsentrevokeHandlerCurrentConsentrevokeKey, bool) {
	var zero ConsentrevokeHandlerCurrentConsentrevokeKey
	if value == nil {
		return zero, false
	}
	if value.Namespace == nil {
		return zero, false
	}
	if value.Id == nil {
		return zero, false
	}
	return ConsentrevokeHandlerCurrentConsentrevokeKey{Namespace: *value.Namespace, Id: *value.Id}, true
}

type ConsentrevokeHandlerCurrentConsentrevokeIndexedByKey map[ConsentrevokeHandlerCurrentConsentrevokeKey]*CurrentConsentrevokeView

func (rows ConsentrevokeHandlerCurrentConsentrevokeSlice) IndexByKey() (ConsentrevokeHandlerCurrentConsentrevokeIndexedByKey, error) {
	result := make(ConsentrevokeHandlerCurrentConsentrevokeIndexedByKey)
	for _, row := range rows {
		key, ok := ConsentrevokeHandlerCurrentConsentrevokeIndexByKeyKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index ConsentrevokeHandlerCurrentConsentrevokeSlice.IndexByKey")
		}
		result[key] = row
	}
	return result, nil
}
func (index ConsentrevokeHandlerCurrentConsentrevokeIndexedByKey) Has(key ConsentrevokeHandlerCurrentConsentrevokeKey) bool {
	_, ok := index[key]
	return ok
}

type ConsentrevokeHandlerCurrentConsentrevokeGroupedByKey map[ConsentrevokeHandlerCurrentConsentrevokeKey][]*CurrentConsentrevokeView

func (rows ConsentrevokeHandlerCurrentConsentrevokeSlice) GroupByKey() ConsentrevokeHandlerCurrentConsentrevokeGroupedByKey {
	result := make(ConsentrevokeHandlerCurrentConsentrevokeGroupedByKey)
	for _, row := range rows {
		key, ok := ConsentrevokeHandlerCurrentConsentrevokeIndexByKeyKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index ConsentrevokeHandlerCurrentConsentrevokeGroupedByKey) Has(key ConsentrevokeHandlerCurrentConsentrevokeKey) bool {
	_, ok := index[key]
	return ok
}

type ConsentrevokeHandlerCurrentAuditSlice []*CurrentAuditView

func ConsentrevokeHandlerCurrentAuditIndexByNamespaceKey(value *CurrentAuditView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.Namespace == nil {
		return zero, false
	}
	return *value.Namespace, true
}

type ConsentrevokeHandlerCurrentAuditIndexedByNamespace map[string]*CurrentAuditView

func (rows ConsentrevokeHandlerCurrentAuditSlice) IndexByNamespace() (ConsentrevokeHandlerCurrentAuditIndexedByNamespace, error) {
	result := make(ConsentrevokeHandlerCurrentAuditIndexedByNamespace)
	for _, row := range rows {
		key, ok := ConsentrevokeHandlerCurrentAuditIndexByNamespaceKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index ConsentrevokeHandlerCurrentAuditSlice.IndexByNamespace")
		}
		result[key] = row
	}
	return result, nil
}
func (index ConsentrevokeHandlerCurrentAuditIndexedByNamespace) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type ConsentrevokeHandlerCurrentAuditGroupedByNamespace map[string][]*CurrentAuditView

func (rows ConsentrevokeHandlerCurrentAuditSlice) GroupByNamespace() ConsentrevokeHandlerCurrentAuditGroupedByNamespace {
	result := make(ConsentrevokeHandlerCurrentAuditGroupedByNamespace)
	for _, row := range rows {
		key, ok := ConsentrevokeHandlerCurrentAuditIndexByNamespaceKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index ConsentrevokeHandlerCurrentAuditGroupedByNamespace) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func ConsentrevokeHandlerCurrentAuditIndexByIdKey(value *CurrentAuditView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.Id == nil {
		return zero, false
	}
	return *value.Id, true
}

type ConsentrevokeHandlerCurrentAuditIndexedById map[string]*CurrentAuditView

func (rows ConsentrevokeHandlerCurrentAuditSlice) IndexById() (ConsentrevokeHandlerCurrentAuditIndexedById, error) {
	result := make(ConsentrevokeHandlerCurrentAuditIndexedById)
	for _, row := range rows {
		key, ok := ConsentrevokeHandlerCurrentAuditIndexByIdKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index ConsentrevokeHandlerCurrentAuditSlice.IndexById")
		}
		result[key] = row
	}
	return result, nil
}
func (index ConsentrevokeHandlerCurrentAuditIndexedById) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type ConsentrevokeHandlerCurrentAuditGroupedById map[string][]*CurrentAuditView

func (rows ConsentrevokeHandlerCurrentAuditSlice) GroupById() ConsentrevokeHandlerCurrentAuditGroupedById {
	result := make(ConsentrevokeHandlerCurrentAuditGroupedById)
	for _, row := range rows {
		key, ok := ConsentrevokeHandlerCurrentAuditIndexByIdKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index ConsentrevokeHandlerCurrentAuditGroupedById) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func ConsentrevokeHandlerCurrentAuditIndexByRequestIdKey(value *CurrentAuditView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.RequestId == nil {
		return zero, false
	}
	return *value.RequestId, true
}

type ConsentrevokeHandlerCurrentAuditIndexedByRequestId map[string]*CurrentAuditView

func (rows ConsentrevokeHandlerCurrentAuditSlice) IndexByRequestId() (ConsentrevokeHandlerCurrentAuditIndexedByRequestId, error) {
	result := make(ConsentrevokeHandlerCurrentAuditIndexedByRequestId)
	for _, row := range rows {
		key, ok := ConsentrevokeHandlerCurrentAuditIndexByRequestIdKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index ConsentrevokeHandlerCurrentAuditSlice.IndexByRequestId")
		}
		result[key] = row
	}
	return result, nil
}
func (index ConsentrevokeHandlerCurrentAuditIndexedByRequestId) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type ConsentrevokeHandlerCurrentAuditGroupedByRequestId map[string][]*CurrentAuditView

func (rows ConsentrevokeHandlerCurrentAuditSlice) GroupByRequestId() ConsentrevokeHandlerCurrentAuditGroupedByRequestId {
	result := make(ConsentrevokeHandlerCurrentAuditGroupedByRequestId)
	for _, row := range rows {
		key, ok := ConsentrevokeHandlerCurrentAuditIndexByRequestIdKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index ConsentrevokeHandlerCurrentAuditGroupedByRequestId) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func ConsentrevokeHandlerCurrentAuditIndexByKindKey(value *CurrentAuditView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.Kind == nil {
		return zero, false
	}
	return *value.Kind, true
}

type ConsentrevokeHandlerCurrentAuditIndexedByKind map[string]*CurrentAuditView

func (rows ConsentrevokeHandlerCurrentAuditSlice) IndexByKind() (ConsentrevokeHandlerCurrentAuditIndexedByKind, error) {
	result := make(ConsentrevokeHandlerCurrentAuditIndexedByKind)
	for _, row := range rows {
		key, ok := ConsentrevokeHandlerCurrentAuditIndexByKindKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index ConsentrevokeHandlerCurrentAuditSlice.IndexByKind")
		}
		result[key] = row
	}
	return result, nil
}
func (index ConsentrevokeHandlerCurrentAuditIndexedByKind) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type ConsentrevokeHandlerCurrentAuditGroupedByKind map[string][]*CurrentAuditView

func (rows ConsentrevokeHandlerCurrentAuditSlice) GroupByKind() ConsentrevokeHandlerCurrentAuditGroupedByKind {
	result := make(ConsentrevokeHandlerCurrentAuditGroupedByKind)
	for _, row := range rows {
		key, ok := ConsentrevokeHandlerCurrentAuditIndexByKindKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index ConsentrevokeHandlerCurrentAuditGroupedByKind) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func ConsentrevokeHandlerCurrentAuditIndexByActorIdKey(value *CurrentAuditView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.ActorId == nil {
		return zero, false
	}
	return *value.ActorId, true
}

type ConsentrevokeHandlerCurrentAuditIndexedByActorId map[string]*CurrentAuditView

func (rows ConsentrevokeHandlerCurrentAuditSlice) IndexByActorId() (ConsentrevokeHandlerCurrentAuditIndexedByActorId, error) {
	result := make(ConsentrevokeHandlerCurrentAuditIndexedByActorId)
	for _, row := range rows {
		key, ok := ConsentrevokeHandlerCurrentAuditIndexByActorIdKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index ConsentrevokeHandlerCurrentAuditSlice.IndexByActorId")
		}
		result[key] = row
	}
	return result, nil
}
func (index ConsentrevokeHandlerCurrentAuditIndexedByActorId) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type ConsentrevokeHandlerCurrentAuditGroupedByActorId map[string][]*CurrentAuditView

func (rows ConsentrevokeHandlerCurrentAuditSlice) GroupByActorId() ConsentrevokeHandlerCurrentAuditGroupedByActorId {
	result := make(ConsentrevokeHandlerCurrentAuditGroupedByActorId)
	for _, row := range rows {
		key, ok := ConsentrevokeHandlerCurrentAuditIndexByActorIdKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index ConsentrevokeHandlerCurrentAuditGroupedByActorId) Has(key string) bool {
	_, ok := index[key]
	return ok
}
func ConsentrevokeHandlerCurrentAuditIndexByCreatedAtKey(value *CurrentAuditView) (int, bool) {
	var zero int
	if value == nil {
		return zero, false
	}
	if value.CreatedAt == nil {
		return zero, false
	}
	return *value.CreatedAt, true
}

type ConsentrevokeHandlerCurrentAuditIndexedByCreatedAt map[int]*CurrentAuditView

func (rows ConsentrevokeHandlerCurrentAuditSlice) IndexByCreatedAt() (ConsentrevokeHandlerCurrentAuditIndexedByCreatedAt, error) {
	result := make(ConsentrevokeHandlerCurrentAuditIndexedByCreatedAt)
	for _, row := range rows {
		key, ok := ConsentrevokeHandlerCurrentAuditIndexByCreatedAtKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index ConsentrevokeHandlerCurrentAuditSlice.IndexByCreatedAt")
		}
		result[key] = row
	}
	return result, nil
}
func (index ConsentrevokeHandlerCurrentAuditIndexedByCreatedAt) Has(key int) bool {
	_, ok := index[key]
	return ok
}

type ConsentrevokeHandlerCurrentAuditGroupedByCreatedAt map[int][]*CurrentAuditView

func (rows ConsentrevokeHandlerCurrentAuditSlice) GroupByCreatedAt() ConsentrevokeHandlerCurrentAuditGroupedByCreatedAt {
	result := make(ConsentrevokeHandlerCurrentAuditGroupedByCreatedAt)
	for _, row := range rows {
		key, ok := ConsentrevokeHandlerCurrentAuditIndexByCreatedAtKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index ConsentrevokeHandlerCurrentAuditGroupedByCreatedAt) Has(key int) bool {
	_, ok := index[key]
	return ok
}
func ConsentrevokeHandlerCurrentAuditIndexByPayloadJsonKey(value *CurrentAuditView) (string, bool) {
	var zero string
	if value == nil {
		return zero, false
	}
	if value.PayloadJson == nil {
		return zero, false
	}
	return *value.PayloadJson, true
}

type ConsentrevokeHandlerCurrentAuditIndexedByPayloadJson map[string]*CurrentAuditView

func (rows ConsentrevokeHandlerCurrentAuditSlice) IndexByPayloadJson() (ConsentrevokeHandlerCurrentAuditIndexedByPayloadJson, error) {
	result := make(ConsentrevokeHandlerCurrentAuditIndexedByPayloadJson)
	for _, row := range rows {
		key, ok := ConsentrevokeHandlerCurrentAuditIndexByPayloadJsonKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index ConsentrevokeHandlerCurrentAuditSlice.IndexByPayloadJson")
		}
		result[key] = row
	}
	return result, nil
}
func (index ConsentrevokeHandlerCurrentAuditIndexedByPayloadJson) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type ConsentrevokeHandlerCurrentAuditGroupedByPayloadJson map[string][]*CurrentAuditView

func (rows ConsentrevokeHandlerCurrentAuditSlice) GroupByPayloadJson() ConsentrevokeHandlerCurrentAuditGroupedByPayloadJson {
	result := make(ConsentrevokeHandlerCurrentAuditGroupedByPayloadJson)
	for _, row := range rows {
		key, ok := ConsentrevokeHandlerCurrentAuditIndexByPayloadJsonKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index ConsentrevokeHandlerCurrentAuditGroupedByPayloadJson) Has(key string) bool {
	_, ok := index[key]
	return ok
}

type ConsentrevokeHandlerCurrentAuditKey struct {
	Namespace string
	Id        string
}

func ConsentrevokeHandlerCurrentAuditIndexByKeyKey(value *CurrentAuditView) (ConsentrevokeHandlerCurrentAuditKey, bool) {
	var zero ConsentrevokeHandlerCurrentAuditKey
	if value == nil {
		return zero, false
	}
	if value.Namespace == nil {
		return zero, false
	}
	if value.Id == nil {
		return zero, false
	}
	return ConsentrevokeHandlerCurrentAuditKey{Namespace: *value.Namespace, Id: *value.Id}, true
}

type ConsentrevokeHandlerCurrentAuditIndexedByKey map[ConsentrevokeHandlerCurrentAuditKey]*CurrentAuditView

func (rows ConsentrevokeHandlerCurrentAuditSlice) IndexByKey() (ConsentrevokeHandlerCurrentAuditIndexedByKey, error) {
	result := make(ConsentrevokeHandlerCurrentAuditIndexedByKey)
	for _, row := range rows {
		key, ok := ConsentrevokeHandlerCurrentAuditIndexByKeyKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index ConsentrevokeHandlerCurrentAuditSlice.IndexByKey")
		}
		result[key] = row
	}
	return result, nil
}
func (index ConsentrevokeHandlerCurrentAuditIndexedByKey) Has(key ConsentrevokeHandlerCurrentAuditKey) bool {
	_, ok := index[key]
	return ok
}

type ConsentrevokeHandlerCurrentAuditGroupedByKey map[ConsentrevokeHandlerCurrentAuditKey][]*CurrentAuditView

func (rows ConsentrevokeHandlerCurrentAuditSlice) GroupByKey() ConsentrevokeHandlerCurrentAuditGroupedByKey {
	result := make(ConsentrevokeHandlerCurrentAuditGroupedByKey)
	for _, row := range rows {
		key, ok := ConsentrevokeHandlerCurrentAuditIndexByKeyKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index ConsentrevokeHandlerCurrentAuditGroupedByKey) Has(key ConsentrevokeHandlerCurrentAuditKey) bool {
	_, ok := index[key]
	return ok
}

type ConsentrevokeHandlerCurrentAuditNamespaceAndRequestIdKey struct {
	Namespace string
	RequestId string
}

func ConsentrevokeHandlerCurrentAuditIndexByNamespaceAndRequestIdKey(value *CurrentAuditView) (ConsentrevokeHandlerCurrentAuditNamespaceAndRequestIdKey, bool) {
	var zero ConsentrevokeHandlerCurrentAuditNamespaceAndRequestIdKey
	if value == nil {
		return zero, false
	}
	if value.Namespace == nil {
		return zero, false
	}
	if value.RequestId == nil {
		return zero, false
	}
	return ConsentrevokeHandlerCurrentAuditNamespaceAndRequestIdKey{Namespace: *value.Namespace, RequestId: *value.RequestId}, true
}

type ConsentrevokeHandlerCurrentAuditIndexedByNamespaceAndRequestId map[ConsentrevokeHandlerCurrentAuditNamespaceAndRequestIdKey]*CurrentAuditView

func (rows ConsentrevokeHandlerCurrentAuditSlice) IndexByNamespaceAndRequestId() (ConsentrevokeHandlerCurrentAuditIndexedByNamespaceAndRequestId, error) {
	result := make(ConsentrevokeHandlerCurrentAuditIndexedByNamespaceAndRequestId)
	for _, row := range rows {
		key, ok := ConsentrevokeHandlerCurrentAuditIndexByNamespaceAndRequestIdKey(row)
		if !ok {
			continue
		}
		if _, exists := result[key]; exists {
			return nil, fmt.Errorf("ambiguous application index ConsentrevokeHandlerCurrentAuditSlice.IndexByNamespaceAndRequestId")
		}
		result[key] = row
	}
	return result, nil
}
func (index ConsentrevokeHandlerCurrentAuditIndexedByNamespaceAndRequestId) Has(key ConsentrevokeHandlerCurrentAuditNamespaceAndRequestIdKey) bool {
	_, ok := index[key]
	return ok
}

type ConsentrevokeHandlerCurrentAuditGroupedByNamespaceAndRequestId map[ConsentrevokeHandlerCurrentAuditNamespaceAndRequestIdKey][]*CurrentAuditView

func (rows ConsentrevokeHandlerCurrentAuditSlice) GroupByNamespaceAndRequestId() ConsentrevokeHandlerCurrentAuditGroupedByNamespaceAndRequestId {
	result := make(ConsentrevokeHandlerCurrentAuditGroupedByNamespaceAndRequestId)
	for _, row := range rows {
		key, ok := ConsentrevokeHandlerCurrentAuditIndexByNamespaceAndRequestIdKey(row)
		if !ok {
			continue
		}
		result[key] = append(result[key], row)
	}
	return result
}
func (index ConsentrevokeHandlerCurrentAuditGroupedByNamespaceAndRequestId) Has(key ConsentrevokeHandlerCurrentAuditNamespaceAndRequestIdKey) bool {
	_, ok := index[key]
	return ok
}

type ConsentrevokeHandlerReadIndexes struct {
	CurrentConsentrevoke                       ConsentrevokeHandlerCurrentConsentrevokeSlice
	CurrentConsentrevokeByKey                  ConsentrevokeHandlerCurrentConsentrevokeIndexedByKey
	CurrentConsentrevokeGroupedByKey           ConsentrevokeHandlerCurrentConsentrevokeGroupedByKey
	CurrentAudit                               ConsentrevokeHandlerCurrentAuditSlice
	CurrentAuditByKey                          ConsentrevokeHandlerCurrentAuditIndexedByKey
	CurrentAuditGroupedByNamespaceAndRequestId ConsentrevokeHandlerCurrentAuditGroupedByNamespaceAndRequestId
}

func BuildConsentrevokeHandlerReadIndexes(ctx context.Context, input *RevokeInput) (*ConsentrevokeHandlerReadIndexes, error) {
	if input == nil {
		return nil, fmt.Errorf("read indexes require input")
	}
	metadata, ok := xhandler.ReadMetadataFromContext(ctx)
	if !ok || (xshape.Runtime{}).IsNil(metadata) {
		return nil, fmt.Errorf("read indexes require bound read metadata")
	}
	result := &ConsentrevokeHandlerReadIndexes{}
	{
		projection, err := metadata.Projection("CurrentConsentrevoke")
		if err != nil {
			return nil, err
		}
		if (xshape.Runtime{}).IsNil(projection) {
			return nil, fmt.Errorf("application read projection is unavailable: CurrentConsentrevoke")
		}
		inputAccess, err := xshape.Linked(reflect.TypeOf((*RevokeInput)(nil)).Elem()).Accessor("CurrentConsentrevoke")
		if err != nil {
			return nil, err
		}
		carrier, err := inputAccess.Get(input)
		if err != nil {
			return nil, err
		}
		value := carrier.Interface()
		if projection.DirectOutput() && projection.RootHolder() != "" {
			return nil, fmt.Errorf("direct application read cannot declare a root holder")
		}
		if !projection.DirectOutput() {
			holder := projection.RootHolder()
			if holder == "" {
				return nil, fmt.Errorf("wrapped read projection requires a canonical root holder")
			}
			accessor, err := xshape.Linked(carrier.Type()).Accessor(holder)
			if err != nil {
				return nil, err
			}
			if _, err := (xshape.Collection[CurrentConsentrevokeView]{}).Pointers(reflect.Zero(accessor.Type()).Interface()); err != nil {
				return nil, err
			}
			root, present, err := accessor.GetOptional(value)
			if err != nil {
				return nil, err
			}
			if present {
				value = root.Interface()
			} else {
				value = []*CurrentConsentrevokeView(nil)
			}
		}
		rows, err := (xshape.Collection[CurrentConsentrevokeView]{}).Pointers(value)
		if err != nil {
			return nil, err
		}
		for ordinal, row := range rows {
			if row == nil {
				continue
			}
			loaded, err := projection.Fields(ordinal)
			if err != nil {
				return nil, err
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("Revision") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentConsentrevoke.Revision")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("Namespace") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentConsentrevoke.Namespace")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("Id") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentConsentrevoke.Id")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("ClientId") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentConsentrevoke.ClientId")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("ClientName") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentConsentrevoke.ClientName")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("SessionId") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentConsentrevoke.SessionId")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("ScopeJson") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentConsentrevoke.ScopeJson")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("ModesJson") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentConsentrevoke.ModesJson")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("Purpose") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentConsentrevoke.Purpose")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("DurationSeconds") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentConsentrevoke.DurationSeconds")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("CreatedAt") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentConsentrevoke.CreatedAt")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("RequestExpiresAt") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentConsentrevoke.RequestExpiresAt")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("RequestState") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentConsentrevoke.RequestState")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("Decision") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentConsentrevoke.Decision")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("GrantId") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentConsentrevoke.GrantId")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("GrantCreatedAt") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentConsentrevoke.GrantCreatedAt")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("GrantExpiresAt") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentConsentrevoke.GrantExpiresAt")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("GrantState") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentConsentrevoke.GrantState")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("RevocationState") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentConsentrevoke.RevocationState")
			}
		}
		cloned, err := (xshape.Runtime{}).CloneValue(rows, xshape.CloneOptions{})
		if err != nil {
			return nil, err
		}
		result.CurrentConsentrevoke = ConsentrevokeHandlerCurrentConsentrevokeSlice(cloned.([]*CurrentConsentrevokeView))
		result.CurrentConsentrevokeByKey, err = result.CurrentConsentrevoke.IndexByKey()
		if err != nil {
			return nil, err
		}
		result.CurrentConsentrevokeGroupedByKey = result.CurrentConsentrevoke.GroupByKey()
	}
	{
		projection, err := metadata.Projection("CurrentAudit")
		if err != nil {
			return nil, err
		}
		if (xshape.Runtime{}).IsNil(projection) {
			return nil, fmt.Errorf("application read projection is unavailable: CurrentAudit")
		}
		inputAccess, err := xshape.Linked(reflect.TypeOf((*RevokeInput)(nil)).Elem()).Accessor("CurrentAudit")
		if err != nil {
			return nil, err
		}
		carrier, err := inputAccess.Get(input)
		if err != nil {
			return nil, err
		}
		value := carrier.Interface()
		if projection.DirectOutput() && projection.RootHolder() != "" {
			return nil, fmt.Errorf("direct application read cannot declare a root holder")
		}
		if !projection.DirectOutput() {
			holder := projection.RootHolder()
			if holder == "" {
				return nil, fmt.Errorf("wrapped read projection requires a canonical root holder")
			}
			accessor, err := xshape.Linked(carrier.Type()).Accessor(holder)
			if err != nil {
				return nil, err
			}
			if _, err := (xshape.Collection[CurrentAuditView]{}).Pointers(reflect.Zero(accessor.Type()).Interface()); err != nil {
				return nil, err
			}
			root, present, err := accessor.GetOptional(value)
			if err != nil {
				return nil, err
			}
			if present {
				value = root.Interface()
			} else {
				value = []*CurrentAuditView(nil)
			}
		}
		rows, err := (xshape.Collection[CurrentAuditView]{}).Pointers(value)
		if err != nil {
			return nil, err
		}
		for ordinal, row := range rows {
			if row == nil {
				continue
			}
			loaded, err := projection.Fields(ordinal)
			if err != nil {
				return nil, err
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("Namespace") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentAudit.Namespace")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("Id") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentAudit.Id")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("RequestId") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentAudit.RequestId")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("Kind") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentAudit.Kind")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("ActorId") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentAudit.ActorId")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("CreatedAt") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentAudit.CreatedAt")
			}
			if (xshape.Runtime{}).IsNil(loaded) || !loaded.Has("PayloadJson") {
				return nil, fmt.Errorf("application index field was not loaded: CurrentAudit.PayloadJson")
			}
		}
		cloned, err := (xshape.Runtime{}).CloneValue(rows, xshape.CloneOptions{})
		if err != nil {
			return nil, err
		}
		result.CurrentAudit = ConsentrevokeHandlerCurrentAuditSlice(cloned.([]*CurrentAuditView))
		result.CurrentAuditByKey, err = result.CurrentAudit.IndexByKey()
		if err != nil {
			return nil, err
		}
		result.CurrentAuditGroupedByNamespaceAndRequestId = result.CurrentAudit.GroupByNamespaceAndRequestId()
	}
	return result, nil
}
func (input *RevokeInput) PrepareReadIndexes(ctx context.Context) error {
	if input == nil {
		return fmt.Errorf("read indexes require input")
	}
	input._consentrevokeHandlerReadIndexes = nil
	indexes, err := BuildConsentrevokeHandlerReadIndexes(ctx, input)
	if err := err; err != nil {
		return err
	}
	input._consentrevokeHandlerReadIndexes = indexes
	return nil
}
func (input *RevokeInput) ReadIndexes(ctx context.Context) (*ConsentrevokeHandlerReadIndexes, error) {
	if input == nil {
		return nil, fmt.Errorf("read indexes require input")
	}
	if input._consentrevokeHandlerReadIndexes == nil {
		if err := input.PrepareReadIndexes(ctx); err != nil {
			return nil, err
		}
	}
	return input._consentrevokeHandlerReadIndexes, nil
}
