// Code generated by Datly for consentrevoke; DO NOT EDIT.

package consentrevoke

// RevokeInput is the generated input scaffold for consentrevoke.
type RevokeInput struct {
	Namespace                        string                           `parameter:"Namespace,kind=query,in=namespace,dataType=string,required=true"`
	Consentrevoke                    []*Record                        `parameter:"Consentrevoke,kind=body,in=Data,dataType=[]*Record,cardinality=Many,required=true" view:"consentrevoke,type=Record,entityHooks=RecordLifecycle,table=consent_records" sql:"uri=mechanize_data_consentrevoke_consentrevoke:sql/consentrevoke.sql"`
	ConsentrevokeKeys                []ConsentrevokeKeysRow           `parameter:"ConsentrevokeKeys,kind=param,in=Consentrevoke,cardinality=Many" codec:"structql,'uri=mechanize_data_consentrevoke_consentrevoke:sql/consentrevoke_keys.sql'"`
	CurrentConsentrevoke             []*CurrentConsentrevokeView      `parameter:"CurrentConsentrevoke,kind=view,in=CurrentConsentrevoke,cardinality=Many" view:"CurrentConsentrevoke,table=consent_records" sql:"uri=mechanize_data_consentrevoke_consentrevoke:sql/current_consentrevoke.sql"`
	CurrentAudit                     []*CurrentAuditView              `parameter:"CurrentAudit,kind=view,in=CurrentAudit,cardinality=Many" view:"CurrentAudit,table=consent_audit" sql:"uri=mechanize_data_consentrevoke_consentrevoke:sql/current_audit.sql"`
	_consentrevokeHandlerReadIndexes *ConsentrevokeHandlerReadIndexes `json:"-" sqlx:"-"`
	Has                              *RevokeInputHas                  `setMarker:"true" typeName:"RevokeInputHas" json:"-" sqlx:"-"`
}

type RevokeInputHas struct {
	Namespace            bool
	Consentrevoke        bool
	ConsentrevokeKeys    bool
	CurrentConsentrevoke bool
	CurrentAudit         bool
}
