// Code generated by Datly for consentrevoke; DO NOT EDIT.

package consentrevoke

import (
	embed "embed"
	xdatly "github.com/viant/xdatly"
	reflect "reflect"
)

func init() {}

// Component is the generated component scaffold for consentrevoke.
type ConsentrevokeComponent struct {
	Contract xdatly.Component[RevokeInput, RevokeOutput] "component:\"consentrevoke,path=/internal/data/consentrevoke,method=PATCH,connector=user,view=consentrevoke\" routeName:\"consentrevoke\" mutation:\"patch\" caseFormat:\"lc\""
}

// ConsentrevokeDatlyType returns the public component type.
func ConsentrevokeDatlyType() reflect.Type {
	return reflect.TypeOf((*ConsentrevokeComponent)(nil)).Elem()
}

// The package-level value keeps this real component type reachable for runtime discovery.
var ConsentrevokeDatly = new(ConsentrevokeComponent)
var _datlyReachableConsentrevokeComponent = reflect.TypeFor[ConsentrevokeComponent]()

func (ConsentrevokeComponent) EmbedFS() *embed.FS {
	return &ConsentrevokeDatlyResources
}

func (ConsentrevokeComponent) EmbedNamespace() string {
	return ConsentrevokeDatlyResourceNamespace
}
