// Code generated by Datly for consentconsume; DO NOT EDIT.

package consentconsume

import (
	fmt2 "fmt"
)

func (entity *Record) GetRevision() *int {
	return entity.Revision
}
func (entity *Record) SetRevision(value *int) {
	entity.Revision = value
	if entity.Has == nil {
		entity.Has = &RecordHas{}
	}
	entity.Has.Revision = true
}
func (entity *Record) GetNamespace() *string {
	return entity.Namespace
}
func (entity *Record) SetNamespace(value *string) {
	entity.Namespace = value
	if entity.Has == nil {
		entity.Has = &RecordHas{}
	}
	entity.Has.Namespace = true
}
func (entity *Record) GetId() *string {
	return entity.Id
}
func (entity *Record) SetId(value *string) {
	entity.Id = value
	if entity.Has == nil {
		entity.Has = &RecordHas{}
	}
	entity.Has.Id = true
}
func (entity *Record) GetClientId() *string {
	return entity.ClientId
}
func (entity *Record) SetClientId(value *string) {
	entity.ClientId = value
	if entity.Has == nil {
		entity.Has = &RecordHas{}
	}
	entity.Has.ClientId = true
}
func (entity *Record) GetClientName() *string {
	return entity.ClientName
}
func (entity *Record) SetClientName(value *string) {
	entity.ClientName = value
	if entity.Has == nil {
		entity.Has = &RecordHas{}
	}
	entity.Has.ClientName = true
}
func (entity *Record) GetSessionId() *string {
	return entity.SessionId
}
func (entity *Record) SetSessionId(value *string) {
	entity.SessionId = value
	if entity.Has == nil {
		entity.Has = &RecordHas{}
	}
	entity.Has.SessionId = true
}
func (entity *Record) GetScopeJson() *string {
	return entity.ScopeJson
}
func (entity *Record) SetScopeJson(value *string) {
	entity.ScopeJson = value
	if entity.Has == nil {
		entity.Has = &RecordHas{}
	}
	entity.Has.ScopeJson = true
}
func (entity *Record) GetModesJson() *string {
	return entity.ModesJson
}
func (entity *Record) SetModesJson(value *string) {
	entity.ModesJson = value
	if entity.Has == nil {
		entity.Has = &RecordHas{}
	}
	entity.Has.ModesJson = true
}
func (entity *Record) GetPurpose() *string {
	return entity.Purpose
}
func (entity *Record) SetPurpose(value *string) {
	entity.Purpose = value
	if entity.Has == nil {
		entity.Has = &RecordHas{}
	}
	entity.Has.Purpose = true
}
func (entity *Record) GetDurationSeconds() *int {
	return entity.DurationSeconds
}
func (entity *Record) SetDurationSeconds(value *int) {
	entity.DurationSeconds = value
	if entity.Has == nil {
		entity.Has = &RecordHas{}
	}
	entity.Has.DurationSeconds = true
}
func (entity *Record) GetCreatedAt() *int {
	return entity.CreatedAt
}
func (entity *Record) SetCreatedAt(value *int) {
	entity.CreatedAt = value
	if entity.Has == nil {
		entity.Has = &RecordHas{}
	}
	entity.Has.CreatedAt = true
}
func (entity *Record) GetRequestExpiresAt() *int {
	return entity.RequestExpiresAt
}
func (entity *Record) SetRequestExpiresAt(value *int) {
	entity.RequestExpiresAt = value
	if entity.Has == nil {
		entity.Has = &RecordHas{}
	}
	entity.Has.RequestExpiresAt = true
}
func (entity *Record) GetRequestState() *string {
	return entity.RequestState
}
func (entity *Record) SetRequestState(value *string) {
	entity.RequestState = value
	if entity.Has == nil {
		entity.Has = &RecordHas{}
	}
	entity.Has.RequestState = true
}
func (entity *Record) GetDecision() *string {
	return entity.Decision
}
func (entity *Record) SetDecision(value *string) {
	entity.Decision = value
	if entity.Has == nil {
		entity.Has = &RecordHas{}
	}
	entity.Has.Decision = true
}
func (entity *Record) GetGrantId() *string {
	return entity.GrantId
}
func (entity *Record) SetGrantId(value *string) {
	entity.GrantId = value
	if entity.Has == nil {
		entity.Has = &RecordHas{}
	}
	entity.Has.GrantId = true
}
func (entity *Record) GetGrantCreatedAt() *int {
	return entity.GrantCreatedAt
}
func (entity *Record) SetGrantCreatedAt(value *int) {
	entity.GrantCreatedAt = value
	if entity.Has == nil {
		entity.Has = &RecordHas{}
	}
	entity.Has.GrantCreatedAt = true
}
func (entity *Record) GetGrantExpiresAt() *int {
	return entity.GrantExpiresAt
}
func (entity *Record) SetGrantExpiresAt(value *int) {
	entity.GrantExpiresAt = value
	if entity.Has == nil {
		entity.Has = &RecordHas{}
	}
	entity.Has.GrantExpiresAt = true
}
func (entity *Record) GetGrantState() *string {
	return entity.GrantState
}
func (entity *Record) SetGrantState(value *string) {
	entity.GrantState = value
	if entity.Has == nil {
		entity.Has = &RecordHas{}
	}
	entity.Has.GrantState = true
}
func (entity *Record) GetRevocationState() *string {
	return entity.RevocationState
}
func (entity *Record) SetRevocationState(value *string) {
	entity.RevocationState = value
	if entity.Has == nil {
		entity.Has = &RecordHas{}
	}
	entity.Has.RevocationState = true
}
func (entity *Record) GetAudit() []*Audit {
	return entity.Audit
}
func (entity *Record) SetAudit(value []*Audit) {
	entity.Audit = value
	if entity.Has == nil {
		entity.Has = &RecordHas{}
	}
	entity.Has.Audit = true
}
func (entity *Audit) GetNamespace() *string {
	return entity.Namespace
}
func (entity *Audit) SetNamespace(value *string) {
	entity.Namespace = value
	if entity.Has == nil {
		entity.Has = &AuditHas{}
	}
	entity.Has.Namespace = true
}
func (entity *Audit) GetId() *string {
	return entity.Id
}
func (entity *Audit) SetId(value *string) {
	entity.Id = value
	if entity.Has == nil {
		entity.Has = &AuditHas{}
	}
	entity.Has.Id = true
}
func (entity *Audit) GetRequestId() *string {
	return entity.RequestId
}
func (entity *Audit) SetRequestId(value *string) {
	entity.RequestId = value
	if entity.Has == nil {
		entity.Has = &AuditHas{}
	}
	entity.Has.RequestId = true
}
func (entity *Audit) GetKind() *string {
	return entity.Kind
}
func (entity *Audit) SetKind(value *string) {
	entity.Kind = value
	if entity.Has == nil {
		entity.Has = &AuditHas{}
	}
	entity.Has.Kind = true
}
func (entity *Audit) GetActorId() *string {
	return entity.ActorId
}
func (entity *Audit) SetActorId(value *string) {
	entity.ActorId = value
	if entity.Has == nil {
		entity.Has = &AuditHas{}
	}
	entity.Has.ActorId = true
}
func (entity *Audit) GetCreatedAt() *int {
	return entity.CreatedAt
}
func (entity *Audit) SetCreatedAt(value *int) {
	entity.CreatedAt = value
	if entity.Has == nil {
		entity.Has = &AuditHas{}
	}
	entity.Has.CreatedAt = true
}
func (entity *Audit) GetPayloadJson() *string {
	return entity.PayloadJson
}
func (entity *Audit) SetPayloadJson(value *string) {
	entity.PayloadJson = value
	if entity.Has == nil {
		entity.Has = &AuditHas{}
	}
	entity.Has.PayloadJson = true
}
func (input *ConsumeOnceInput) ProjectCurrentAuditParentKeys(previous []*CurrentConsentconsumeView) ([]struct {
	Namespace *string "sqlx:\"namespace\""
	RequestId *string "sqlx:\"request_id\""
}, error) {
	result := []struct {
		Namespace *string "sqlx:\"namespace\""
		RequestId *string "sqlx:\"request_id\""
	}{}
	for _, row := range previous {
		if row == nil {
			continue
		}
		if row.Namespace == nil || row.Id == nil {
			return nil, fmt2.Errorf("scoped parent identity is null")
		}
		result = append(result, struct {
			Namespace *string "sqlx:\"namespace\""
			RequestId *string "sqlx:\"request_id\""
		}{Namespace: row.Namespace, RequestId: row.Id})
	}
	return result, nil
}
